import KolmogorovMathlib.AlgorithmicRandomness.EffectiveOpen
import KolmogorovMathlib.MonotoneComplexity.EffectiveOpen
import KolmogorovMathlib.Prefix.Encoding

/-!
# Effectively open sets of sequences are exactly those generated by an enumerable relation

Two descriptions of an effectively open subset of Cantor space are matched here. On one side,
the set generated at a string `x` by a halting relation, whose generating cylinders are listed by
the computable enumeration `cantorOpenREEnumerator`; on the other, the definition of
`IsEffectiveOpen`. `isEffectiveOpen_cantorOpen_of_isRE` gives one direction and
`exists_isRE_cantorOpen_of_isEffectiveOpen` the other, combined in
`isEffectiveOpen_iff_exists_cantorOpen`. This lets constructions phrased with recursively
enumerable relations be used wherever effectively open sets are expected.
-/

open Kolmogorov Set

namespace Kolmogorov

/-- Enumeration of the strings whose pair with `x` is accepted by the code `c` within the number of
steps read off the index, listing the generators of the effective open set attached to `x`. -/
def cantorOpenREEnumerator (c : Nat.Partrec.Code) (x : BitString) (n : ℕ) : Option BitString :=
  let ⟨k, s⟩ := Nat.unpair n
  match Encodable.decode₂ BitString k with
  | none => none
  | some p =>
    if (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome then some p else none

/-- The enumeration of the generators of an effective open set is computable in the base string and
the index. -/
lemma computable_cantorOpenREEnumerator (c : Nat.Partrec.Code) :
    Computable₂ (cantorOpenREEnumerator c) := by
  have H : Primrec₂ (cantorOpenREEnumerator c) := by
    change Primrec (fun q : BitString × ℕ => cantorOpenREEnumerator c q.1 q.2)
    have h_eq : (fun (q : BitString × ℕ) => cantorOpenREEnumerator c q.1 q.2) =
      fun (q : BitString × ℕ) =>
        let k := (Nat.unpair q.2).1
        let s := (Nat.unpair q.2).2
        (Encodable.decode₂ BitString k).bind (fun p =>
          cond (Nat.Partrec.Code.evaln s c (Encodable.encode (p, q.1))).isSome (some p) none) := by
      funext q; rcases q with ⟨x, n⟩; dsimp [cantorOpenREEnumerator]
      match h : Encodable.decode₂ BitString (Nat.unpair n).1 with
      | none => rfl
      | some val =>
        dsimp
        have H_cond :
            (if (Nat.Partrec.Code.evaln (Nat.unpair n).2 c
                  (Encodable.encode (val, x))).isSome then some val else none) =
              cond (Nat.Partrec.Code.evaln (Nat.unpair n).2 c
                (Encodable.encode (val, x))).isSome (some val) none := by
          cases (Nat.Partrec.Code.evaln (Nat.unpair n).2 c
            (Encodable.encode (val, x))).isSome <;> rfl
        exact H_cond
    rw [h_eq]
    refine Primrec.option_bind ?_ ?_
    · exact Primrec.decode₂.comp (Primrec.fst.comp (Primrec.unpair.comp Primrec.snd))
    · have h_isSome : Primrec (fun q : (BitString × ℕ) × BitString =>
          (Nat.Partrec.Code.evaln (Nat.unpair q.1.2).2 c
            (Encodable.encode (q.2, q.1.1))).isSome) := by
        have h_evaln := Nat.Partrec.Code.primrec_evaln
        have h1 : Primrec (fun q : (BitString × ℕ) × BitString => Encodable.encode (q.2, q.1.1)) :=
          Primrec.encode.comp (Primrec.pair Primrec.snd (Primrec.fst.comp Primrec.fst))
        have h_s : Primrec (fun q : (BitString × ℕ) × BitString => (Nat.unpair q.1.2).2) :=
          Primrec.snd.comp (Primrec.unpair.comp (Primrec.snd.comp Primrec.fst))
        exact Primrec.option_isSome.comp
          (h_evaln.comp (Primrec.pair (Primrec.pair h_s (Primrec.const c)) h1))
      have h_cond : Primrec (fun q : (BitString × ℕ) × BitString =>
          cond (Nat.Partrec.Code.evaln (Nat.unpair q.1.2).2 c
            (Encodable.encode (q.2, q.1.1))).isSome (some q.2) none) := by
        refine Primrec.cond h_isSome (Primrec.option_some.comp Primrec.snd) (Primrec.const none)
      exact h_cond
  exact Primrec.to_comp H

/-- The cylinders listed by the enumeration union to the open set generated by the halting relation
of the code `c` at `x`. -/
lemma range_cantorOpenREEnumerator (c : Nat.Partrec.Code) (x : BitString) :
    ⋃ n, (cantorOpenREEnumerator c x n).elim ∅ cantorCylinder =
      cantorOpen (fun p y => (c.eval (Encodable.encode (p, y))).Dom) x := by
  ext w
  simp only [cantorOpen, mem_iUnion]
  constructor
  · rintro ⟨n, hn⟩
    dsimp [cantorOpenREEnumerator] at hn
    revert hn
    match hk : Encodable.decode₂ BitString (Nat.unpair n).1 with
    | none =>
      intro hn
      exact False.elim hn
    | some p =>
      dsimp
      by_cases hs :
          (Nat.Partrec.Code.evaln (Nat.unpair n).2 c (Encodable.encode (p, x))).isSome = true
      · intro hn
        use p
        have H_dom : (c.eval (Encodable.encode (p, x))).Dom := by
          exact Part.dom_iff_mem.mpr
            ⟨_, Nat.Partrec.Code.evaln_sound (Option.isSome_iff_exists.mp hs).choose_spec⟩
        use H_dom
        have hs_rewritten : (Nat.Partrec.Code.evaln (Nat.unpair n).2 c
            (Nat.pair (Encodable.encode p) (Encodable.encode x))).isSome = true := hs
        revert hn
        simp [hs_rewritten]
      · intro hn
        have hs_rewritten : (Nat.Partrec.Code.evaln (Nat.unpair n).2 c
            (Nat.pair (Encodable.encode p) (Encodable.encode x))).isSome = false :=
          Bool.eq_false_of_not_eq_true hs
        revert hn
        simp [hs_rewritten]
  · rintro ⟨p, hp, hw⟩
    have H_eval := hp
    obtain ⟨v, hv⟩ := Part.dom_iff_mem.mp H_eval
    obtain ⟨s, hs⟩ := Nat.Partrec.Code.evaln_complete.mp hv
    use Nat.pair (Encodable.encode p) s
    dsimp [cantorOpenREEnumerator]
    rw [Nat.unpair_pair, Encodable.encodek₂]
    dsimp
    have H_isSome : (Nat.Partrec.Code.evaln s c
        (Nat.pair (Encodable.encode p) (Encodable.encode x))).isSome = true := by
      exact Option.isSome_iff_exists.mpr ⟨v, hs⟩
    simp [H_isSome, hw]

/-- The open set generated by a recursively enumerable relation at any string is effectively open.
-/
theorem isEffectiveOpen_cantorOpen_of_isRE
    {R : BitString → BitString → Prop}
    (hR : IsRE fun q : BitString × BitString => R q.1 q.2) (x : BitString) :
    IsEffectiveOpen (cantorOpen R x) := by
  rcases hR with ⟨f, hf, hfR⟩
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hf
  have hc' : ∀ p y, (c.eval (Encodable.encode (p, y))).Dom ↔ R p y := by
    intro p y
    have h_eq : c.eval (Encodable.encode (p, y)) = (f (p, y)).map Encodable.encode := by
      have hc_app : c.eval (Encodable.encode (p, y)) =
          (fun n => Part.bind (Encodable.decode n : Option (BitString × BitString))
            fun a => (f a).map Encodable.encode) (Encodable.encode (p, y)) := by
        rw [hc]
      rw [hc_app]
      simp
    rw [h_eq]
    simp [hfR]
  use (fun n => cantorOpenREEnumerator c x n)
  constructor
  · have H : Computable₂ (cantorOpenREEnumerator c) := computable_cantorOpenREEnumerator c
    change Computable (fun n => cantorOpenREEnumerator c x n)
    exact H.comp (Computable.const x) Computable.id
  · rw [range_cantorOpenREEnumerator c x]
    congr
    ext p y
    exact (hc' p y).symm

/-- The stagewise test "the `k`-th enumerated string is `q.1` and `q.2` is the `k`-th
condition code" is computable in the pair and the stage. -/
private lemma computable₂_enumMatchCheck {g : ℕ → Option BitString} (hg : Computable g)
    {c : ℕ → BitString} (hc : Computable c) :
    Computable₂ (fun (q : BitString × BitString) (k : ℕ) =>
      g k == some q.1 && q.2 == c k) := by
  have h_i : Computable (fun (qi : (BitString × BitString) × ℕ) => qi.2) := Computable.snd
  have h_f : Computable (fun (qi : (BitString × BitString) × ℕ) => g qi.2) := hg.comp h_i
  have h_q1 : Computable (fun (qi : (BitString × BitString) × ℕ) => some qi.1.1) :=
    Primrec.option_some.to_comp.comp (Computable.fst.comp Computable.fst)
  have h_enc_f : Computable
      (fun (qi : (BitString × BitString) × ℕ) => Encodable.encode (g qi.2)) :=
    Primrec.encode.to_comp.comp h_f
  have h_enc_q1 : Computable
      (fun (qi : (BitString × BitString) × ℕ) => Encodable.encode (some qi.1.1)) :=
    Primrec.encode.to_comp.comp h_q1
  have h_eq : Computable₂ (fun (a b : ℕ) => a == b) := Primrec.beq.to_comp
  have h_eq1 : Computable (fun (qi : (BitString × BitString) × ℕ) =>
      (Encodable.encode (g qi.2)) == (Encodable.encode (some qi.1.1))) :=
    h_eq.comp h_enc_f h_enc_q1
  have h_q2 : Computable (fun (qi : (BitString × BitString) × ℕ) => qi.1.2) :=
    Computable.snd.comp Computable.fst
  have h_nil : Computable (fun (qi : (BitString × BitString) × ℕ) => c qi.2) :=
    hc.comp h_i
  have h_enc_q2 : Computable
      (fun (qi : (BitString × BitString) × ℕ) => Encodable.encode qi.1.2) :=
    Primrec.encode.to_comp.comp h_q2
  have h_enc_nil : Computable
      (fun (qi : (BitString × BitString) × ℕ) => Encodable.encode (c qi.2)) :=
    Primrec.encode.to_comp.comp h_nil
  have h_eq2 : Computable (fun (qi : (BitString × BitString) × ℕ) =>
      (Encodable.encode qi.1.2) == (Encodable.encode (c qi.2))) :=
    h_eq.comp h_enc_q2 h_enc_nil
  have H_and : Computable (fun (qi : (BitString × BitString) × ℕ) =>
      ((Encodable.encode (g qi.2)) == (Encodable.encode (some qi.1.1))) &&
      ((Encodable.encode qi.1.2) == (Encodable.encode (c qi.2)))) := by
    have h_and : Computable₂ (fun (a b : Bool) => a && b) := by
      have h_and_primrec : Primrec (fun (p : Bool × Bool) => p.1 && p.2) := by
        have h_eq : (fun (p : Bool × Bool) => p.1 && p.2) =
            (fun p : Bool × Bool => bif p.1 then p.2 else false) := by
          ext p; cases p.1 <;> cases p.2 <;> rfl
        rw [h_eq]; exact Primrec.cond Primrec.fst Primrec.snd (Primrec.const false)
      exact h_and_primrec.to_comp
    exact h_and.comp h_eq1 h_eq2
  have H_and_eq : (fun (qi : (BitString × BitString) × ℕ) =>
      ((Encodable.encode (g qi.2)) == (Encodable.encode (some qi.1.1))) &&
      ((Encodable.encode qi.1.2) == (Encodable.encode (c qi.2)))) =
      (fun qi : (BitString × BitString) × ℕ =>
        (fun (q : BitString × BitString) (k : ℕ) =>
          (g k == some q.1) && (q.2 == c k)) qi.1 qi.2) := by
    ext qi
    have h1_iff : ((Encodable.encode (g qi.2)) ==
        (Encodable.encode (some qi.1.1))) = true ↔ (g qi.2 == some qi.1.1) = true := by
      constructor
      · intro h; exact beq_iff_eq.mpr (Encodable.encode_inj.mp (beq_iff_eq.mp h))
      · intro h; exact beq_iff_eq.mpr (congrArg Encodable.encode (beq_iff_eq.mp h))
    have h2_iff : ((Encodable.encode qi.1.2) ==
        (Encodable.encode (c qi.2))) = true ↔ (qi.1.2 == c qi.2) = true := by
      constructor
      · intro h; exact beq_iff_eq.mpr (Encodable.encode_inj.mp (beq_iff_eq.mp h))
      · intro h; exact beq_iff_eq.mpr (congrArg Encodable.encode (beq_iff_eq.mp h))
    have h1_eq : ((Encodable.encode (g qi.2)) == (Encodable.encode (some qi.1.1))) =
        (g qi.2 == some qi.1.1) := by
      cases hc1 : ((Encodable.encode (g qi.2)) == (Encodable.encode (some qi.1.1))) <;>
        cases hc2 : (g qi.2 == some qi.1.1)
      · rfl
      · have : true = false := by have h := h1_iff.mpr hc2; rw [hc1] at h; exact h.symm
        contradiction
      · have : true = false := by have h := h1_iff.mp hc1; rw [hc2] at h; exact h.symm
        contradiction
      · rfl
    have h2_eq : ((Encodable.encode qi.1.2) == (Encodable.encode (c qi.2))) =
        (qi.1.2 == c qi.2) := by
      cases hc1 : ((Encodable.encode qi.1.2) == (Encodable.encode (c qi.2))) <;>
        cases hc2 : (qi.1.2 == c qi.2)
      · rfl
      · have : true = false := by have h := h2_iff.mpr hc2; rw [hc1] at h; exact h.symm
        contradiction
      · have : true = false := by have h := h2_iff.mp hc1; rw [hc2] at h; exact h.symm
        contradiction
      · rfl
    change (((Encodable.encode (g qi.2)) == (Encodable.encode (some qi.1.1))) &&
      ((Encodable.encode qi.1.2) == (Encodable.encode (c qi.2)))) =
      ((g qi.2 == some qi.1.1) && (qi.1.2 == c qi.2))
    rw [h1_eq, h2_eq]
  exact cast (congrArg Computable H_and_eq) H_and

/-- A set of sequences is effectively open exactly when it is generated at the empty string by a
recursively enumerable relation. -/
theorem isEffectiveOpen_iff_exists_cantorOpen
    (U : Set CantorSeq) :
    IsEffectiveOpen U ↔
      ∃ R : BitString → BitString → Prop,
        IsRE (fun q : BitString × BitString => R q.1 q.2) ∧
        U = cantorOpen R [] := by
  constructor
  · rintro ⟨f, hf, hU_eq⟩
    use fun p y => ∃ i, f i = some p ∧ y = []
    constructor
    · let check := fun (q : BitString × BitString) (i : ℕ) =>
        f i == some q.1 && q.2 == []
      have hcheck : Computable₂ check :=
        computable₂_enumMatchCheck hf (Computable.const [])
      have h_rfind : Partrec (fun q => Nat.rfind (check q : ℕ →. Bool)) :=
        Partrec.rfind hcheck.partrec₂
      refine ⟨fun q => (Nat.rfind (check q : ℕ →. Bool)).map (fun _ => ()),
        h_rfind.map (Computable.const ()).to₂, ?_⟩
      intro q
      change (Nat.rfind (check q : ℕ →. Bool)).Dom ↔ _
      rw [Nat.rfind_dom]
      simp only [PFun.coe_val, Part.mem_some_iff]
      have hrfind_simp : (∃ k, true = check q k ∧ ∀ {m : ℕ}, m < k →
          (Part.some (check q m)).Dom) ↔ (∃ k, check q k = true) := by
        constructor
        · rintro ⟨k, hk, _⟩; exact ⟨k, hk.symm⟩
        · rintro ⟨k, hk⟩; exact ⟨k, hk.symm, fun _ => Part.some_dom _⟩
      rw [hrfind_simp]
      constructor
      · rintro ⟨k, hk⟩
        simp only [check, Bool.and_eq_true, beq_iff_eq] at hk
        exact ⟨k, hk.1, hk.2⟩
      · rintro ⟨i, h1, h2⟩
        use i
        simp only [check, h1, h2, beq_self_eq_true, Bool.and_self]
    · rw [hU_eq]
      ext x
      simp only [cantorOpen, mem_iUnion]
      constructor
      · rintro ⟨i, hi⟩
        cases h_f : f i with
        | none => rw [h_f] at hi; exact False.elim hi
        | some v =>
          rw [h_f] at hi
          simp only [Option.elim_some] at hi
          use v
          refine ⟨⟨i, h_f, trivial⟩, hi⟩
      · rintro ⟨p, hR, hp⟩
        obtain ⟨i, hf_eq, -⟩ := hR
        use i; rw [hf_eq]; simp only [Option.elim_some]; exact hp
  · rintro ⟨R, hR, h_eq⟩
    have H := isEffectiveOpen_cantorOpen_of_isRE hR []
    rw [h_eq]
    exact H

/-- Every effectively open set is generated at the empty string by a recursively enumerable
relation. -/
theorem exists_isRE_cantorOpen_of_isEffectiveOpen
    {U : Set CantorSeq} (hU : IsEffectiveOpen U) :
    ∃ R : BitString → BitString → Prop,
      IsRE (fun q : BitString × BitString => R q.1 q.2) ∧ U = cantorOpen R [] :=
  Kolmogorov.isEffectiveOpen_iff_exists_cantorOpen U |>.mp hU

/-- Indexing a recursively enumerable relation by the codes of the naturals gives a uniformly
effective sequence of open sets. -/
theorem isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE
    {R : BitString → BitString → Prop}
    (hR : IsRE fun q : BitString × BitString => R q.1 q.2) :
    IsUniformlyEffectiveOpen (fun n => cantorOpen R (natCode n)) := by
  rcases hR with ⟨f, hf, hfR⟩
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hf
  have hc' : ∀ p y, (c.eval (Encodable.encode (p, y))).Dom ↔ R p y := by
    intro p y
    have h_eq : c.eval (Encodable.encode (p, y)) = (f (p, y)).map Encodable.encode := by
      have hc_app : c.eval (Encodable.encode (p, y)) =
          (fun n => Part.bind (Encodable.decode n : Option (BitString × BitString))
            fun a => (f a).map Encodable.encode) (Encodable.encode (p, y)) := by
        rw [hc]
      rw [hc_app]
      simp
    rw [h_eq]
    simp [hfR]
  use (fun n i => cantorOpenREEnumerator c (natCode n) i)
  constructor
  · have H : Computable (fun p : BitString × ℕ => cantorOpenREEnumerator c p.1 p.2) :=
      computable_cantorOpenREEnumerator c
    have h_natCode_fst : Computable (fun (q : ℕ × ℕ) => natCode q.1) :=
      primrec_natCode.to_comp.comp Computable.fst
    have h_snd : Computable (fun (q : ℕ × ℕ) => q.2) := Computable.snd
    have h_pair : Computable (fun (q : ℕ × ℕ) => (natCode q.1, q.2)) :=
      Computable.pair h_natCode_fst h_snd
    have h_comp := @Computable.comp (ℕ × ℕ) (BitString × ℕ) (Option BitString) _ _ _
      (fun p : BitString × ℕ => cantorOpenREEnumerator c p.1 p.2)
      (fun q : ℕ × ℕ => (natCode q.1, q.2)) H h_pair
    have h_eq : (fun (q : ℕ × ℕ) =>
          (fun (p : BitString × ℕ) => cantorOpenREEnumerator c p.1 p.2) (natCode q.1, q.2)) =
        (fun q : ℕ × ℕ => (fun n i => cantorOpenREEnumerator c (natCode n) i) q.1 q.2) := rfl
    exact cast (congrArg Computable h_eq) h_comp
  · intro n
    rw [range_cantorOpenREEnumerator c (natCode n)]
    have h_R_eq : (fun p y => (c.eval (Encodable.encode (p, y))).Dom) = R := by
      ext p y
      exact hc' p y
    rw [h_R_eq]

/-- A sequence of sets is uniformly effectively open exactly when it is the sequence generated by a
single recursively enumerable relation at the codes of the naturals. -/
theorem isUniformlyEffectiveOpen_iff_exists_cantorOpen_natCode
    (U : ℕ → Set CantorSeq) :
    IsUniformlyEffectiveOpen U ↔
      ∃ R : BitString → BitString → Prop,
        IsRE (fun q : BitString × BitString => R q.1 q.2) ∧
        ∀ n, U n = cantorOpen R (natCode n) := by
  constructor
  · rintro ⟨f, hf, hU_eq⟩
    use fun p y => ∃ i n, f n i = some p ∧ y = natCode n
    constructor
    · let check := fun (q : BitString × BitString) (k : ℕ) =>
        let i := (Nat.unpair k).1
        let n := (Nat.unpair k).2
        f n i == some q.1 && q.2 == natCode n
      have hg : Computable (fun k : ℕ => f (Nat.unpair k).2 (Nat.unpair k).1) :=
        hf.comp (Primrec.snd.comp Primrec.unpair).to_comp
          (Primrec.fst.comp Primrec.unpair).to_comp
      have hcn : Computable (fun k : ℕ => natCode (Nat.unpair k).2) :=
        primrec_natCode.to_comp.comp (Primrec.snd.comp Primrec.unpair).to_comp
      have hcheck : Computable₂ check := computable₂_enumMatchCheck hg hcn
      have h_rfind : Partrec (fun q => Nat.rfind (check q : ℕ →. Bool)) :=
        Partrec.rfind hcheck.partrec₂
      refine ⟨fun q => (Nat.rfind (check q : ℕ →. Bool)).map (fun _ => ()),
        h_rfind.map (Computable.const ()).to₂, ?_⟩
      intro q
      change (Nat.rfind (check q : ℕ →. Bool)).Dom ↔ _
      rw [Nat.rfind_dom]
      simp only [PFun.coe_val, Part.mem_some_iff]
      have hrfind_simp : (∃ k, true = check q k ∧ ∀ {m : ℕ}, m < k →
          (Part.some (check q m)).Dom) ↔ (∃ k, check q k = true) := by
        constructor
        · rintro ⟨k, hk, _⟩; exact ⟨k, hk.symm⟩
        · rintro ⟨k, hk⟩; exact ⟨k, hk.symm, fun _ => Part.some_dom _⟩
      rw [hrfind_simp]
      constructor
      · rintro ⟨k, hk⟩
        simp only [check, Bool.and_eq_true, beq_iff_eq] at hk
        exact ⟨(Nat.unpair k).1, (Nat.unpair k).2, hk.1, hk.2⟩
      · rintro ⟨i, n, h1, h2⟩
        use Nat.pair i n
        simp only [check, Nat.unpair_pair, h1, h2, beq_self_eq_true, Bool.and_self]
    · intro n
      rw [hU_eq n]
      ext x
      simp only [cantorOpen, mem_iUnion]
      constructor
      · rintro ⟨i, hi⟩
        cases h_f : f n i with
        | none => rw [h_f] at hi; exact False.elim hi
        | some v =>
          rw [h_f] at hi
          simp only [Option.elim_some] at hi
          use v
          refine ⟨⟨i, n, h_f, rfl⟩, hi⟩
      · rintro ⟨p, hR, hp⟩
        obtain ⟨i, n', hi, hn'⟩ := hR
        have h_n_eq : n' = n := natCode_injective hn'.symm
        subst h_n_eq
        use i
        rw [hi]
        simp only [Option.elim_some]
        exact hp
  · rintro ⟨R, hR, h_eq⟩
    have H := Kolmogorov.isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE hR
    have h_U : U = fun n => cantorOpen R (natCode n) := funext h_eq
    rw [h_U]
    exact H

end Kolmogorov
