import KolmogorovMathlib.MonotoneComplexity.CylinderMass
import KolmogorovMathlib.Foundation.RecursivelyEnumerable
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinCore.LSCApproximation
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinCore.UniformNumerators
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinCore

/-!
# Effective open subsets of Cantor space

This module defines `cantorOpen` and establishes its basic topological
and measure-theoretic properties.
-/

namespace Kolmogorov

open MeasureTheory
open scoped ENNReal

/-- An effective open subset of Cantor space parameterized by a binary relation `R`. -/
def cantorOpen (R : BitString → BitString → Prop) (x : BitString) : Set CantorSeq :=
  ⋃ p, ⋃ (_ : R p x), cantorCylinder p

/-- The set generated by an enumeration relation at `x` is open. -/
lemma isOpen_cantorOpen (R : BitString → BitString → Prop) (x : BitString) :
    IsOpen (cantorOpen R x) := by
  apply isOpen_iUnion
  intro p
  apply isOpen_iUnion
  intro _
  exact isOpen_cantorCylinder p

/-- The set generated by an enumeration relation at `x` is measurable. -/
lemma measurableSet_cantorOpen (R : BitString → BitString → Prop) (x : BitString) :
    MeasurableSet (cantorOpen R x) :=
  (isOpen_cantorOpen R x).measurableSet

/-- The uniform measure of the open set generated at `x`. -/
noncomputable def cantorOpenMass (R : BitString → BitString → Prop) (x : BitString) : ℝ≥0∞ :=
  uniformMeasure (cantorOpen R x)

/-- The strings enumerated at `x` by stage `s`. -/
def discoveredPrefixes (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) : Finset BitString :=
  (boundedPrograms s).toFinset.filter fun p =>
    (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome

/-- The number of strings of length `s` covered by what has been enumerated at `x` by stage `s`. -/
def coveredCount (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) : ℕ :=
  ((exactLengthPrograms s).toFinset.filter fun z =>
    ∃ p ∈ discoveredPrefixes c s x, p <+: z).card

/-- The sequences covered at `x` by stage `s`. -/
def coveredSet (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) : Set CantorSeq :=
  ⋃ z ∈ (exactLengthPrograms s).toFinset.filter (fun z =>
    ∃ p ∈ discoveredPrefixes c s x, p <+: z), cantorCylinder z

/-- The enumerated strings only accumulate. -/
lemma discoveredPrefixes_mono (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) :
    discoveredPrefixes c s x ⊆ discoveredPrefixes c (s + 1) x := by
  intro p hp
  simp only [discoveredPrefixes, Finset.mem_filter, List.mem_toFinset] at hp ⊢
  refine ⟨?_, ?_⟩
  · apply (mem_boundedPrograms_iff p (s + 1)).mpr
    apply le_trans ((mem_boundedPrograms_iff p s).mp hp.1) (Nat.le_succ s)
  · obtain ⟨v, hv⟩ := Option.isSome_iff_exists.mp hp.2
    exact Option.isSome_iff_exists.mpr ⟨v, Nat.Partrec.Code.evaln_mono (Nat.le_succ s) hv⟩

/-- The covered sets only grow. -/
lemma coveredSet_mono (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) :
    coveredSet c s x ⊆ coveredSet c (s + 1) x := by
  intro w hw
  simp only [coveredSet, Set.mem_iUnion, Finset.mem_filter, List.mem_toFinset, exists_prop,
    cantorCylinder, Set.mem_setOf_eq, isCantorPrefix_iff_cantorPrefix_eq] at hw ⊢
  rcases hw with ⟨z, ⟨hz_len, p, hp, hpz⟩, hwz⟩
  let z' := cantorPrefix w (s + 1)
  have hz'_len : z' ∈ exactLengthPrograms (s + 1) := by
    have h : (s + 1) = z'.length := (cantorPrefix_length w (s + 1)).symm
    rw [h]
    exact mem_exactLengthPrograms_self z'
  use z'
  have hz' : cantorPrefix w z'.length = z' := by
    rw [cantorPrefix_length w (s + 1)]
  refine ⟨⟨hz'_len, p, discoveredPrefixes_mono c s x hp, ?_⟩, hz'⟩
  have hzs : z.length = s := exactLengthPrograms_length_eq s z hz_len
  have hz_pref_z' : z <+: z' := by
    rw [← hwz, hzs]
    exact cantorPrefix_mono w (Nat.le_succ s)
  exact List.IsPrefix.trans hpz hz_pref_z'



/-- The measure of the stage-`s` covered set is its count in units of `2 ^ -s`. -/
lemma measure_coveredSet_eq_dyadic (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) :
    uniformMeasure (coveredSet c s x) = dyadicValue (coveredCount c s x) s := by
  unfold coveredSet dyadicValue
  rw [MeasureTheory.measure_biUnion_finset]
  · simp only [uniformMeasure_cantorCylinder]
    have h_eq : (∑ x ∈ (exactLengthPrograms s).toFinset.filter
        (fun z => ∃ p ∈ discoveredPrefixes c s x, p <+: z), (2 : ENNReal)⁻¹ ^ x.length)
        = ∑ x ∈ (exactLengthPrograms s).toFinset.filter
            (fun z => ∃ p ∈ discoveredPrefixes c s x, p <+: z), (2 : ENNReal)⁻¹ ^ s := by
      apply Finset.sum_congr rfl
      intro z hz
      simp only [Finset.mem_filter, List.mem_toFinset] at hz
      rw [exactLengthPrograms_length_eq s z hz.1]
    rw [h_eq]
    rw [Finset.sum_const]
    unfold coveredCount
    rw [div_eq_mul_inv, ENNReal.inv_pow]
    exact nsmul_eq_mul (α := ENNReal) _ _
  · intro z1 hz1 z2 hz2 hneq
    simp only [Finset.mem_coe, Finset.mem_filter, List.mem_toFinset] at hz1 hz2
    have h_len1 := exactLengthPrograms_length_eq s z1 hz1.1
    have h_len2 := exactLengthPrograms_length_eq s z2 hz2.1
    apply cantorCylinder_disjoint_of_incompatible
    · intro h
      have h_eq : z1 = z2 := by
        obtain ⟨t, ht⟩ := h
        have ht_len : z2.length = z1.length + t.length := by rw [← ht, List.length_append]
        have : t.length = 0 := by omega
        have ht_nil : t = [] := by cases t <;> simp at this; rfl
        rw [ht_nil, List.append_nil] at ht
        exact ht
      exact hneq h_eq
    · intro h
      have h_eq : z2 = z1 := by
        obtain ⟨t, ht⟩ := h
        have ht_len : z1.length = z2.length + t.length := by rw [← ht, List.length_append]
        have : t.length = 0 := by omega
        have ht_nil : t = [] := by cases t <;> simp at this; rfl
        rw [ht_nil, List.append_nil] at ht
        exact ht
      exact hneq h_eq.symm
  · intro z _
    exact measurableSet_cantorCylinder z

/-- The covered count at least doubles from one stage to the next. -/
lemma coveredCount_succ_ge_two_mul (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) :
    2 * coveredCount c s x ≤ coveredCount c (s + 1) x := by
  unfold coveredCount
  let F (n : ℕ) :=
    (exactLengthPrograms n).toFinset.filter (fun z => ∃ p ∈ discoveredPrefixes c n x, p <+: z)
  change 2 * (F s).card ≤ (F (s + 1)).card
  let f_false (z : List Bool) := z ++ [false]
  let f_true (z : List Bool) := z ++ [true]
  have h_inj_false : ∀ z1 ∈ F s, ∀ z2 ∈ F s, f_false z1 = f_false z2 → z1 = z2 := by
    intro z1 _ z2 _ h
    exact List.append_cancel_right h
  have h_inj_true : ∀ z1 ∈ F s, ∀ z2 ∈ F s, f_true z1 = f_true z2 → z1 = z2 := by
    intro z1 _ z2 _ h
    exact List.append_cancel_right h
  have h_disj : Disjoint (Finset.image f_false (F s)) (Finset.image f_true (F s)) := by
    rw [Finset.disjoint_iff_ne]
    intro w1 hw1 w2 hw2 h_eq
    simp only [Finset.mem_image] at hw1 hw2
    rcases hw1 with ⟨z1, _, rfl⟩
    rcases hw2 with ⟨z2, _, rfl⟩
    have h_eq_str : z1 ++ [false] = z2 ++ [true] := h_eq
    have h_len : (z1 ++ [false]).length = (z2 ++ [true]).length := by rw [h_eq_str]
    simp only [List.length_append, List.length_singleton, add_right_cancel_iff] at h_len
    have h_inj := List.append_inj h_eq_str h_len
    cases h_inj.2
  have h_map_false : Finset.image f_false (F s) ⊆ F (s + 1) := by
    intro w hw
    rcases Finset.mem_image.mp hw with ⟨z, hz, rfl⟩
    dsimp [F] at hz ⊢
    simp only [Finset.mem_filter, List.mem_toFinset] at hz ⊢
    refine ⟨?_, ?_⟩
    · have h_len := exactLengthPrograms_length_eq s z hz.1
      have hw_len : (z ++ [false]).length = s + 1 := by rw [List.length_append, h_len]; rfl
      rw [← hw_len]
      exact mem_exactLengthPrograms_self _
    · rcases hz.2 with ⟨p, hp, hpz⟩
      refine ⟨p, discoveredPrefixes_mono c s x hp, hpz.trans ⟨[false], rfl⟩⟩
  have h_map_true : Finset.image f_true (F s) ⊆ F (s + 1) := by
    intro w hw
    rcases Finset.mem_image.mp hw with ⟨z, hz, rfl⟩
    dsimp [F] at hz ⊢
    simp only [Finset.mem_filter, List.mem_toFinset] at hz ⊢
    refine ⟨?_, ?_⟩
    · have h_len := exactLengthPrograms_length_eq s z hz.1
      have hw_len : (z ++ [true]).length = s + 1 := by rw [List.length_append, h_len]; rfl
      rw [← hw_len]
      exact mem_exactLengthPrograms_self _
    · rcases hz.2 with ⟨p, hp, hpz⟩
      refine ⟨p, discoveredPrefixes_mono c s x hp, hpz.trans ⟨[true], rfl⟩⟩
  have h_union : Finset.image f_false (F s) ∪ Finset.image f_true (F s) ⊆ F (s + 1) :=
    Finset.union_subset h_map_false h_map_true
  have h_card_union : (Finset.image f_false (F s) ∪ Finset.image f_true (F s)).card
      = (Finset.image f_false (F s)).card + (Finset.image f_true (F s)).card :=
    Finset.card_union_of_disjoint h_disj
  have h_card_false : (Finset.image f_false (F s)).card = (F s).card :=
    Finset.card_image_of_injOn h_inj_false
  have h_card_true : (Finset.image f_true (F s)).card = (F s).card :=
    Finset.card_image_of_injOn h_inj_true
  rw [h_card_false, h_card_true] at h_card_union
  have : 2 * (F s).card = (Finset.image f_false (F s) ∪ Finset.image f_true (F s)).card := by
    rw [h_card_union, two_mul]
  rw [this]
  exact Finset.card_le_card h_union

/-- The covered sets exhaust the open set generated by the relation. -/
lemma iUnion_coveredSet_eq_cantorOpen (R : BitString → BitString → Prop) (c : Nat.Partrec.Code)
    (hc : ∀ p x, (c.eval (Encodable.encode (p, x))).Dom ↔ R p x)
    (x : BitString) :
    (⋃ s, coveredSet c s x) = cantorOpen R x := by
  ext w
  simp only [coveredSet, Set.mem_iUnion, Finset.mem_filter, List.mem_toFinset, exists_prop,
    cantorCylinder, Set.mem_setOf_eq, cantorOpen, isCantorPrefix_iff_cantorPrefix_eq]
  constructor
  · rintro ⟨s, z, ⟨hz_len, p, hp, hpz⟩, hwz⟩
    simp only [discoveredPrefixes, Finset.mem_filter, List.mem_toFinset] at hp
    have h_dom : (c.eval (Encodable.encode (p, x))).Dom := by
      obtain ⟨v, hv⟩ := Option.isSome_iff_exists.mp hp.2
      exact Part.dom_iff_mem.mpr ⟨v, Nat.Partrec.Code.evaln_sound hv⟩
    use p
    refine ⟨(hc p x).mp h_dom, ?_⟩
    have h_pref1 : p <+: z := hpz
    have h_pref2 : z <+: cantorPrefix w z.length := by rw [hwz]
    have h_pref := List.IsPrefix.trans h_pref1 h_pref2
    have h_eq : p = List.take p.length z := by
      obtain ⟨rest, hrest⟩ := hpz
      rw [← hrest, List.take_left]
    rw [← hwz] at h_eq
    have h_take : List.take p.length (cantorPrefix w z.length) = cantorPrefix w p.length := by
      have h_le : p.length ≤ z.length := List.IsPrefix.length_le hpz
      exact List.ext_getElem (by simp [h_le]) (fun i h1 h2 => by simp [cantorPrefix])
    rw [h_take] at h_eq
    exact h_eq.symm
  · rintro ⟨p, ⟨hR, hpw⟩⟩
    have h_dom := (hc p x).mpr hR
    obtain ⟨v, hv⟩ := Part.dom_iff_mem.mp h_dom
    obtain ⟨s_fuel, h_evaln⟩ := Nat.Partrec.Code.evaln_complete.mp hv
    have h_isSome : (Nat.Partrec.Code.evaln s_fuel c (Encodable.encode (p, x))).isSome := by
      exact Option.isSome_iff_exists.mpr ⟨v, h_evaln⟩
    let s := max s_fuel p.length
    use s
    let z := cantorPrefix w s
    use z
    have hz_len : z.length = s := cantorPrefix_length w s
    have hz_in : z ∈ exactLengthPrograms s := by
      rw [← hz_len]
      exact mem_exactLengthPrograms_self z
    refine ⟨⟨hz_in, p, ?_, ?_⟩, by rw [hz_len]⟩
    · simp only [discoveredPrefixes, Finset.mem_filter, List.mem_toFinset]
      refine ⟨?_, ?_⟩
      · apply (mem_boundedPrograms_iff p s).mpr
        exact le_max_right s_fuel p.length
      · exact Option.isSome_iff_exists.mpr
          ⟨v, Nat.Partrec.Code.evaln_mono (le_max_left s_fuel p.length) h_evaln⟩
    · have h_eq : p = List.take p.length z := by
        have h_le : p.length ≤ s := le_max_right s_fuel p.length
        have : cantorPrefix w p.length = List.take p.length (cantorPrefix w s) := by
          exact List.ext_getElem (by simp [h_le]) (fun i h1 h2 => by simp [cantorPrefix])
        rw [← this, hpw]
      rw [h_eq]
      exact ⟨z.drop p.length, List.take_append_drop p.length z⟩


/-- The length of a filtered list is the sum of the indicator values. -/
lemma list_length_filter_eq_sum {α : Type*} (L : List α) (P : α → Bool) :
    (L.filter (fun a => P a)).length = (L.map (fun a => if P a then 1 else 0)).sum := by
  induction L with
  | nil => rfl
  | cons hd tl ih =>
    simp only [List.filter_cons, List.map_cons, List.sum_cons]
    by_cases h : P hd = true
    · simp [h, ih]; omega
    · have h' : P hd = false := by exact Bool.eq_false_iff.mpr h
      simp [h', ih]

/-- A list satisfies a predicate somewhere exactly when the sum of the indicators is positive. -/
lemma list_any_eq_sum {α : Type*} (L : List α) (P : α → Bool) :
    (L.any P = true) ↔ ((L.map (fun a => if P a then 1 else 0)).sum > 0) := by
  induction L with
  | nil => simp
  | cons hd tl ih =>
    simp only [List.any_cons, List.map_cons, List.sum_cons, Bool.or_eq_true]
    by_cases h : P hd = true
    · simp [h]
    · have h' : P hd = false := by exact Bool.eq_false_iff.mpr h
      simp [h', ih]

/-- Existence of an entry satisfying a decidable predicate, as positivity of an indicator sum. -/
lemma list_exists_eq_sum {α : Type*} (L : List α) (P : α → Prop) [DecidablePred P] :
    (∃ x ∈ L, P x) ↔ ((L.map (fun a => if P a then (1:ℕ) else 0)).sum > 0) := by
  induction L with
  | nil => simp
  | cons hd tl ih =>
    simp only [List.mem_cons, exists_eq_or_imp, List.map_cons, List.sum_cons]
    by_cases h : P hd
    · simp [h]
    · simp [h, ih]

/-- The prefix relation on strings of a fixed length, as positivity of an indicator sum. -/
lemma isPrefixOf_eq_sum (s : ℕ) (p z : BitString) (hz : z.length = s) :
    (p <+: z) ↔
      (((boundedPrograms s).map (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0) := by
  have : (fun ext => if decide (p ++ ext = z) then 1 else 0)
      = (fun ext => if p ++ ext = z then 1 else 0) := by
    ext ext; by_cases h : p ++ ext = z <;> simp [h]
  rw [this, ← list_exists_eq_sum]
  constructor
  · rintro ⟨ext, hext⟩
    have h_len : ext.length ≤ s := by
      have : (p ++ ext).length = z.length := congrArg List.length hext
      rw [List.length_append, hz] at this
      omega
    exact ⟨ext, (mem_boundedPrograms_iff ext s).mpr h_len, hext⟩
  · rintro ⟨ext, _, hext⟩
    exact ⟨ext, hext⟩

/-- The covered count, written as a nested indicator sum, which is the primitive recursive shape. -/
lemma coveredCount_eq_sum (c : Nat.Partrec.Code) (s : ℕ) (x : BitString) :
    coveredCount c s x = ((exactLengthPrograms s).map (fun z =>
      if decide (((boundedPrograms s).map (fun p =>
        if ((Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome
          && decide (((boundedPrograms s).map
            (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0)) then 1 else 0)).sum > 0)
      then 1 else 0)).sum := by
  have H : coveredCount c s x = ((exactLengthPrograms s).filter (fun z =>
      (boundedPrograms s).any (fun p =>
        ((Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome
          && decide (p <+: z))))).length := by
    unfold coveredCount discoveredPrefixes
    rw [← List.toFinset_card_of_nodup (List.Nodup.filter _ (exactLengthPrograms_nodup s))]
    congr 1
    ext z
    simp only [Finset.mem_filter, List.mem_toFinset, List.mem_filter, List.any_eq_true,
      Bool.and_eq_true, decide_eq_true_eq]
    constructor
    · rintro ⟨hz1, p, ⟨hp1, hp2⟩, hpz⟩
      refine ⟨hz1, p, hp1, hp2, hpz⟩
    · rintro ⟨hz1, p, hp, h1, h2⟩
      refine ⟨hz1, p, ⟨hp, h1⟩, h2⟩
  rw [H]
  rw [list_length_filter_eq_sum]
  congr 1
  apply List.map_congr_left
  intro z hz
  have h_len : z.length = s := exactLengthPrograms_length_eq s z hz
  have h_subst : (fun p => (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome
      && decide (p <+: z))
    = (fun p => (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome
        && decide (((boundedPrograms s).map
          (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0)) := by
    ext p
    have h_iff := isPrefixOf_eq_sum s p z h_len
    have h_dec : decide (p <+: z)
        = decide (((boundedPrograms s).map
          (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0) :=
      decide_eq_decide.mpr h_iff
    rw [h_dec]
  rw [h_subst]
  have h_eq := list_any_eq_sum (boundedPrograms s)
    (fun p => (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome
      && decide (((boundedPrograms s).map
        (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0))
  by_cases hh : ((boundedPrograms s).any fun p =>
      (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome &&
        decide (0 < (List.map
          (fun ext => if decide (p ++ ext = z) then 1 else 0) (boundedPrograms s)).sum)) = true
  · have hh2 := h_eq.mp hh
    simp only [Bool.and_eq_true, decide_eq_true_eq, List.any_eq_true] at hh hh2 ⊢
    rw [if_pos hh, if_pos hh2]
  · have hh_false : ((boundedPrograms s).any fun p =>
      (Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome &&
        decide (0 < (List.map
          (fun ext => if decide (p ++ ext = z) then 1 else 0) (boundedPrograms s)).sum)) = false :=
      Bool.eq_false_iff.mpr hh
    have hh2 : ¬ (((boundedPrograms s).map fun p =>
          if
            ((Nat.Partrec.Code.evaln s c (Encodable.encode (p, x))).isSome &&
                decide (0 < (List.map
                  (fun ext => if decide (p ++ ext = z) then 1 else 0) (boundedPrograms s)).sum))
          then 1
          else 0).sum >
      0) := fun hh3 => hh (h_eq.mpr hh3)
    simp only [Bool.and_eq_true, decide_eq_true_eq, List.any_eq_true] at hh hh2 ⊢
    rw [if_neg hh, if_neg hh2]



/-- The covered count is computable in the stage and the string. -/
lemma computable_coveredCount (c : Nat.Partrec.Code) :
    Computable (fun q : ℕ × BitString => coveredCount c q.1 q.2) := by
  have h_sum : Primrec (fun l : List ℕ ↦ List.sum l) := by
    convert Primrec.list_foldr _ _ _ using 1
    rotate_left
    · exact ℕ
    · exact inferInstance
    · exact fun l ↦ l
    · exact fun _ ↦ 0
    · exact fun l p ↦ p.1 + p.2
    · exact Primrec.id
    · exact Primrec.const 0
    · exact Primrec.nat_add.comp (Primrec.fst.comp Primrec.snd) (Primrec.snd.comp Primrec.snd)
    · exact funext fun l ↦ by induction l <;> simp +decide [*]
  have h_if : Primrec (fun q : Bool ↦ if q then 1 else 0) := by
    convert Primrec.cond _ _ _
    rotate_left
    · exact fun x ↦ x
    · exact Primrec.id
    · exact Primrec.const 1
    · exact Primrec.const 0
    · cases ‹_› <;> rfl
  have h_gt0 : Primrec (fun n : ℕ => decide (n > 0)) := by
    have : (fun n : ℕ => decide (n > 0)) = fun n => n.casesOn false (fun _ => true) := by
      ext n; cases n <;> rfl
    rw [this]
    exact Primrec.nat_casesOn Primrec.id (Primrec.const false) (Primrec.const true)
  have h_eq : Primrec (fun q : List Bool × List Bool => decide (q.1 = q.2)) := by
    have ⟨_, H⟩ : PrimrecRel (@Eq (List Bool)) := Primrec.eq
    convert H
  have h_and : Primrec (fun q : Bool × Bool => q.1 && q.2) := by
    have : (fun (q : Bool × Bool) => q.1 && q.2) = fun q => cond q.1 q.2 false := by
      ext q; cases q.1 <;> rfl
    rw [this]
    exact Primrec.cond Primrec.fst Primrec.snd (Primrec.const false)
  have h_evaln : Primrec (fun q : (ℕ × BitString) × BitString =>
      (Nat.Partrec.Code.evaln q.1.1 c (Encodable.encode (q.2, q.1.2))).isSome) := by
    have := Nat.Partrec.Code.primrec_evaln
    have h1 : Primrec (fun q : (ℕ × BitString) × BitString => Encodable.encode (q.2, q.1.2)) :=
      Primrec.encode.comp (Primrec.pair Primrec.snd (Primrec.snd.comp Primrec.fst))
    convert Primrec.option_isSome.comp
      (this.comp (Primrec.pair (Primrec.pair (Primrec.fst.comp Primrec.fst) (Primrec.const c)) h1))
      using 1
  have h_inner_sum : Primrec (fun q : (ℕ × BitString) × BitString × BitString =>
      decide (((boundedPrograms q.1.1).map
        (fun ext => if decide (q.2.2 ++ ext = q.2.1) then 1 else 0)).sum > 0)) := by
    have h_map : Primrec (fun q : (ℕ × BitString) × BitString × BitString =>
        (boundedPrograms q.1.1).map
          (fun ext => if decide (q.2.2 ++ ext = q.2.1) then 1 else 0)) := by
      refine Primrec.list_map ?_ ?_
      · exact primrec_boundedPrograms.comp (Primrec.fst.comp Primrec.fst)
      · have hh_eq : Primrec (fun q' : ((ℕ × BitString) × BitString × BitString) × BitString =>
            decide (q'.1.2.2 ++ q'.2 = q'.1.2.1)) := by
          have left_app :
              Primrec (fun q' : ((ℕ × BitString) × BitString × BitString) × BitString =>
                q'.1.2.2 ++ q'.2) :=
            Primrec.list_append.comp (Primrec.snd.comp (Primrec.snd.comp Primrec.fst)) Primrec.snd
          have right_app :
              Primrec (fun q' : ((ℕ × BitString) × BitString × BitString) × BitString =>
                q'.1.2.1) :=
            Primrec.fst.comp (Primrec.snd.comp Primrec.fst)
          exact h_eq.comp (Primrec.pair left_app right_app)
        exact h_if.comp hh_eq
    exact h_gt0.comp (h_sum.comp h_map)
  have h_middle_sum : Primrec (fun q : (ℕ × BitString) × BitString =>
      decide (((boundedPrograms q.1.1).map (fun p =>
        if ((Nat.Partrec.Code.evaln q.1.1 c (Encodable.encode (p, q.1.2))).isSome
          && decide (((boundedPrograms q.1.1).map
            (fun ext => if decide (p ++ ext = q.2) then 1 else 0)).sum > 0))
          then 1 else 0)).sum > 0)) := by
    have h_map : Primrec (fun q : (ℕ × BitString) × BitString =>
        (boundedPrograms q.1.1).map (fun p =>
          if ((Nat.Partrec.Code.evaln q.1.1 c (Encodable.encode (p, q.1.2))).isSome
            && decide (((boundedPrograms q.1.1).map
              (fun ext => if decide (p ++ ext = q.2) then 1 else 0)).sum > 0))
            then 1 else 0)) := by
      refine Primrec.list_map ?_ ?_
      · exact primrec_boundedPrograms.comp (Primrec.fst.comp Primrec.fst)
      · have h_cond : Primrec (fun q' : ((ℕ × BitString) × BitString) × BitString =>
            (Nat.Partrec.Code.evaln q'.1.1.1 c (Encodable.encode (q'.2, q'.1.1.2))).isSome
            && decide (((boundedPrograms q'.1.1.1).map
              (fun ext => if decide (q'.2 ++ ext = q'.1.2) then 1 else 0)).sum > 0)) := by
          have h_left : Primrec (fun q' : ((ℕ × BitString) × BitString) × BitString =>
              (Nat.Partrec.Code.evaln q'.1.1.1 c (Encodable.encode (q'.2, q'.1.1.2))).isSome) :=
            h_evaln.comp (Primrec.pair (Primrec.fst.comp Primrec.fst) Primrec.snd)
          have h_right : Primrec (fun q' : ((ℕ × BitString) × BitString) × BitString =>
              decide (((boundedPrograms q'.1.1.1).map
                (fun ext => if decide (q'.2 ++ ext = q'.1.2) then 1 else 0)).sum > 0)) := by
            have h_arg : Primrec (fun q' : ((ℕ × BitString) × BitString) × BitString =>
                (q'.1.1, (q'.1.2, q'.2))) :=
              Primrec.pair (Primrec.fst.comp Primrec.fst)
                (Primrec.pair (Primrec.snd.comp Primrec.fst) Primrec.snd)
            exact h_inner_sum.comp h_arg
          exact h_and.comp (Primrec.pair h_left h_right)
        exact h_if.comp h_cond
    exact h_gt0.comp (h_sum.comp h_map)
  have h_outer_sum : Primrec (fun q : ℕ × BitString => ((exactLengthPrograms q.1).map (fun z =>
      if decide (((boundedPrograms q.1).map (fun p =>
        if ((Nat.Partrec.Code.evaln q.1 c (Encodable.encode (p, q.2))).isSome
          && decide (((boundedPrograms q.1).map
            (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0)) then 1 else 0)).sum > 0)
      then 1 else 0)).sum) := by
    have h_map : Primrec (fun q : ℕ × BitString => ((exactLengthPrograms q.1).map (fun z =>
        if decide (((boundedPrograms q.1).map (fun p =>
          if ((Nat.Partrec.Code.evaln q.1 c (Encodable.encode (p, q.2))).isSome
            && decide (((boundedPrograms q.1).map
              (fun ext => if decide (p ++ ext = z) then 1 else 0)).sum > 0))
            then 1 else 0)).sum > 0)
        then 1 else 0))) := by
      refine Primrec.list_map ?_ ?_
      · exact primrec_exactLengthPrograms.comp Primrec.fst
      · exact h_if.comp h_middle_sum
    exact h_sum.comp h_map
  convert Primrec.to_comp h_outer_sum using 1
  ext q
  exact coveredCount_eq_sum c q.1 q.2



/-- The covered sets are monotone in the stage. -/
lemma coveredSet_mono_sets (c : Nat.Partrec.Code) (x : BitString) :
    Monotone (fun s => coveredSet c s x) := by
  apply monotone_nat_of_le_succ
  intro s w hw
  simp only [coveredSet, Set.mem_iUnion, Finset.mem_filter, List.mem_toFinset, exists_prop,
    cantorCylinder, Set.mem_setOf_eq, isCantorPrefix_iff_cantorPrefix_eq] at hw ⊢
  rcases hw with ⟨z1, ⟨hz1_len, p, hp, hpz1⟩, hwz1⟩
  use cantorPrefix w (s + 1)
  have hz2_len : (cantorPrefix w (s + 1)).length = s + 1 := cantorPrefix_length w (s + 1)
  have hz2_in : cantorPrefix w (s + 1) ∈ exactLengthPrograms (s + 1) := by
    have h := mem_exactLengthPrograms_self (cantorPrefix w (s + 1))
    rw [hz2_len] at h
    exact h
  refine ⟨⟨hz2_in, p, ?_, ?_⟩, by rw [hz2_len]⟩
  · exact discoveredPrefixes_mono c s x hp
  · have h_pref1 : p <+: z1 := hpz1
    have h_pref2 : z1 <+: cantorPrefix w z1.length := by rw [hwz1]
    have h_pref_z1 : p <+: cantorPrefix w z1.length := List.IsPrefix.trans h_pref1 h_pref2
    have h_len_p : p.length ≤ z1.length := List.IsPrefix.length_le h_pref1
    have h_eq : p = List.take p.length (cantorPrefix w z1.length) := by
      obtain ⟨rest, hrest⟩ := h_pref_z1
      rw [← hrest, List.take_left]
    have h_take : List.take p.length (cantorPrefix w z1.length) = cantorPrefix w p.length := by
      apply List.ext_getElem
      · simp [cantorPrefix_length, h_len_p]
      · intro i h1 h2
        simp [cantorPrefix]
    rw [h_take] at h_eq
    have h_le : p.length ≤ s + 1 := by
      have : z1.length = s := exactLengthPrograms_length_eq s z1 hz1_len
      omega
    have h_eq2 : p = List.take p.length (cantorPrefix w (s + 1)) := by
      generalize hk : s + 1 = n
      have h_len_p_le_n : p.length ≤ n := by omega
      have h_z2 : cantorPrefix w p.length = List.take p.length (cantorPrefix w n) := by
        apply List.ext_getElem
        · simp [cantorPrefix_length, h_len_p_le_n]
        · intro i h1 h2
          simp [cantorPrefix]
      rw [← h_z2]
      exact h_eq
    rw [h_eq2]
    exact ⟨_, List.take_append_drop p.length _⟩

/-- The measure of the open set generated by a recursively enumerable relation is lower
semicomputable in the parameter. -/
theorem cantorOpenMass_isLSC {R : BitString → BitString → Prop}
    (hR : IsRE fun q : BitString × BitString => R q.1 q.2) :
    IsLSC fun x _ => cantorOpenMass R x := by
  rcases hR with ⟨f, hf, hfR⟩
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hf
  have hc' : ∀ p x, (c.eval (Encodable.encode (p, x))).Dom ↔ R p x := by
    intro p x
    have h_eq : c.eval (Encodable.encode (p, x)) = (f (p, x)).map Encodable.encode := by
      have hc_app : c.eval (Encodable.encode (p, x)) =
          (fun n => Part.bind (Encodable.decode n : Option (BitString × BitString))
            fun a => (f a).map Encodable.encode) (Encodable.encode (p, x)) := by
        rw [hc]
      rw [hc_app]
      simp
    rw [h_eq]
    simp [hfR]
  use fun s x _ => coveredCount c s x
  refine ⟨?_, ?_, ?_⟩
  · intro s x _
    have h_le := coveredCount_succ_ge_two_mul c s x
    unfold dyadicValue
    have h1 : (coveredCount c s x : ENNReal) / 2 ^ s
        = (coveredCount c s x * 2 : ENNReal) / 2 ^ (s + 1) := by
      rw [pow_succ]
      have h_mul := ENNReal.mul_div_mul_right (c := 2)
        (a := (coveredCount c s x : ENNReal)) (b := 2 ^ s) (by norm_num) (by norm_num)
      exact h_mul.symm
    rw [h1]
    have h_le_coe : (coveredCount c s x * 2 : ENNReal) ≤ (coveredCount c (s + 1) x : ENNReal) := by
      calc (coveredCount c s x * 2 : ENNReal)
        _ = ((coveredCount c s x * 2 : ℕ) : ENNReal) := by norm_cast
        _ = ((2 * coveredCount c s x : ℕ) : ENNReal) := by rw [mul_comm]
        _ ≤ ((coveredCount c (s + 1) x : ℕ) : ENNReal) := by exact_mod_cast h_le
    gcongr
  · intro x _
    change ⨆ s, dyadicValue (coveredCount c s x) s = uniformMeasure (cantorOpen R x)
    rw [← iUnion_coveredSet_eq_cantorOpen R c hc' x]
    have h_mono : Monotone (fun s => coveredSet c s x) := coveredSet_mono_sets c x
    have h_sup_eval := h_mono.measure_iUnion (μ := uniformMeasure)
    have h_dyad : ∀ s, dyadicValue (coveredCount c s x) s = uniformMeasure (coveredSet c s x) :=
      fun s => (measure_coveredSet_eq_dyadic c s x).symm
    simp_rw [h_dyad]
    exact h_sup_eval.symm
  · change Computable ((fun q : ℕ × BitString => coveredCount c q.1 q.2)
      ∘ (fun p : ℕ × BitString × BitString => (p.1, p.2.1)))
    apply Computable.comp (Kolmogorov.computable_coveredCount c)
    apply Computable.pair Computable.fst (Computable.fst.comp Computable.snd)


end Kolmogorov
