import KolmogorovMathlib.MonotoneComplexity.GacsDayLadderStep

/-!
# Joint computability of the ladder, via codes

`exists_grayLadderStep` (in `GacsDayLadderStepClosure`) asks for a transformer
`F` of family strategy schemes whose iterate `ladderScheme F` is computable
*jointly in the amplification stage*. That joint computability cannot be read
off from stage-wise computability: `ladderScheme F k` is obtained by `k`
applications of `F`, so one needs a uniform, effective description of the
transformer itself.

This file supplies exactly that reduction. The effective description used is the standard
one: a *code transformer*. If

* `c0` is a code for the base scheme,
* `G : ℕ → Code → Code` is a computable map on codes, and
* `G k` turns any code for a scheme `sigma` into a code for `F k sigma`,

then `ladderScheme F` is computable in the sense of
`UniformFamilyStrategySchemeComputable`
(`uniformFamilyStrategySchemeComputable_ladderScheme`).

Nothing here presupposes the construction: the code transformer is data a
future half-step has to produce, and `exists_code_of_familyStrategySchemeComputable`
shows the base code always exists.

The two general lemmas `exists_code_of_computable` and
`computable_of_codeFamily` are stated for arbitrary primcodable types; they are
the only computability facts used.
-/

namespace Kolmogorov

open Encodable

/-! ### Codes for total computable functions -/

/-- `c` is a code for the total function `f`: on the encoding of any input it
converges to the encoding of the value. -/
def CodeComputes {α σ : Type} [Primcodable α] [Primcodable σ]
    (c : Nat.Partrec.Code) (f : α → σ) : Prop :=
  ∀ a : α, c.eval (encode a) = Part.some (encode (f a))

/-- Every computable function has a code. -/
theorem exists_code_of_computable {α σ : Type} [Primcodable α] [Primcodable σ] {f : α → σ}
    (hf : Computable f) : ∃ c : Nat.Partrec.Code, CodeComputes c f := by
  have hnat : Nat.Partrec fun n => Part.bind (decode (α := α) n) fun a =>
      Part.map encode (Part.some (f a)) := hf
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hnat
  refine ⟨c, fun a => ?_⟩
  rw [show c.eval = _ from hc]
  simp

/-- A computable family of codes for a family of functions makes the family
jointly computable. This is the only place where the universal function is
used. -/
theorem computable_of_codeFamily {α σ : Type} [Primcodable α] [Primcodable σ]
    (code : ℕ → Nat.Partrec.Code) (hcode : Computable code)
    (f : ℕ → α → σ) (h : ∀ k, CodeComputes (code k) (f k)) :
    Computable (fun p : ℕ × α => f p.1 p.2) := by
  have hpart : Partrec (fun p : ℕ × α => (code p.1).eval (encode p.2)) :=
    Nat.Partrec.Code.eval_part.comp (hcode.comp Computable.fst)
      (Computable.encode.comp Computable.snd)
  have heq : Partrec (fun p : ℕ × α => (Part.some (encode (f p.1 p.2)) : Part ℕ)) :=
    hpart.of_eq fun p => h p.1 p.2
  exact Computable.encode_iff.mp heq

/-! ### Codes for family strategy schemes -/

/-- The argument tuple of a family strategy scheme: the two dyadic depths, the
unavailable allocation, the family size and the finite history. -/
abbrev SchemeInput := (ℕ × ℕ) × (Allocation × (ℕ × FamilyGameHistory))

/-- `c` is a code for the family strategy scheme `sigma`. -/
def CodeComputesScheme (c : Nat.Partrec.Code) (sigma : FamilyStrategyScheme) : Prop :=
  CodeComputes c (fun p : SchemeInput => sigma p.1.1 p.1.2 p.2.1 p.2.2.1 p.2.2.2)

/-- A coded scheme is computable. -/
theorem familyStrategySchemeComputable_of_code {c : Nat.Partrec.Code}
    {sigma : FamilyStrategyScheme} (h : CodeComputesScheme c sigma) :
    FamilyStrategySchemeComputable sigma := by
  have hcode : Computable (fun _ : ℕ => c) := Computable.const c
  have := computable_of_codeFamily (fun _ => c) hcode
    (fun _ (p : SchemeInput) => sigma p.1.1 p.1.2 p.2.1 p.2.2.1 p.2.2.2) (fun _ => h)
  exact this.comp ((Computable.const 0).pair Computable.id)

/-- Every computable scheme has a code. -/
theorem exists_code_of_familyStrategySchemeComputable {sigma : FamilyStrategyScheme}
    (h : FamilyStrategySchemeComputable sigma) :
    ∃ c : Nat.Partrec.Code, CodeComputesScheme c sigma :=
  exists_code_of_computable h

/-! ### The coded ladder -/

/-- The ladder of codes generated by a code transformer. -/
def codeLadder (c0 : Nat.Partrec.Code) (G : ℕ → Nat.Partrec.Code → Nat.Partrec.Code) :
    ℕ → Nat.Partrec.Code :=
  fun k => Nat.rec (motive := fun _ => Nat.Partrec.Code) c0 (fun k' c => G k' c) k

/-- Iterating a computable code transformer from a starting code gives a computable ladder of
codes. -/
theorem computable_codeLadder (c0 : Nat.Partrec.Code)
    {G : ℕ → Nat.Partrec.Code → Nat.Partrec.Code} (hG : Computable₂ G) :
    Computable (codeLadder c0 G) := by
  have h := Computable.nat_rec (f := fun k : ℕ => k) (g := fun _ : ℕ => c0)
      (h := fun (_ : ℕ) (p : ℕ × Nat.Partrec.Code) => G p.1 p.2) Computable.id
      (Computable.const c0) (hG.comp (Computable.fst.comp Computable.snd)
        (Computable.snd.comp Computable.snd))
  simpa [codeLadder] using h

/-- **Item 7 of the ladder plan.** A computable transformer of *codes* which
tracks the transformer `F` of schemes makes the whole ladder `ladderScheme F`
computable jointly in the amplification stage, the two dyadic depths, the
unavailable allocation, the family size and the history.

This is the shape in which the remaining half-step should discharge the
computability conjunct of `exists_grayLadderStep`: produce `G`, not a proof of
computability at each stage separately. -/
theorem uniformFamilyStrategySchemeComputable_ladderScheme
    (F : ℕ → FamilyStrategyScheme → FamilyStrategyScheme)
    (c0 : Nat.Partrec.Code) (G : ℕ → Nat.Partrec.Code → Nat.Partrec.Code)
    (hG : Computable₂ G)
    (hbase : CodeComputesScheme c0 (fun a _e => baseFamilyStrategy a))
    (hstep : ∀ (k : ℕ) (c : Nat.Partrec.Code) (sigma : FamilyStrategyScheme),
      CodeComputesScheme c sigma → CodeComputesScheme (G k c) (F k sigma)) :
    UniformFamilyStrategySchemeComputable (ladderScheme F) := by
  have hcodes : ∀ k, CodeComputesScheme (codeLadder c0 G k) (ladderScheme F k) := by
    intro k
    induction k with
    | zero => exact hbase
    | succ k ih => exact hstep k _ _ ih
  have hjoint : Computable (fun p : ℕ × SchemeInput =>
      ladderScheme F p.1 p.2.1.1 p.2.1.2 p.2.2.1 p.2.2.2.1 p.2.2.2.2) :=
    computable_of_codeFamily (codeLadder c0 G) (computable_codeLadder c0 hG)
      (fun k (p : SchemeInput) => ladderScheme F k p.1.1 p.1.2 p.2.1 p.2.2.1 p.2.2.2)
      hcodes
  have hreshuffle : Computable (fun q : (ℕ × ℕ × ℕ) × (Allocation × (ℕ × FamilyGameHistory)) =>
      ((q.1.1, ((q.1.2.1, q.1.2.2), q.2)) : ℕ × SchemeInput)) :=
    (Computable.fst.comp Computable.fst).pair
      (((Computable.fst.comp (Computable.snd.comp Computable.fst)).pair
        (Computable.snd.comp (Computable.snd.comp Computable.fst))).pair Computable.snd)
  have hcomp := hjoint.comp hreshuffle
  exact hcomp

/-- The base scheme of the ladder always has a code. -/
theorem exists_code_baseFamilyScheme :
    ∃ c : Nat.Partrec.Code, CodeComputesScheme c (fun a (_e : ℕ) => baseFamilyStrategy a) :=
  exists_code_of_familyStrategySchemeComputable computable_baseFamilyScheme

/-- The form in which a future half-step should use the reduction: only the
code transformer has to be produced, since the base code exists by
`exists_code_baseFamilyScheme`. -/
theorem uniformFamilyStrategySchemeComputable_ladderScheme_of_codeStep
    (F : ℕ → FamilyStrategyScheme → FamilyStrategyScheme)
    (G : ℕ → Nat.Partrec.Code → Nat.Partrec.Code) (hG : Computable₂ G)
    (hstep : ∀ (k : ℕ) (c : Nat.Partrec.Code) (sigma : FamilyStrategyScheme),
      CodeComputesScheme c sigma → CodeComputesScheme (G k c) (F k sigma)) :
    UniformFamilyStrategySchemeComputable (ladderScheme F) := by
  obtain ⟨c0, hc0⟩ := exists_code_baseFamilyScheme
  exact uniformFamilyStrategySchemeComputable_ladderScheme F c0 G hG hc0 hstep

/-- **The remaining half-step obligation, in reduced form.** Given Day's
transformer `F`, a computable transformer `G` of codes that tracks it, and the
semantic rung step, the statement of `exists_grayLadderStep` follows: the
computability conjunct is discharged by
`uniformFamilyStrategySchemeComputable_ladderScheme_of_codeStep`.

This is a reduction, not a decomposition into new leaves: both hypotheses are
about the *real* transformer, so no placeholder can satisfy them (a constant
empty transformer already fails the semantic conditions encoded by
`GrayRung`). -/
theorem exists_grayLadderStep_of_codeStep
    (F : ℕ → FamilyStrategyScheme → FamilyStrategyScheme)
    (G : ℕ → Nat.Partrec.Code → Nat.Partrec.Code) (hG : Computable₂ G)
    (htracks : ∀ (k : ℕ) (code : Nat.Partrec.Code) (sigma : FamilyStrategyScheme),
      CodeComputesScheme code sigma → CodeComputesScheme (G k code) (F k sigma))
    (const : ℕ) (hconst : 2 ≤ const)
    (hstep : ∀ k L B sigma, B ≤ max 2 (const * (k + 1) * 2 ^ L) → GrayRung k L B sigma →
      GrayRung (k + 1) (const * (k + 1) ^ 2 * L + const * (k + 1))
        (max 2 (const * (k + 1) *
          2 ^ (const * (k + 1) ^ 2 * L + const * (k + 1)))) (F k sigma)) :
    ∃ (F : ℕ → FamilyStrategyScheme → FamilyStrategyScheme) (c : ℕ), 2 ≤ c ∧
      UniformFamilyStrategySchemeComputable (ladderScheme F) ∧
      ∀ k L B sigma, B ≤ max 2 (c * (k + 1) * 2 ^ L) → GrayRung k L B sigma →
        GrayRung (k + 1) (c * (k + 1) ^ 2 * L + c * (k + 1))
          (max 2 (c * (k + 1) *
            2 ^ (c * (k + 1) ^ 2 * L + c * (k + 1)))) (F k sigma) :=
  ⟨F, const, hconst,
    uniformFamilyStrategySchemeComputable_ladderScheme_of_codeStep F G hG htracks, hstep⟩

end Kolmogorov
