/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.ProbabilisticGenerator
import KolmogorovMathlib.MonotoneComplexity.ContinuousStreamMap
import KolmogorovMathlib.MonotoneComplexity.MonotoneInfinite
import KolmogorovMathlib.MonotoneComplexity.REClosure

/-!
# Composing a probabilistic generator with a computable stream map

This module builds the generator-composition bridge: if `G` is a probabilistic
generator and `f` is a computable (continuous, enumerable-graph) map on streams,
then `fun w => f (G.output w)` is again the output map of a probabilistic
generator, whose lower graph is the relational composition of the lower graph of
`G` with the lower graph of `f`.
-/

namespace Kolmogorov

/-- The relational composition of the lower graph of a probabilistic generator
`G` with the lower graph of a stream map `f`. -/
def generatorCompositionLowerGraph
    (G : ProbabilisticGenerator) (f : BitStream → BitStream)
    (p y : BitString) : Prop :=
  ∃ x, G.lowerGraph p x ∧ streamLowerGraph f x y

/-- Any finite approximation of `f s` is already an approximation of `f` applied
to some finite approximation of `s`. -/
lemma exists_finite_approx_of_finite_le {f : BitStream → BitStream}
    (hf : IsContinuousStreamMap f) {s : BitStream} {y : BitString}
    (hy : BitStream.finite y ≤ f s) :
    ∃ x : BitString, BitStream.finite x ≤ s ∧ BitStream.finite y ≤ f (.finite x) := by
  cases s with
  | finite x => exact ⟨x, le_refl _, hy⟩
  | infinite w =>
    rcases (continuousStreamMap_finite_le_infinite_iff f hf w y).1 hy with ⟨n, hn⟩
    exact ⟨cantorPrefix w n, BitStream.finite_cantorPrefix_le_infinite w n, hn⟩

/-- Leaf 1: the composed lower graph is enumerable. -/
lemma generatorCompositionLowerGraph_isRE
    (G : ProbabilisticGenerator) {f : BitStream → BitStream}
    (hf : IsComputableStreamMap f) :
    IsRE fun q : BitString × BitString => generatorCompositionLowerGraph G f q.1 q.2 := by
  have h1 : IsRE fun r : (BitString × BitString) × BitString => G.lowerGraph r.1.1 r.2 :=
    G.lowerGraph_re.comp_computable
      (Computable.pair (Computable.fst.comp Computable.fst) Computable.snd)
  have h2 : IsRE fun r : (BitString × BitString) × BitString =>
      streamLowerGraph f r.2 r.1.2 :=
    hf.2.comp_computable
      (Computable.pair Computable.snd (Computable.snd.comp Computable.fst))
  exact IsRE.exists_encodable (h1.and h2)

/-- Leaf 2: soundness of the composed lower graph for the composed output map. -/
lemma generatorCompositionLowerGraph_sound
    (G : ProbabilisticGenerator) {f : BitStream → BitStream}
    (hf : IsContinuousStreamMap f) {p y : BitString}
    (h : generatorCompositionLowerGraph G f p y) :
    cantorCylinder p ⊆ (fun w => f (G.output w)) ⁻¹' bitStreamCylinder y := by
  rcases h with ⟨x, hGx, hfy⟩
  intro w hw
  have hx : BitStream.finite x ≤ G.output w := G.lowerGraph_sound hGx hw
  exact le_trans hfy (hf.1 hx)

/-- Leaf 3: completeness of the composed lower graph for the composed output map. -/
lemma generatorCompositionLowerGraph_complete
    (G : ProbabilisticGenerator) {f : BitStream → BitStream}
    (hf : IsContinuousStreamMap f) {w : CantorSeq} {y : BitString}
    (h : f (G.output w) ∈ bitStreamCylinder y) :
    ∃ p, w ∈ cantorCylinder p ∧ generatorCompositionLowerGraph G f p y := by
  have hy : BitStream.finite y ≤ f (G.output w) := h
  rcases exists_finite_approx_of_finite_le hf hy with ⟨x, hx, hfy⟩
  have hxc : G.output w ∈ bitStreamCylinder x := hx
  rcases G.lowerGraph_complete hxc with ⟨p, hp, hpg⟩
  exact ⟨p, hp, ⟨x, hpg, hfy⟩⟩

/-- The composition of a probabilistic generator with a computable stream map,
again a probabilistic generator. -/
def generatorComposition (G : ProbabilisticGenerator) (f : BitStream → BitStream)
    (hf : IsComputableStreamMap f) : ProbabilisticGenerator where
  output w := f (G.output w)
  lowerGraph := generatorCompositionLowerGraph G f
  lowerGraph_re := generatorCompositionLowerGraph_isRE G hf
  lowerGraph_sound := fun h => generatorCompositionLowerGraph_sound G hf.1 h
  lowerGraph_complete := fun h => generatorCompositionLowerGraph_complete G hf.1 h

/-- The composite generator outputs the image under `f` of the output of `G`. -/
@[simp] lemma generatorComposition_output (G : ProbabilisticGenerator)
    {f : BitStream → BitStream} (hf : IsComputableStreamMap f) (w : CantorSeq) :
    (generatorComposition G f hf).output w = f (G.output w) := rfl

/-- The class of output maps of probabilistic generators is closed under
postcomposition with a computable stream map. -/
theorem exists_probabilisticGenerator_output_comp (G : ProbabilisticGenerator)
    {f : BitStream → BitStream} (hf : IsComputableStreamMap f) :
    ∃ H : ProbabilisticGenerator, H.output = fun w => f (G.output w) :=
  ⟨generatorComposition G f hf, rfl⟩

/-- The tree semimeasure generated by the composition is the mass of the
`G.output`-preimage of the `f`-preimage of the cylinder, i.e. the image under
`f` of the measure generated by `G`. -/
lemma generatedTreeSemimeasure_generatorComposition (G : ProbabilisticGenerator)
    {f : BitStream → BitStream} (hf : IsComputableStreamMap f) (x : BitString) :
    generatedTreeSemimeasure (generatorComposition G f hf) x =
      uniformMeasure (G.output ⁻¹' (f ⁻¹' bitStreamCylinder x)) := rfl

/-- The image of the measure generated by a probabilistic generator under a
computable stream map is a lower semicomputable continuous semimeasure. -/
theorem generatorComposition_isLowerSemicomputableContinuousSemimeasure
    (G : ProbabilisticGenerator) {f : BitStream → BitStream} (hf : IsComputableStreamMap f) :
    IsLowerSemicomputableContinuousSemimeasure
      (fun x => uniformMeasure (G.output ⁻¹' (f ⁻¹' bitStreamCylinder x))) :=
  generatedTreeSemimeasure_isLowerSemicomputableContinuousSemimeasure
    (generatorComposition G f hf)

end Kolmogorov
