import KolmogorovMathlib.MonotoneComplexity.SemimeasureRealization
import KolmogorovMathlib.AlgorithmicRandomness.ComputableMeasure

/-!
# Representing continuous tree semimeasures by intervals and by measures

A continuous tree semimeasure is the same thing as a way of splitting the unit interval, and —
when the tree inequality is an equality — the same thing as a probability measure on Cantor
space.

### Outline

* the cylinder masses of a computable probability measure form a lower semicomputable continuous
  semimeasure (`isLowerSemicomputableContinuousSemimeasure_of_isComputableMeasure`), with
  `bitStreamMass`, the π-system lemma `isPiSystem_range_bitStreamCylinder` and the uniqueness
  statement `bitStreamMeasure_unique`;
* interval realisation: every continuous tree semimeasure is realised by allocating to each
  string a subinterval of `[0, 1]` of the right length, nested along the prefix order;
* the mass of the infinite extensions of a string, obtained as the limit of the masses of its
  descendants;
* Cantor-space realisation of an exactly additive semimeasure, ending in
  `exists_measure_cantorSeq_of_isContinuousTreeSemimeasure_of_exact`.

Source: SUV Theorem 77(b).
-/

open scoped ENNReal

namespace Kolmogorov

open MeasureTheory BitStream

instance : SecondCountableTopology BitStream :=
  isTopologicalBasis_bitStreamCylinders.secondCountableTopology
    (Set.countable_range bitStreamCylinder)

-- Problem 119 uses the Borel σ-algebra of the prefix topology on `BitStream`.
instance : MeasurableSpace BitStream := borel BitStream

instance : BorelSpace BitStream where
  measurable_eq := rfl

/-- The Borel structure on bit streams is generated by the cylinders. -/
lemma borel_bitStream_eq_generateFrom :
    borel BitStream = MeasurableSpace.generateFrom (Set.range bitStreamCylinder) :=
  isTopologicalBasis_bitStreamCylinders.borel_eq_generateFrom

/-- The cylinder of the empty string is the whole space. -/
lemma cantorCylinder_nil_eq : cantorCylinder [] = Set.univ := by
  ext w
  simp only [cantorCylinder, Set.mem_ofPred_eq, Set.mem_univ, iff_true]
  intro i hi
  simp only [List.length_nil, not_lt_zero] at hi

-- Theorem 77(a)
/-- The cylinder-mass function of a computable probability measure is a lower semicomputable
continuous semimeasure. -/
theorem isLowerSemicomputableContinuousSemimeasure_of_isComputableMeasure
    {μ : Measure CantorSeq} [IsProbabilityMeasure μ] (h : IsComputableMeasure μ) :
    IsLowerSemicomputableContinuousSemimeasure (cantorMass μ) := by
  constructor
  · constructor
    · unfold cantorMass
      rw [cantorCylinder_nil_eq]
      exact measure_univ
    · intro x
      exact le_of_eq (cantorMass_add μ x).symm
  · rcases h with ⟨a, hcomp, hbound⟩
    use fun s x _ => computableENNRealToLowerApprox (a x) s
    constructor
    · intro s x ctx
      exact computableENNRealToLowerApprox_mono (a x) s
    · constructor
      · intro x ctx
        have h1 : ∀ s, cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s ∧
                       dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s := by
          intro s
          have H := hbound x s
          exact ⟨H.2, H.1⟩
        exact computableENNRealToLowerApprox_limit h1
      · have h_comp2 : Computable₂
          (fun (x : BitString) (s : ℕ) => computableENNRealToLowerApprox (a x) s) :=
          computable₂_computableENNRealToLowerApprox a hcomp
        have h_proj_s : Computable (fun p : ℕ × BitString × BitString => p.1) := Computable.fst
        have h_proj_x : Computable (fun p : ℕ × BitString × BitString => p.2.1) :=
          Computable.fst.comp Computable.snd
        exact h_comp2.comp h_proj_x h_proj_s

-- Theorem 77(b) itself lives in `TwoSidedMeasureRepresentation.lean` as
-- `exists_isComputableMeasure_of_isLowerSemicomputableContinuousSemimeasure`,
-- proved for the faithful two-sided `IsComputableMeasure`.  The historical
-- floor-selector reading is refuted in `FloorSelectorObstruction.lean`
-- (`not_forall_exists_isFloorComputableMeasure_of_exact`).

/-- The mass a measure on bit streams gives to the cylinder of a finite string. -/
def bitStreamMass (μ : Measure BitStream) (x : BitString) : ℝ≥0∞ :=
  μ (bitStreamCylinder x)

/-- The cylinders form a π-system. -/
lemma isPiSystem_range_bitStreamCylinder :
    IsPiSystem (Set.range bitStreamCylinder) := by
  rintro _ ⟨x, rfl⟩ _ ⟨y, rfl⟩ hne
  by_cases hxy : x <+: y
  · rw [bitStreamCylinder_inter_of_prefix hxy]
    exact ⟨y, rfl⟩
  · by_cases hyx : y <+: x
    · rw [Set.inter_comm, bitStreamCylinder_inter_of_prefix hyx]
      exact ⟨x, rfl⟩
    · exact absurd ((bitStreamCylinder_disjoint_of_incompatible hxy hyx).inter_eq ▸ hne)
        (by simp)

/-- Two probability measures on bit streams with the same cylinder masses are equal. -/
lemma bitStreamMeasure_unique (μ ν : Measure BitStream)
    [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
    (h : ∀ x, bitStreamMass μ x = bitStreamMass ν x) : μ = ν := by
  refine MeasureTheory.ext_of_generate_finite (Set.range bitStreamCylinder)
    borel_bitStream_eq_generateFrom isPiSystem_range_bitStreamCylinder ?_ ?_
  · rintro _ ⟨x, rfl⟩
    exact h x
  · simp [measure_univ]

/-- A continuous tree semimeasure determines at most one measure with those cylinder masses. -/
theorem bitStreamMeasure_unique_of_mass_eq {a : BitString → ℝ≥0∞}
    (ha : IsContinuousTreeSemimeasure a) (μ ν : Measure BitStream)
    (hμ : ∀ x, bitStreamMass μ x = a x) (hν : ∀ x, bitStreamMass ν x = a x) :
    μ = ν := by
  have hμ_univ : μ Set.univ = 1 := by
    rw [← bitStreamCylinder_nil, ← bitStreamMass, hμ, ha.1]
  have hν_univ : ν Set.univ = 1 := by
    rw [← bitStreamCylinder_nil, ← bitStreamMass, hν, ha.1]
  let : IsProbabilityMeasure μ := ⟨hμ_univ⟩
  let : IsProbabilityMeasure ν := ⟨hν_univ⟩
  exact bitStreamMeasure_unique μ ν fun x => (hμ x).trans (hν x).symm

/-- The output map of a probabilistic generator is measurable. -/
lemma ProbabilisticGenerator.measurable_output (G : ProbabilisticGenerator) :
    Measurable G.output := by
  change @Measurable CantorSeq BitStream _ (borel BitStream) G.output
  rw [borel_bitStream_eq_generateFrom]
  apply measurable_generateFrom
  rintro _ ⟨x, rfl⟩
  rw [preimage_bitStreamCylinder_eq_cantorOpen]
  exact measurableSet_cantorOpen _ _

/-- The lower-semicomputable case of the Problem 119 representation, obtained
by pushing uniform measure through the realizing probabilistic generator. -/
theorem exists_measure_bitStream_of_isLowerSemicomputableContinuousSemimeasure
    {a : BitString → ℝ≥0∞} (ha : IsLowerSemicomputableContinuousSemimeasure a) :
    ∃ μ : Measure BitStream, IsProbabilityMeasure μ ∧ ∀ x, bitStreamMass μ x = a x := by
  obtain ⟨G, hG⟩ := exists_probabilisticGenerator_generatedTreeSemimeasure_eq ha
  let μ := Measure.map G.output uniformMeasure
  have hμ : IsProbabilityMeasure μ := inferInstance
  refine ⟨μ, hμ, fun x => ?_⟩
  rw [bitStreamMass, Measure.map_apply G.measurable_output
    (isOpen_bitStreamCylinder x).measurableSet]
  exact hG x

/-!
### Interval realization of an arbitrary continuous tree semimeasure

Every continuous tree semimeasure `a` can be realized by allocating to each
string `x` a half-open subinterval `treeIco a x ⊆ [0,1)` of length `a x`, with
the two children of `x` occupying disjoint subintervals at the left end of the
interval of `x`.  Pushing the Lebesgue measure of `[0,1)` forward along the map
sending a point to the stream whose prefixes are the strings whose intervals
contain it produces a measure on `BitStream` with the prescribed cylinder
masses.  This is the noneffective half of Problem 119.
-/

section IntervalRealization

variable {a : BitString → ℝ≥0∞}

/-- The left endpoint of the interval allocated to `x`. -/
noncomputable def treeLeftEnd (a : BitString → ℝ≥0∞) (x : BitString) : ℝ :=
  ∑ i ∈ Finset.range x.length,
    if x.getD i false then (a (x.take i ++ [false])).toReal else 0

/-- The interval of the empty string starts at zero. -/
@[simp] lemma treeLeftEnd_nil : treeLeftEnd a [] = 0 := by
  simp [treeLeftEnd]

/-- Appending a bit moves the left endpoint by the mass of the zero child, and only for the one
child. -/
lemma treeLeftEnd_append (x : BitString) (b : Bool) :
    treeLeftEnd a (x ++ [b]) =
      treeLeftEnd a x + (if b then (a (x ++ [false])).toReal else 0) := by
  unfold treeLeftEnd
  rw [List.length_append, List.length_singleton, Finset.sum_range_succ]
  congr 1
  · refine Finset.sum_congr rfl fun i hi => ?_
    rw [Finset.mem_range] at hi
    rw [List.getD_eq_getElem?_getD, List.getElem?_append_left hi,
      ← List.getD_eq_getElem?_getD, List.take_append_of_le_length hi.le]
  · have h1 : (x ++ [b]).getD x.length false = b := by
      simp [List.getD_eq_getElem?_getD]
    have h2 : (x ++ [b]).take x.length = x := by simp
    rw [h1, h2]

/-- The zero child keeps the left endpoint of its parent. -/
lemma treeLeftEnd_append_false (x : BitString) :
    treeLeftEnd a (x ++ [false]) = treeLeftEnd a x := by
  simp [treeLeftEnd_append]

/-- The one child starts where the zero child ends. -/
lemma treeLeftEnd_append_true (x : BitString) :
    treeLeftEnd a (x ++ [true]) = treeLeftEnd a x + (a (x ++ [false])).toReal := by
  simp [treeLeftEnd_append]

/-- The real masses of the two children add up to at most the mass of the parent. -/
lemma IsContinuousTreeSemimeasure.toReal_children_le
    (ha : IsContinuousTreeSemimeasure a) (x : BitString) :
    (a (x ++ [false])).toReal + (a (x ++ [true])).toReal ≤ (a x).toReal := by
  rw [← ENNReal.toReal_add (ha.ne_top _) (ha.ne_top _)]
  exact ENNReal.toReal_mono (ha.ne_top x) (ha.2 x)

/-- The half-open interval allocated to the string `x`. -/
noncomputable def treeIco (a : BitString → ℝ≥0∞) (x : BitString) : Set ℝ :=
  Set.Ico (treeLeftEnd a x) (treeLeftEnd a x + (a x).toReal)

/-- The interval of the empty string is `[0, 1)`. -/
lemma treeIco_nil (ha : IsContinuousTreeSemimeasure a) :
    treeIco a [] = Set.Ico (0 : ℝ) 1 := by
  simp [treeIco, ha.1]

/-- The interval of a child is contained in the interval of its parent. -/
lemma treeIco_append_subset (ha : IsContinuousTreeSemimeasure a) (x : BitString) (b : Bool) :
    treeIco a (x ++ [b]) ⊆ treeIco a x := by
  have hsum := ha.toReal_children_le x
  have h0 : (0 : ℝ) ≤ (a (x ++ [false])).toReal := ENNReal.toReal_nonneg
  have h1 : (0 : ℝ) ≤ (a (x ++ [true])).toReal := ENNReal.toReal_nonneg
  cases b
  · rw [treeIco, treeIco, treeLeftEnd_append_false]
    exact Set.Ico_subset_Ico le_rfl (by linarith)
  · rw [treeIco, treeIco, treeLeftEnd_append_true]
    exact Set.Ico_subset_Ico (by linarith) (by linarith)

/-- The interval of an extension is contained in the interval of the prefix. -/
lemma treeIco_prefix_subset (ha : IsContinuousTreeSemimeasure a) {x y : BitString}
    (h : x <+: y) : treeIco a y ⊆ treeIco a x := by
  obtain ⟨z, rfl⟩ := h
  induction z using List.reverseRecOn with
  | nil => rw [List.append_nil]
  | append_singleton z b ih =>
    rw [← List.append_assoc]
    exact (treeIco_append_subset ha (x ++ z) b).trans ih

/-- The intervals of the two children are disjoint. -/
lemma not_mem_treeIco_true_of_mem_false {r : ℝ} (x : BitString)
    (h0 : r ∈ treeIco a (x ++ [false])) : r ∉ treeIco a (x ++ [true]) := by
  intro h1
  rw [treeIco, treeLeftEnd_append_false] at h0
  rw [treeIco, treeLeftEnd_append_true] at h1
  exact absurd h1.1 (not_le.mpr h0.2)

/-- Two strings whose intervals share a point are comparable for the prefix order. -/
lemma prefix_or_prefix_of_mem_treeIco (ha : IsContinuousTreeSemimeasure a) {r : ℝ}
    {x y : BitString} (hx : r ∈ treeIco a x) (hy : r ∈ treeIco a y) :
    x <+: y ∨ y <+: x := by
  by_contra hcon
  obtain ⟨c, b, hbx, hby⟩ := divergence_of_not_prefix hcon
  have h1 : r ∈ treeIco a (c ++ [b]) := treeIco_prefix_subset ha hbx hx
  have h2 : r ∈ treeIco a (c ++ [!b]) := treeIco_prefix_subset ha hby hy
  cases b with
  | false =>
    simp only [Bool.not_false] at h2
    exact not_mem_treeIco_true_of_mem_false c h1 h2
  | true =>
    simp only [Bool.not_true] at h2
    exact not_mem_treeIco_true_of_mem_false c h2 h1

/-- The strings whose allocated interval contains the point `r`, together with
the empty string. -/
noncomputable def treeIcoPrefixSet (a : BitString → ℝ≥0∞) (r : ℝ) : Set BitString :=
  {x | x = [] ∨ r ∈ treeIco a x}

/-- The strings whose intervals contain a given real form a prefix set, hence describe a stream. -/
lemma isStreamPrefixSet_treeIcoPrefixSet (ha : IsContinuousTreeSemimeasure a) (r : ℝ) :
    IsStreamPrefixSet (treeIcoPrefixSet a r) := by
  refine ⟨Or.inl rfl, ?_, ?_⟩
  · intro x y hxy hy
    rcases hy with rfl | hy
    · exact Or.inl (List.prefix_nil.mp hxy)
    · exact Or.inr (treeIco_prefix_subset ha hxy hy)
  · intro x y hx hy
    rcases hx with rfl | hx
    · exact Or.inl List.nil_prefix
    · rcases hy with rfl | hy
      · exact Or.inr List.nil_prefix
      · exact prefix_or_prefix_of_mem_treeIco ha hx hy

/-- The stream determined by a point `r` of the unit interval. -/
noncomputable def treeIcoStream (ha : IsContinuousTreeSemimeasure a) (r : ℝ) : BitStream :=
  BitStream.ofPrefixSet (treeIcoPrefixSet a r) (isStreamPrefixSet_treeIcoPrefixSet ha r)

/-- The stream attached to a real lies in the cylinder of `x` exactly when the interval of `x`
contains that real. -/
lemma mem_bitStreamCylinder_treeIcoStream (ha : IsContinuousTreeSemimeasure a)
    (x : BitString) (r : ℝ) :
    treeIcoStream ha r ∈ bitStreamCylinder x ↔ x ∈ treeIcoPrefixSet a r :=
  BitStream.finite_le_ofPrefixSet_iff (isStreamPrefixSet_treeIcoPrefixSet ha r) x

/-- For a nonempty string the preimage of its cylinder is its interval. -/
lemma preimage_bitStreamCylinder_treeIcoStream_of_ne_nil
    (ha : IsContinuousTreeSemimeasure a) {x : BitString} (hx : x ≠ []) :
    treeIcoStream ha ⁻¹' bitStreamCylinder x = treeIco a x := by
  ext r
  simp only [Set.mem_preimage, mem_bitStreamCylinder_treeIcoStream ha, treeIcoPrefixSet,
    Set.mem_ofPred_eq, hx, false_or]

/-- The preimage of the cylinder of the empty string is everything. -/
lemma preimage_bitStreamCylinder_treeIcoStream_nil (ha : IsContinuousTreeSemimeasure a) :
    treeIcoStream ha ⁻¹' bitStreamCylinder [] = Set.univ := by
  ext r
  simp only [Set.mem_preimage, mem_bitStreamCylinder_treeIcoStream ha, treeIcoPrefixSet,
    Set.mem_ofPred_eq, Set.mem_univ, true_or]

/-- The preimage of a cylinder under the interval map is measurable. -/
lemma measurableSet_preimage_bitStreamCylinder_treeIcoStream
    (ha : IsContinuousTreeSemimeasure a) (x : BitString) :
    MeasurableSet (treeIcoStream ha ⁻¹' bitStreamCylinder x) := by
  by_cases hx : x = []
  · subst hx
    rw [preimage_bitStreamCylinder_treeIcoStream_nil ha]
    exact MeasurableSet.univ
  · rw [preimage_bitStreamCylinder_treeIcoStream_of_ne_nil ha hx]
    exact measurableSet_Ico

/-- The map sending a real to the stream of intervals containing it is measurable. -/
lemma measurable_treeIcoStream (ha : IsContinuousTreeSemimeasure a) :
    Measurable (treeIcoStream ha) := by
  change @Measurable ℝ BitStream _ (borel BitStream) (treeIcoStream ha)
  rw [borel_bitStream_eq_generateFrom]
  apply measurable_generateFrom
  rintro _ ⟨x, rfl⟩
  exact measurableSet_preimage_bitStreamCylinder_treeIcoStream ha x

/-- Inside `[0, 1)` the preimage of a cylinder is exactly the interval of its string. -/
lemma preimage_bitStreamCylinder_treeIcoStream_inter (ha : IsContinuousTreeSemimeasure a)
    (x : BitString) :
    treeIcoStream ha ⁻¹' bitStreamCylinder x ∩ Set.Ico (0 : ℝ) 1 = treeIco a x := by
  ext r
  simp only [Set.mem_inter_iff, Set.mem_preimage, mem_bitStreamCylinder_treeIcoStream ha,
    treeIcoPrefixSet, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨rfl | h, hr⟩
    · rw [treeIco_nil ha]; exact hr
    · exact h
  · intro h
    refine ⟨Or.inr h, ?_⟩
    have : treeIco a x ⊆ treeIco a [] := treeIco_prefix_subset ha List.nil_prefix
    rw [treeIco_nil ha] at this
    exact this h

end IntervalRealization

-- Problem 119, existence part of the general (not necessarily effective) correspondence.
/-- Every continuous tree semimeasure is the cylinder-mass function of a measure on bit streams. -/
theorem exists_measure_bitStream_of_isContinuousTreeSemimeasure
    {a : BitString → ℝ≥0∞} (ha : IsContinuousTreeSemimeasure a) :
    ∃ μ : Measure BitStream, ∀ x, bitStreamMass μ x = a x := by
  refine ⟨Measure.map (treeIcoStream ha) (volume.restrict (Set.Ico (0 : ℝ) 1)), fun x => ?_⟩
  rw [bitStreamMass, Measure.map_apply (measurable_treeIcoStream ha)
      (isOpen_bitStreamCylinder x).measurableSet,
    Measure.restrict_apply (measurableSet_preimage_bitStreamCylinder_treeIcoStream ha x),
    preimage_bitStreamCylinder_treeIcoStream_inter ha x, treeIco, Real.volume_Ico,
    add_sub_cancel_left]
  exact ENNReal.ofReal_toReal (ha.ne_top x)

/-!
### The mass of the infinite extensions of a string

The set of infinite streams extending `x` is the decreasing intersection of the
level sets of finite extensions of `x`, so its measure is the infimum of the
level sums.  This is the infinite-prefix mass formula of Problem 119.
-/

section InfinitePrefixMass

open MeasureTheory

/-- The prefix of length `|x| + n` of a sequence starting with `x` is `x` followed by the prefix
of the shifted sequence. -/
lemma cantorPrefix_append_of_isCantorPrefix {x : BitString} {w : CantorSeq}
    (hx : IsCantorPrefix x w) (n : ℕ) :
    cantorPrefix w (x.length + n) = x ++ cantorPrefix (fun i => w (x.length + i)) n := by
  refine List.ext_getElem (by simp) fun i h1 h2 => ?_
  have hi : i < x.length + n := by simpa using h1
  rw [cantorPrefix_getElem]
  by_cases hlt : i < x.length
  · rw [List.getElem_append_left hlt]
    exact hx i hlt
  · rw [List.getElem_append_right (by omega), cantorPrefix_getElem]
    congr 1
    omega

/-- The infinite streams extending `x` are the intersection over `n` of the unions of the
cylinders of the extensions of `x` by `n` bits. -/
lemma infinitePrefix_eq_iInter_levelExtensions (x : BitString) :
    {s : BitStream | ∃ w, s = .infinite w ∧ IsCantorPrefix x w} =
      ⋂ n, ⋃ y ∈ (exactLengthPrograms n).toFinset, bitStreamCylinder (x ++ y) := by
  ext s
  simp only [Set.mem_ofPred_eq, Set.mem_iInter, Set.mem_iUnion, List.mem_toFinset, exists_prop]
  constructor
  · rintro ⟨w, rfl, hxw⟩ n
    refine ⟨cantorPrefix (fun i => w (x.length + i)) n,
      mem_exactLengthPrograms_of_length _ n (cantorPrefix_length _ n), ?_⟩
    refine mem_bitStreamCylinder_infinite.mpr ?_
    rw [isCantorPrefix_iff_cantorPrefix_eq]
    simp only [List.length_append, cantorPrefix_length]
    exact cantorPrefix_append_of_isCantorPrefix hxw n
  · intro h
    cases s with
    | finite z =>
      obtain ⟨y, hy, hmem⟩ := h (z.length + 1)
      have hlen := exactLengthPrograms_length_eq _ _ hy
      have hle := (mem_bitStreamCylinder_finite.mp hmem).length_le
      simp only [List.length_append] at hle
      omega
    | infinite w =>
      obtain ⟨y, hy, hmem⟩ := h 0
      have hlen := exactLengthPrograms_length_eq _ _ hy
      have hy0 : y = [] := List.length_eq_zero_iff.mp hlen
      subst hy0
      refine ⟨w, rfl, ?_⟩
      have hpre := mem_bitStreamCylinder_infinite.mp hmem
      simpa using hpre

/-- The measure of the level-`n` extensions of `x` is the sum of their cylinder masses. -/
lemma measure_levelExtensions_eq_sum {a : BitString → ℝ≥0∞}
    (μ : Measure BitStream) (hμ : ∀ z, bitStreamMass μ z = a z)
    (x : BitString) (n : ℕ) :
    μ (⋃ y ∈ (exactLengthPrograms n).toFinset, bitStreamCylinder (x ++ y)) =
      ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ y) := by
  have hdisj : ((exactLengthPrograms n).toFinset : Set BitString).PairwiseDisjoint
      (fun y => bitStreamCylinder (x ++ y)) := by
    intro y1 h1 y2 h2 hne
    have hl1 := exactLengthPrograms_length_eq _ _ (List.mem_toFinset.mp h1)
    have hl2 := exactLengthPrograms_length_eq _ _ (List.mem_toFinset.mp h2)
    have hne' : x ++ y1 ≠ x ++ y2 := fun h => hne (List.append_cancel_left h)
    have hlen : (x ++ y1).length = (x ++ y2).length := by
      simp only [List.length_append, hl1, hl2]
    refine bitStreamCylinder_disjoint_of_incompatible ?_ ?_
    · exact fun hp => hne' (hp.eq_of_length hlen)
    · exact fun hp => hne' (hp.eq_of_length hlen.symm).symm
  rw [measure_biUnion_finset hdisj fun y _ => (isOpen_bitStreamCylinder _).measurableSet]
  exact Finset.sum_congr rfl fun y _ => hμ (x ++ y)

/-- The unions of the level extensions of `x` shrink as the level grows. -/
lemma levelExtensions_antitone (x : BitString) :
    Antitone fun n => ⋃ y ∈ (exactLengthPrograms n).toFinset, bitStreamCylinder (x ++ y) := by
  refine antitone_nat_of_succ_le fun n s hs => ?_
  simp only [Set.mem_iUnion, List.mem_toFinset, exists_prop] at hs ⊢
  obtain ⟨y, hy, hmem⟩ := hs
  have hlen := exactLengthPrograms_length_eq _ _ hy
  refine ⟨y.take n, mem_exactLengthPrograms_of_length _ n (by simp [hlen]), ?_⟩
  refine bitStreamCylinder_subset_of_prefix ?_ hmem
  exact ⟨y.drop n, by rw [List.append_assoc, List.take_append_drop]⟩

/-- Problem 119's infinite-prefix mass formula: the measure of the set of
infinite streams extending `x` is the infimum over levels of the total mass of
the finite extensions of `x` of that level. -/
theorem measure_infinitePrefix_eq_iInf {a : BitString → ℝ≥0∞}
    (ha : IsContinuousTreeSemimeasure a) (μ : Measure BitStream)
    (hμ : ∀ z, bitStreamMass μ z = a z) (x : BitString) :
    μ {s : BitStream | ∃ w, s = .infinite w ∧ IsCantorPrefix x w} =
      ⨅ n, ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ y) := by
  have hmeas : ∀ n, NullMeasurableSet
      (⋃ y ∈ (exactLengthPrograms n).toFinset, bitStreamCylinder (x ++ y)) μ := fun n =>
    (Finset.measurableSet_biUnion _
      fun y _ => (isOpen_bitStreamCylinder _).measurableSet).nullMeasurableSet
  have hfin : ∃ n, μ (⋃ y ∈ (exactLengthPrograms n).toFinset,
      bitStreamCylinder (x ++ y)) ≠ ⊤ := by
    refine ⟨0, ?_⟩
    rw [measure_levelExtensions_eq_sum μ hμ x 0]
    simp only [exactLengthPrograms, List.toFinset_cons, List.toFinset_nil, insert_empty_eq,
      Finset.sum_singleton, List.append_nil]
    exact ha.ne_top x
  rw [infinitePrefix_eq_iInter_levelExtensions x,
    (levelExtensions_antitone x).measure_iInter hmeas hfin]
  exact iInf_congr fun n => measure_levelExtensions_eq_sum μ hμ x n

end InfinitePrefixMass

/-!
### Cantor-space realization of an exactly additive continuous semimeasure

If the tree inequality `a (x0) + a (x1) ≤ a x` is in fact an equality, then no
mass is lost to the finite streams, so the measure produced on `BitStream` is
carried by the infinite streams and can be transported to Cantor space.  This is
the measure-theoretic half of Theorem 77(b).
-/

section CantorRealization

open MeasureTheory

/-- The set of infinite streams inside `BitStream`. -/
def bitStreamInfiniteSet : Set BitStream := {s | ∃ w : CantorSeq, s = .infinite w}

/-- The union of all cylinders whose defining string has length `n`. -/
def bitStreamLevel (n : ℕ) : Set BitStream :=
  ⋃ y ∈ (exactLengthPrograms n).toFinset, bitStreamCylinder y

/-- Each level set of bit streams is measurable. -/
lemma measurableSet_bitStreamLevel (n : ℕ) : MeasurableSet (bitStreamLevel n) :=
  Finset.measurableSet_biUnion _ fun y _ => (isOpen_bitStreamCylinder y).measurableSet

/-- The infinite bit streams are the intersection of the level sets. -/
lemma bitStreamInfiniteSet_eq_iInter :
    bitStreamInfiniteSet = ⋂ n, bitStreamLevel n := by
  ext s
  simp only [bitStreamInfiniteSet, bitStreamLevel, Set.mem_ofPred_eq, Set.mem_iInter,
    Set.mem_iUnion, List.mem_toFinset, exists_prop]
  constructor
  · rintro ⟨w, rfl⟩ n
    refine ⟨cantorPrefix w n, mem_exactLengthPrograms_of_length _ n (cantorPrefix_length w n), ?_⟩
    refine mem_bitStreamCylinder_infinite.mpr ?_
    rw [isCantorPrefix_iff_cantorPrefix_eq, cantorPrefix_length]
  · intro h
    cases s with
    | finite y =>
      obtain ⟨z, hz, hmem⟩ := h (y.length + 1)
      have hlen := exactLengthPrograms_length_eq _ _ hz
      have hpref := (mem_bitStreamCylinder_finite.mp hmem).length_le
      omega
    | infinite w => exact ⟨w, rfl⟩

/-- The set of infinite bit streams is measurable. -/
lemma measurableSet_bitStreamInfiniteSet : MeasurableSet bitStreamInfiniteSet := by
  rw [bitStreamInfiniteSet_eq_iInter]
  exact MeasurableSet.iInter fun n => measurableSet_bitStreamLevel n

/-- The measure of a level set is the sum of the cylinder masses of the strings of that length. -/
lemma measure_bitStreamLevel {a : BitString → ℝ≥0∞} (μ : Measure BitStream)
    (hμ : ∀ x, bitStreamMass μ x = a x) (n : ℕ) :
    μ (bitStreamLevel n) = ∑ y ∈ (exactLengthPrograms n).toFinset, a y := by
  have h := measure_levelExtensions_eq_sum μ hμ [] n
  simpa [bitStreamLevel] using h

/-- For an exactly additive tree function, the extensions of `x` by `n` bits carry exactly the
mass of `x`. -/
lemma sum_extensions_eq_of_exact {a : BitString → ℝ≥0∞}
    (hadd : ∀ x, a x = a (x ++ [false]) + a (x ++ [true])) (x : BitString) (n : ℕ) :
    ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ y) = a x := by
  induction n generalizing x with
  | zero =>
    simp only [exactLengthPrograms, List.toFinset_cons, List.toFinset_nil, insert_empty_eq,
      Finset.sum_singleton, List.append_nil]
  | succ n ih =>
    rw [exactLengthPrograms_succ_eq_cons_image]
    have h_disj : Disjoint ((exactLengthPrograms n).toFinset.image (fun y => false :: y))
        ((exactLengthPrograms n).toFinset.image (fun y => true :: y)) := by
      rw [Finset.disjoint_iff_ne]
      rintro u hu v hv rfl
      rw [Finset.mem_image] at hu hv
      obtain ⟨yu, _, rfl⟩ := hu
      obtain ⟨yv, _, hv2⟩ := hv
      simp only [List.cons.injEq] at hv2
      exact Bool.noConfusion hv2.1
    rw [Finset.sum_union h_disj]
    have h_sum1 : ∑ y ∈ (exactLengthPrograms n).toFinset.image (fun y => false :: y), a (x ++ y)
        = ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ false :: y) := by
      apply Finset.sum_image
      intro y _ z _ eq
      simp only [List.cons.injEq] at eq
      exact eq.2
    have h_sum2 : ∑ y ∈ (exactLengthPrograms n).toFinset.image (fun y => true :: y), a (x ++ y)
        = ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ true :: y) := by
      apply Finset.sum_image
      intro y _ z _ eq
      simp only [List.cons.injEq] at eq
      exact eq.2
    have h_eq1 : ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ false :: y)
        = ∑ y ∈ (exactLengthPrograms n).toFinset, a ((x ++ [false]) ++ y) :=
      Finset.sum_congr rfl fun y _ => by rw [List.append_assoc]; rfl
    have h_eq2 : ∑ y ∈ (exactLengthPrograms n).toFinset, a (x ++ true :: y)
        = ∑ y ∈ (exactLengthPrograms n).toFinset, a ((x ++ [true]) ++ y) :=
      Finset.sum_congr rfl fun y _ => by rw [List.append_assoc]; rfl
    rw [h_sum1, h_sum2, h_eq1, h_eq2, ih (x ++ [false]), ih (x ++ [true])]
    exact (hadd x).symm

/-- For an exactly additive continuous tree semimeasure, each level carries total mass one. -/
lemma sum_level_eq_one_of_exact {a : BitString → ℝ≥0∞} (ha : IsContinuousTreeSemimeasure a)
    (hadd : ∀ x, a x = a (x ++ [false]) + a (x ++ [true])) (n : ℕ) :
    ∑ y ∈ (exactLengthPrograms n).toFinset, a y = 1 := by
  have h := sum_extensions_eq_of_exact hadd [] n
  simp only [List.nil_append] at h
  rw [h, ha.1]

/-- Forget the finite streams: an infinite stream is sent to the underlying
sequence, and the finite streams are sent to a junk point. -/
def bitStreamToCantor : BitStream → CantorSeq
  | .finite _ => fun _ => false
  | .infinite w => w

/-- On the infinite streams, the preimage of a Cantor cylinder is the corresponding bit-stream
cylinder. -/
lemma preimage_cantorCylinder_bitStreamToCantor (x : BitString) :
    bitStreamToCantor ⁻¹' cantorCylinder x ∩ bitStreamInfiniteSet
      = bitStreamCylinder x ∩ bitStreamInfiniteSet := by
  ext s
  cases s with
  | finite y =>
    have hfin : ¬ ∃ w : CantorSeq, (BitStream.finite y) = .infinite w := by
      rintro ⟨w, hw⟩
      exact BitStream.noConfusion hw
    simp only [Set.mem_inter_iff, bitStreamInfiniteSet, Set.mem_ofPred_eq, hfin, and_false]
  | infinite w =>
    have hinf : (BitStream.infinite w) ∈ bitStreamInfiniteSet := ⟨w, rfl⟩
    simp only [Set.mem_inter_iff, Set.mem_preimage, hinf, and_true]
    exact Iff.trans Iff.rfl mem_bitStreamCylinder_infinite.symm

/-- The map from bit streams to Cantor sequences is measurable. -/
lemma measurable_bitStreamToCantor : Measurable bitStreamToCantor := by
  have h : @Measurable BitStream CantorSeq _
      (MeasurableSpace.generateFrom (Set.range cantorCylinder)) bitStreamToCantor := by
    apply measurable_generateFrom
    rintro _ ⟨x, rfl⟩
    by_cases hx : IsCantorPrefix x (fun _ => false)
    · have hsplit : bitStreamToCantor ⁻¹' cantorCylinder x
          = (bitStreamCylinder x ∩ bitStreamInfiniteSet) ∪ bitStreamInfiniteSetᶜ := by
        ext s
        cases s with
        | finite y =>
          have hfin : (BitStream.finite y) ∉ bitStreamInfiniteSet := by
            rintro ⟨w, hw⟩
            exact BitStream.noConfusion hw
          simp only [Set.mem_preimage, Set.mem_union, Set.mem_inter_iff, Set.mem_compl_iff,
            hfin, not_false_eq_true, or_true, iff_true, and_false]
          exact hx
        | infinite w =>
          have hinf : (BitStream.infinite w) ∈ bitStreamInfiniteSet := ⟨w, rfl⟩
          simp only [Set.mem_preimage, Set.mem_union, Set.mem_inter_iff, Set.mem_compl_iff,
            hinf, not_true_eq_false, or_false, and_true]
          exact Iff.trans Iff.rfl mem_bitStreamCylinder_infinite.symm
      rw [hsplit]
      exact (((isOpen_bitStreamCylinder x).measurableSet.inter
        measurableSet_bitStreamInfiniteSet).union measurableSet_bitStreamInfiniteSet.compl)
    · have hsplit : bitStreamToCantor ⁻¹' cantorCylinder x
          = bitStreamCylinder x ∩ bitStreamInfiniteSet := by
        ext s
        cases s with
        | finite y =>
          have hfin : (BitStream.finite y) ∉ bitStreamInfiniteSet := by
            rintro ⟨w, hw⟩
            exact BitStream.noConfusion hw
          simp only [Set.mem_preimage, Set.mem_inter_iff, hfin, and_false, iff_false]
          exact hx
        | infinite w =>
          have hinf : (BitStream.infinite w) ∈ bitStreamInfiniteSet := ⟨w, rfl⟩
          simp only [Set.mem_preimage, Set.mem_inter_iff, hinf, and_true]
          exact Iff.trans Iff.rfl mem_bitStreamCylinder_infinite.symm
      rw [hsplit]
      exact (isOpen_bitStreamCylinder x).measurableSet.inter measurableSet_bitStreamInfiniteSet
  rwa [generateFrom_range_cantorCylinder] at h

/-- The measure-theoretic half of Theorem 77(b): an exactly additive continuous
tree semimeasure is the cylinder-mass function of a measure on Cantor space. -/
theorem exists_measure_cantorSeq_of_isContinuousTreeSemimeasure_of_exact
    {a : BitString → ℝ≥0∞} (ha : IsContinuousTreeSemimeasure a)
    (hadd : ∀ x, a x = a (x ++ [false]) + a (x ++ [true])) :
    ∃ μ : Measure CantorSeq, ∀ x, cantorMass μ x = a x := by
  obtain ⟨ν, hν⟩ := exists_measure_bitStream_of_isContinuousTreeSemimeasure ha
  have hν_univ : ν Set.univ = 1 := by
    rw [← bitStreamCylinder_nil, ← bitStreamMass, hν, ha.1]
  have hlevel : ∀ n, ν (bitStreamLevel n) = 1 := by
    intro n
    rw [measure_bitStreamLevel ν hν n]
    exact sum_level_eq_one_of_exact ha hadd n
  have hnull : ν bitStreamInfiniteSetᶜ = 0 := by
    rw [bitStreamInfiniteSet_eq_iInter, Set.compl_iInter]
    refine measure_iUnion_null fun n => ?_
    rw [measure_compl (measurableSet_bitStreamLevel n)
      (by rw [hlevel n]; exact ENNReal.one_ne_top), hν_univ, hlevel n, tsub_self]
  refine ⟨Measure.map bitStreamToCantor ν, fun x => ?_⟩
  rw [cantorMass, Measure.map_apply measurable_bitStreamToCantor (measurableSet_cantorCylinder x),
    ← measure_inter_conull hnull, preimage_cantorCylinder_bitStreamToCantor x,
    measure_inter_conull hnull]
  exact hν x

end CantorRealization

end Kolmogorov
