import KolmogorovMathlib.MonotoneComplexity.EffectiveOpen
import KolmogorovMathlib.MonotoneComplexity.REClosure
import KolmogorovMathlib.Foundation.RecursivelyEnumerable
import KolmogorovMathlib.MonotoneComplexity.TreeSemimeasure
import KolmogorovMathlib.AlgorithmicRandomness.StrongLaw

/-!
# Probabilistic generators

This module defines probabilistic generators and the continuous tree semimeasures
they generate.
-/

namespace Kolmogorov

open MeasureTheory ENNReal

/-- A machine that turns an infinite fair coin sequence into an output stream, together with a
recursively enumerable graph recording which input prefixes already force which output prefixes.
Soundness says a forced pair really constrains the output; completeness says every output prefix
is forced by some input prefix. -/
structure ProbabilisticGenerator where
  output : CantorSeq → BitStream
  lowerGraph : BitString → BitString → Prop
  lowerGraph_re : IsRE fun q : BitString × BitString => lowerGraph q.1 q.2
  lowerGraph_sound : ∀ {p y}, lowerGraph p y →
      cantorCylinder p ⊆ output ⁻¹' bitStreamCylinder y
  lowerGraph_complete : ∀ {w y}, output w ∈ bitStreamCylinder y →
      ∃ p, w ∈ cantorCylinder p ∧ lowerGraph p y

/-- The probability that the generator `G` outputs a stream extending `x`, computed as the uniform
measure of the set of input sequences with that output. -/
noncomputable def generatedTreeSemimeasure (G : ProbabilisticGenerator) (x : BitString) : ℝ≥0∞ :=
  uniformMeasure (G.output ⁻¹' bitStreamCylinder x)

/-- The inputs whose output extends `x` are exactly the union of the cylinders that the lower graph
of `G` associates with `x`. -/
lemma preimage_bitStreamCylinder_eq_cantorOpen (G : ProbabilisticGenerator) (x : BitString) :
    G.output ⁻¹' bitStreamCylinder x = cantorOpen G.lowerGraph x := by
  ext w
  simp only [cantorOpen, Set.mem_preimage, Set.mem_iUnion]
  constructor
  · intro hw
    rcases G.lowerGraph_complete hw with ⟨p, hp, hp_graph⟩
    exact ⟨p, hp_graph, hp⟩
  · rintro ⟨p, hp_graph, hp⟩
    exact G.lowerGraph_sound hp_graph hp

instance : IsProbabilityMeasure uniformMeasure := by
  unfold uniformMeasure
  infer_instance

/-- Every output extends the empty string, so the generated semimeasure has total mass `1` at the
root. -/
lemma generatedTreeSemimeasure_nil (G : ProbabilisticGenerator) :
    generatedTreeSemimeasure G [] = 1 := by
  unfold generatedTreeSemimeasure
  rw [bitStreamCylinder_nil]
  simp

/-- The two children of `x` receive disjoint sets of inputs, so their generated masses sum to at
most
the mass of `x`. -/
lemma generatedTreeSemimeasure_children_le (G : ProbabilisticGenerator) (x : BitString) :
    generatedTreeSemimeasure G (x ++ [false]) + generatedTreeSemimeasure G (x ++ [true])
      ≤ generatedTreeSemimeasure G x := by
  unfold generatedTreeSemimeasure
  have hne : ∀ (b1 b2 : Bool), b1 ≠ b2 → ¬ (x ++ [b1]) <+: (x ++ [b2]) := by
    intro b1 b2 hb hpref
    have hlen : (x ++ [b1]).length = (x ++ [b2]).length := by simp
    have heq := List.IsPrefix.eq_of_length hpref hlen
    have hbb := List.append_cancel_left heq
    rw [List.cons.injEq] at hbb
    exact hb hbb.1
  have hdisj : Disjoint (bitStreamCylinder (x ++ [false])) (bitStreamCylinder (x ++ [true])) :=
    bitStreamCylinder_disjoint_of_incompatible (hne false true (by decide))
      (hne true false (by decide))
  have hdisj' : Disjoint (G.output ⁻¹' bitStreamCylinder (x ++ [false]))
      (G.output ⁻¹' bitStreamCylinder (x ++ [true])) := hdisj.preimage G.output
  have h_meas2 : MeasurableSet (G.output ⁻¹' bitStreamCylinder (x ++ [true])) := by
    rw [preimage_bitStreamCylinder_eq_cantorOpen]
    exact measurableSet_cantorOpen _ _
  rw [← measure_union hdisj' h_meas2]
  apply measure_mono
  intro w hw
  simp only [Set.mem_union, Set.mem_preimage] at hw
  cases hw with
  | inl hw =>
    exact bitStreamCylinder_subset_of_prefix (List.prefix_append x [false]) hw
  | inr hw =>
    exact bitStreamCylinder_subset_of_prefix (List.prefix_append x [true]) hw

/-- The semimeasure generated by a probabilistic generator is a continuous tree semimeasure. -/
lemma generatedTreeSemimeasure_isContinuousTreeSemimeasure (G : ProbabilisticGenerator) :
    IsContinuousTreeSemimeasure (generatedTreeSemimeasure G) :=
  ⟨generatedTreeSemimeasure_nil G, generatedTreeSemimeasure_children_le G⟩

/-- A string is all zeros exactly when it is a prefix of the constantly zero sequence. -/
lemma eq_replicate_false_iff_cantorPrefix {x : BitString} :
    x = List.replicate x.length false ↔ IsCantorPrefix x (fun _ => false) := by
  rw [List.eq_replicate_iff]
  constructor
  · rintro ⟨_, h2⟩ i hi
    exact (h2 _ (List.getElem_mem hi)).symm
  · intro h
    refine ⟨rfl, ?_⟩
    intro b hb
    rcases List.mem_iff_getElem.mp hb with ⟨i, hi, rfl⟩
    exact (h i hi).symm


/-- Boolean test deciding whether a bit string consists only of zeros. -/
def myAllFalse : List Bool → Bool :=
  fun x => List.foldr (fun b acc => bif b then false else acc) true x

/-- The test `myAllFalse` returns `true` exactly on the all-zero strings. -/
lemma myAllFalse_eq (x : List Bool) : myAllFalse x = true ↔ x = List.replicate x.length false := by
  induction x with
  | nil => simp [myAllFalse]
  | cons b tail ih =>
    simp only [myAllFalse, List.foldr_cons, List.length_cons, List.replicate]
    cases b
    · simp only [Bool.cond_false]
      constructor
      · intro h
        rw [ih.mp h]
        simp only [List.length_replicate]
      · intro h
        injection h with _ h2
        exact ih.mpr h2
    · simp only [Bool.cond_true]
      constructor
      · intro h; contradiction
      · intro h; injection h with h1 _; contradiction

/-- The all-zero test is primitive recursive. -/
lemma primrec_myAllFalse : Primrec myAllFalse := by
  have step : Primrec₂ (fun (a : List Bool) (p : Bool × Bool) => bif p.1 then false else p.2) := by
    have hc : Primrec (fun (q : List Bool × (Bool × Bool)) => q.2.1) := Primrec.fst.comp Primrec.snd
    have hf : Primrec (fun (q : List Bool × (Bool × Bool)) => false) := Primrec.const false
    have hg : Primrec (fun (q : List Bool × (Bool × Bool)) => q.2.2) := Primrec.snd.comp Primrec.snd
    exact Primrec.cond hc hf hg
  exact Primrec.list_foldr Primrec.id (Primrec.const true) step

/-- A string is all zeros exactly when it is a prefix of the all-zero string of its own length. -/
lemma eq_replicate_false_iff_cantorPrefix2 {x : BitString} :
    x = List.replicate x.length false ↔
    x <+: List.replicate x.length false := by
  constructor
  · intro h; rw [h]
    simp only [List.length_replicate]
    exact List.prefix_rfl
  · intro h
    have hlen1 : x.length = (List.replicate x.length false).length := by simp
    exact List.IsPrefix.eq_of_length h hlen1

/-- The relation "the second component is an all-zero string" is recursively enumerable; this is the
lower graph of the generator that always outputs zeros. -/
lemma lowerGraph_re_proof : IsRE (fun q : BitString × BitString =>
    q.2 <+: List.replicate q.2.length false) := by
  let check : BitString × BitString → Bool := fun q => myAllFalse q.2
  have h_iff : ∀ q, check q = true ↔ q.2 <+: List.replicate q.2.length false := by
    intro q
    rw [myAllFalse_eq]
    exact eq_replicate_false_iff_cantorPrefix2
  have h_comp : Computable check := by
    exact Primrec.to_comp (primrec_myAllFalse.comp Primrec.snd)
  exact isRE_of_computable_bool _ check h_iff h_comp

/-- The deterministic generator that outputs the constantly zero stream on every input. -/
def zeroGenerator : ProbabilisticGenerator where
  output _ := .infinite fun _ => false
  lowerGraph p y := y <+: (List.replicate y.length false)
  lowerGraph_re := lowerGraph_re_proof
  lowerGraph_sound := by
    intro p y hy w hw
    simp only [bitStreamCylinder]
    have h1 : IsCantorPrefix y (fun _ => false) := by
      exact eq_replicate_false_iff_cantorPrefix.mp (List.IsPrefix.eq_of_length hy (by simp))
    exact h1
  lowerGraph_complete := by
    intro w y hy
    simp only [bitStreamCylinder] at hy
    have h1 : y = List.replicate y.length false := by
      exact eq_replicate_false_iff_cantorPrefix.mpr hy
    use []
    constructor
    · change IsCantorPrefix [] w
      intro i hi
      contradiction
    · rw [h1]
      simp only [List.length_replicate]
      exact List.prefix_rfl
/-- The generator that always outputs zeros realises the semimeasure concentrated on the all-zero
branch: mass `1` on all-zero strings and `0` elsewhere. -/
lemma zeroGenerator_semimeasure (x : BitString) :
    generatedTreeSemimeasure zeroGenerator x = if x = List.replicate x.length false then 1 else 0 :=
   
    by
  unfold generatedTreeSemimeasure zeroGenerator
  have h_univ : (fun _ : CantorSeq => BitStream.infinite fun _ => false) ⁻¹' bitStreamCylinder x =
    if x = List.replicate x.length false then Set.univ else ∅ := by
    ext w
    split_ifs with h
    · simp only [Set.mem_preimage, bitStreamCylinder, Set.mem_Ici, Set.mem_univ, iff_true]
      change IsCantorPrefix x (fun _ => false)
      exact eq_replicate_false_iff_cantorPrefix.mp h
    · simp only [Set.mem_preimage,
    bitStreamCylinder,
    Set.mem_Ici,
    Set.mem_empty_iff_false,
    iff_false]
      intro hle
      have hle' : IsCantorPrefix x (fun _ => false) := hle
      exact h (eq_replicate_false_iff_cantorPrefix.mpr hle')
  rw [h_univ]
  split_ifs with h
  · simp [measure_univ]
  · simp

/-- The semimeasure generated by a probabilistic generator is a lower semicomputable continuous
semimeasure, so it is dominated by the universal continuous semimeasure. -/
theorem generatedTreeSemimeasure_isLowerSemicomputableContinuousSemimeasure
    (G : ProbabilisticGenerator) :
    IsLowerSemicomputableContinuousSemimeasure (generatedTreeSemimeasure G) := by
  refine ⟨generatedTreeSemimeasure_isContinuousTreeSemimeasure G, ?_⟩
  have h_eq : (fun (x : BitString) (_ : BitString) => generatedTreeSemimeasure G x)
      = (fun x _ => cantorOpenMass G.lowerGraph x) := by
    ext x _
    unfold generatedTreeSemimeasure cantorOpenMass
    rw [preimage_bitStreamCylinder_eq_cantorOpen]
  rw [h_eq]
  exact cantorOpenMass_isLSC G.lowerGraph_re

end Kolmogorov
