import KolmogorovMathlib.MonotoneComplexity.Stream
import KolmogorovMathlib.AlgorithmicRandomness.Cylinders
import KolmogorovMathlib.AlgorithmicRandomness.Cantor
import Mathlib.Topology.Bases

/-!
# SUV prefix topology on finite/infinite streams

This module defines the prefix-cone topology on `BitStream` exactly as
described in SUV §4.4.3. The space `E = Σ ∪ Ω` is endowed with the topology
generated by the cones `bitStreamCylinder x`, which are the basic open sets.

## Conflation guard
Cylinder mass `p(x) = p(x0) + p(x1)` (equality, §3.1) ≠ tree semimeasure
`a(x) ≥ a(x0) + a(x1)` (inequality, Thm 75) ≠ the existing discrete
`aprioriMeasure`. No identification without a proved bridge.
-/

namespace Kolmogorov
open BitStream

/-- The cone of all finite and infinite extensions of a string `x`. -/
def bitStreamCylinder (x : BitString) : Set BitStream := Set.Ici (.finite x)

/-- A finite stream lies in the cylinder of `x` exactly when `x` is a prefix of it. -/
lemma mem_bitStreamCylinder_finite {x y : BitString} :
    .finite y ∈ bitStreamCylinder x ↔ x <+: y := by
  change BitStream.le (.finite x) (.finite y) ↔ x <+: y
  exact BitStream.finite_le_finite_iff

/-- An infinite stream lies in the cylinder of `x` exactly when `x` is a prefix of its sequence. -/
lemma mem_bitStreamCylinder_infinite {x : BitString} {w : CantorSeq} :
    .infinite w ∈ bitStreamCylinder x ↔ IsCantorPrefix x w := by
  change BitStream.le (.finite x) (.infinite w) ↔ IsCantorPrefix x w
  exact BitStream.finite_le_infinite_iff

/-- The cylinder of the empty string is the whole stream space. -/
lemma bitStreamCylinder_nil : bitStreamCylinder [] = Set.univ := by
  ext s
  simp only [Set.mem_univ, iff_true]
  change BitStream.le (.finite []) s
  cases s with
  | finite y => exact List.nil_prefix
  | infinite w => intro i hi; simp at hi

/-- Cylinders over longer strings are contained in cylinders over their prefixes. -/
lemma bitStreamCylinder_subset_of_prefix {x y : BitString} (h : x <+: y) :
    bitStreamCylinder y ⊆ bitStreamCylinder x := by
  intro s hs
  rw [bitStreamCylinder, Set.mem_Ici] at hs ⊢
  exact le_trans (BitStream.finite_le_finite_iff.mpr h) hs

/-- Intersecting a cylinder with a cylinder over an extension gives the smaller cylinder. -/
lemma bitStreamCylinder_inter_of_prefix {x y : BitString} (h : x <+: y) :
    bitStreamCylinder x ∩ bitStreamCylinder y = bitStreamCylinder y := by
  apply Set.inter_eq_right.mpr
  exact bitStreamCylinder_subset_of_prefix h

/-- Cylinders over prefix-incomparable strings are disjoint. -/
lemma bitStreamCylinder_disjoint_of_incompatible {x y : BitString}
    (h1 : ¬ x <+: y) (h2 : ¬ y <+: x) :
    Disjoint (bitStreamCylinder x) (bitStreamCylinder y) := by
  rw [Set.disjoint_iff]
  intro s hs
  simp only [Set.mem_inter_iff, bitStreamCylinder, Set.mem_Ici] at hs
  have hx := hs.1
  have hy := hs.2
  rcases le_total x.length y.length with hlen | hlen
  · have h_pref : x <+: y := by
      rw [List.prefix_iff_eq_take]
      apply List.ext_getElem
      · simp [hlen]
      · intro i hi1 hi2
        have hi : i < x.length := by simpa using hi1
        have hi_y : i < y.length := by omega
        simp only [List.getElem_take]
        cases s with
        | finite z =>
          change x <+: z at hx
          change y <+: z at hy
          have H1 := List.IsPrefix.getElem hx hi
          have H2 := List.IsPrefix.getElem hy hi_y
          rw [H1, H2]
        | infinite w =>
          change IsCantorPrefix x w at hx
          change IsCantorPrefix y w at hy
          have H1 := hx i hi
          have H2 := hy i hi_y
          rw [← H1, H2]
    exact (h1 h_pref).elim
  · have h_pref : y <+: x := by
      rw [List.prefix_iff_eq_take]
      apply List.ext_getElem
      · simp [hlen]
      · intro i hi1 hi2
        have hi : i < y.length := by simpa using hi1
        have hi_x : i < x.length := by omega
        simp only [List.getElem_take]
        cases s with
        | finite z =>
          change x <+: z at hx
          change y <+: z at hy
          have H1 := List.IsPrefix.getElem hy hi
          have H2 := List.IsPrefix.getElem hx hi_x
          rw [H1, H2]
        | infinite w =>
          change IsCantorPrefix x w at hx
          change IsCantorPrefix y w at hy
          have H1 := hy i hi
          have H2 := hx i hi_x
          rw [← H1, H2]
    exact (h2 h_pref).elim

instance : TopologicalSpace BitStream := .generateFrom (Set.range bitStreamCylinder)

/-- The cylinders form a basis of the topology on the space of finite and infinite bit streams. -/
lemma isTopologicalBasis_bitStreamCylinders :
    TopologicalSpace.IsTopologicalBasis (Set.range bitStreamCylinder) := by
  apply TopologicalSpace.isTopologicalBasis_of_isOpen_of_nhds
  · rintro s ⟨x, rfl⟩
    exact TopologicalSpace.GenerateOpen.basic _ ⟨x, rfl⟩
  · intro a u ha hu
    induction hu with
    | basic s hs =>
      rcases hs with ⟨x, rfl⟩
      exact ⟨bitStreamCylinder x, ⟨x, rfl⟩, ha, Set.Subset.refl _⟩
    | univ =>
      exact ⟨bitStreamCylinder [], ⟨[], rfl⟩, by rw [bitStreamCylinder_nil]; exact Set.mem_univ a,
        Set.subset_univ _⟩
    | inter s1 s2 hs1 hs2 ih1 ih2 =>
      rcases ih1 ha.1 with ⟨c1, ⟨x1, rfl⟩, ha1, hc1⟩
      rcases ih2 ha.2 with ⟨c2, ⟨x2, rfl⟩, ha2, hc2⟩
      have ha_inter : a ∈ bitStreamCylinder x1 ∩ bitStreamCylinder x2 := ⟨ha1, ha2⟩
      rcases le_total x1.length x2.length with hlen | hlen
      · by_cases h_comp : x1 <+: x2
        · exact ⟨bitStreamCylinder x2, ⟨x2, rfl⟩, ha2,
          Set.subset_inter (Set.Subset.trans (bitStreamCylinder_subset_of_prefix h_comp) hc1) hc2⟩
        · by_cases h_comp2 : x2 <+: x1
          · exact ⟨bitStreamCylinder x1, ⟨x1, rfl⟩, ha1,
          Set.subset_inter hc1 (Set.Subset.trans (bitStreamCylinder_subset_of_prefix h_comp2) hc2)⟩
          · have h_disj := bitStreamCylinder_disjoint_of_incompatible h_comp h_comp2
            exfalso
            exact Set.disjoint_iff.mp h_disj ha_inter
      · by_cases h_comp : x2 <+: x1
        · exact ⟨bitStreamCylinder x1, ⟨x1, rfl⟩, ha1,
          Set.subset_inter hc1 (Set.Subset.trans (bitStreamCylinder_subset_of_prefix h_comp) hc2)⟩
        · by_cases h_comp2 : x1 <+: x2
          · exact ⟨bitStreamCylinder x2, ⟨x2, rfl⟩, ha2,
          Set.subset_inter (Set.Subset.trans (bitStreamCylinder_subset_of_prefix h_comp2) hc1) hc2⟩
          · have h_disj := bitStreamCylinder_disjoint_of_incompatible h_comp2 h_comp
            exfalso
            exact Set.disjoint_iff.mp h_disj ha_inter
    | sUnion S h ih =>
      rcases ha with ⟨s, hs, ha_s⟩
      rcases ih s hs ha_s with ⟨c, hc, hac, hcs⟩
      exact ⟨c, hc, hac, Set.Subset.trans hcs (Set.subset_sUnion_of_mem hs)⟩

/-- Pulling a stream cylinder back along the inclusion of Cantor space gives the corresponding
Cantor
cylinder. -/
lemma preimage_bitStreamCylinder_infinite (x : BitString) :
    BitStream.infinite ⁻¹' bitStreamCylinder x = cantorCylinder x := by
  ext w
  simp only [Set.mem_preimage]
  change BitStream.le (.finite x) (.infinite w) ↔ _
  exact BitStream.finite_le_infinite_iff

/-- Every cylinder of the stream space is open. -/
lemma isOpen_bitStreamCylinder (x : BitString) : IsOpen (bitStreamCylinder x) :=
  isTopologicalBasis_bitStreamCylinders.isOpen ⟨x, rfl⟩

/-- A set of streams is open exactly when it contains the whole cylinder of each of its finite
members and, for each of its infinite members, some finite prefix. -/
theorem isOpen_bitStream_iff {A : Set BitStream} :
    IsOpen A ↔
      (∀ x, BitStream.finite x ∈ A → bitStreamCylinder x ⊆ A) ∧
      (∀ w, BitStream.infinite w ∈ A →
        ∃ n, BitStream.finite (cantorPrefix w n) ∈ A) := by
  constructor
  · intro hA
    constructor
    · intro x hx
      rw [isTopologicalBasis_bitStreamCylinders.isOpen_iff] at hA
      rcases hA (BitStream.finite x) hx with ⟨c, ⟨y, rfl⟩, hyx, hyA⟩
      have hyx_pref : y <+: x := mem_bitStreamCylinder_finite.mp hyx
      exact Set.Subset.trans (bitStreamCylinder_subset_of_prefix hyx_pref) hyA
    · intro w hw
      rw [isTopologicalBasis_bitStreamCylinders.isOpen_iff] at hA
      rcases hA (BitStream.infinite w) hw with ⟨c, ⟨y, rfl⟩, hyw, hyA⟩
      have hyw_pref : IsCantorPrefix y w := mem_bitStreamCylinder_infinite.mp hyw
      use y.length
      have h_eq : cantorPrefix w y.length = y := by
        exact (isCantorPrefix_iff_cantorPrefix_eq y w).mp hyw_pref
      rw [h_eq]
      apply hyA
      exact mem_bitStreamCylinder_finite.mpr (List.prefix_refl y)
  · intro h
    rw [isTopologicalBasis_bitStreamCylinders.isOpen_iff]
    intro a ha
    cases a with
    | finite x =>
      exact ⟨bitStreamCylinder x, ⟨x, rfl⟩, mem_bitStreamCylinder_finite.mpr (List.prefix_refl x),
             h.1 x ha⟩
    | infinite w =>
      rcases h.2 w ha with ⟨n, hn⟩
      have h_pref : IsCantorPrefix (cantorPrefix w n) w := by
        rw [isCantorPrefix_iff_cantorPrefix_eq, cantorPrefix_length]
      exact ⟨bitStreamCylinder (cantorPrefix w n), ⟨cantorPrefix w n, rfl⟩,
             mem_bitStreamCylinder_infinite.mpr h_pref,
             h.1 _ hn⟩

end Kolmogorov
