/-
Copyright (c) 2024 Author Name. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Author Name
-/
import KolmogorovMathlib.InformationInequalities.Basic
import KolmogorovMathlib.InformationInequalities.Ingleton
import KolmogorovMathlib.InformationInequalities.ProductSpace
import Mathlib.Analysis.Convex.Basic
import Mathlib.Data.Fin.VecNotation

/-!
# The inequalities for two and three strings

SUV Section 10.10, pp. 336–337.

The class of linear information inequalities is known explicitly only for `n ≤ 3`.

* For `n = 2` the entropy region itself is known: a triple `(h₁, h₂, h₁₂)` is the entropy
  vector of some pair of random variables exactly when `H(ξ₂ | ξ₁)`, `H(ξ₁ | ξ₂)` and
  `I(ξ₁ : ξ₂)` are non-negative, and every true inequality is a non-negative combination of
  these three.
* For `n = 3`, in the Venn coordinates `a₁, …, a₇` of the three-variable diagram, the cone
  cut out by the basic inequalities is generated by the seven unit vectors of the regions and
  one more vector, with `−1` on the centre `I(ξ₁ : ξ₂ : ξ₃)` and `1` on the three regions next
  to it.  All eight are entropy vectors — the last one is that of two independent uniform bits
  and their sum modulo `2` — so every true inequality for three variables is a consequence of
  the basic inequalities.

Problems 292–293 add two facts about the shape of the entropy region `E`: it is closed under
addition, and its closure is convex.

Coordinates.  The book's `E` lives in `ℝ^{2^n − 1}`, indexed by the non-empty `I`.  Here a
point is a function on all `Finset (Fin n)`, and every entropy vector has the value `0` at `∅`
(the empty subtuple is constant); statements that describe `E` exactly therefore include the
normalisation `v ∅ = 0`.  The book's `ξ₁, ξ₂, ξ₃` are the indices `0, 1, 2`.
-/

namespace Kolmogorov

open Finset

/-! ### Evaluating a form on a concrete entropy vector -/

/-- A form that holds for entropies is non-positive on every point of the entropy region. -/
private theorem sum_mul_nonpos_of_holdsForEntropies {n : ℕ} {f : LinearForm n}
    (h : HoldsForEntropies f) {v : Finset (Fin n) → ℝ} (hv : v ∈ entropyRegion n) :
    ∑ I ∈ nonemptyParts n, f I * v I ≤ 0 := by
  obtain ⟨m, μ, X, rfl⟩ := hv
  exact h (Fin m) μ X

/-- The four subsets of `Fin 2`, for case analysis. -/
private theorem cases4 (I : Finset (Fin 2)) : I = ∅ ∨ I = {0} ∨ I = {1} ∨ I = {0, 1} := by
  revert I; decide

/-- A sum over the non-empty subsets of `Fin 2`, written out. -/
private theorem sum_nonemptyParts_two (g : Finset (Fin 2) → ℝ) :
    ∑ I ∈ nonemptyParts 2, g I = g {0} + g {1} + g {0, 1} := by
  rw [show nonemptyParts 2 = {{0}, {1}, {0, 1}} by decide]
  simp +decide [Finset.sum_insert]
  ring

/-- Splitting a non-negative real `b₅ ≤ b₂ + b₄ + b₆` into three parts bounded by `b₂, b₄, b₆`:
the bookkeeping behind the three-variable dual argument. -/
private theorem exists_split_three {b₂ b₄ b₆ b₅ : ℝ} (h₂ : 0 ≤ b₂) (h₄ : 0 ≤ b₄) (h₆ : 0 ≤ b₆)
    (h₅ : 0 ≤ b₅) (hle : b₅ ≤ b₂ + b₄ + b₆) :
    ∃ s₂ s₄ s₆ : ℝ, 0 ≤ s₂ ∧ s₂ ≤ b₂ ∧ 0 ≤ s₄ ∧ s₄ ≤ b₄ ∧ 0 ≤ s₆ ∧ s₆ ≤ b₆ ∧
      s₂ + s₄ + s₆ = b₅ := by
  rcases le_total b₅ b₂ with h | h
  · exact ⟨b₅, 0, 0, h₅, h, le_rfl, h₄, le_rfl, h₆, by ring⟩
  rcases le_total (b₅ - b₂) b₄ with h' | h'
  · exact ⟨b₂, b₅ - b₂, 0, h₂, le_rfl, by linarith, h', le_rfl, h₆, by ring⟩
  · exact ⟨b₂, b₄, b₅ - b₂ - b₄, h₂, le_rfl, h₄, le_rfl, by linarith, by linarith, by ring⟩

/-! ### Three variables -/

/-- The eight generators of the cone of basic inequalities for three variables, written in
entropy coordinates `(H₁, H₂, H₃, H₁₂, H₁₃, H₂₃, H₁₂₃)`.  The first seven are the unit vectors
of the seven regions of the Venn diagram — `H(ξ₁ | ξ₂ξ₃)`, `I(ξ₁ : ξ₂ | ξ₃)`,
`H(ξ₂ | ξ₁ξ₃)`, `I(ξ₁ : ξ₃ | ξ₂)`, the centre `I(ξ₁ : ξ₂ : ξ₃)`, `I(ξ₂ : ξ₃ | ξ₁)`,
`H(ξ₃ | ξ₁ξ₂)` — and the eighth has `−1` on the centre and `1` on the three conditional mutual
informations; it is the entropy vector `(1, 1, 1, 2, 2, 2, 2)` of two independent uniform bits
and their sum modulo `2`.  SUV Section 10.10, p. 337. -/
def threeGenerators : Fin 8 → Finset (Fin 3) → ℝ :=
  ![LinearForm.ofTable [({0}, 1), ({0, 1}, 1), ({0, 2}, 1), ({0, 1, 2}, 1)],
    LinearForm.ofTable [({0}, 1), ({1}, 1), ({0, 1}, 1), ({0, 2}, 1), ({1, 2}, 1),
      ({0, 1, 2}, 1)],
    LinearForm.ofTable [({1}, 1), ({0, 1}, 1), ({1, 2}, 1), ({0, 1, 2}, 1)],
    LinearForm.ofTable [({0}, 1), ({2}, 1), ({0, 1}, 1), ({0, 2}, 1), ({1, 2}, 1),
      ({0, 1, 2}, 1)],
    LinearForm.ofTable [({0}, 1), ({1}, 1), ({2}, 1), ({0, 1}, 1), ({0, 2}, 1), ({1, 2}, 1),
      ({0, 1, 2}, 1)],
    LinearForm.ofTable [({1}, 1), ({2}, 1), ({0, 1}, 1), ({0, 2}, 1), ({1, 2}, 1),
      ({0, 1, 2}, 1)],
    LinearForm.ofTable [({2}, 1), ({0, 2}, 1), ({1, 2}, 1), ({0, 1, 2}, 1)],
    LinearForm.ofTable [({0}, 1), ({1}, 1), ({2}, 1), ({0, 1}, 2), ({0, 2}, 2), ({1, 2}, 2),
      ({0, 1, 2}, 2)]]

/-- The eight subsets of `Fin 3`, for case analysis. -/
private theorem cases8 (I : Finset (Fin 3)) : I = ∅ ∨ I = {0} ∨ I = {1} ∨ I = {2} ∨
    I = {0, 1} ∨ I = {0, 2} ∨ I = {1, 2} ∨ I = {0, 1, 2} := by
  revert I; decide

/-- The uniform distribution on two outcomes: a fair bit. -/
private noncomputable def uniformTwo : FiniteProbSpace (Fin 2) where
  prob _ := 1 / 2
  prob_nonneg _ := by norm_num
  sum_prob := by simp

/-- A fair bit has entropy `1`. -/
private theorem entropy_uniformTwo_id : entropy uniformTwo (fun ω : Fin 2 => ω) = 1 := by
  have hd : ∀ a : Fin 2, uniformTwo.dist (fun ω : Fin 2 => ω) a = 1 / 2 := by
    intro a
    simp [FiniteProbSpace.dist, FiniteProbSpace.probOf, uniformTwo, Finset.filter_eq']
  have hr : rangeFinset (fun ω : Fin 2 => ω) = Finset.univ := by
    ext a
    simp
  have h2 : Real.log 2 ≠ 0 := (Real.log_pos (by norm_num)).ne'
  rw [entropy, hr, Fin.sum_univ_two, hd, hd, negMulLog2, Real.negMulLog, one_div, Real.log_inv]
  field_simp
  ring

/-- A constant random variable has entropy `0`. -/
private theorem entropy_const {Ω : Type} [Fintype Ω] [Nonempty Ω] {α : Type} [DecidableEq α]
    (μ : FiniteProbSpace Ω) (c : α) : entropy μ (fun _ => c) = 0 := by
  have hr : rangeFinset (fun _ : Ω => c) = {c} := by
    ext a
    simp [eq_comm]
  have hd : μ.dist (fun _ : Ω => c) c = 1 := by
    simp [FiniteProbSpace.dist]
  rw [entropy, hr, Finset.sum_singleton, hd]
  simp [negMulLog2, Real.negMulLog]

/-- The entropy vector of the tuple "a fair bit at the indices of `S`, the constant `0`
elsewhere": the value `1` on every set meeting `S` and `0` on the others.  These are the
seven region vectors of the three-variable Venn diagram. -/
private theorem indicator_mem_entropyRegion (S : Finset (Fin 3)) :
    (fun I : Finset (Fin 3) => if (I ∩ S).Nonempty then (1 : ℝ) else 0) ∈ entropyRegion 3 := by
  refine ⟨2, uniformTwo, fun i ω => if i ∈ S then ω.val else 0, ?_⟩
  funext I
  simp only [entropyVector, entropySub]
  split_ifs with h
  · obtain ⟨i, hi⟩ := h
    rw [Finset.mem_inter] at hi
    have hinj :
        Function.Injective (subtuple (fun i (ω : Fin 2) => if i ∈ S then ω.val else 0) I) := by
      intro ω₁ ω₂ hω
      have := congrFun hω ⟨i, hi.1⟩
      exact Fin.ext (by simpa [subtuple, hi.2] using this)
    rw [← entropy_uniformTwo_id]
    exact (entropy_comp_of_injective uniformTwo (fun ω => ω) hinj).symm
  · have hconst : subtuple (fun i (ω : Fin 2) => if i ∈ S then ω.val else 0) I
        = fun _ => fun _ => 0 := by
      funext ω i
      simp only [subtuple, ite_eq_right_iff]
      intro hiS
      exact (h ⟨i.1, Finset.mem_inter.2 ⟨i.2, hiS⟩⟩).elim
    rw [hconst, entropy_const]

/-- The supports of the first seven generators: generator `k` is the vector with `1` on the
sets meeting `threeSupports k`. -/
private def threeSupports : Fin 7 → Finset (Fin 3) :=
  ![{0}, {0, 1}, {1}, {0, 2}, {0, 1, 2}, {1, 2}, {2}]

private theorem threeGenerators_castSucc (k : Fin 7) : threeGenerators k.castSucc
    = fun I : Finset (Fin 3) => if (I ∩ threeSupports k).Nonempty then (1 : ℝ) else 0 := by
  funext I
  fin_cases k <;> rcases cases8 I with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    simp +decide [threeGenerators, LinearForm.ofTable]

/-- The uniform distribution on four outcomes: two independent fair bits. -/
private noncomputable def uniformFour : FiniteProbSpace (Fin 4) where
  prob _ := 1 / 4
  prob_nonneg _ := by norm_num
  sum_prob := by
    rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin]
    norm_num

/-- The entropy summand at `1/2`. -/
private theorem negMulLog2_half : negMulLog2 (1 / 2) = 1 / 2 := by
  have h2 : Real.log 2 ≠ 0 := (Real.log_pos (by norm_num)).ne'
  rw [negMulLog2, Real.negMulLog, one_div, Real.log_inv]
  field_simp

/-- The entropy summand at `1/4`. -/
private theorem negMulLog2_quarter : negMulLog2 (1 / 4) = 1 / 2 := by
  have h2 : Real.log 2 ≠ 0 := (Real.log_pos (by norm_num)).ne'
  have h4 : Real.log 4 = 2 * Real.log 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.log_pow]
    norm_num
  rw [negMulLog2, Real.negMulLog, one_div, Real.log_inv, h4]
  field_simp
  ring

/-- Two fair bits and their sum modulo `2`, as a triple of `ℕ`-valued variables on the
uniform space `Fin 4`: the outcome `ω` carries the bits `ω / 2` and `ω % 2`. -/
private def xorTriple : Fin 3 → Fin 4 → ℕ :=
  ![fun ω => ω.val / 2, fun ω => ω.val % 2, fun ω => (ω.val / 2 + ω.val % 2) % 2]

/-- The uniform outcome of `Fin 4` has entropy `2`. -/
private theorem entropy_uniformFour_id : entropy uniformFour (fun ω : Fin 4 => ω) = 2 := by
  have hd : ∀ a : Fin 4, uniformFour.dist (fun ω : Fin 4 => ω) a = 1 / 4 := by
    intro a
    simp [FiniteProbSpace.dist, FiniteProbSpace.probOf, uniformFour, Finset.filter_eq']
  have hr : rangeFinset (fun ω : Fin 4 => ω) = Finset.univ := by
    ext a
    simp
  rw [entropy, hr, Fin.sum_univ_four, hd, hd, hd, hd, negMulLog2_quarter]
  norm_num

/-- Each of the three variables of `xorTriple` is a fair bit: entropy `1`. -/
private theorem entropy_xorTriple (i : Fin 3) : entropy uniformFour (xorTriple i) = 1 := by
  have hd : ∀ a : ℕ, uniformFour.dist (xorTriple i) a
      = ∑ ω : Fin 4, if xorTriple i ω = a then (1 / 4 : ℝ) else 0 := by
    intro a
    rw [FiniteProbSpace.dist, FiniteProbSpace.probOf, Finset.sum_filter]
    rfl
  have hr : rangeFinset (xorTriple i) = {0, 1} := by
    fin_cases i <;> decide
  rw [entropy, hr, Finset.sum_pair (by decide), hd, hd]
  fin_cases i <;> norm_num [xorTriple, Fin.sum_univ_four, negMulLog2_half]

/-- `H(ξ_{\{i\}}) = H(ξ_i)`. -/
private theorem entropySub_singleton' {Ω : Type} [Fintype Ω] (μ : FiniteProbSpace Ω) {n : ℕ}
    (X : Fin n → Ω → ℕ) (i : Fin n) : entropySub μ X {i} = entropy μ (X i) := by
  have hg : Function.Injective (fun a : ℕ => fun _ : ({i} : Finset (Fin n)) => a) := by
    intro a b h
    exact congrFun h ⟨i, Finset.mem_singleton_self i⟩
  have hc : subtuple X {i} = (fun a : ℕ => fun _ : ({i} : Finset (Fin n)) => a) ∘ X i := by
    funext ω j
    have hj : j.val = i := Finset.mem_singleton.1 j.2
    simp [subtuple, hj]
  rw [entropySub, hc, entropy_comp_of_injective μ (X i) hg]

/-- A subtuple of `xorTriple` that determines the outcome has entropy `2`. -/
private theorem entropySub_xorTriple_of_injective (I : Finset (Fin 3))
    (hinj : Function.Injective (subtuple xorTriple I)) :
    entropySub uniformFour xorTriple I = 2 := by
  have h := entropy_comp_of_injective uniformFour (fun ω : Fin 4 => ω) hinj
  rw [entropy_uniformFour_id] at h
  exact h

/-- The eighth generator, `(1, 1, 1, 2, 2, 2, 2)`, is the entropy vector of two independent
fair bits and their sum modulo `2`.  SUV Section 10.10, p. 337. -/
private theorem xorGenerator_mem_entropyRegion : threeGenerators 7 ∈ entropyRegion 3 := by
  refine ⟨4, uniformFour, xorTriple, ?_⟩
  funext I
  have hsingle : ∀ i : Fin 3, entropyVector uniformFour xorTriple {i} = 1 := fun i => by
    rw [entropyVector, entropySub_singleton', entropy_xorTriple]
  have hinj : ∀ (I : Finset (Fin 3)) (i j : Fin 3), i ∈ I → j ∈ I → i ≠ j →
      Function.Injective (subtuple xorTriple I) := by
    intro I i j hi hj hij ω₁ ω₂ h
    have h0 := congrFun h ⟨i, hi⟩
    have h1 := congrFun h ⟨j, hj⟩
    fin_cases i <;> fin_cases j <;> simp [subtuple, xorTriple] at h0 h1 hij <;>
      exact Fin.ext (by omega)
  rcases cases8 I with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · simp [threeGenerators, LinearForm.ofTable, entropyVector]
  · rw [hsingle]
    simp +decide [threeGenerators, LinearForm.ofTable]
  · rw [hsingle]
    simp +decide [threeGenerators, LinearForm.ofTable]
  · rw [hsingle]
    simp +decide [threeGenerators, LinearForm.ofTable]
  · rw [entropyVector,
      entropySub_xorTriple_of_injective _ (hinj _ 0 1 (by decide) (by decide) (by decide))]
    simp +decide [threeGenerators, LinearForm.ofTable]
  · rw [entropyVector,
      entropySub_xorTriple_of_injective _ (hinj _ 0 2 (by decide) (by decide) (by decide))]
    simp +decide [threeGenerators, LinearForm.ofTable]
  · rw [entropyVector,
      entropySub_xorTriple_of_injective _ (hinj _ 1 2 (by decide) (by decide) (by decide))]
    simp +decide [threeGenerators, LinearForm.ofTable]
  · rw [entropyVector,
      entropySub_xorTriple_of_injective _ (hinj _ 0 1 (by decide) (by decide) (by decide))]
    simp +decide [threeGenerators, LinearForm.ofTable]

/-- Each of the eight generators of the three-variable cone is an entropy vector.
SUV Section 10.10, p. 337 (unnumbered). -/
theorem threeGenerators_mem_entropyRegion (k : Fin 8) : threeGenerators k ∈ entropyRegion 3 := by
  by_cases hk : k = 7
  · subst hk
    exact xorGenerator_mem_entropyRegion
  · have hk' : k.val < 7 := by
      have h8 := k.isLt
      have : k.val ≠ 7 := fun h => hk (Fin.ext h)
      omega
    obtain ⟨j, rfl⟩ : ∃ j : Fin 7, k = j.castSucc := ⟨⟨k, hk'⟩, Fin.ext rfl⟩
    rw [threeGenerators_castSucc]
    exact indicator_mem_entropyRegion _

/-- For three variables the cone cut out by the basic inequalities is the set of non-negative
combinations of the eight generators.  To write a point of the cone as such a combination, use
the special generator with coefficient `|a₅|` when the centre coordinate `a₅` is negative and
adjust the other coordinates.  SUV Section 10.10, p. 337 (unnumbered). -/
theorem basicCone_three_eq_generated :
    basicCone 3 = {v | ∃ c : Fin 8 → ℝ, (∀ k, 0 ≤ c k) ∧
      ∀ I, v I = ∑ k, c k * threeGenerators k I} := by
  ext v
  constructor
  · rintro ⟨hempty, hnn, hmono, hsub⟩
    have hm1 := hmono {1, 2} {0, 1, 2} (by decide)
    have hm2 := hmono {0, 2} {0, 1, 2} (by decide)
    have hm3 := hmono {0, 1} {0, 1, 2} (by decide)
    have hs1 := hsub {0, 2} {1, 2}
    have hs2 := hsub {0, 1} {1, 2}
    have hs3 := hsub {0, 1} {0, 2}
    have hp1 := hsub {0} {1}
    have hp2 := hsub {0} {2}
    have hp3 := hsub {1} {2}
    rw [show ({0, 2} : Finset (Fin 3)) ∩ {1, 2} = {2} by decide,
      show ({0, 2} : Finset (Fin 3)) ∪ {1, 2} = {0, 1, 2} by decide] at hs1
    rw [show ({0, 1} : Finset (Fin 3)) ∩ {1, 2} = {1} by decide,
      show ({0, 1} : Finset (Fin 3)) ∪ {1, 2} = {0, 1, 2} by decide] at hs2
    rw [show ({0, 1} : Finset (Fin 3)) ∩ {0, 2} = {0} by decide,
      show ({0, 1} : Finset (Fin 3)) ∪ {0, 2} = {0, 1, 2} by decide] at hs3
    rw [show ({0} : Finset (Fin 3)) ∩ {1} = ∅ by decide,
      show ({0} : Finset (Fin 3)) ∪ {1} = {0, 1} by decide, hempty] at hp1
    rw [show ({0} : Finset (Fin 3)) ∩ {2} = ∅ by decide,
      show ({0} : Finset (Fin 3)) ∪ {2} = {0, 2} by decide, hempty] at hp2
    rw [show ({1} : Finset (Fin 3)) ∩ {2} = ∅ by decide,
      show ({1} : Finset (Fin 3)) ∪ {2} = {1, 2} by decide, hempty] at hp3
    set a₅ := v {0} + v {1} + v {2} - v {0, 1} - v {0, 2} - v {1, 2} + v {0, 1, 2} with ha₅
    rcases le_or_gt 0 a₅ with h5 | h5
    · refine ⟨![v {0, 1, 2} - v {1, 2}, v {0, 2} + v {1, 2} - v {2} - v {0, 1, 2},
        v {0, 1, 2} - v {0, 2}, v {0, 1} + v {1, 2} - v {1} - v {0, 1, 2}, a₅,
        v {0, 1} + v {0, 2} - v {0} - v {0, 1, 2}, v {0, 1, 2} - v {0, 1}, 0], ?_, ?_⟩
      · intro k
        fin_cases k <;> simp <;> linarith
      · intro I
        rcases cases8 I with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
          simp +decide [Fin.sum_univ_eight, threeGenerators, LinearForm.ofTable] <;> linarith
    · refine ⟨![v {0, 1, 2} - v {1, 2}, v {0, 2} + v {1, 2} - v {2} - v {0, 1, 2} + a₅,
        v {0, 1, 2} - v {0, 2}, v {0, 1} + v {1, 2} - v {1} - v {0, 1, 2} + a₅, 0,
        v {0, 1} + v {0, 2} - v {0} - v {0, 1, 2} + a₅, v {0, 1, 2} - v {0, 1}, -a₅],
        ?_, ?_⟩
      · intro k
        fin_cases k <;> simp <;> linarith
      · intro I
        rcases cases8 I with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
          simp +decide [Fin.sum_univ_eight, threeGenerators, LinearForm.ofTable] <;> linarith
  · rintro ⟨c, hc, hv⟩
    have hg : ∀ k, threeGenerators k ∈ basicCone 3 := fun k =>
      entropyRegion_subset_basicCone 3 (threeGenerators_mem_entropyRegion k)
    refine ⟨?_, ?_, ?_, ?_⟩
    · rw [hv ∅]
      exact Finset.sum_eq_zero fun k _ => by rw [(hg k).1, mul_zero]
    · intro I
      rw [hv I]
      exact Finset.sum_nonneg fun k _ => mul_nonneg (hc k) ((hg k).2.1 I)
    · intro I J hIJ
      rw [hv I, hv J]
      exact Finset.sum_le_sum fun k _ => mul_le_mul_of_nonneg_left ((hg k).2.2.1 I J hIJ) (hc k)
    · intro I J
      rw [hv (I ∩ J), hv (I ∪ J), hv I, hv J, ← Finset.sum_add_distrib,
        ← Finset.sum_add_distrib]
      refine Finset.sum_le_sum fun k _ => ?_
      rw [← mul_add, ← mul_add]
      exact mul_le_mul_of_nonneg_left ((hg k).2.2.2 I J) (hc k)

/-- A sum over the non-empty subsets of `Fin 3`, written out. -/
private theorem sum_nonemptyParts_three (g : Finset (Fin 3) → ℝ) :
    ∑ I ∈ nonemptyParts 3, g I =
      g {0} + g {1} + g {2} + g {0, 1} + g {0, 2} + g {1, 2} + g {0, 1, 2} := by
  rw [show nonemptyParts 3 = {{0}, {1}, {2}, {0, 1}, {0, 2}, {1, 2}, {0, 1, 2}} by decide]
  simp +decide [Finset.sum_insert]
  ring

/-- For three variables every linear inequality that is true for entropies is a consequence of
the basic inequalities, i.e. a non-negative combination of them.
SUV Section 10.10, p. 337 (unnumbered). -/
theorem isShannonType_of_holdsForEntropies_three (f : LinearForm 3) (h : HoldsForEntropies f) :
    IsShannonType f := by
  have hg : ∀ k : Fin 8, f {0} * threeGenerators k {0} + f {1} * threeGenerators k {1}
      + f {2} * threeGenerators k {2} + f {0, 1} * threeGenerators k {0, 1}
      + f {0, 2} * threeGenerators k {0, 2} + f {1, 2} * threeGenerators k {1, 2}
      + f {0, 1, 2} * threeGenerators k {0, 1, 2} ≤ 0 := fun k => by
    have := sum_mul_nonpos_of_holdsForEntropies h (threeGenerators_mem_entropyRegion k)
    rwa [sum_nonemptyParts_three] at this
  have e₁ := hg 0
  have e₂ := hg 1
  have e₃ := hg 2
  have e₄ := hg 3
  have e₅ := hg 4
  have e₆ := hg 5
  have e₇ := hg 6
  have e₈ := hg 7
  simp +decide [threeGenerators, LinearForm.ofTable] at e₁ e₂ e₃ e₄ e₅ e₆ e₇ e₈
  obtain ⟨s₂, s₄, s₆, hs₂, hs₂', hs₄, hs₄', hs₆, hs₆', hsum⟩ :=
    exists_split_three (b₂ := -(f {0} + f {1} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}))
      (b₄ := -(f {0} + f {2} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}))
      (b₆ := -(f {1} + f {2} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}))
      (b₅ := -(f {0} + f {1} + f {2} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}))
      (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)
  refine ⟨9, ![monotonicityForm 3 {1, 2} {0}, monotonicityForm 3 {0, 2} {1},
    monotonicityForm 3 {0, 1} {2}, basicInequality 3 {0} {1} {2}, basicInequality 3 {0} {2} {1},
    basicInequality 3 {1} {2} {0}, basicInequality 3 {0} {1} ∅, basicInequality 3 {0} {2} ∅,
    basicInequality 3 {1} {2} ∅],
    ![-(f {0} + f {0, 1} + f {0, 2} + f {0, 1, 2}), -(f {1} + f {0, 1} + f {1, 2} + f {0, 1, 2}),
      -(f {2} + f {0, 2} + f {1, 2} + f {0, 1, 2}),
      -(f {0} + f {1} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}) - s₂,
      -(f {0} + f {2} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}) - s₄,
      -(f {1} + f {2} + f {0, 1} + f {0, 2} + f {1, 2} + f {0, 1, 2}) - s₆, s₂, s₄, s₆],
    ?_, ?_, ?_⟩
  · intro k
    fin_cases k <;> simp <;> linarith
  · intro k
    fin_cases k
    · exact Or.inr ⟨_, _, rfl⟩
    · exact Or.inr ⟨_, _, rfl⟩
    · exact Or.inr ⟨_, _, rfl⟩
    all_goals exact Or.inl ⟨_, _, _, rfl⟩
  · intro I hI
    rcases cases8 I with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · exact (Finset.not_nonempty_empty hI).elim
    all_goals
      simp +decide [Fin.sum_univ_succ, basicInequality, monotonicityForm]
      try linarith


/-! ### Problems 292–293 -/

/-- **Problem 292.**  For every `n` the entropy region is closed under addition: combine
independent copies of two tuples realising the two vectors.  SUV Problem 292, p. 337. -/
theorem add_mem_entropyRegion {n : ℕ} {v w : Finset (Fin n) → ℝ} (hv : v ∈ entropyRegion n)
    (hw : w ∈ entropyRegion n) : v + w ∈ entropyRegion n := by
  obtain ⟨m, μ, X, rfl⟩ := hv
  obtain ⟨m', ν, Y, rfl⟩ := hw
  refine ⟨m * m', prodSpace μ ν, fun i k =>
    Nat.pair (X i (finProdFinEquiv.symm k).1) (Y i (finProdFinEquiv.symm k).2), ?_⟩
  funext I
  simp only [Pi.add_apply, entropyVector, entropySub]
  have hginj : Function.Injective
      (fun p : (I → ℕ) × (I → ℕ) => fun i : I => Nat.pair (p.1 i) (p.2 i)) := by
    intro p q h
    refine Prod.ext (funext fun i => ?_) (funext fun i => ?_)
    · exact (Nat.pair_eq_pair.1 (congrFun h i)).1
    · exact (Nat.pair_eq_pair.1 (congrFun h i)).2
  have hcomp : subtuple (fun i k =>
      Nat.pair (X i (finProdFinEquiv.symm k).1) (Y i (finProdFinEquiv.symm k).2)) I
      = (fun p : (I → ℕ) × (I → ℕ) => fun i : I => Nat.pair (p.1 i) (p.2 i))
        ∘ pairRV (fun k => subtuple X I (finProdFinEquiv.symm k).1)
          (fun k => subtuple Y I (finProdFinEquiv.symm k).2) := rfl
  rw [hcomp, entropy_comp_of_injective _ _ hginj, entropy_prodSpace_pair]

/-- The cone of basic inequalities is closed: it is cut out by closed conditions on the
coordinates. -/
private theorem isClosed_basicCone (n : ℕ) : IsClosed (basicCone n) := by
  have h1 : IsClosed {v : Finset (Fin n) → ℝ | v ∅ = 0} :=
    isClosed_eq (continuous_apply ∅) continuous_const
  have h2 : IsClosed {v : Finset (Fin n) → ℝ | ∀ I, 0 ≤ v I} := by
    rw [Set.ofPred_forall]
    exact isClosed_iInter fun I => isClosed_le continuous_const (continuous_apply I)
  have h3 : IsClosed {v : Finset (Fin n) → ℝ | ∀ I J, I ⊆ J → v I ≤ v J} := by
    rw [Set.ofPred_forall]
    refine isClosed_iInter fun I => ?_
    rw [Set.ofPred_forall]
    refine isClosed_iInter fun J => ?_
    by_cases h : I ⊆ J
    · simp only [h, true_implies]
      exact isClosed_le (continuous_apply I) (continuous_apply J)
    · simp only [h, false_implies, Set.ofPred_true]
      exact isClosed_univ
  have h4 : IsClosed {v : Finset (Fin n) → ℝ | ∀ I J, v (I ∩ J) + v (I ∪ J) ≤ v I + v J} := by
    rw [Set.ofPred_forall]
    refine isClosed_iInter fun I => ?_
    rw [Set.ofPred_forall]
    exact isClosed_iInter fun J => isClosed_le
      ((continuous_apply (I ∩ J)).add (continuous_apply (I ∪ J)))
      ((continuous_apply I).add (continuous_apply J))
  exact h1.inter (h2.inter (h3.inter h4))

/-- The zero vector is an entropy vector: that of a tuple of constants. -/
private theorem zero_mem_entropyRegion (n : ℕ) :
    (0 : Finset (Fin n) → ℝ) ∈ entropyRegion n := by
  refine ⟨1, ⟨fun _ => 1, fun _ => zero_le_one, by simp⟩, fun _ _ => 0, ?_⟩
  funext I
  simp only [Pi.zero_apply, entropyVector, entropySub]
  have hconst : subtuple (fun _ _ => (0 : ℕ)) I = fun _ : Fin 1 => fun _ : I => (0 : ℕ) := rfl
  rw [hconst, entropy_const]

/-- The closure of the entropy region is closed under addition (Problem 292 and continuity). -/
private theorem add_mem_closure_entropyRegion {n : ℕ} {v w : Finset (Fin n) → ℝ}
    (hv : v ∈ closure (entropyRegion n)) (hw : w ∈ closure (entropyRegion n)) :
    v + w ∈ closure (entropyRegion n) :=
  map_mem_closure₂ continuous_add hv hw fun _ ha _ hb => add_mem_entropyRegion ha hb

/-- The space `μ` scaled by `ε`, together with a fresh outcome `Fin.last m` of probability
`1 - ε`: the variables are "switched on" with probability `ε`. -/
private noncomputable def mixSpace {m : ℕ} (μ : FiniteProbSpace (Fin m)) {ε : ℝ} (h0 : 0 ≤ ε)
    (h1 : ε ≤ 1) : FiniteProbSpace (Fin (m + 1)) where
  prob k := Fin.lastCases (1 - ε) (fun ω => ε * μ.prob ω) k
  prob_nonneg k := by
    induction k using Fin.lastCases with
    | last => simp only [Fin.lastCases_last]; linarith
    | cast ω => simp only [Fin.lastCases_castSucc]; exact mul_nonneg h0 (μ.prob_nonneg ω)
  sum_prob := by
    rw [Fin.sum_univ_castSucc]
    simp only [Fin.lastCases_castSucc, Fin.lastCases_last, ← Finset.mul_sum, μ.sum_prob]
    ring

/-- A random variable on the mixed space: `Y` on the old outcomes, `none` on the fresh one. -/
private def mixRV {m : ℕ} {β : Type} (Y : Fin m → β) : Fin (m + 1) → Option β :=
  Fin.lastCases none fun ω => some (Y ω)

private theorem rangeFinset_mixRV {m : ℕ} {β : Type} [DecidableEq β] (Y : Fin m → β) :
    rangeFinset (mixRV Y) = insert none ((rangeFinset Y).image some) := by
  ext o
  simp only [mem_rangeFinset, Finset.mem_insert, Finset.mem_image]
  constructor
  · rintro ⟨k, rfl⟩
    induction k using Fin.lastCases with
    | last => exact Or.inl (by simp [mixRV])
    | cast ω => exact Or.inr ⟨Y ω, ⟨ω, rfl⟩, by simp [mixRV]⟩
  · rintro (rfl | ⟨b, ⟨ω, rfl⟩, rfl⟩)
    · exact ⟨Fin.last m, by simp [mixRV]⟩
    · exact ⟨ω.castSucc, by simp [mixRV]⟩

private theorem dist_mixSpace_none {m : ℕ} (μ : FiniteProbSpace (Fin m)) {ε : ℝ} (h0 : 0 ≤ ε)
    (h1 : ε ≤ 1) {β : Type} [DecidableEq β] (Y : Fin m → β) :
    (mixSpace μ h0 h1).dist (mixRV Y) none = 1 - ε := by
  simp only [FiniteProbSpace.dist, FiniteProbSpace.probOf, Finset.sum_filter]
  rw [Fin.sum_univ_castSucc]
  simp [mixSpace, mixRV]

private theorem dist_mixSpace_some {m : ℕ} (μ : FiniteProbSpace (Fin m)) {ε : ℝ} (h0 : 0 ≤ ε)
    (h1 : ε ≤ 1) {β : Type} [DecidableEq β] (Y : Fin m → β) (b : β) :
    (mixSpace μ h0 h1).dist (mixRV Y) (some b) = ε * μ.dist Y b := by
  simp only [FiniteProbSpace.dist, FiniteProbSpace.probOf, Finset.sum_filter]
  rw [Fin.sum_univ_castSucc]
  simp [mixSpace, mixRV, Finset.mul_sum, mul_ite]

/-- Switching a variable on with probability `ε` scales its entropy by `ε` and adds `h(ε)`. -/
private theorem entropy_mixSpace_mixRV {m : ℕ} (μ : FiniteProbSpace (Fin m)) {ε : ℝ}
    (h0 : 0 ≤ ε) (h1 : ε ≤ 1) {β : Type} [DecidableEq β] (Y : Fin m → β) :
    entropy (mixSpace μ h0 h1) (mixRV Y) = ε * entropy μ Y + binaryEntropy ε := by
  rw [entropy, rangeFinset_mixRV, Finset.sum_insert (by simp),
    Finset.sum_image fun _ _ _ _ h => Option.some_injective _ h, dist_mixSpace_none]
  have h : ∀ b ∈ rangeFinset Y, negMulLog2 ((mixSpace μ h0 h1).dist (mixRV Y) (some b))
      = μ.dist Y b * negMulLog2 ε + ε * negMulLog2 (μ.dist Y b) := fun b _ => by
    rw [dist_mixSpace_some, negMulLog2_mul]
  rw [Finset.sum_congr rfl h, Finset.sum_add_distrib, ← Finset.sum_mul, μ.sum_dist_eq_one,
    one_mul, ← Finset.mul_sum, binaryEntropy, entropy]
  ring

/-- The tuple with values `X i + 1` on the old outcomes and the dummy value `0` on the fresh
one. -/
private def mixTuple {m n : ℕ} (X : Fin n → Fin m → ℕ) : Fin n → Fin (m + 1) → ℕ :=
  fun i => Fin.lastCases 0 fun ω => X i ω + 1

private theorem subtuple_mixTuple {m n : ℕ} (X : Fin n → Fin m → ℕ) (I : Finset (Fin n)) :
    subtuple (mixTuple X) I
      = (fun (o : Option (I → ℕ)) (i : I) => o.elim 0 fun g => g i + 1)
        ∘ mixRV (subtuple X I) := by
  funext k
  induction k using Fin.lastCases with
  | last => funext i; simp [subtuple, mixTuple, mixRV]
  | cast ω => funext i; simp [subtuple, mixTuple, mixRV]

private theorem injective_optionElim {n : ℕ} {I : Finset (Fin n)} (hI : I.Nonempty) :
    Function.Injective fun (o : Option (I → ℕ)) (i : I) => o.elim 0 fun g => g i + 1 := by
  obtain ⟨i₀, hi₀⟩ := hI
  intro o₁ o₂ h
  have h' : ∀ i : I, o₁.elim 0 (fun g => g i + 1) = o₂.elim 0 (fun g => g i + 1) :=
    fun i => congrFun h i
  cases o₁ <;> cases o₂
  · rfl
  · exact absurd (h' ⟨i₀, hi₀⟩) (by simp)
  · exact absurd (h' ⟨i₀, hi₀⟩) (by simp)
  · exact congrArg some (funext fun i => by simpa using h' i)

private theorem entropyVector_mixTuple {m n : ℕ} (μ : FiniteProbSpace (Fin m)) {ε : ℝ}
    (h0 : 0 ≤ ε) (h1 : ε ≤ 1) (X : Fin n → Fin m → ℕ) (I : Finset (Fin n)) :
    entropyVector (mixSpace μ h0 h1) (mixTuple X) I
      = ε * entropyVector μ X I + if I.Nonempty then binaryEntropy ε else 0 := by
  by_cases hI : I.Nonempty
  · rw [ite_eq_left hI]
    simp only [entropyVector, entropySub]
    rw [subtuple_mixTuple, entropy_comp_of_injective _ _ (injective_optionElim hI),
      entropy_mixSpace_mixRV]
  · rw [ite_eq_right hI, Finset.not_nonempty_iff_eq_empty.1 hI]
    simp [entropyVector]

/-- Switching a tuple on with probability `ε` (and a dummy value otherwise) scales its entropy
vector by `ε` and adds `h(ε)` to every non-empty coordinate. -/
private theorem mix_mem_entropyRegion {n : ℕ} {v : Finset (Fin n) → ℝ} (hv : v ∈ entropyRegion n)
    {ε : ℝ} (h0 : 0 ≤ ε) (h1 : ε ≤ 1) :
    (fun I => ε * v I + if I.Nonempty then binaryEntropy ε else 0) ∈ entropyRegion n := by
  obtain ⟨m, μ, X, rfl⟩ := hv
  exact ⟨m + 1, mixSpace μ h0 h1, mixTuple X,
    funext fun I => (entropyVector_mixTuple μ h0 h1 X I).symm⟩

/-- Integer multiples of an entropy vector are entropy vectors (independent copies). -/
private theorem nsmul_mem_entropyRegion {n : ℕ} {v : Finset (Fin n) → ℝ}
    (hv : v ∈ entropyRegion n) (k : ℕ) : (k : ℝ) • v ∈ entropyRegion n := by
  induction k with
  | zero => simpa using zero_mem_entropyRegion n
  | succ k ih =>
    have h : ((k + 1 : ℕ) : ℝ) • v = (k : ℝ) • v + v := by
      rw [Nat.cast_succ, add_smul, one_smul]
    rw [h]
    exact add_mem_entropyRegion ih hv

/-- `h(ε) → 0` as `ε → 0`. -/
private theorem tendsto_binaryEntropy_zero :
    Filter.Tendsto binaryEntropy (nhds 0) (nhds 0) := by
  have hc : Continuous binaryEntropy := by
    unfold binaryEntropy negMulLog2
    fun_prop
  have h := hc.tendsto 0
  simpa [binaryEntropy, negMulLog2] using h

/-- For `0 ≤ t ≤ 1`, `t • v` is a limit of entropy vectors: switch `k + 1` independent copies
on with probability `t / (k + 1)`, which gives `t • v + h(t / (k + 1))` on the non-empty
coordinates, and let `k → ∞`. -/
private theorem smul_mem_closure_entropyRegion_of_le_one {n : ℕ} {t : ℝ} (ht : 0 ≤ t)
    (ht1 : t ≤ 1) {v : Finset (Fin n) → ℝ} (hv : v ∈ entropyRegion n) :
    t • v ∈ closure (entropyRegion n) := by
  have hε : ∀ k : ℕ, 0 ≤ t / ((k : ℝ) + 1) ∧ t / ((k : ℝ) + 1) ≤ 1 := fun k =>
    ⟨div_nonneg ht (by positivity), by
      rw [div_le_one (by positivity)]
      linarith [(Nat.cast_nonneg k : (0 : ℝ) ≤ k)]⟩
  have hmem : ∀ k : ℕ, (fun I => t * v I + if I.Nonempty then binaryEntropy (t / ((k : ℝ) + 1))
      else 0) ∈ entropyRegion n := by
    intro k
    have h := mix_mem_entropyRegion (nsmul_mem_entropyRegion hv (k + 1)) (hε k).1 (hε k).2
    convert h using 1
    funext I
    simp only [Pi.smul_apply, smul_eq_mul, Nat.cast_succ]
    congr 1
    field_simp
  have htend : Filter.Tendsto (fun k : ℕ => t / ((k : ℝ) + 1)) Filter.atTop (nhds 0) := by
    have h := (tendsto_const_div_atTop_nhds_zero_nat t).comp (Filter.tendsto_add_atTop_nat 1)
    simpa [Function.comp_def] using h
  refine mem_closure_of_tendsto (b := Filter.atTop) ?_ (Filter.Eventually.of_forall hmem)
  refine tendsto_pi_nhds.2 fun I => ?_
  have h0 : (t • v) I = t * v I + 0 := by simp
  rw [h0]
  refine tendsto_const_nhds.add ?_
  by_cases hI : I.Nonempty
  · simp only [hI, ite_true]
    exact tendsto_binaryEntropy_zero.comp htend
  · simp only [hI, ite_false]
    exact tendsto_const_nhds

/-- Multiplying an entropy vector by a non-negative real stays in the closure of the entropy
region.  Multiplication by an integer is `add_mem_entropyRegion`; multiplication by a small
`ε` is approximated by taking the variables with probability `ε` and fixed dummy values
otherwise, which changes every entropy by at most `H(ε)`.  SUV Problem 293, p. 337 (hint). -/
private theorem smul_mem_closure_entropyRegion {n : ℕ} {t : ℝ} (ht : 0 ≤ t)
    {v : Finset (Fin n) → ℝ} (hv : v ∈ entropyRegion n) :
    t • v ∈ closure (entropyRegion n) := by
  have hfloor : (0 : ℝ) ≤ t - ⌊t⌋₊ := sub_nonneg.2 (Nat.floor_le ht)
  have hfloor1 : t - ⌊t⌋₊ ≤ 1 := by linarith [Nat.lt_floor_add_one t]
  have hdecomp : t • v = (⌊t⌋₊ : ℝ) • v + (t - ⌊t⌋₊) • v := by
    rw [← add_smul]
    congr 1
    ring
  rw [hdecomp]
  exact add_mem_closure_entropyRegion (subset_closure (nsmul_mem_entropyRegion hv _))
    (smul_mem_closure_entropyRegion_of_le_one hfloor hfloor1 hv)

/-- The closure of the entropy region is closed under multiplication by non-negative reals. -/
private theorem smul_mem_closure_entropyRegion_of_mem_closure {n : ℕ} {t : ℝ} (ht : 0 ≤ t)
    {v : Finset (Fin n) → ℝ} (hv : v ∈ closure (entropyRegion n)) :
    t • v ∈ closure (entropyRegion n) := by
  have h := map_mem_closure (f := fun w : Finset (Fin n) → ℝ => t • w)
    ((continuous_const (y := t)).smul continuous_id) hv fun _ hw =>
      smul_mem_closure_entropyRegion ht hw
  rwa [closure_closure] at h

/-- For three variables the entropy region is dense in the cone of basic inequalities: its
closure is that cone.  SUV Section 10.11, p. 338 (unnumbered). -/
theorem closure_entropyRegion_three : closure (entropyRegion 3) = basicCone 3 := by
  refine Set.Subset.antisymm
    (closure_minimal (entropyRegion_subset_basicCone 3) (isClosed_basicCone 3)) ?_
  intro v hv
  rw [basicCone_three_eq_generated] at hv
  obtain ⟨c, hc, hv⟩ := hv
  have hv' : v = ∑ k, c k • threeGenerators k := by
    funext I
    rw [hv I, Finset.sum_apply]
    rfl
  rw [hv']
  refine Finset.sum_induction _ (fun w => w ∈ closure (entropyRegion 3))
    (fun _ _ ha hb => add_mem_closure_entropyRegion ha hb)
    (subset_closure (zero_mem_entropyRegion 3)) fun k _ => ?_
  exact smul_mem_closure_entropyRegion (hc k) (threeGenerators_mem_entropyRegion k)

/-- **Problem 293.**  For every `n` the closure of the entropy region is convex.
SUV Problem 293, p. 337. -/
theorem convex_closure_entropyRegion (n : ℕ) : Convex ℝ (closure (entropyRegion n)) := by
  intro v hv w hw a b ha hb _
  exact add_mem_closure_entropyRegion (smul_mem_closure_entropyRegion_of_mem_closure ha hv)
    (smul_mem_closure_entropyRegion_of_mem_closure hb hw)

/-! ### Two variables -/

/-- Every non-negative real is the entropy of some random variable: mix `N ≥ h` fair bits
with a dummy value and use the intermediate value theorem in the mixing probability. -/
private theorem exists_entropy_eq {h : ℝ} (hh : 0 ≤ h) :
    ∃ (m : ℕ) (μ : FiniteProbSpace (Fin m)) (Y : Fin m → ℕ), entropy μ Y = h := by
  obtain ⟨m, μ, X, hX⟩ := nsmul_mem_entropyRegion (indicator_mem_entropyRegion {0}) ⌈h⌉₊
  have hN : entropy μ (X 0) = ⌈h⌉₊ := by
    have h0 := congrFun hX {0}
    simp only [Pi.smul_apply, smul_eq_mul, Finset.inter_self, Finset.singleton_nonempty, ite_true,
      mul_one, entropyVector, entropySub_singleton'] at h0
    exact h0.symm
  have hf : ContinuousOn (fun θ : ℝ => θ * ⌈h⌉₊ + binaryEntropy θ) (Set.Icc 0 1) := by
    unfold binaryEntropy negMulLog2
    fun_prop
  have hmem : h ∈ Set.Icc ((fun θ : ℝ => θ * ⌈h⌉₊ + binaryEntropy θ) 0)
      ((fun θ : ℝ => θ * ⌈h⌉₊ + binaryEntropy θ) 1) := by
    simpa [binaryEntropy, negMulLog2] using And.intro hh (Nat.le_ceil h)
  obtain ⟨θ, ⟨hθ0, hθ1⟩, hθ⟩ := intermediate_value_Icc zero_le_one hf hmem
  have hinj : Function.Injective (fun o : Option ℕ => o.elim 0 (· + 1)) := by
    intro o₁ o₂ h
    cases o₁ <;> cases o₂ <;> simp_all
  refine ⟨m + 1, mixSpace μ hθ0 hθ1, (fun o : Option ℕ => o.elim 0 (· + 1)) ∘ mixRV (X 0), ?_⟩
  rw [entropy_comp_of_injective _ _ hinj, entropy_mixSpace_mixRV, hN]
  exact hθ

/-- Independent variables `α, β, γ` of entropies `e₁, e₂, e₃` give the pair
`ξ₁ = ⟨α, β⟩`, `ξ₂ = ⟨β, γ⟩` with entropy vector `(e₁ + e₂, e₂ + e₃, e₁ + e₂ + e₃)`. -/
private theorem exists_mem_entropyRegion_two {e₁ e₂ e₃ : ℝ} (h₁ : 0 ≤ e₁) (h₂ : 0 ≤ e₂)
    (h₃ : 0 ≤ e₃) : ∃ v ∈ entropyRegion 2,
      v {0} = e₁ + e₂ ∧ v {1} = e₂ + e₃ ∧ v {0, 1} = e₁ + e₂ + e₃ := by
  obtain ⟨a, μα, α, hα⟩ := exists_entropy_eq h₁
  obtain ⟨b, μβ, β, hβ⟩ := exists_entropy_eq h₂
  obtain ⟨c, μγ, γ, hγ⟩ := exists_entropy_eq h₃
  have hpair : Function.Injective (fun p : ℕ × ℕ => Nat.pair p.1 p.2) := fun p q h =>
    Prod.ext (Nat.pair_eq_pair.1 h).1 (Nat.pair_eq_pair.1 h).2
  refine ⟨entropyVector (prodSpace μα (prodSpace μβ μγ))
    ![fun k => Nat.pair (α (finProdFinEquiv.symm k).1)
        (β (finProdFinEquiv.symm (finProdFinEquiv.symm k).2).1),
      fun k => Nat.pair (β (finProdFinEquiv.symm (finProdFinEquiv.symm k).2).1)
        (γ (finProdFinEquiv.symm (finProdFinEquiv.symm k).2).2)], ⟨_, _, _, rfl⟩, ?_, ?_, ?_⟩
  · rw [entropyVector, entropySub_singleton']
    have h := entropy_comp_of_injective (prodSpace μα (prodSpace μβ μγ))
      (pairRV (fun k => α (finProdFinEquiv.symm k).1)
        (fun k => (fun k' => β (finProdFinEquiv.symm k').1) (finProdFinEquiv.symm k).2)) hpair
    beta_reduce at h
    rw [entropy_prodSpace_pair μα _ α (fun k' => β (finProdFinEquiv.symm k').1), hα,
      entropy_prodSpace_fst, hβ] at h
    exact h
  · rw [entropyVector, entropySub_singleton']
    have h := entropy_comp_of_injective (prodSpace μα (prodSpace μβ μγ))
      (fun k => pairRV (fun k' => β (finProdFinEquiv.symm k').1)
        (fun k' => γ (finProdFinEquiv.symm k').2) (finProdFinEquiv.symm k).2) hpair
    beta_reduce at h
    rw [entropy_prodSpace_snd μα _ (pairRV (fun k' => β (finProdFinEquiv.symm k').1)
      (fun k' => γ (finProdFinEquiv.symm k').2)), entropy_prodSpace_pair, hβ, hγ] at h
    exact h
  · rw [entropyVector, entropySub]
    have hψ : Function.Injective (fun (p : ℕ × (ℕ × ℕ)) (i : ({0, 1} : Finset (Fin 2))) =>
        if i.val = 0 then Nat.pair p.1 p.2.1 else Nat.pair p.2.1 p.2.2) := by
      intro p q h
      have h0 := congrFun h ⟨0, by decide⟩
      have h1 := congrFun h ⟨1, by decide⟩
      simp only [ite_true, Fin.isValue, Fin.one_eq_zero_iff, OfNat.ofNat_ne_one, ite_false,
        Nat.pair_eq_pair] at h0 h1
      exact Prod.ext h0.1 (Prod.ext h0.2 h1.2)
    have h := entropy_comp_of_injective (prodSpace μα (prodSpace μβ μγ))
      (pairRV (fun k => α (finProdFinEquiv.symm k).1)
        (fun k => pairRV (fun k' => β (finProdFinEquiv.symm k').1)
          (fun k' => γ (finProdFinEquiv.symm k').2) (finProdFinEquiv.symm k).2)) hψ
    rw [entropy_prodSpace_pair, entropy_prodSpace_pair, hα, hβ, hγ] at h
    rw [← add_assoc] at h
    convert h using 2
    funext k i
    rcases i with ⟨i, hi⟩
    fin_cases i <;> rfl

/-- **The entropy region for two variables.**  A vector is the entropy vector of a pair of
random variables if and only if `0 ≤ h₁ ≤ h₁₂`, `0 ≤ h₂ ≤ h₁₂` and `h₁₂ ≤ h₁ + h₂` (together
with the normalisation `v ∅ = 0` of this library's coordinates).  Sufficiency takes three
independent variables `α, β, γ` of prescribed entropies and `ξ₁ = ⟨α, β⟩`, `ξ₂ = ⟨β, γ⟩`.
SUV Section 10.10, p. 336 (unnumbered). -/
theorem entropyRegion_two :
    entropyRegion 2 = {v | v ∅ = 0 ∧ 0 ≤ v {0} ∧ v {0} ≤ v {0, 1} ∧ 0 ≤ v {1} ∧
      v {1} ≤ v {0, 1} ∧ v {0, 1} ≤ v {0} + v {1}} := by
  ext v
  constructor
  · intro hv
    obtain ⟨h0, hnn, hmono, hsub⟩ := entropyRegion_subset_basicCone 2 hv
    have h := hsub {0} {1}
    rw [show ({0} : Finset (Fin 2)) ∩ {1} = ∅ by decide,
      show ({0} : Finset (Fin 2)) ∪ {1} = {0, 1} by decide, h0] at h
    exact ⟨h0, hnn _, hmono _ _ (by decide), hnn _, hmono _ _ (by decide), by linarith⟩
  · rintro ⟨h0, h1, h2, h3, h4, h5⟩
    obtain ⟨w, hw, hw0, hw1, hw01⟩ := exists_mem_entropyRegion_two (e₁ := v {0, 1} - v {1})
      (e₂ := v {0} + v {1} - v {0, 1}) (e₃ := v {0, 1} - v {0}) (by linarith) (by linarith)
      (by linarith)
    have hvw : v = w := by
      funext I
      rcases cases4 I with rfl | rfl | rfl | rfl
      · rw [h0, (entropyRegion_subset_basicCone 2 hw).1]
      · rw [hw0]; ring
      · rw [hw1]; ring
      · rw [hw01]; ring
    rw [hvw]
    exact hw

/-- For two variables every linear inequality that is true for entropies is a non-negative
combination of the basic inequalities.  SUV Section 10.10, p. 336 (unnumbered). -/
theorem isShannonType_of_holdsForEntropies_two (f : LinearForm 2) (h : HoldsForEntropies f) :
    IsShannonType f := by
  have hmem : ∀ v : Finset (Fin 2) → ℝ, v ∅ = 0 → 0 ≤ v {0} → v {0} ≤ v {0, 1} → 0 ≤ v {1} →
      v {1} ≤ v {0, 1} → v {0, 1} ≤ v {0} + v {1} → v ∈ entropyRegion 2 := by
    intro v h0 h1 h2 h3 h4 h5
    rw [entropyRegion_two]
    exact ⟨h0, h1, h2, h3, h4, h5⟩
  have hval : ∀ v ∈ entropyRegion 2, f {0} * v {0} + f {1} * v {1} + f {0, 1} * v {0, 1} ≤ 0 := by
    intro v hv
    have := sum_mul_nonpos_of_holdsForEntropies h hv
    rwa [sum_nonemptyParts_two] at this
  have hpt : ∀ t : List (Finset (Fin 2) × ℝ), LinearForm.ofTable t ∅ = 0 ∧
      0 ≤ LinearForm.ofTable t {0} ∧ LinearForm.ofTable t {0} ≤ LinearForm.ofTable t {0, 1} ∧
      0 ≤ LinearForm.ofTable t {1} ∧ LinearForm.ofTable t {1} ≤ LinearForm.ofTable t {0, 1} ∧
      LinearForm.ofTable t {0, 1} ≤ LinearForm.ofTable t {0} + LinearForm.ofTable t {1} →
      f {0} * LinearForm.ofTable t {0} + f {1} * LinearForm.ofTable t {1}
        + f {0, 1} * LinearForm.ofTable t {0, 1} ≤ 0 :=
    fun t ⟨h0, h1, h2, h3, h4, h5⟩ => hval _ (hmem _ h0 h1 h2 h3 h4 h5)
  have e₁ := hpt [({0}, 1), ({0, 1}, 1)] (by simp +decide [LinearForm.ofTable])
  have e₂ := hpt [({0}, 1), ({1}, 1), ({0, 1}, 1)] (by simp +decide [LinearForm.ofTable])
  have e₃ := hpt [({1}, 1), ({0, 1}, 1)] (by simp +decide [LinearForm.ofTable])
  simp +decide [LinearForm.ofTable] at e₁ e₂ e₃
  refine ⟨3, ![monotonicityForm 2 {1} {0}, basicInequality 2 {0} {1} ∅, monotonicityForm 2 {0} {1}],
    ![-(f {0} + f {0, 1}), -(f {0} + f {1} + f {0, 1}), -(f {1} + f {0, 1})], ?_, ?_, ?_⟩
  · intro k
    fin_cases k <;> simp <;> linarith
  · intro k
    fin_cases k
    · exact Or.inr ⟨_, _, rfl⟩
    · exact Or.inl ⟨_, _, _, rfl⟩
    · exact Or.inr ⟨_, _, rfl⟩
  · intro I hI
    rcases cases4 I with rfl | rfl | rfl | rfl
    · exact (Finset.not_nonempty_empty hI).elim
    all_goals
      simp +decide [Fin.sum_univ_succ, basicInequality, monotonicityForm]
      try ring

end Kolmogorov
