import KolmogorovMathlib.AlgorithmicStatistics.BoundedLists.StandardBlock.Part02
import KolmogorovMathlib.AlgorithmicStatistics.BoundedLists.TailProfile
import KolmogorovMathlib.Restricted.EffectiveSelection.Part01

/-!
# Standard blocks: the improved selector

`prop:better-std` needs a block to be recoverable not from its own code but from any *anchor*
inside it, given short advice.  That selector is built here.

`betterStandardBlockAdvice` packs the bound `m`, the block exponent `r` and a branch flag into
`2 * |bits m| + 2 * |bits r| + 3` bits, with field readers and round-trip lemmas;
`betterStandardModelList` and `betterStandardModelSeen` are the stage test it runs.
`exists_betterStandard_stage` shows the stage search terminates,
`betterStandardLastMember_idxOf_bounds` places the last member seen in the doubled window
around `x`, and `betterStandardBlockSelector_of_anchor_mem` and
`betterStandardBlockSelector_recovers` are the conclusions: from any anchor in the block, the
selector returns the block.

The other half of the module bounds the suffix coordinate from a model code
(`suffixCoordinate_lower_of_model_code`, with the auxiliary
`suffixCoordinate_overhead_lt_logSlack` and `suffixCoordinate_count_lt`), and
`getElem_mem_standardBlock_of_bounds` and `idxOf_completedBoundedOutput_mem_standardBlock`
convert between indices in the completed list and membership in a block.
-/

namespace Kolmogorov
open Nat.Partrec (Code)
open Kolmogorov.CodedFiniteDistribution

/-- Overhead term in the advice length bound for `suffixCoordinate_lower_of_model_code` is
strictly bounded by `logSlack C m`. -/
private theorem suffixCoordinate_overhead_lt_logSlack
    (Clen Cmap COmega C q m p_len : ℕ)
    (hC : Clen + Cmap + COmega + 5 ≤ C)
    (hp : p_len ≤ q) (hqm : q < m) :
    2 * (Nat.bits p_len).length + 2 * (Nat.bits m).length + 2 +
        Clen + Cmap + COmega < logSlack C m := by
  have hpBits : (Nat.bits p_len).length ≤ (Nat.bits m).length :=
    length_natBits_mono (hp.trans (Nat.le_of_lt hqm))
  have hSlackBound : 4 * (Nat.bits m).length +
      (Clen + Cmap + COmega + 2) < logSlack C m := by
    unfold logSlack
    calc
      4 * (Nat.bits m).length + (Clen + Cmap + COmega + 2)
        ≤ C * (Nat.bits m).length + (Clen + Cmap + COmega + 2) := by gcongr; omega
      _ < C * (Nat.bits m).length + C := by gcongr; omega
  calc
    2 * (Nat.bits p_len).length + 2 * (Nat.bits m).length + 2 +
        Clen + Cmap + COmega
      ≤ 2 * (Nat.bits m).length + 2 * (Nat.bits m).length + 2 +
        Clen + Cmap + COmega := by gcongr
    _ = 4 * (Nat.bits m).length + (Clen + Cmap + COmega + 2) := by ring
    _ < logSlack C m := hSlackBound

/-- The remaining output count after the covering stage for `A` is strictly less than the
suffix coordinate of any element `x ∈ A`. -/
private theorem suffixCoordinate_count_lt
    (c : Code) (m : ℕ) (x : BitString) (A : Finset BitString)
    (hxA : x ∈ A) (hsubset : ∀ y ∈ A, y ∈ completedBoundedOutput c m)
    (t₀ : ℕ)
    (ht₀spec : (canonicalFinsetList A).all
      (fun y => (boundedOutputStage c m t₀).elem y) = true) :
    omegaCount c m - (boundedOutputStage c m t₀).length <
      suffixCoordinate c m x := by
  have hxCompleted : x ∈ completedBoundedOutput c m := hsubset x hxA
  have hxList : x ∈ canonicalFinsetList A := mem_canonicalFinsetList.mpr hxA
  have hxStage : x ∈ boundedOutputStage c m t₀ := by
    rw [List.all_eq_true] at ht₀spec
    have hxElem := ht₀spec x hxList
    simpa [List.elem_eq_mem] using hxElem
  have hprefix : boundedOutputStage c m t₀ <+: completedBoundedOutput c m :=
    boundedOutputStage_prefix_completed c m t₀
  obtain ⟨R, hR, hRtail⟩ := prefix_remainder_length_le_tailAfter hprefix hxStage
  have hcountR : omegaCount c m - (boundedOutputStage c m t₀).length = R.length := by
    dsimp [omegaCount]
    rw [hR, List.length_append]
    omega
  have htail : tailAfter (completedBoundedOutput c m) x < suffixCoordinate c m x := by
    unfold suffixCoordinate
    rw [suffixCountIncluding_eq_tailAfter_add_one hxCompleted]
    omega
  rw [hcountR]
  exact lt_of_le_of_lt hRtail htail

/-- The omega code for `c` and `m` is generated by `standardBlockOmegaDecoder` when fed
the advice constructed from a covering program `p` and count `count`. -/
private theorem standardBlockOmegaDecoder_mem_of_covering_stage
    (V : Map) (c : Code) (m : ℕ) (A : Finset BitString) (hA : A.Nonempty)
    (hsubset : ∀ y ∈ A, y ∈ completedBoundedOutput c m)
    (p : BitString) (hp : produces V p [] (codedUniformOn A hA).code)
    (t₀ : ℕ)
    (ht₀spec : (canonicalFinsetList A).all
      (fun y => (boundedOutputStage c m t₀).elem y) = true)
    (ht₀min : ∀ t < t₀, (canonicalFinsetList A).all
      (fun y => (boundedOutputStage c m t).elem y) = false) :
    omegaNatCode c m ∈ standardBlockOmegaDecoder V c (plainProgramAdvice p m
      (omegaCount c m - (boundedOutputStage c m t₀).length)) := by
  let ACode := (codedUniformOn A hA).code
  let AList := canonicalFinsetList A
  let count := omegaCount c m - (boundedOutputStage c m t₀).length
  have hAList : AList = (decodeDistributionData ACode).map CodedDistributionEntry.point :=
    (dataPoints_codedUniformOn A hA).symm
  have hAListSubset : ∀ y ∈ AList, y ∈ completedBoundedOutput c m := by
    intro y hy
    exact hsubset y (mem_canonicalFinsetList.mp hy)
  have ht₀mem : t₀ ∈ Nat.rfind (fun t => Part.some
      (AList.all (fun y => (boundedOutputStage c m t).elem y))) := by
    refine Nat.mem_rfind.mpr ⟨?_, ?_⟩
    · exact Part.mem_some_iff.mpr ht₀spec.symm
    · intro t ht
      exact Part.mem_some_iff.mpr (ht₀min t ht).symm
  have hrecover : descriptionTailOmegaSelector c
      (descriptionTailOmegaInput ACode m count) =
        Part.some (Nat.bits (omegaCount c m)) := by
    apply descriptionTailOmegaSelector_recovers c m ACode AList hAList hAListSubset count
    exact ⟨t₀, (Part.eq_some_iff.mpr ht₀mem).symm, rfl⟩
  have htailSelector : omegaNatCode c m ∈ descriptionTailOmegaSelector c
      (descriptionTailOmegaInput ACode m count) :=
    Part.eq_some_iff.mp hrecover
  unfold standardBlockOmegaDecoder
  simp only [plainProgramAdvice, decodeSecond_pairCode, decodeFirst_pairCode,
    bitsToNat_bits, List.take_left, List.drop_left]
  rw [Part.mem_bind_iff]
  refine ⟨ACode, hp, ?_⟩
  simpa using htailSelector

/-- A model of plain complexity at most `q` all of whose members have complexity at
most `m` forces its members to have suffix coordinate at least
`2 ^ (m - q - logSlack C m)`. -/
theorem suffixCoordinate_lower_of_model_code
    (V : Map) (hV : isOptimalConditional V)
    (c : Code) (hc : IsCodeFor c V) :
    ∃ C, ∀ m (q : ℕ) x (A : Finset BitString) (hA : A.Nonempty),
      x ∈ A →
      (∀ y ∈ A, y ∈ completedBoundedOutput c m) →
      plainK V (codedUniformOn A hA).code ≤ (q : ENat) →
      2 ^ (m - q - logSlack C m) ≤ suffixCoordinate c m x := by
  obtain ⟨COmega, hOmega⟩ :=
    plainKNat_omegaCount_lower V hV c hc
  obtain ⟨Cmap, hmap⟩ :=
    plainK_partrec_map_le V hV
      (standardBlockOmegaDecoder V c)
      (standardBlockOmegaDecoder_partrec V hV.1 c)
  obtain ⟨Clen, hlen⟩ := plainK_le_length V hV
  let C := COmega + Cmap + Clen + 5
  refine ⟨C, fun m q x A hA hxA hsubset hcode => ?_⟩
  have hxCompleted : x ∈ completedBoundedOutput c m :=
    hsubset x hxA
  have hsuffixPos : 0 < suffixCoordinate c m x := by
    unfold suffixCoordinate
    exact suffixCountIncluding_pos_iff_mem.mpr hxCompleted
  by_cases hsmall : m ≤ q + logSlack C m
  · have hzero : m - q - logSlack C m = 0 := by omega
    rw [hzero]
    exact hsuffixPos
  · have hqm : q < m := by omega
    have hmPos : 0 < m := by omega
    let ACode := (codedUniformOn A hA).code
    obtain ⟨p, hpLength, hp⟩ :
        ∃ p, p.length ≤ q ∧ produces V p [] ACode := by
      exact (condK_le_iff V ACode [] q).mp hcode
    let AList := canonicalFinsetList A
    have hcover :
        ∃ t, AList.all (fun y =>
          (boundedOutputStage c m t).elem y) = true := by
      obtain ⟨t, ht⟩ :=
        exists_stage_covering_finset c m A hsubset
      refine ⟨t, ?_⟩
      rw [List.all_eq_true]
      intro y hy
      rw [List.elem_eq_mem]
      exact decide_eq_true
        (ht y (mem_canonicalFinsetList.mp hy))
    let t₀ := Nat.find hcover
    have ht₀spec :
        AList.all (fun y =>
          (boundedOutputStage c m t₀).elem y) = true :=
      Nat.find_spec hcover
    have ht₀min : ∀ t < t₀, AList.all (fun y =>
        (boundedOutputStage c m t).elem y) = false :=
      fun t ht => Bool.eq_false_iff.mpr (Nat.find_min hcover ht)
    let count :=
      omegaCount c m -
        (boundedOutputStage c m t₀).length
    have hcountLt : count < suffixCoordinate c m x :=
      suffixCoordinate_count_lt c m x A hxA hsubset t₀ ht₀spec
    have hdecoder :
        omegaNatCode c m ∈
          standardBlockOmegaDecoder V c
            (plainProgramAdvice p m count) :=
      standardBlockOmegaDecoder_mem_of_covering_stage
        V c m A hA hsubset p hp t₀ ht₀spec ht₀min
    let input := plainProgramAdvice p m count
    have hinputLength :
        input.length =
          p.length + 2 * (Nat.bits p.length).length +
            2 * (Nat.bits m).length +
            (Nat.bits count).length + 2 :=
      plainProgramAdvice_length p m count
    have hoverhead :
        2 * (Nat.bits p.length).length +
            2 * (Nat.bits m).length + 2 +
            Clen + Cmap + COmega <
          logSlack C m :=
      suffixCoordinate_overhead_lt_logSlack
        Clen Cmap COmega C q m p.length (by dsimp [C]; omega)
        hpLength hqm
    have hdecode :
        plainKNat V (omegaCount c m) ≤
          plainK V input + (Cmap : ENat) := by
      exact hmap input (omegaNatCode c m)
        (by simpa [input] using hdecoder)
    have hmBoundENat :
        (m : ENat) ≤
          ((p.length + (Nat.bits count).length +
            (2 * (Nat.bits p.length).length +
              2 * (Nat.bits m).length + 2 +
              Clen + Cmap + COmega) : ℕ) : ENat) := by
      calc
        (m : ENat)
            ≤ plainKNat V (omegaCount c m) +
                (COmega : ENat) :=
          hOmega m
        _ ≤ (plainK V input + (Cmap : ENat)) +
              (COmega : ENat) := by
          gcongr
        _ ≤ (((input.length : ENat) + (Clen : ENat)) +
              (Cmap : ENat)) + (COmega : ENat) := by
          gcongr
          exact hlen input
        _ = ((p.length + (Nat.bits count).length +
              (2 * (Nat.bits p.length).length +
                2 * (Nat.bits m).length + 2 +
                Clen + Cmap + COmega) : ℕ) : ENat) := by
          rw [hinputLength]
          push_cast
          ring
    have hmBound :
        m ≤ p.length + (Nat.bits count).length +
          (2 * (Nat.bits p.length).length +
            2 * (Nat.bits m).length + 2 +
            Clen + Cmap + COmega) := by
      exact_mod_cast hmBoundENat
    by_contra hpow
    push Not at hpow
    have hcountPow :
        count < 2 ^ (m - q - logSlack C m) :=
      lt_trans hcountLt hpow
    have hcountBits :
        (Nat.bits count).length ≤
          m - q - logSlack C m :=
      length_natBits_lt_pow hcountPow
    omega

/-! ## The conditional selector required by `prop_better_std`

The selector first waits until every point decoded from the condition model has
appeared in the bound-`m` enumeration.  It then takes the last such point in
enumeration order.  The requested source-standard block is either the aligned
`2^r` block containing that point or the immediately preceding aligned block;
one flag selects the branch.  A final call to
`standardBlockFromMemberSelector` waits until the selected block is complete.
-/

/-- The advice of the improved block selector: the bound `m`, the block exponent `r`
and the flag choosing the current or the preceding aligned block. -/
def betterStandardBlockAdvice (m r : ℕ) (current : Bool) : BitString :=
  pairCode (Nat.bits m)
    (pairCode (Nat.bits r) [current])

/-- The bound read off an improved block advice. -/
def betterStandardBlockAdviceM (z : BitString) : ℕ :=
  bitsToNat (decodeFirst z)

/-- The block exponent read off an improved block advice. -/
def betterStandardBlockAdviceR (z : BitString) : ℕ :=
  bitsToNat (decodeFirst (decodeSecond z))

/-- The branch flag read off an improved block advice. -/
def betterStandardBlockAdviceCurrent (z : BitString) : Bool :=
  (decodeSecond (decodeSecond z)).headI

/-- The bound is read back from an assembled advice. -/
@[simp] theorem betterStandardBlockAdviceM_advice
    (m r : ℕ) (current : Bool) :
    betterStandardBlockAdviceM
      (betterStandardBlockAdvice m r current) = m := by
  unfold betterStandardBlockAdviceM
    betterStandardBlockAdvice
  rw [decodeFirst_pairCode, bitsToNat_bits]

/-- The block exponent is read back from an assembled advice. -/
@[simp] theorem betterStandardBlockAdviceR_advice
    (m r : ℕ) (current : Bool) :
    betterStandardBlockAdviceR
      (betterStandardBlockAdvice m r current) = r := by
  unfold betterStandardBlockAdviceR
    betterStandardBlockAdvice
  rw [decodeSecond_pairCode, decodeFirst_pairCode,
    bitsToNat_bits]

/-- The branch flag is read back from an assembled advice. -/
@[simp] theorem betterStandardBlockAdviceCurrent_advice
    (m r : ℕ) (current : Bool) :
    betterStandardBlockAdviceCurrent
      (betterStandardBlockAdvice m r current) = current := by
  unfold betterStandardBlockAdviceCurrent
    betterStandardBlockAdvice
  rw [decodeSecond_pairCode, decodeSecond_pairCode]
  rfl

/-- The length of an improved block advice: `2 * |bits m| + 2 * |bits r| + 3`. -/
theorem betterStandardBlockAdvice_length
    (m r : ℕ) (current : Bool) :
    (betterStandardBlockAdvice m r current).length =
      2 * (Nat.bits m).length +
        2 * (Nat.bits r).length + 3 := by
  simp [betterStandardBlockAdvice, length_pairCode]
  omega

/-- The points of the model coded by a string. -/
def betterStandardModelList (ACode : BitString) :
    List BitString :=
  (decodeDistributionData ACode).map
    CodedDistributionEntry.point

/-- Whether all points of the coded model have appeared in the bound-`m` enumeration
by stage `t`. -/
def betterStandardModelSeen
    (c : Code) (ACode advice : BitString) (t : ℕ) : Bool :=
  (betterStandardModelList ACode).all (fun y =>
    (boundedOutputStage c
      (betterStandardBlockAdviceM advice) t).elem y)

/-- The point of the model that appears last in the bound-`m` enumeration at stage
`t`. -/
def betterStandardLastMember
    (c : Code) (ACode advice : BitString) (t : ℕ) : BitString :=
  (((boundedOutputStage c
      (betterStandardBlockAdviceM advice) t).filter
        (fun y => decide
          (y ∈ betterStandardModelList ACode))).reverse).headI

/-- The anchor point selected by the advice: the last member itself, or the point
just before the aligned block containing it. -/
def betterStandardAnchor
    (c : Code) (ACode advice : BitString) (t : ℕ) : BitString :=
  let L := boundedOutputStage c
    (betterStandardBlockAdviceM advice) t
  let last := betterStandardLastMember c ACode advice t
  let p := 2 ^ betterStandardBlockAdviceR advice
  let start :=
    (L.findIdx (fun y => decide (y = last)) / p) * p
  if betterStandardBlockAdviceCurrent advice then
    last
  else
    L.getD (start - 1) []

/-- The improved block selector: wait until the whole conditioning model has
appeared, choose the anchor by the advice and return the completed standard
block containing it. -/
noncomputable def betterStandardBlockSelector
    (c : Code) : BitString → BitString →. BitString :=
  fun ACode advice =>
    (Nat.rfind (fun t => Part.some
      (betterStandardModelSeen c ACode advice t))).bind
        (fun t =>
          standardBlockFromMemberSelector c
            (betterStandardAnchor c ACode advice t)
            (standardBlockAdvice
              (betterStandardBlockAdviceM advice)
              (betterStandardBlockAdviceR advice)))

/-- The improved block selector is partial recursive in the model code and the
advice. -/
theorem betterStandardBlockSelector_partrec
    (c : Code) :
    Partrec (fun q : BitString × BitString =>
      betterStandardBlockSelector c q.1 q.2) := by
  have hm : Primrec betterStandardBlockAdviceM :=
    bitsToNat_primrec.comp decodeFirst_primrec
  have hr : Primrec betterStandardBlockAdviceR :=
    bitsToNat_primrec.comp
      (decodeFirst_primrec.comp
        decodeSecond_primrec)
  have hcurrent : Primrec betterStandardBlockAdviceCurrent :=
    Primrec.list_headI.comp
      (decodeSecond_primrec.comp
        decodeSecond_primrec)
  have hmodel : Primrec betterStandardModelList :=
    Primrec.list_map decodeDistributionData_primrec
      (entry_point_primrec.comp Primrec.snd).to₂
  have hstage : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        boundedOutputStage c
          (betterStandardBlockAdviceM q.1.2) q.2) :=
    (boundedOutputStage_primrec c).comp
      (Primrec.pair
        (hm.comp (Primrec.snd.comp Primrec.fst))
        Primrec.snd)
  have hseenPred : Primrec₂
      (fun (q : (BitString × BitString) × ℕ)
        (y : BitString) =>
          decide (y ∈ boundedOutputStage c
            (betterStandardBlockAdviceM q.1.2) q.2)) :=
    (bitString_mem_primrec.comp Primrec.snd
      (hstage.comp Primrec.fst)).to₂
  have hseen : Computable₂
      (fun (q : BitString × BitString) (t : ℕ) =>
        betterStandardModelSeen c q.1 q.2 t) := by
    have hall : Primrec
        (fun q : (BitString × BitString) × ℕ =>
          (betterStandardModelList q.1.1).all
            (fun y => decide (y ∈ boundedOutputStage c
              (betterStandardBlockAdviceM q.1.2) q.2))) :=
      list_all_primrec
        (hmodel.comp (Primrec.fst.comp Primrec.fst))
        hseenPred
    exact hall.to_comp.to₂ |>.of_eq (fun _ => by
      simp only [betterStandardModelSeen, List.elem_eq_mem])
  have hsearch : Partrec
      (fun q : BitString × BitString =>
        Nat.rfind (fun t => Part.some
          (betterStandardModelSeen c q.1 q.2 t))) :=
    Partrec.rfind hseen.partrec₂
  have hmodelMem : Primrec₂
      (fun (q : (BitString × BitString) × ℕ)
        (y : BitString) =>
          decide (y ∈ betterStandardModelList q.1.1)) :=
    (bitString_mem_primrec.comp Primrec.snd
      (hmodel.comp
        (Primrec.fst.comp
          (Primrec.fst.comp Primrec.fst)))).to₂
  have hfiltered : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        (boundedOutputStage c
          (betterStandardBlockAdviceM q.1.2) q.2).filter
            (fun y => decide
              (y ∈ betterStandardModelList q.1.1))) :=
    list_filter_primrec hstage hmodelMem
  have hlast : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        betterStandardLastMember c q.1.1 q.1.2 q.2) := by
    exact (Primrec.list_headI.comp
      (Primrec.list_reverse.comp hfiltered)).of_eq
        (fun _ => rfl)
  have hidx : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        (boundedOutputStage c
          (betterStandardBlockAdviceM q.1.2) q.2).findIdx
            (fun y => decide
              (y = betterStandardLastMember c
                q.1.1 q.1.2 q.2))) :=
    Primrec.list_findIdx hstage
      ((PrimrecPred.decide
        (Primrec.eq.comp Primrec.snd
          (hlast.comp Primrec.fst))).to₂)
  have hp : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        2 ^ betterStandardBlockAdviceR q.1.2) :=
    Kolmogorov.primrec_two_pow_aux.comp
      (hr.comp (Primrec.snd.comp Primrec.fst))
  have hstart : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        ((boundedOutputStage c
          (betterStandardBlockAdviceM q.1.2) q.2).findIdx
            (fun y => decide
              (y = betterStandardLastMember c
                q.1.1 q.1.2 q.2)) /
            2 ^ betterStandardBlockAdviceR q.1.2) *
              2 ^ betterStandardBlockAdviceR q.1.2) :=
    Primrec.nat_mul.comp
      (Primrec.nat_div.comp hidx hp) hp
  have hprevious : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        (boundedOutputStage c
          (betterStandardBlockAdviceM q.1.2) q.2).getD
            ((((boundedOutputStage c
              (betterStandardBlockAdviceM q.1.2) q.2).findIdx
                (fun y => decide
                  (y = betterStandardLastMember c
                    q.1.1 q.1.2 q.2)) /
                2 ^ betterStandardBlockAdviceR q.1.2) *
                  2 ^ betterStandardBlockAdviceR q.1.2) - 1) []) :=
    (Primrec.list_getD []).comp hstage
      (Primrec.pred.comp hstart)
  have hanchor : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        betterStandardAnchor c q.1.1 q.1.2 q.2) := by
    exact (Primrec.cond
      (hcurrent.comp (Primrec.snd.comp Primrec.fst))
      hlast hprevious).of_eq (fun q => by
        simp [betterStandardAnchor])
  have hadvice : Primrec
      (fun q : (BitString × BitString) × ℕ =>
        standardBlockAdvice
          (betterStandardBlockAdviceM q.1.2)
          (betterStandardBlockAdviceR q.1.2)) := by
    unfold standardBlockAdvice
    exact pairCode_primrec.comp
      (primrec_natBits.comp
        (hm.comp (Primrec.snd.comp Primrec.fst)))
      (primrec_natBits.comp
        (hr.comp (Primrec.snd.comp Primrec.fst)))
  have hpost : Partrec₂
      (fun (q : BitString × BitString) (t : ℕ) =>
        standardBlockFromMemberSelector c
          (betterStandardAnchor c q.1 q.2 t)
          (standardBlockAdvice
            (betterStandardBlockAdviceM q.2)
            (betterStandardBlockAdviceR q.2))) := by
    exact ((standardBlockFromMemberSelector_partrec c).comp
      (hanchor.to_comp.pair hadvice.to_comp)).to₂
  unfold betterStandardBlockSelector
  exact (Partrec.bind hsearch hpost).of_eq (fun _ => rfl)

/-- Absorption: two `logSlack` terms in the same argument sum to one. -/
theorem logSlack_add_same (a b m : ℕ) :
    logSlack a m + logSlack b m = logSlack (a + b) m :=
  (logSlack_add_constants a b m).symm

/-- A constant below the slack constant is dominated by the whole slack. -/
theorem const_le_logSlack {k C m : ℕ} (h : k ≤ C) : k ≤ logSlack C m := by
  unfold logSlack; omega

/-- Composed selector for the length-filtered branch of `prop_better_std`.  The
paired advice carries the real block advice in its first component and `Nat.bits
n` in its second; the selector length-filters the conditioning model to `n`-bit
strings before running the block selector.  This lets the length-restricted
model be reconstructed from the *original* model code inside one selector. -/
noncomputable def betterStandardFilterSelector
    (c : Code) : BitString → BitString →. BitString :=
  fun ACode p =>
    betterStandardBlockSelector c
      (lengthFilterUniformCode (pairCode ACode (decodeSecond p)))
      (decodeFirst p)

/-- The length-filtering variant of the improved block selector is partial recursive
in the model code and the paired advice. -/
theorem betterStandardFilterSelector_partrec (c : Code) :
    Partrec (fun q : BitString × BitString =>
      betterStandardFilterSelector c q.1 q.2) := by
  have hinner := Computable.pair (Computable.fst (α := BitString) (β := BitString))
    (decodeSecond_computable.comp (Computable.snd (α := BitString) (β := BitString)))
  have hpair := pairCode_computable.comp hinner
  have hpre := lengthFilterUniformCode_computable.comp hpair
  have hpost := decodeFirst_computable.comp (Computable.snd (α := BitString) (β := BitString))
  have hmap := Computable.pair hpre hpost
  have hcomp := (betterStandardBlockSelector_partrec c).comp hmap
  exact hcomp

/-- The last element selected by reversing a filtered duplicate-free list is a
filtered member at least as late as every specified filtered member. -/
theorem last_filtered_member_idxOf_ge
    (P : BitString → Bool) (L : List BitString) (hL : L.Nodup)
    (x : BitString) (hxL : x ∈ L) (hxP : P x = true) :
    let last := ((L.filter P).reverse).headI
    last ∈ L ∧ P last = true ∧ L.idxOf x ≤ L.idxOf last := by
  induction L generalizing x with
  | nil => simp at hxL
  | cons a L ih =>
      have hnodup := List.nodup_cons.mp hL
      rcases List.mem_cons.mp hxL with rfl | hxTail
      · by_cases htail : ∃ y ∈ L, P y = true
        · have hfilter : L.filter P ≠ [] := by
            simpa [List.filter_eq_nil_iff] using htail
          have hrev : (L.filter P).reverse ≠ [] := by
            simpa using hfilter
          obtain ⟨y, hy, hPy⟩ := htail
          have hlast := ih hnodup.2 y hy hPy
          rw [show (List.filter P (x :: L)).reverse =
              (L.filter P).reverse ++ [x] by simp [hxP]]
          rw [show (((L.filter P).reverse ++ [x]).headI) =
              ((L.filter P).reverse).headI by
            cases hq : (L.filter P).reverse with
            | nil => exact (hrev hq).elim
            | cons _ _ => rfl]
          dsimp only at hlast
          obtain ⟨hlastMem, hlastP, _⟩ := hlast
          have hlastNe : ((L.filter P).reverse).headI ≠ x := by
            intro heq
            exact hnodup.1 (heq.symm ▸ hlastMem)
          simp [hlastMem, hlastP,
            List.idxOf_cons_ne _ hlastNe.symm]
        · have hfilter : L.filter P = [] := by
            rw [List.filter_eq_nil_iff]
            exact fun y hy hPy => htail ⟨y, hy, hPy⟩
          simp [hxP, hfilter]
      · have hne : x ≠ a := fun h => hnodup.1 (h ▸ hxTail)
        have htailResult := ih hnodup.2 x hxTail hxP
        by_cases hPa : P a = true
        · by_cases hfilter : L.filter P = []
          · have hcontra : P x = false := by
              have := List.filter_eq_nil_iff.mp hfilter x hxTail
              simpa using this
            simp_all
          · have hrev : (L.filter P).reverse ≠ [] := by
              simpa using hfilter
            rw [show (List.filter P (a :: L)).reverse =
                (L.filter P).reverse ++ [a] by simp [hPa]]
            rw [show (((L.filter P).reverse ++ [a]).headI) =
                ((L.filter P).reverse).headI by
              cases hq : (L.filter P).reverse with
              | nil => exact (hrev hq).elim
              | cons _ _ => rfl]
            dsimp only at htailResult
            obtain ⟨hlastMem, hlastP, hidx⟩ := htailResult
            have hlastNe : ((L.filter P).reverse).headI ≠ a := by
              intro heq
              exact hnodup.1 (heq.symm ▸ hlastMem)
            refine ⟨List.mem_cons_of_mem _ hlastMem, hlastP, ?_⟩
            rw [List.idxOf_cons_ne _ hne.symm,
              List.idxOf_cons_ne _ hlastNe.symm]
            omega
        · have hPaf : P a = false := Bool.eq_false_iff.mpr hPa
          simp only [List.filter_cons_of_neg hPa]
          dsimp only at htailResult
          obtain ⟨hlastMem, hlastP, hidx⟩ := htailResult
          have hlastNe : ((L.filter P).reverse).headI ≠ a := by
            intro heq
            rw [heq] at hlastP
            simp [hPaf] at hlastP
          refine ⟨List.mem_cons_of_mem _ hlastMem, hlastP, ?_⟩
          rw [List.idxOf_cons_ne _ hne.symm,
            List.idxOf_cons_ne _ hlastNe.symm]
          omega

/-- Every completed-output element whose index is in the interval defining a
nonempty standard block belongs to that block. -/
theorem getElem_mem_standardBlock_of_bounds
    (c : Code) (m r : ℕ) (x : BitString)
    (hxB : x ∈ standardBlock c m r x)
    (k : ℕ)
    (hk : k < (completedBoundedOutput c m).length)
    (hlo :
      omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) ≤ k)
    (hhi :
      k < omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ r) :
    (completedBoundedOutput c m)[k] ∈ standardBlock c m r x := by
  have hbit := standardBlock_testBit_of_mem c m r x hxB
  unfold standardBlock
  rw [ite_eq_left hbit, List.mem_toFinset, List.mem_take_iff_getElem]
  let start :=
    omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1)
  refine ⟨k - start, ?_, ?_⟩
  · simp only [List.length_drop]
    exact Nat.lt_min.mpr
      ⟨by dsimp [start]; omega, by dsimp [start]; omega⟩
  · have hsum : start + (k - start) = k := by omega
    rw [List.getElem_drop]
    change (completedBoundedOutput c m)[start + (k - start)] =
      (completedBoundedOutput c m)[k]
    exact getElem_congr rfl hsum _

/-- Bounds on the index in `completedBoundedOutput` of an element belonging to a standard block. -/
private theorem idxOf_completedBoundedOutput_mem_standardBlock
    (c : Code) (m r : ℕ) (x : BitString) (hxB : x ∈ standardBlock c m r x) :
    let L := completedBoundedOutput c m
    let start := omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1)
    start ≤ L.idxOf x ∧ L.idxOf x < start + 2 ^ r := by
  intro L start
  let p := 2 ^ r
  have hbit := standardBlock_testBit_of_mem c m r x hxB
  unfold standardBlock at hxB
  rw [ite_eq_left hbit, List.mem_toFinset] at hxB
  have hnodupL : L.Nodup := boundedOutputStage_nodup c m (maxHaltingStage c m)
  obtain ⟨k, hk, hkx⟩ := List.mem_take_iff_getElem.mp hxB
  have hkP : k < p := Nat.lt_of_lt_of_le hk (Nat.min_le_left _ _)
  have hglobal : start + k < L.length := by
    simp only [List.length_drop] at hk
    dsimp [start, p, L] at *
    omega
  have hidx : L.idxOf x = start + k := by
    have hi := hnodupL.idxOf_getElem (start + k) hglobal
    simp only [List.getElem_drop] at hkx
    rw [hkx] at hi
    exact hi
  dsimp [L, start] at hidx ⊢
  omega

/-- Aligned block calculation for the preceding block anchor in `betterStandardBlockSelector`. -/
private theorem betterStandard_false_branch_index
    (omega_cnt r il : ℕ)
    (hafter : omega_cnt / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ r ≤ il)
    (hilLt : il < omega_cnt / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ (r + 1)) :
    (il / 2 ^ r) * 2 ^ r = omega_cnt / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ r := by
  let p := 2 ^ r
  let q := omega_cnt / 2 ^ (r + 1)
  have hpow : 2 ^ (r + 1) = 2 * p := by dsimp [p]; rw [pow_succ']
  have hstart : omega_cnt / 2 ^ (r + 1) * 2 ^ (r + 1) = (2 * q) * p := by
    dsimp [q]
    rw [hpow]
    ring
  have hilLt' : il < (2 * q) * p + 2 * p := by
    rw [← hstart, ← hpow]
    exact hilLt
  have hilDiv : il / p = 2 * q + 1 := by
    apply Nat.div_eq_of_lt_le
    · calc
        (2 * q + 1) * p = (2 * q) * p + p := by ring
        _ ≤ il := by rw [← hstart]; exact hafter
    · calc
        il < (2 * q) * p + 2 * p := hilLt'
        _ = (2 * q + 1 + 1) * p := by ring
  calc
    (il / p) * p = (2 * q + 1) * p := by rw [hilDiv]
    _ = omega_cnt / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ r := by rw [hstart]; ring

/-- **The stage search of the improved selector terminates.**  If every member of `M` appears
in the completed bound-`m` list, there is a stage `t₀` that the `rfind` of the selector returns
for either branch flag and in which every member of `M` has already been enumerated. -/
theorem exists_betterStandard_stage (c : Code) (m r : ℕ)
    (M : Finset BitString) (hM : M.Nonempty)
    (hsubset : ∀ y ∈ M, y ∈ completedBoundedOutput c m) :
    ∃ t₀ : ℕ,
      (∀ flag : Bool, t₀ ∈ Nat.rfind (fun t => Part.some
        (betterStandardModelSeen c (codedUniformOn M hM).code
          (betterStandardBlockAdvice m r flag) t))) ∧
      ∀ y ∈ M, y ∈ boundedOutputStage c m t₀ := by
  set ACode := (codedUniformOn M hM).code with hACode
  have hModelList : betterStandardModelList ACode = canonicalFinsetList M :=
    dataPoints_codedUniformOn M hM
  obtain ⟨tCover, htCover⟩ := exists_stage_covering_finset c m M hsubset
  have hseenCover :
      betterStandardModelSeen c ACode (betterStandardBlockAdvice m r false) tCover = true := by
    rw [betterStandardModelSeen, betterStandardBlockAdviceM_advice, List.all_eq_true]
    intro y hy
    rw [List.elem_eq_mem, decide_eq_true_eq]
    apply htCover y
    exact mem_canonicalFinsetList.mp (hModelList ▸ hy)
  have hex : ∃ t,
      betterStandardModelSeen c ACode (betterStandardBlockAdvice m r false) t = true :=
    ⟨tCover, hseenCover⟩
  have hkey : ∀ (flag : Bool) (t : ℕ),
      betterStandardModelSeen c ACode (betterStandardBlockAdvice m r flag) t =
        betterStandardModelSeen c ACode (betterStandardBlockAdvice m r false) t := by
    intro flag t
    simp only [betterStandardModelSeen, betterStandardBlockAdviceM_advice]
  refine ⟨Nat.find hex, fun flag => ?_, ?_⟩
  · refine Nat.mem_rfind.mpr ⟨?_, ?_⟩
    · rw [Part.mem_some_iff, hkey flag]
      exact (Nat.find_spec hex).symm
    · intro t ht
      rw [Part.mem_some_iff, hkey flag]
      exact (Bool.eq_false_of_ne_true (Nat.find_min hex ht)).symm
  · intro y hy
    have hyModel : y ∈ betterStandardModelList ACode := by
      rw [hModelList, mem_canonicalFinsetList]
      exact hy
    have hall := List.all_eq_true.mp (Nat.find_spec hex)
    simpa only [betterStandardModelSeen, betterStandardBlockAdviceM_advice,
      List.elem_eq_mem, decide_eq_true_eq] using hall y hyModel

/-- **The last member lies in the doubled window of `x`.**  In a stage that has seen every
member of `M`, the member enumerated last lies in the stage prefix `boundedOutputStage c m t₀`,
at an index at least the start of the aligned window of the source-standard block of `x` and
below that start plus `2 ^ (r + 1)`. -/
theorem betterStandardLastMember_idxOf_bounds (c : Code) (m r : ℕ) (x : BitString)
    (M : Finset BitString) (hM : M.Nonempty) (hxM : x ∈ M)
    (hxB : x ∈ standardBlock c m r x) (flag : Bool) {t₀ : ℕ}
    (hMstage : ∀ y ∈ M, y ∈ boundedOutputStage c m t₀) :
    betterStandardLastMember c (codedUniformOn M hM).code
        (betterStandardBlockAdvice m r flag) t₀ ∈ boundedOutputStage c m t₀ ∧
      omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) ≤
        (boundedOutputStage c m t₀).idxOf (betterStandardLastMember c
          (codedUniformOn M hM).code (betterStandardBlockAdvice m r flag) t₀) ∧
      (boundedOutputStage c m t₀).idxOf (betterStandardLastMember c
          (codedUniformOn M hM).code (betterStandardBlockAdvice m r flag) t₀) <
        omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ (r + 1) := by
  set ACode := (codedUniformOn M hM).code with hACode
  set S := boundedOutputStage c m t₀ with hSdef
  set L := completedBoundedOutput c m with hLdef
  set last := betterStandardLastMember c ACode (betterStandardBlockAdvice m r flag) t₀
    with hlastDef
  have hModelList : betterStandardModelList ACode = canonicalFinsetList M :=
    dataPoints_codedUniformOn M hM
  have hxS : x ∈ S := hMstage x hxM
  have hSnodup : S.Nodup := boundedOutputStage_nodup c m t₀
  have hlast : last ∈ S ∧ last ∈ betterStandardModelList ACode ∧ S.idxOf x ≤ S.idxOf last := by
    have h := last_filtered_member_idxOf_ge
      (fun y => decide (y ∈ betterStandardModelList ACode)) S hSnodup x hxS
      (by simp [hModelList, hxM])
    simpa only [decide_eq_true_eq, hlastDef, betterStandardLastMember,
      betterStandardBlockAdviceM_advice, hSdef] using h
  have hprefix : S <+: L := boundedOutputStage_prefix_completed c m t₀
  have hlastL : last ∈ L := hprefix.sublist.subset hlast.1
  have hixEq : S.idxOf x = L.idxOf x := hprefix.idxOf_eq_of_mem hxS
  have hilEq : S.idxOf last = L.idxOf last := hprefix.idxOf_eq_of_mem hlast.1
  have hxBounds : omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) ≤ L.idxOf x ∧
      L.idxOf x < omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ r :=
    idxOf_completedBoundedOutput_mem_standardBlock c m r x hxB
  have hcountLt : omegaCount c m <
      omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) + 2 ^ (r + 1) := by
    have hmod := Nat.mod_lt (omegaCount c m) (show 0 < 2 ^ (r + 1) by positivity)
    have hdecomp := Nat.mod_add_div (omegaCount c m) (2 ^ (r + 1))
    have hstart' : omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) =
        2 ^ (r + 1) * (omegaCount c m / 2 ^ (r + 1)) := by ring
    rw [hstart']
    omega
  have hilL : L.idxOf last < omegaCount c m := by
    have hlen : L.length = omegaCount c m := rfl
    rw [← hlen]
    exact List.idxOf_lt_length_of_mem hlastL
  have hidx := hlast.2.2
  refine ⟨hlast.1, ?_, ?_⟩ <;> omega

/-- **The improved selector recovers the block from any anchor inside it.**  Once the stage
search has settled at `t₀` and the anchor the advice selects there lies in the source-standard
block of `x`, the selector outputs the canonical code of that block. -/
theorem betterStandardBlockSelector_of_anchor_mem (c : Code) (m r : ℕ) (x ACode : BitString)
    (hxB : x ∈ standardBlock c m r x) (flag : Bool) {t₀ : ℕ}
    (ht₀ : t₀ ∈ Nat.rfind (fun t => Part.some
      (betterStandardModelSeen c ACode (betterStandardBlockAdvice m r flag) t)))
    (hanchor : betterStandardAnchor c ACode (betterStandardBlockAdvice m r flag) t₀ ∈
      standardBlock c m r x) :
    (codedUniformOn (standardBlock c m r x) ⟨x, hxB⟩).code ∈
      betterStandardBlockSelector c ACode (betterStandardBlockAdvice m r flag) := by
  unfold betterStandardBlockSelector
  rw [Part.mem_bind_iff]
  refine ⟨t₀, ht₀, ?_⟩
  simp only [betterStandardBlockAdviceM_advice, betterStandardBlockAdviceR_advice]
  have hrec := standardBlockFromMemberSelector_recovers c m r
    (betterStandardAnchor c ACode (betterStandardBlockAdvice m r flag) t₀)
    (by simpa only [standardBlock] using hanchor)
  simpa only [standardBlock] using hrec

/-- **Conditional selector geometry leaf for `prop:better-std`.**  From the
canonical code of any model `M` that contains `x` and whose members all appear
in the completed bound-`m` list, together with the `(m, r, flag)` advice, the
selector recovers the canonical code of the source-standard block containing
`x`.

* Let `L = completedBoundedOutput c m`, `sStart = (omegaCount c m / 2^(r+1)) * 2^(r+1)`,
  so `standardBlock c m r x = ((L.drop sStart).take (2^r)).toFinset` and
  `sStart ≤ L.idxOf x < sStart + 2^r` (`standardBlock_eq_completedDyadicBlock`,
  `standardBlock_start_add_size_le`).
* The `rfind` in `betterStandardBlockSelector` terminates: at
  `boundedOutputCompletionTime c m` every member of `M ⊆ L` has appeared
  (`exists_stage_covering_finset`), so `betterStandardModelSeen … = true`. Let
  `t₀` be its `Nat.find`; `boundedOutputStage c m t₀ <+: L`
  (`boundedOutputStage_prefix_completed`).
* `betterStandardLastMember … t₀` is the `M`-member of maximal index in `L`
  (last in enumeration order; the stage is a prefix and contains all of `M`).
  Call it `last`; since `x ∈ M`, `L.idxOf last ≥ L.idxOf x ≥ sStart`, and
  `L.idxOf last < omegaCount c m ≤ sStart + 2^(r+1)` (block fits + tail `< 2^r`).
* Choose `flag := decide (L.idxOf last < sStart + 2^r)`.  In both branches the
  `betterStandardAnchor` lands at an index in `[sStart, sStart + 2^r)`, hence in
  `standardBlock c m r x` (`standardBlock` ignores its last argument).
* Finish with `standardBlockFromMemberSelector_recovers c m r anchor _`; the
  block code is anchor-independent (`standardBlock c m r anchor =
  standardBlock c m r x`) and `codedUniformOn … .code` is independent of the
  nonemptiness witness. -/
theorem betterStandardBlockSelector_recovers
    (c : Code) (m r : ℕ) (x : BitString)
    (M : Finset BitString) (hM : M.Nonempty)
    (hxM : x ∈ M)
    (hsubset : ∀ y ∈ M, y ∈ completedBoundedOutput c m)
    (hxB : x ∈ standardBlock c m r x) :
    ∃ flag : Bool,
      (codedUniformOn (standardBlock c m r x) ⟨x, hxB⟩).code ∈
        betterStandardBlockSelector c
          (codedUniformOn M hM).code
          (betterStandardBlockAdvice m r flag) := by
  set ACode := (codedUniformOn M hM).code with hACode
  obtain ⟨t₀, ht₀, hMstage⟩ := exists_betterStandard_stage c m r M hM hsubset
  set S := boundedOutputStage c m t₀ with hSdef
  set L := completedBoundedOutput c m with hLdef
  set p := 2 ^ r with hp
  set start := omegaCount c m / 2 ^ (r + 1) * 2 ^ (r + 1) with hstart
  set last := betterStandardLastMember c ACode (betterStandardBlockAdvice m r false) t₀
    with hlastDef
  obtain ⟨hlastS, hstartIl, hilLt⟩ :=
    betterStandardLastMember_idxOf_bounds c m r x M hM hxM hxB false hMstage
  have hprefix : S <+: L := boundedOutputStage_prefix_completed c m t₀
  have hlastL : last ∈ L := hprefix.sublist.subset hlastS
  set il := S.idxOf last with hil
  have hilEq : il = L.idxOf last := hprefix.idxOf_eq_of_mem hlastS
  have hilLtL : il < L.length := by
    rw [hilEq]
    exact List.idxOf_lt_length_of_mem hlastL
  have hlastAt : L[il]'hilLtL = last := by
    have hidxLt : L.idxOf last < L.length := List.idxOf_lt_length_of_mem hlastL
    exact (getElem_congr rfl hilEq hilLtL).trans (List.getElem_idxOf hidxLt)
  by_cases hcurrent : il < start + p
  · refine ⟨true, betterStandardBlockSelector_of_anchor_mem c m r x ACode hxB true
      (ht₀ true) ?_⟩
    have hlastBlock : last ∈ standardBlock c m r x := by
      have hmem := getElem_mem_standardBlock_of_bounds c m r x hxB il hilLtL
        (by simpa [hstart] using hstartIl) (by simpa [hstart, hp] using hcurrent)
      rwa [hlastAt] at hmem
    simpa only [betterStandardAnchor, betterStandardBlockAdviceM_advice,
      betterStandardBlockAdviceR_advice, betterStandardBlockAdviceCurrent_advice,
      ↓reduceIte, hlastDef, betterStandardLastMember] using hlastBlock
  · refine ⟨false, betterStandardBlockSelector_of_anchor_mem c m r x ACode hxB false
      (ht₀ false) ?_⟩
    have hafter : start + p ≤ il := by omega
    have hblockStart : (S.findIdx (fun y => decide (y = last)) / p) * p = start + p := by
      rw [findIdx_decide_eq_eq_idxOf]
      change (il / p) * p = start + p
      exact betterStandard_false_branch_index (omegaCount c m) r il hafter hilLt
    have hp1 : 1 ≤ p := Nat.one_le_two_pow
    set k := start + p - 1 with hk
    have hkLtS : k < S.length := by
      have : il < S.length := List.idxOf_lt_length_of_mem hlastS
      omega
    have hkLower : start ≤ k := by omega
    have hkUpper : k < start + p := by omega
    have hanchorEq : S.getD (((S.findIdx (fun y => decide (y = last)) / p) * p) - 1) [] =
        L[k]'(lt_of_lt_of_le hkLtS hprefix.length_le) := by
      rw [hblockStart]
      change S.getD k [] = _
      rw [List.getD_eq_getElem S [] hkLtS]
      exact hprefix.getElem hkLtS
    have hanchorBlock :
        S.getD (((S.findIdx (fun y => decide (y = last)) / p) * p) - 1) [] ∈
          standardBlock c m r x := by
      rw [hanchorEq]
      exact getElem_mem_standardBlock_of_bounds c m r x hxB k
        (lt_of_lt_of_le hkLtS hprefix.length_le)
        (by simpa [hstart] using hkLower) (by simpa [hstart, hp] using hkUpper)
    simpa only [betterStandardAnchor, betterStandardBlockAdviceM_advice,
      betterStandardBlockAdviceR_advice, betterStandardBlockAdviceCurrent_advice,
      Bool.false_eq_true, ↓reduceIte, hlastDef, betterStandardLastMember] using hanchorBlock

end Kolmogorov
