/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.ArithmeticCoding
import KolmogorovMathlib.MonotoneComplexity.ConcatenationBound
import KolmogorovMathlib.MonotoneComplexity.EffectiveOpenBridge
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.CondEnumeration
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.Infra
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorrConverse
import KolmogorovMathlib.MonotoneComplexity.MonotoneFromPrefix
import KolmogorovMathlib.MonotoneComplexity.SharedCoding
import KolmogorovMathlib.AlgorithmicProbability.UniversalSemimeasure
import KolmogorovMathlib.AlgorithmicRandomness.Disjointify
import KolmogorovMathlib.AlgorithmicRandomness.ExpectationBounded

/-!
# Section 5.6 (Levin-Schnorr): shared definitions and Chapter 3 / Chapter 5 bridges

This module collects the notions used by the Section 5.6 skeleton (milestone C10) of
Shen-Uspensky-Vereshchagin, *Kolmogorov Complexity and Algorithmic Randomness*.

## Rendering of the source inequality

The source writes the randomness criterion with real logarithms,
`-log p(x) - KM(x) ≤ c` where `p(x) = μ(Ω_x)` (SUV p. 146).  Exponentiating, this is the
*totally defined* `ℝ≥0∞` inequality

`2 ^ (-KM(x)) ≤ 2 ^ c * p(x)`,

i.e. `complexityWeight (KMOf D x) ≤ (2 : ℝ≥0∞) ^ c * cantorMass μ x`.  All statements below use
this multiplicative form.  This is not a weakening: the two forms are equivalent whenever
`0 < p(x) < ∞`, and the multiplicative form is the *correct* reading at `p(x) = 0`
(where `-log p(x) = +∞`), while the real-logarithm form with the Lean convention
`Real.logb 2 0 = 0` would silently become vacuous there and would make the converse
direction of Theorem 90 false.  The same convention is already used by the proved half of
Theorem 89 (`exists_const_cantorMass_mul_le_complexityWeight_KMOf`).

## Bridges

`prefixHitSet S` is the set of sequences having a prefix in `S` -- the Chapter 5 way of
turning an enumerable set of strings into an open set.  The lemmas
`isEffectiveOpen_prefixHitSet_of_isRE`, `isUniformlyEffectiveOpen_prefixHitSet_of_isRE` and
`isMartinLofTest_prefixHitSet` are the named bridges from the Chapter 5 `cantorOpen`/`IsRE`
layer to the Chapter 3 `IsEffectiveOpen`/`IsUniformlyEffectiveOpen`/`IsMartinLofTest` layer.
They are proved, not assumed, and they route through the existing sorry-free bridges
`isEffectiveOpen_cantorOpen_of_isRE` and `isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE`
of `MonotoneComplexity/EffectiveOpenBridge.lean`.
-/

namespace Kolmogorov

open MeasureTheory
open scoped ENNReal

/-! ### An r.e. relation composed with a computable map -/

/-- Precomposing an r.e. predicate with a total computable map gives an r.e. predicate. -/
lemma IsRE.compComputable {α β : Type*} [Primcodable α] [Primcodable β] {R : β → Prop}
    (hR : IsRE R) {g : α → β} (hg : Computable g) : IsRE fun a => R (g a) := by
  obtain ⟨f, hf, hfR⟩ := hR
  exact ⟨fun a => f (g a), hf.comp hg, fun a => hfR (g a)⟩

/-! ### Sets of sequences generated by a set of strings -/

/-- The set of infinite sequences having some prefix in `S`.  This is the union of the
cylinders `Ω_x` over `x ∈ S` (SUV p. 146: "the set of all infinite sequences that have a
prefix in `D_c`"). -/
def prefixHitSet (S : Set BitString) : Set CantorSeq :=
  {w | ∃ n, cantorPrefix w n ∈ S}

/-- The sequences with a prefix in `S` form the union of the cylinders of the members of `S`. -/
lemma prefixHitSet_eq_iUnion_cantorCylinder (S : Set BitString) :
    prefixHitSet S = ⋃ x ∈ S, cantorCylinder x := by
  ext w
  simp only [prefixHitSet, Set.mem_setOf_eq, Set.mem_iUnion, exists_prop]
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨cantorPrefix w n, hn, ?_⟩
    exact (isCantorPrefix_iff_cantorPrefix_eq _ w).2 (by simp [cantorPrefix_length])
  · rintro ⟨x, hx, hw⟩
    refine ⟨x.length, ?_⟩
    rw [(isCantorPrefix_iff_cantorPrefix_eq x w).1 hw]
    exact hx

/-- **Bridge (measure).** For an arbitrary Borel measure on Cantor space the mass of
`prefixHitSet S` is bounded by the sum of the masses of the prefix-minimal elements of `S`.
This is the measure step of Lemma 1 in the proof of Theorem 90 ("without changing this union
we may keep only minimal `x ∈ D_c`", SUV p. 146); it generalises the uniform-measure lemma
`uniformMeasure_iUnion_cantorCylinder_le` of `LevinSchnorrMass.lean` to any `μ`. -/
lemma measure_prefixHitSet_le_tsum_minimalPrefixElements (μ : Measure CantorSeq)
    (S : Set BitString) :
    μ (prefixHitSet S) ≤ ∑' x : minimalPrefixElements S, cantorMass μ (x : BitString) := by
  rw [prefixHitSet_eq_iUnion_cantorCylinder, ← iUnion_cantorCylinder_minimalPrefixElements S]
  refine le_trans (measure_biUnion_le μ (Set.to_countable _) cantorCylinder) (le_of_eq ?_)
  exact tsum_congr fun _ => rfl

/-- **Bridge (Chapter 5 r.e. layer → Chapter 3 effective-open layer).** If a set of strings is
r.e., then the set of sequences having a prefix in it is effectively open in the Chapter 3
sense. -/
theorem isEffectiveOpen_prefixHitSet_of_isRE {S : Set BitString}
    (hS : IsRE fun x : BitString => x ∈ S) : IsEffectiveOpen (prefixHitSet S) := by
  have hRE : IsRE fun q : BitString × BitString => q.1 ∈ S := hS.compComputable Computable.fst
  have h := isEffectiveOpen_cantorOpen_of_isRE (R := fun p (_ : BitString) => p ∈ S) hRE []
  have heq : cantorOpen (fun p (_ : BitString) => p ∈ S) [] = prefixHitSet S := by
    rw [prefixHitSet_eq_iUnion_cantorCylinder]
    rfl
  rwa [heq] at h

/-- **Bridge (uniform version).** A uniformly r.e. family of sets of strings induces a
uniformly effectively open family of subsets of Cantor space.  The index `c` is recovered
from the length of the unary code `natCode c` used by
`isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE`. -/
theorem isUniformlyEffectiveOpen_prefixHitSet_of_isRE {S : ℕ → Set BitString}
    (hS : IsRE fun q : ℕ × BitString => q.2 ∈ S q.1) :
    IsUniformlyEffectiveOpen fun c => prefixHitSet (S c) := by
  have hmap : Computable fun q : BitString × BitString => (q.2.length - 1, q.1) := by
    refine Computable.pair ?_ Computable.fst
    exact (Primrec.nat_sub.comp (Primrec.list_length.comp Primrec.snd)
      (Primrec.const 1)).to_comp
  have hRE : IsRE fun q : BitString × BitString => q.1 ∈ S (q.2.length - 1) :=
    hS.compComputable hmap
  have h := isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE
    (R := fun p y => p ∈ S (y.length - 1)) hRE
  have heq : (fun c => cantorOpen (fun p y => p ∈ S (y.length - 1)) (natCode c))
      = fun c => prefixHitSet (S c) := by
    funext c
    rw [prefixHitSet_eq_iUnion_cantorCylinder]
    simp only [cantorOpen, length_natCode, Nat.add_sub_cancel]
  rwa [heq] at h

/-- **Bridge (Martin-Löf test).** A uniformly r.e. family of sets of strings whose induced
open sets have `μ`-mass at most `2^{-c}` is a Martin-Löf test for `μ`. -/
theorem isMartinLofTest_prefixHitSet {μ : Measure CantorSeq} {S : ℕ → Set BitString}
    (hS : IsRE fun q : ℕ × BitString => q.2 ∈ S q.1)
    (hmass : ∀ c, μ (prefixHitSet (S c)) ≤ (2 : ℝ≥0∞)⁻¹ ^ c) :
    IsMartinLofTest μ fun c => prefixHitSet (S c) := by
  refine ⟨isUniformlyEffectiveOpen_prefixHitSet_of_isRE hS, fun c => ?_⟩
  rw [dyadicValue_one_eq_inv_two_pow']
  exact hmass c

/-! ### Deficiency sets

SUV p. 146 fixes a constant `c` and considers the set `D_c` of strings `x` with
`-log p(x) - KM(x) > c`.  The three variants below are the monotone (`KM`, Theorem 90),
a priori (`KA`, Theorem 91) and prefix (`K`, Theorem 92) forms.  In each case
`x ∈ D_c` reads `2^c * p(x) < 2^(-complexity of x)`.
-/

/-- SUV p. 146: `D_c = {x : -log p(x) - KM_D(x) > c}`, in multiplicative form. -/
def monotoneDeficiencySet (μ : Measure CantorSeq) (D : BitStream → BitStream) (c : ℕ) :
    Set BitString :=
  {x | (2 : ℝ≥0∞) ^ c * cantorMass μ x < complexityWeight (KMOf D x)}

/-- SUV p. 148 (Theorem 91): the a priori-complexity deficiency set
`{x : -log p(x) - KA(x) > c}`, in multiplicative form. -/
def aPrioriDeficiencySet (μ : Measure CantorSeq) (c : ℕ) : Set BitString :=
  {x | (2 : ℝ≥0∞) ^ c * cantorMass μ x < universalContinuousSemimeasure x}

/-- SUV p. 148 (Theorem 92): the prefix-complexity deficiency set
`{x : -log p(x) - K(x) > c}`, in multiplicative form. -/
def prefixDeficiencySet (μ : Measure CantorSeq) (U : Map) (c : ℕ) : Set BitString :=
  {x | (2 : ℝ≥0∞) ^ c * cantorMass μ x < complexityWeight (KPPlain U x)}

/-- SUV p. 146: `-log p(x) - KM_D(x) ≤ c` for one `c` and every prefix `x` of `w`. -/
def BoundedMonotoneDeficiency (μ : Measure CantorSeq) (D : BitStream → BitStream)
    (w : CantorSeq) : Prop :=
  ∃ c : ℕ, ∀ n : ℕ, complexityWeight (KMOf D (cantorPrefix w n))
    ≤ (2 : ℝ≥0∞) ^ c * cantorMass μ (cantorPrefix w n)

/-- SUV p. 148: `-log p(x) - KA(x) ≤ c` for one `c` and every prefix `x` of `w`. -/
def BoundedAPrioriDeficiency (μ : Measure CantorSeq) (w : CantorSeq) : Prop :=
  ∃ c : ℕ, ∀ n : ℕ, universalContinuousSemimeasure (cantorPrefix w n)
    ≤ (2 : ℝ≥0∞) ^ c * cantorMass μ (cantorPrefix w n)

/-- SUV p. 148: `-log p(x) - K(x) ≤ c` for one `c` and every prefix `x` of `w`. -/
def BoundedPrefixDeficiency (μ : Measure CantorSeq) (U : Map) (w : CantorSeq) : Prop :=
  ∃ c : ℕ, ∀ n : ℕ, complexityWeight (KPPlain U (cantorPrefix w n))
    ≤ (2 : ℝ≥0∞) ^ c * cantorMass μ (cantorPrefix w n)

/-- A sequence has bounded monotone deficiency exactly when some level of the deficiency test avoids
all of its prefixes. -/
lemma boundedMonotoneDeficiency_iff_forall_not_mem {μ : Measure CantorSeq}
    {D : BitStream → BitStream} {w : CantorSeq} :
    BoundedMonotoneDeficiency μ D w ↔
      ∃ c : ℕ, ∀ n : ℕ, cantorPrefix w n ∉ monotoneDeficiencySet μ D c := by
  simp [BoundedMonotoneDeficiency, monotoneDeficiencySet, not_lt]

/-- A sequence has bounded a priori deficiency exactly when some level of the deficiency test avoids
all of its prefixes. -/
lemma boundedAPrioriDeficiency_iff_forall_not_mem {μ : Measure CantorSeq} {w : CantorSeq} :
    BoundedAPrioriDeficiency μ w ↔
      ∃ c : ℕ, ∀ n : ℕ, cantorPrefix w n ∉ aPrioriDeficiencySet μ c := by
  simp [BoundedAPrioriDeficiency, aPrioriDeficiencySet, not_lt]

/-- A sequence has bounded prefix deficiency exactly when some level of the deficiency test avoids
all of its prefixes. -/
lemma boundedPrefixDeficiency_iff_forall_not_mem {μ : Measure CantorSeq} {U : Map}
    {w : CantorSeq} :
    BoundedPrefixDeficiency μ U w ↔
      ∃ c : ℕ, ∀ n : ℕ, cantorPrefix w n ∉ prefixDeficiencySet μ U c := by
  simp [BoundedPrefixDeficiency, prefixDeficiencySet, not_lt]

/-! ### Enumerability of the deficiency sets

SUV p. 146: "The set `D_c` is enumerable (since `p` is computable and `KM` is upper
semicomputable, the difference is lower semicomputable)."  The three statements below are
that remark, uniformly in `c`.
-/

/-- SUV Theorem 90 (Section 5.6, p. 146): the monotone deficiency sets `D_c` are uniformly
enumerable, because `μ` is computable and `KM_D` is upper semicomputable. -/
theorem isRE_monotoneDeficiencySet {μ : Measure CantorSeq} [IsProbabilityMeasure μ]
    (hμ : IsComputableMeasure μ) {D : BitStream → BitStream}
    (hD : IsOptimalMonotoneDecompressor D) :
    IsRE fun q : ℕ × BitString => q.2 ∈ monotoneDeficiencySet μ D q.1 := by
  have hf : Computable fun p : (ℕ × BitString) × ℕ => (p.1.2, p.2 + 1) :=
    Computable.pair (Computable.snd.comp Computable.fst)
      (Primrec.succ.to_comp.comp Computable.snd)
  have hg : Computable fun p : (ℕ × BitString) × ℕ => (p.1.1, p.1.2, 1, p.2) :=
    Computable.pair (Computable.fst.comp Computable.fst)
      (Computable.pair (Computable.snd.comp Computable.fst)
        (Computable.pair (Computable.const 1) Computable.snd))
  have h1 : IsRE fun p : (ℕ × BitString) × ℕ => KMOf D p.1.2 < ((p.2 + 1 : ℕ) : ℕ∞) :=
    (KMOf_isRE_lt hD.1).comp_computable hf
  have h2 : IsRE fun p : (ℕ × BitString) × ℕ =>
      (2 : ℝ≥0∞) ^ p.1.1 * cantorMass μ p.1.2 < dyadicValue 1 p.2 :=
    (isRE_two_pow_mul_cantorMass_lt_dyadicValue hμ).comp_computable hg
  exact (h1.and h2).exists_encodable.of_iff fun _ => lt_complexityWeight_iff_exists_nat.symm

/-- SUV Theorem 91 (Section 5.6, p. 148): the a priori deficiency sets are uniformly
enumerable, because `μ` is computable and the universal continuous semimeasure is lower
semicomputable. -/
theorem isRE_aPrioriDeficiencySet {μ : Measure CantorSeq} [IsProbabilityMeasure μ]
    (hμ : IsComputableMeasure μ) :
    IsRE fun q : ℕ × BitString => q.2 ∈ aPrioriDeficiencySet μ q.1 := by
  obtain ⟨approx, _hmono, hsup, hcomp⟩ :=
    universalContinuousSemimeasure_isLowerSemicomputableContinuousSemimeasure.2
  have hsup' : ∀ x : BitString,
      ⨆ s, dyadicValue (approx s x []) s = universalContinuousSemimeasure x :=
    fun x => hsup x []
  have hg : Computable fun p : (ℕ × BitString) × ℕ =>
      (p.1.1, p.1.2, approx p.2 p.1.2 [], p.2) := by
    refine Computable.pair (Computable.fst.comp Computable.fst)
      (Computable.pair (Computable.snd.comp Computable.fst)
        (Computable.pair ?_ Computable.snd))
    exact hcomp.comp (Computable.pair Computable.snd
      (Computable.pair (Computable.snd.comp Computable.fst) (Computable.const [])))
  have h2 : IsRE fun p : (ℕ × BitString) × ℕ =>
      (2 : ℝ≥0∞) ^ p.1.1 * cantorMass μ p.1.2 < dyadicValue (approx p.2 p.1.2 []) p.2 :=
    (isRE_two_pow_mul_cantorMass_lt_dyadicValue hμ).comp_computable hg
  refine (IsRE.exists_encodable (R := fun (q : ℕ × BitString) (s : ℕ) =>
    (2 : ℝ≥0∞) ^ q.1 * cantorMass μ q.2 < dyadicValue (approx s q.2 []) s)
    h2).of_iff fun q => ?_
  constructor
  · rintro ⟨s, hs⟩
    refine lt_of_lt_of_le hs ?_
    rw [← hsup' q.2]
    exact le_iSup (fun s => dyadicValue (approx s q.2 []) s) s
  · intro h
    have hiSup : (2 : ℝ≥0∞) ^ q.1 * cantorMass μ q.2
        < ⨆ s, dyadicValue (approx s q.2 []) s := by
      rwa [hsup' q.2]
    exact lt_iSup_iff.1 hiSup

/-- SUV Theorem 92 (Section 5.6, p. 148): the prefix deficiency sets are uniformly
enumerable, because `μ` is computable and `K` is upper semicomputable. -/
theorem isRE_prefixDeficiencySet {μ : Measure CantorSeq} [IsProbabilityMeasure μ]
    (hμ : IsComputableMeasure μ) {U : Map} (hU : IsOptimalPrefixConditional U) :
    IsRE fun q : ℕ × BitString => q.2 ∈ prefixDeficiencySet μ U q.1 := by
  have hf : Computable fun p : (ℕ × BitString) × ℕ => (p.1.2, p.2 + 1) :=
    Computable.pair (Computable.snd.comp Computable.fst)
      (Primrec.succ.to_comp.comp Computable.snd)
  have hg : Computable fun p : (ℕ × BitString) × ℕ => (p.1.1, p.1.2, 1, p.2) :=
    Computable.pair (Computable.fst.comp Computable.fst)
      (Computable.pair (Computable.snd.comp Computable.fst)
        (Computable.pair (Computable.const 1) Computable.snd))
  have h1 : IsRE fun p : (ℕ × BitString) × ℕ => KPPlain U p.1.2 < ((p.2 + 1 : ℕ) : ℕ∞) :=
    (isRE_KPPlain_lt hU.isDecompressor).comp_computable hf
  have h2 : IsRE fun p : (ℕ × BitString) × ℕ =>
      (2 : ℝ≥0∞) ^ p.1.1 * cantorMass μ p.1.2 < dyadicValue 1 p.2 :=
    (isRE_two_pow_mul_cantorMass_lt_dyadicValue hμ).comp_computable hg
  exact (h1.and h2).exists_encodable.of_iff fun _ => lt_complexityWeight_iff_exists_nat.symm

/-! ### Conditional measures

SUV p. 149 (proof of Theorem 93): `μ_x` is the measure concentrated on `Ω_x` given by
`μ_x(Ω_y) = μ(Ω_{xy}) / μ(Ω_x)`, and the source calls `x ↦ μ_x` a *computable family of
probability measures*.  That reading is correct exactly at the prefixes of positive mass:
`condCantorMass_nil` and `condCantorMass_add` below say that `μ_x` is normalised and additive
on the two children of every vertex when `μ(Ω_x) ≠ 0`, while
`condCantorMass_of_cantorMass_eq_zero` says that at a null `x` the quotient degenerates to the
zero function, which is not a probability distribution.  The definition therefore stays the
source's verbatim quotient and the positivity hypothesis is carried by the only statement that
uses the family, the relativised Theorem 89 in `Criteria.lean`.
-/

/-- SUV p. 149: the mass `μ_x(Ω_y) = μ(Ω_{xy}) / μ(Ω_x)` of the conditional measure `μ_x`,
transcribed verbatim.  In `ℝ≥0∞` the quotient is `⊤` when `μ(Ω_x) = 0 < μ(Ω_{xy})`, which
cannot happen for a measure, and `0` when both vanish; the latter case is exactly where `μ_x`
fails to be a probability measure, see `condCantorMass_of_cantorMass_eq_zero`. -/
noncomputable def condCantorMass (μ : Measure CantorSeq) (x y : BitString) : ℝ≥0∞ :=
  cantorMass μ (x ++ y) / cantorMass μ x

/-- SUV p. 149: `μ_x` is normalised, `μ_x(Ω) = μ_x(Ω_Λ) = 1`, as soon as `μ(Ω_x) ≠ 0`. -/
lemma condCantorMass_nil (μ : Measure CantorSeq) [IsFiniteMeasure μ] {x : BitString}
    (hx : cantorMass μ x ≠ 0) : condCantorMass μ x [] = 1 := by
  rw [condCantorMass, List.append_nil]
  exact ENNReal.div_self hx (measure_ne_top μ _)

/-- SUV p. 149: `μ_x` is additive on the two children of every vertex,
`μ_x(Ω_y) = μ_x(Ω_{y0}) + μ_x(Ω_{y1})`.  Together with `condCantorMass_nil` this is the
statement that `μ_x` is a probability distribution on `Ω` (concentrated on `Ω_x`) whenever
`μ(Ω_x) ≠ 0`; it is the cylinder-mass form of "the measure concentrated on `Ω_x`". -/
lemma condCantorMass_add (μ : Measure CantorSeq) (x y : BitString) :
    condCantorMass μ x y
      = condCantorMass μ x (y ++ [false]) + condCantorMass μ x (y ++ [true]) := by
  rw [condCantorMass, condCantorMass, condCantorMass, ← List.append_assoc,
    ← List.append_assoc, ENNReal.div_add_div_same, ← cantorMass_add]

/-- SUV p. 149, the degenerate case: at a null prefix `x` the quotient `μ(Ω_{xy})/μ(Ω_x)` is
`0/0`, so `μ_x` is identically zero and is *not* a probability measure.  This is why the
relativised Theorem 89 carries the hypothesis `cantorMass μ x ≠ 0`. -/
lemma condCantorMass_of_cantorMass_eq_zero (μ : Measure CantorSeq) {x : BitString}
    (hx : cantorMass μ x = 0) (y : BitString) : condCantorMass μ x y = 0 := by
  have hle : cantorMass μ (x ++ y) ≤ cantorMass μ x :=
    measure_mono (cantorCylinder_subset_of_prefix ⟨y, rfl⟩)
  have hxy : cantorMass μ (x ++ y) = 0 := le_antisymm (hx ▸ hle) (zero_le _)
  simp [condCantorMass, hxy]

/-! ### Conditional monotone complexity

SUV Problem 135 (Section 5.4, p. 132) uses the conditional monotone complexity `KM(y | x)`
"defined in a natural way (we do not require monotonicity with respect to the condition
`x`)".  A conditional monotone decompressor is therefore a family `D y : E → E` of computable
maps of finite-or-infinite streams indexed by the condition `y`, uniformly computable in `y`
but with no monotonicity requirement in `y`.
-/

/-- SUV Problem 135 (Section 5.4, p. 132): a computable *conditional* map of finite-or-infinite
streams.  Each `D y` is a continuous stream map, and the lower graph is r.e. jointly in the
condition, the program and the output.  Monotonicity in the condition `y` is deliberately not
required. -/
def IsComputableConditionalStreamMap (D : BitString → BitStream → BitStream) : Prop :=
  (∀ y, IsContinuousStreamMap (D y)) ∧
    IsRE fun t : BitString × BitString × BitString => streamLowerGraph (D t.1) t.2.1 t.2.2

/-- SUV Problem 135 (Section 5.4, p. 132): the conditional monotone complexity
`KM_D(x | y)` -- the least length of a program `p` with `x ⪯ D y (p)`. -/
noncomputable def condKMOf (D : BitString → BitStream → BitStream) (x y : BitString) : ℕ∞ :=
  sInf {l : ℕ∞ | ∃ p : BitString, monotoneProduces (D y) p x ∧ l = p.length}

/-- SUV Problem 135 (Section 5.4, p. 132): optimality for conditional monotone decompressors,
with the source quantifier order `∃ D, ∀ D', ∃ c, ∀ x y`. -/
def IsOptimalConditionalMonotoneDecompressor (D : BitString → BitStream → BitStream) : Prop :=
  IsComputableConditionalStreamMap D ∧
    ∀ D', IsComputableConditionalStreamMap D' →
      ∃ c : ℕ, ∀ x y, condKMOf D x y ≤ condKMOf D' x y + c

/-- SUV Problem 135 (Section 5.4, p. 132), the tagged conditional lower graph: a program is read as
`natCode i ++ p`, the self-delimiting index `i` selecting the `i`-th conditionally computable
stream map. For each fixed condition `y` this is the unconditional `taggedStreamLowerGraph` of
the family `fun i => U i y`, so every unconditional fact about `taggedStreamLowerGraph` applies
to it; only joint enumerability in the condition is a genuinely conditional matter. -/
def condTaggedStreamLowerGraph (U : ℕ → BitString → BitString → BitString → Prop)
    (y : BitString) : BitString → BitString → Prop :=
  taggedStreamLowerGraph fun i => U i y

/-- **Conditional form of SUV Theorem 83 (p. 129).**  The enumeration of all
computable stream maps can be made uniform in a `BitString` condition: there is a family
`U i y` of stream lower graphs, r.e. jointly in `(i, y, p, out)`, that contains the lower
graph of every computable *conditional* stream map, with an index `i` that does not depend on
the condition.

*Proved* in `LevinSchnorr/CondEnumeration.lean`: no new machinery was needed, because
`StreamRelationSanitizer.lean` already states its sanitizer for an arbitrary `Primcodable`
parameter type.  Folding the condition into the program slot of `universalStreamRel` and
running the sanitizer with parameter type `ℕ × BitString` gives an index independent of the
condition, which is exactly what conditional optimality requires.  INTERFACE_PROBLEM 1 is
thereby resolved. -/
theorem exists_universal_computableConditionalStreamMap_lowerGraphs :
    ∃ U : ℕ → BitString → BitString → BitString → Prop,
      (∀ i y, IsStreamLowerGraph (U i y)) ∧
      (∀ D, IsComputableConditionalStreamMap D →
        ∃ i, ∀ y p z, U i y p z ↔ streamLowerGraph (D y) p z) ∧
      IsRE fun t : (ℕ × BitString) × BitString × BitString => U t.1.1 t.1.2 t.2.1 t.2.2 :=
  ⟨condUniversalStreamRel, condUniversalStreamRel_isStreamLowerGraph,
    fun _ hD => condUniversalStreamRel_complete hD.1 hD.2, condUniversalStreamRel_isRE⟩

/-- Joint enumerability of the tagged conditional family: the conditional
analogue of `taggedStreamLowerGraph_isRE` (`MonotoneOptimality.lean`, l. 170).

Proved below by exactly that copy. -/
theorem isRE_condTaggedStreamLowerGraph {U : ℕ → BitString → BitString → BitString → Prop}
    (hU : IsRE fun t : (ℕ × BitString) × BitString × BitString => U t.1.1 t.1.2 t.2.1 t.2.2) :
    IsRE fun t : BitString × BitString × BitString =>
      condTaggedStreamLowerGraph U t.1 t.2.1 t.2.2 := by
  classical
  have hnil : IsRE fun t : BitString × BitString × BitString => t.2.2 = [] := by
    refine isRE_of_computable_bool _ (fun t : BitString × BitString × BitString =>
      decide (t.2.2 = [])) (fun _ => decide_eq_true_iff) ?_
    exact Primrec.to_comp (PrimrecPred.decide
      (Primrec.eq.comp (Primrec.snd.comp Primrec.snd) (Primrec.const [])))
  have hmap : Computable fun w : (BitString × BitString × BitString) × (ℕ × BitString) =>
      ((w.2.1, w.1.1), (w.2.2, w.1.2.2)) :=
    Computable.pair
      (Computable.pair (Computable.fst.comp Computable.snd)
        (Computable.fst.comp Computable.fst))
      (Computable.pair (Computable.snd.comp Computable.snd)
        (Computable.snd.comp (Computable.snd.comp Computable.fst)))
  have hUcomp : IsRE fun w : (BitString × BitString × BitString) × (ℕ × BitString) =>
      U w.2.1 w.1.1 w.2.2 w.1.2.2 := hU.comp_computable hmap
  have hpred : Computable fun w : (BitString × BitString × BitString) × (ℕ × BitString) =>
      decide (w.1.2.1 = natCode w.2.1 ++ w.2.2) := by
    refine Primrec.to_comp (PrimrecPred.decide ?_)
    exact Primrec.eq.comp (Primrec.fst.comp (Primrec.snd.comp Primrec.fst))
      (Primrec.list_append.comp (primrec_natCode.comp (Primrec.fst.comp Primrec.snd))
        (Primrec.snd.comp Primrec.snd))
  have hand : IsRE fun w : (BitString × BitString × BitString) × (ℕ × BitString) =>
      w.1.2.1 = natCode w.2.1 ++ w.2.2 ∧ U w.2.1 w.1.1 w.2.2 w.1.2.2 :=
    (hUcomp.and_computable hpred).of_iff fun _ => by rw [decide_eq_true_iff]
  have hright : IsRE fun t : BitString × BitString × BitString =>
      ∃ i p, t.2.1 = natCode i ++ p ∧ U i t.1 p t.2.2 := by
    refine (IsRE.exists_encodable
      (R := fun (t : BitString × BitString × BitString) (b : ℕ × BitString) =>
        t.2.1 = natCode b.1 ++ b.2 ∧ U b.1 t.1 b.2 t.2.2) hand).of_iff fun t => ?_
    constructor
    · rintro ⟨⟨i, p⟩, h⟩
      exact ⟨i, p, h⟩
    · rintro ⟨i, p, h⟩
      exact ⟨(i, p), h⟩
  exact (hnil.or hright).of_iff fun _ => Iff.rfl

/-- SUV Problem 135 (Section 5.4, p. 132): an optimal conditional monotone decompressor
exists.  This is the conditional analogue of Theorem 84 and is what makes `KM(· | ·)` a
well-defined notion.

Proved here from the two leaves above by the tagging construction of
`exists_optimalMonotoneDecompressor`: `condKMOf D x y` is *definitionally* `KMOf (D y) x`, so
once the condition is fixed the whole optimality argument is the unconditional one and
`KMOf_tagged_le_add` supplies the constant `(natCode i).length`, uniformly in `y` because the
index `i` produced by the universal family does not depend on `y`. -/
theorem exists_optimalConditionalMonotoneDecompressor :
    ∃ D : BitString → BitStream → BitStream, IsOptimalConditionalMonotoneDecompressor D := by
  obtain ⟨U, hU_LG, hU_comp, hU_RE⟩ :=
    exists_universal_computableConditionalStreamMap_lowerGraphs
  refine ⟨fun y => streamMapOfLowerGraph (condTaggedStreamLowerGraph U y)
    (taggedStreamLowerGraph_isStreamLowerGraph _ (fun i => hU_LG i y)), ⟨?_, ?_⟩, ?_⟩
  · exact fun y => streamMapOfLowerGraph_isContinuousStreamMap _
  · refine (isRE_condTaggedStreamLowerGraph hU_RE).of_iff fun t => ?_
    exact (streamMapOfLowerGraph_finite_spec _ t.2.1 t.2.2).symm
  · intro D' hD'
    obtain ⟨i, hi⟩ := hU_comp D' hD'
    refine ⟨(natCode i).length, fun x y => ?_⟩
    refine KMOf_tagged_le_add (c := i) fun p hp => ?_
    have hl2 : U i y p x := (hi y p x).mpr hp
    have hl3 : condTaggedStreamLowerGraph U y (natCode i ++ p) x := Or.inr ⟨i, p, rfl, hl2⟩
    rwa [monotoneProduces, streamMapOfLowerGraph_finite_spec]

/-! ### Restrictions to a finite index set

SUV p. 149 (Problems 144 and 145): `w(F)` is the string of bits `w i` for `i ∈ F`, taken in
increasing order of `i`, and `p_{F,Z}` is the `μ`-probability of the event `w(F) = Z`.
-/

/-- SUV p. 149: `w(F)`, the restriction of `w` to the finite index set `F`, read in increasing
order of indices. -/
def restrictSeq (F : Finset ℕ) (w : CantorSeq) : BitString :=
  (F.sort (· ≤ ·)).map w

/-- Restricting a sequence to a finite set of coordinates gives a string of that set's cardinality.
-/
@[simp] lemma length_restrictSeq (F : Finset ℕ) (w : CantorSeq) :
    (restrictSeq F w).length = F.card := by
  simp [restrictSeq]

/- The canonical binary code `finsetCode` of a finite set of indices (SUV p. 149, the first
component of the pair `(F, w(F))`) is the shared one of
`KolmogorovMathlib.MonotoneComplexity.SharedCoding`: `finsetCode F = natToBitString
(Encodable.encode F)`, with `finsetCode_injective` and the coding-invariance lemma
`exists_const_KPPlain_finsetCode_invariant` proved there. -/

/-- SUV p. 149: `p_{F,Z}`, the `μ`-probability of the event `w(F) = Z`. -/
noncomputable def finsetEventMass (μ : Measure CantorSeq) (F : Finset ℕ) (Z : BitString) :
    ℝ≥0∞ :=
  μ {w : CantorSeq | restrictSeq F w = Z}

/-! ### The ample-excess functions of Problems 146 and 147 -/

/-- SUV Problem 146 (Section 5.6, p. 150): the function
`t(w) = ∑_{x ⊑ w} m(x) / p(x)`, the sum being over all finite prefixes of `w`.
The `ℝ≥0∞` quotient realises the source convention that `m(x)/p(x)` is infinite when
`p(x) = 0`. -/
noncomputable def prefixSumRatio (m : BitString → ℝ≥0∞) (μ : Measure CantorSeq)
    (w : CantorSeq) : ℝ≥0∞ :=
  ∑' n : ℕ, m (cantorPrefix w n) / cantorMass μ (cantorPrefix w n)

/-- SUV Problem 147 (Section 5.6, p. 150): the supremum version
`sup_{x ⊑ w} m(x) / p(x)` of `prefixSumRatio`. -/
noncomputable def prefixSupRatio (m : BitString → ℝ≥0∞) (μ : Measure CantorSeq)
    (w : CantorSeq) : ℝ≥0∞ :=
  ⨆ n : ℕ, m (cantorPrefix w n) / cantorMass μ (cantorPrefix w n)

end Kolmogorov
