/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.APrioriLogGap
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.Basic
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.CondConcatenation
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.DecidableLengths
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.FinsetDeficiency
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.FinsetKraft
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.FinsetRestriction
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.MaximalSumTest
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.MaximalSupTest
import KolmogorovMathlib.MonotoneComplexity.ExpectationBoundedDeficiency

/-!
# Section 5.4-5.6: the required exercises

The required problems of Sections 5.4-5.6 of Shen-Uspensky-Vereshchagin: Problems 135 and 140
of Sections 5.4-5.5, and Problems 143, 144, 145, 146 and 147 of Section 5.6.

The remaining required problems (158, 161, 162, 165, 169, 170, 174, 176, 185, 187) belong to
Sections 5.7-5.9 and are stated elsewhere.

Problem 141 (binary intervals) and Problem 134 (`KM(xy) ≤ K(x) + KM(y) + O(1)`) are already
proved in the repository and are only used here.
-/

namespace Kolmogorov

open MeasureTheory
open scoped ENNReal

/-! ## Problem 135: conditional form of the concatenation bound -/

/-- SUV Problem 135 (Section 5.4, p. 132): in Problem 134 one can replace `KM(y)` by the
conditional monotone complexity `KM(y | x)`, i.e. `KM(xy) ≤ K(x) + KM(y | x) + O(1)` with one
constant uniform in `x` and `y`.

The unconditional Problem 134 is proved as `exists_const_KMOf_append_le_KPPlain_add_KMOf`; the
conditional complexity is `condKMOf` for an optimal conditional monotone decompressor. -/
theorem problem_135_KMOf_append_le_KPPlain_add_condKMOf {D : BitStream → BitStream}
    (hD : IsOptimalMonotoneDecompressor D) {U : Map} (hU : IsOptimalPrefixConditional U)
    {Dc : BitString → BitStream → BitStream}
    (hDc : IsOptimalConditionalMonotoneDecompressor Dc) :
    ∃ c : ℕ, ∀ x y : BitString, KMOf D (x ++ y) ≤ KPPlain U x + condKMOf Dc y x + c :=
  exists_const_KMOf_append_le_KP_add_condKMOf hD hU.isPrefixMachine hU.isDecompressor hDc.1

/-! ## Problem 140: monotone versus a priori complexity -/

/-! ## Problem 143: randomness from a decidable set of lengths -/

/-! ## Problems 144 and 145: the permutation-invariant criterion -/

/-- SUV Problem 145 (Section 5.6, p. 150): let `F 0 ⊆ F 1 ⊆ F 2 ⊆ …` be a computable sequence
of finite sets with `⋃ᵢ F i = ℕ`.  If `K(F i, w(F i)) ≥ -log p_{F i, w(F i)} - c` for some `c`
and all `i`, then `w` is Martin-Löf random with respect to `μ`.

Together with Problem 144 this shows that the condition of Problem 144 is also sufficient, and
that it is enough to test one increasing computable exhaustion of `ℕ`.  The sets `F i` are
coded by the shared `finsetCode`, and as in Problem 144 the statement is coding-independent
(`exists_const_KPPlain_finsetCode_invariant`).

Source hint (p. 150): "using permutation of indices, we may assume that the `F i` are initial
segments of `ℕ`; then we refer to Problem 143".  Carrying that out literally needs a computable
permutation `π` of `ℕ` with `π(F i) = range |F i|`, the pushforward measure `π_*μ`, its
computability, and the invariance of Martin-Löf randomness under `π`, none of which exists in
the repository.  The case `F i = Finset.range i`, where no permutation is needed, is proved as
`problem_145_range_isMartinLofRandom` (`LevinSchnorr/UniformFinsetCriterion.lean`).

Every shortcut past the permutation fails for one reason: the measure side needs
`{0,…,n−1} ⊆ F i` (giving `p_{F i, w(F i)} ≤ μ(Ω_{(w)ₙ})`), while the complexity side needs
`F i ⊆ {0,…,n−1}` (so that `(w)ₙ` determines `w(F i)`), and both at once force `F i = range n`.

The permutation-free route is to redo the Kraft-Chaitin half of Theorem 90 on the filtration
generated by the events `{v : v(F) = Z}` instead of the prefix filtration.  What is already
in place for it:
the geometry, `sort_take_eq_range`, `restrictSeq_take`, `measurableSet_setOf_restrictSeq` and
the partition identity `cantorMass_eq_sum_finsetEventMass` (`LevinSchnorr/FinsetDeficiency.lean`);
the effectivity, `exists_uniform_lsc_finsetEventMass` (`LevinSchnorr/FinsetEventLSC.lean`),
which approximates `p_{F,Z}` from *below*, the side a Kraft-Chaitin request function needs; and
`exists_forall_lt_mem_of_exhaustion`. -/
theorem problem_145_isMartinLofRandom_of_computable_exhaustion {μ : Measure CantorSeq}
    [IsProbabilityMeasure μ] (hμ : IsComputableMeasure μ) {U : Map}
    (hU : IsOptimalPrefixConditional U) {F : ℕ → Finset ℕ} (hF : Computable F)
    (hmono : ∀ i : ℕ, F i ⊆ F (i + 1)) (hcover : ∀ k : ℕ, ∃ i : ℕ, k ∈ F i) {w : CantorSeq}
    (hw : ∃ c : ℕ, ∀ i : ℕ,
      complexityWeight (KPPair U (finsetCode (F i)) (restrictSeq (F i) w))
        ≤ (2 : ℝ≥0∞) ^ c * finsetEventMass μ (F i) (restrictSeq (F i) w)) :
    IsMartinLofRandom μ w :=
  problem_145_isMartinLofRandom_of_computable_exhaustion' hμ hU hF hmono hcover hw

/-! ## Problems 146 and 147: the ample excess lemma -/

/-- SUV Problem 146 (Section 5.6, p. 150): the function `w ↦ ∑_{x ⊑ w} m(x) / p(x)` is an
expectation-bounded randomness test for `μ`, where `m` is the discrete a priori probability
and `p(x) = μ(Ω_x)`.

Its integral is `∑_x p(x) · m(x)/p(x) = ∑_x m(x) ≤ 1`; lower semicomputability follows from
that of `m` and computability of `μ`.

The integral half is `lintegral_prefixSumRatio_le` (`LevinSchnorr/ExpectationTests.lean`),
proved there; the semicomputability half is the clean leaf
`isLowerSemicomputableFun_prefixSumRatio` of the same module. -/
theorem problem_146_isExpectationBoundedRandomnessTest_prefixSumRatio {μ : Measure CantorSeq}
    [IsProbabilityMeasure μ] (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞}
    (hm : IsUniversalSemimeasure m) :
    IsExpectationBoundedRandomnessTest μ (prefixSumRatio m μ) :=
  ⟨isLowerSemicomputableFun_prefixSumRatio hμ hm, lintegral_prefixSumRatio_le μ hm.1.1⟩

/-- SUV Problem 146 (Section 5.6, p. 150): `∑_{x ⊑ w} m(x) / p(x)` is a *universal*
expectation-bounded randomness test: it dominates every expectation-bounded test up to a
constant factor, in the sense of `exists_maximal_expectation_bounded_test` (Theorem 42).

Source hint: a lower semicomputable function on Cantor space is a sum of characteristic
functions of intervals with non-negative coefficients; collecting the coefficients at each
vertex `x` of the binary tree gives a lower semicomputable `u` on strings with
`∑_x p(x) u(x) ≤ 1`, and the maximal such `u` is `m(x)/p(x)` up to a `Θ(1)` factor. -/
theorem problem_146_maximal_prefixSumRatio {μ : Measure CantorSeq} [IsProbabilityMeasure μ]
    (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞} (hm : IsUniversalSemimeasure m) :
    ∀ v : CantorSeq → ℝ≥0∞, IsExpectationBoundedRandomnessTest μ v →
      ∃ c : NNReal, ∀ w : CantorSeq, v w ≤ c * prefixSumRatio m μ w :=
  fun v hv => maximal_prefixSumRatio hμ hm v hv

/-- SUV Problem 147 (Section 5.6, p. 150): the supremum `sup_{x ⊑ w} m(x)/p(x)` is again an
expectation-bounded randomness test (it is pointwise below the sum of Problem 146).

The integral half is `lintegral_prefixSupRatio_le` (`LevinSchnorr/ExpectationTests.lean`),
proved there from `prefixSupRatio_le_prefixSumRatio`; the semicomputability half is the
clean leaf `isLowerSemicomputableFun_prefixSupRatio` of the same module. -/
theorem problem_147_isExpectationBoundedRandomnessTest_prefixSupRatio {μ : Measure CantorSeq}
    [IsProbabilityMeasure μ] (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞}
    (hm : IsUniversalSemimeasure m) :
    IsExpectationBoundedRandomnessTest μ (prefixSupRatio m μ) :=
  ⟨isLowerSemicomputableFun_prefixSupRatio hμ hm, lintegral_prefixSupRatio_le μ hm.1.1⟩

/-- SUV Problem 147 (Section 5.6, p. 150): the quantity `sup_n 2^(n - K((w)_n))`, the
multiplicative form of the source's `sup_n [n - K(w₀ … w_{n-1})]`. -/
noncomputable def prefixExcessSup (U : Map) (w : CantorSeq) : ℝ≥0∞ :=
  ⨆ n : ℕ, (2 : ℝ≥0∞) ^ n * complexityWeight (KPPlain U (cantorPrefix w n))

/-- SUV Problem 147 (Section 5.6, p. 150), uniform-measure case: the expectation-bounded
randomness deficiency equals `sup_n [n - K(w₀ … w_{n-1})]` up to an additive constant.
Multiplicatively: the universal test `sup_{x ⊑ w} m(x)/2^(-l(x))` and `prefixExcessSup U w`
agree up to two constant factors `2^(-c₁)` and `2^(c₂)`.

This is the quantitative version of the Levin-Schnorr theorem with prefix complexity proved
by Gács, and rediscovered by J. Miller and L. Yu as the "ample excess lemma". -/
theorem problem_147_uniform_prefixSupRatio_eq_prefixExcessSup {m : BitString → ℝ≥0∞}
    (hm : IsUniversalSemimeasure m) {U : Map} (hU : IsOptimalPrefixConditional U) :
    ∃ c₁ c₂ : ℕ, ∀ w : CantorSeq,
      (2 : ℝ≥0∞)⁻¹ ^ c₁ * prefixExcessSup U w ≤ prefixSupRatio m uniformMeasure w ∧
        prefixSupRatio m uniformMeasure w ≤ (2 : ℝ≥0∞) ^ c₂ * prefixExcessSup U w := by
  have hratio : ∀ (w : CantorSeq) (n : ℕ),
      m (cantorPrefix w n) / cantorMass uniformMeasure (cantorPrefix w n)
        = (2 : ℝ≥0∞) ^ n * m (cantorPrefix w n) := by
    intro w n
    rw [cantorMass_uniformMeasure, cantorPrefix_length, div_eq_mul_inv, ← ENNReal.inv_pow,
      inv_inv, mul_comm]
  have hsupeq : ∀ w : CantorSeq,
      prefixSupRatio m uniformMeasure w
        = ⨆ n : ℕ, (2 : ℝ≥0∞) ^ n * m (cantorPrefix w n) := by
    intro w
    rw [prefixSupRatio]
    exact iSup_congr fun n => hratio w n
  obtain ⟨c₂, hc₂⟩ := lowerSemicomputableSemimeasure_le_prefixComplexityWeight hm.1 hU
  obtain ⟨c, hcpos, hc⟩ := prefixComplexityWeight_le_universalSemimeasure hm hU
  obtain ⟨c₁, hc₁⟩ := exists_inv_two_pow_lt (ne_of_gt hcpos)
  have hinv : (2 : ℝ≥0∞) ^ c₂ * ((2 : ℝ≥0∞)⁻¹) ^ c₂ = 1 := by
    rw [← mul_pow, ENNReal.mul_inv_cancel (by norm_num) (by norm_num), one_pow]
  refine ⟨c₁, c₂, fun w => ⟨?_, ?_⟩⟩
  · rw [hsupeq, prefixExcessSup, ENNReal.mul_iSup]
    refine iSup_mono fun n => ?_
    have hstep : (2 : ℝ≥0∞)⁻¹ ^ c₁ * complexityWeight (KPPlain U (cantorPrefix w n))
        ≤ m (cantorPrefix w n) :=
      le_trans (mul_le_mul_left hc₁.le _) (hc (cantorPrefix w n))
    calc (2 : ℝ≥0∞)⁻¹ ^ c₁
            * ((2 : ℝ≥0∞) ^ n * complexityWeight (KPPlain U (cantorPrefix w n)))
        = (2 : ℝ≥0∞) ^ n
            * ((2 : ℝ≥0∞)⁻¹ ^ c₁ * complexityWeight (KPPlain U (cantorPrefix w n))) := by
          rw [← mul_assoc, ← mul_assoc, mul_comm ((2 : ℝ≥0∞)⁻¹ ^ c₁) ((2 : ℝ≥0∞) ^ n)]
      _ ≤ (2 : ℝ≥0∞) ^ n * m (cantorPrefix w n) := by gcongr
  · rw [hsupeq, prefixExcessSup, ENNReal.mul_iSup]
    refine iSup_mono fun n => ?_
    have hstep : m (cantorPrefix w n)
        ≤ (2 : ℝ≥0∞) ^ c₂ * complexityWeight (KPPlain U (cantorPrefix w n)) := by
      calc m (cantorPrefix w n)
          = (2 : ℝ≥0∞) ^ c₂ * ((2 : ℝ≥0∞)⁻¹ ^ c₂ * m (cantorPrefix w n)) := by
            rw [← mul_assoc, hinv, one_mul]
        _ ≤ (2 : ℝ≥0∞) ^ c₂ * complexityWeight (KPPlain U (cantorPrefix w n)) := by
            gcongr
            exact hc₂ (cantorPrefix w n)
    calc (2 : ℝ≥0∞) ^ n * m (cantorPrefix w n)
        ≤ (2 : ℝ≥0∞) ^ n
            * ((2 : ℝ≥0∞) ^ c₂ * complexityWeight (KPPlain U (cantorPrefix w n))) := by
          gcongr
      _ = (2 : ℝ≥0∞) ^ c₂
            * ((2 : ℝ≥0∞) ^ n * complexityWeight (KPPlain U (cantorPrefix w n))) := by
          rw [← mul_assoc, ← mul_assoc, mul_comm ((2 : ℝ≥0∞) ^ n) ((2 : ℝ≥0∞) ^ c₂)]

/-- SUV Problem 146 (Section 5.6, p. 150), assembled: `w ↦ ∑_{x ⊑ w} m(x) / p(x)` is a
*maximal* expectation-bounded randomness test in the sense of
`IsMaximalExpectationBoundedTest` (SUV Theorem 42, §3.5), i.e. the two leaves above are
exactly the two conjuncts of that shared predicate. -/
theorem problem_146_isMaximalExpectationBoundedTest {μ : Measure CantorSeq}
    [IsProbabilityMeasure μ] (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞}
    (hm : IsUniversalSemimeasure m) :
    IsMaximalExpectationBoundedTest μ (prefixSumRatio m μ) :=
  ⟨problem_146_isExpectationBoundedRandomnessTest_prefixSumRatio hμ hm,
    problem_146_maximal_prefixSumRatio hμ hm⟩

/-- SUV Problem 147 (Section 5.6, p. 150), assembled: `w ↦ sup_{x ⊑ w} m(x) / p(x)` is a
*maximal* expectation-bounded randomness test in the sense of
`IsMaximalExpectationBoundedTest`. -/
theorem problem_147_isMaximalExpectationBoundedTest {μ : Measure CantorSeq}
    [IsProbabilityMeasure μ] (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞}
    (hm : IsUniversalSemimeasure m) :
    IsMaximalExpectationBoundedTest μ (prefixSupRatio m μ) :=
  ⟨problem_147_isExpectationBoundedRandomnessTest_prefixSupRatio hμ hm,
    problem_147_maximal_prefixSupRatio' hμ hm⟩

end Kolmogorov
