/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.Complexity.CanonicalObjects.HubEdges
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.FinsetDeficiency

/-!
# Uniform lower semicomputability of the event masses `p_{F,Z}` (SUV p. 149)

`finsetEventMass μ F Z = μ{v : v(F) = Z}` is a **finite** sum of cylinder masses, over the
strings of any level above `F` that restrict to `Z` (`finsetEventMass_eq_sum`).  Adding up the
lower approximations of those cylinder masses supplied by `isLSC_cantorMass` therefore
approximates `p_{F,Z}` from below, uniformly in `(F, Z)`.

`LevinSchnorr/FinsetDeficiency.lean` needs the *upper* approximation `sliceApprox` — the
deficiency set of Problem 144 is enumerable because `2^c · p_{F,Z}` can be seen to be *small*
at a finite stage.  The Kraft–Chaitin construction on the filtration generated by the events
`{v : v(F) = Z}` (SUV Problem 145, p. 150) needs the other side: the request weight must be
*lower* semicomputable, and that is what this module supplies, in exactly the shape
`isLSC_tsum_nsmul_of_uniform` consumes.

## Main results

* `finsetLevel`, `lt_finsetLevel`, `primrec_finsetLevel` — a computable level above a finite
  index set;
* `eventApprox` — the stage-`s` lower approximation of `p_{F,Z}`;
* `exists_uniform_lsc_finsetEventMass` — the monotone, computable, uniform lower approximation.
-/

namespace Kolmogorov

open MeasureTheory

open scoped ENNReal

/-! ### A computable level above a finite index set -/

/-- A computable level strictly above every element of `F`, obtained from the increasing
enumeration of `F`. -/
def finsetLevel (F : Finset ℕ) : ℕ := (F.sort (· ≤ ·)).foldr max 0 + 1

/-- The level of a finite set of indices is strictly above each of its members. -/
lemma lt_finsetLevel {F : Finset ℕ} {i : ℕ} (h : i ∈ F) : i < finsetLevel F := by
  have hi : i ≤ (F.sort (· ≤ ·)).foldr max 0 :=
    le_foldr_max_of_mem ((Finset.mem_sort (α := ℕ) (· ≤ ·)).2 h)
  rw [finsetLevel]
  omega

/-- The level of a finite set of indices is primitive recursive in the coded set. -/
lemma primrec_finsetLevel : Primrec finsetLevel := by
  have hstep : Primrec₂ fun (_ : Finset ℕ) (q : ℕ × ℕ) => max q.1 q.2 :=
    (Primrec₂.comp Primrec.nat_max (Primrec.fst.comp Primrec.snd)
      (Primrec.snd.comp Primrec.snd)).to₂
  have hfold : Primrec fun F : Finset ℕ => (F.sort (· ≤ ·)).foldr max 0 :=
    Primrec.list_foldr primrec_finsetSort (Primrec.const 0) hstep
  exact Primrec.succ.comp hfold

/-- The level of a finite set of indices is computable in the coded set. -/
lemma computable_finsetLevel : Computable finsetLevel := primrec_finsetLevel.to_comp

/-! ### The lower approximation of `p_{F,Z}` -/

/-- The summand of the lower approximation of `p_{F,Z}`: the stage-`s` lower approximation of
the mass of a cylinder that restricts to `Z` on `F`, and `0` otherwise. -/
def eventTerm (M : ℕ → BitString → BitString → ℕ) (F : Finset ℕ) (Z : BitString) (s : ℕ)
    (x : BitString) : ℕ :=
  if restrictStr F x = Z then M s x [] else 0

/-- `eventTerm` written with `Bool.cond`, the shape `Computable.cond` consumes. -/
lemma eventTerm_eq_cond (M : ℕ → BitString → BitString → ℕ) (F : Finset ℕ) (Z : BitString)
    (s : ℕ) (x : BitString) :
    eventTerm M F Z s x = cond (decide (restrictStr F x = Z)) (M s x []) 0 := by
  by_cases h : restrictStr F x = Z <;> simp [eventTerm, h]

/-- The numerator of the stage-`s` lower approximation of `p_{F,Z}`. -/
def eventApprox (M : ℕ → BitString → BitString → ℕ) (s : ℕ) (F : Finset ℕ) (Z : BitString) :
    ℕ :=
  ((levelList (finsetLevel F)).map (eventTerm M F Z s)).sum

/-- `eventTerm` is computable in all of its arguments.  As in `computable_sliceTerm`, the
ambient type is kept abstract: instantiating it at a concrete product containing `Finset ℕ`
makes the elaborator unfold the `Primcodable.ofDenumerable` instance. -/
lemma computable_eventTerm {α : Type} [Primcodable α] {M : ℕ → BitString → BitString → ℕ}
    (hM : Computable fun p : ℕ × BitString × BitString => M p.1 p.2.1 p.2.2)
    {G : α → Finset ℕ} {Z : α → BitString} {S : α → ℕ}
    (hG : Computable G) (hZ : Computable Z) (hS : Computable S) :
    Computable₂ fun (z : α) (x : BitString) => eventTerm M (G z) (Z z) (S z) x := by
  have hres : Computable fun p : α × BitString => restrictStr (G p.1) p.2 :=
    Computable₂.comp (computable_restrictStr : Computable₂ restrictStr)
      (hG.comp Computable.fst) Computable.snd
  have hZ' : Computable fun p : α × BitString => Z p.1 := hZ.comp Computable.fst
  have heqC : Computable₂ fun x y : BitString => decide (x = y) :=
    Primrec₂.to_comp
      (PrimrecPred.decide Primrec.eq : Primrec₂ fun x y : BitString => decide (x = y))
  have hchk : Computable fun p : α × BitString =>
      decide (restrictStr (G p.1) p.2 = Z p.1) := Computable₂.comp heqC hres hZ'
  have hval : Computable fun p : α × BitString => M (S p.1) p.2 [] :=
    hM.comp (Computable.pair (hS.comp Computable.fst)
      (Computable.pair Computable.snd (Computable.const [])))
  exact (Computable.cond hchk hval (Computable.const 0)).of_eq fun p =>
    (eventTerm_eq_cond M (G p.1) (Z p.1) (S p.1) p.2).symm

/-- `eventApprox` is computable in all of its arguments. -/
lemma computable_eventApprox {α : Type} [Primcodable α] {M : ℕ → BitString → BitString → ℕ}
    (hM : Computable fun p : ℕ × BitString × BitString => M p.1 p.2.1 p.2.2)
    {G : α → Finset ℕ} {Z : α → BitString} {S : α → ℕ}
    (hG : Computable G) (hZ : Computable Z) (hS : Computable S) :
    Computable fun z : α => eventApprox M (S z) (G z) (Z z) :=
  computable_list_sum_map (computable_levelList.comp (computable_finsetLevel.comp hG))
    (computable_eventTerm hM hG hZ hS)

/-- The value of the stage-`s` approximation as a sum over the level above `F`. -/
lemma dyadicValue_eventApprox (M : ℕ → BitString → BitString → ℕ) (s : ℕ) (F : Finset ℕ)
    (Z : BitString) :
    dyadicValue (eventApprox M s F Z) s
      = ∑ x ∈ levelFinset (finsetLevel F), dyadicValue (eventTerm M F Z s x) s := by
  rw [eventApprox, dyadicValue_listMapSum, sum_levelFinset_eq_sum_levelList]

/-- The staged approximations of the event term increase with the stage. -/
lemma dyadicValue_eventTerm_mono {M : ℕ → BitString → BitString → ℕ}
    (hMmono : ∀ s out ctx, dyadicValue (M s out ctx) s
      ≤ dyadicValue (M (s + 1) out ctx) (s + 1))
    (F : Finset ℕ) (Z : BitString) (s : ℕ) (x : BitString) :
    dyadicValue (eventTerm M F Z s x) s ≤ dyadicValue (eventTerm M F Z (s + 1) x) (s + 1) := by
  by_cases h : restrictStr F x = Z
  · simp only [eventTerm, if_pos h]
    exact hMmono s x []
  · simp [eventTerm, h, dyadicValue]

/-- The staged event terms converge to the mass of `x` on the event that the coordinates in `F` read
`Z`, and to zero elsewhere. -/
lemma iSup_dyadicValue_eventTerm {μ : Measure CantorSeq} {M : ℕ → BitString → BitString → ℕ}
    (hMsup : ∀ out ctx, ⨆ s, dyadicValue (M s out ctx) s = cantorMass μ out) (F : Finset ℕ)
    (Z : BitString) (x : BitString) :
    (⨆ s, dyadicValue (eventTerm M F Z s x) s)
      = if restrictStr F x = Z then cantorMass μ x else 0 := by
  by_cases h : restrictStr F x = Z
  · simp only [eventTerm, if_pos h]
    exact hMsup x []
  · simp [eventTerm, h, dyadicValue]

/-- **The uniform lower approximation of the event masses.**  For a computable measure `μ` the
family `p_{F,Z} = μ{v : v(F) = Z}` is lower semicomputable uniformly in the pair `(F, Z)`, in
the shape that `isLSC_tsum_nsmul_of_uniform` consumes. -/
theorem exists_uniform_lsc_finsetEventMass {μ : Measure CantorSeq}
    (hμ : IsComputableMeasure μ) :
    ∃ A : ℕ → Finset ℕ → BitString → ℕ,
      Computable (fun p : ℕ × Finset ℕ × BitString => A p.1 p.2.1 p.2.2) ∧
      (∀ s F Z, dyadicValue (A s F Z) s ≤ dyadicValue (A (s + 1) F Z) (s + 1)) ∧
      (∀ F Z, ⨆ s, dyadicValue (A s F Z) s = finsetEventMass μ F Z) := by
  classical
  obtain ⟨M, hMmono, hMsup, hMcomp⟩ := isLSC_cantorMass hμ
  refine ⟨eventApprox M, ?_, ?_, ?_⟩
  · exact computable_eventApprox hMcomp (Computable.fst.comp Computable.snd)
      (Computable.snd.comp Computable.snd) Computable.fst
  · intro s F Z
    rw [dyadicValue_eventApprox, dyadicValue_eventApprox]
    exact Finset.sum_le_sum fun x _ => dyadicValue_eventTerm_mono hMmono F Z s x
  · intro F Z
    have hmono : ∀ x : BitString, Monotone fun s => dyadicValue (eventTerm M F Z s x) s :=
      fun x => monotone_nat_of_le_succ fun s => dyadicValue_eventTerm_mono hMmono F Z s x
    calc (⨆ s, dyadicValue (eventApprox M s F Z) s)
        = ⨆ s, ∑ x ∈ levelFinset (finsetLevel F), dyadicValue (eventTerm M F Z s x) s := by
          exact iSup_congr fun s => dyadicValue_eventApprox M s F Z
      _ = ∑ x ∈ levelFinset (finsetLevel F), ⨆ s, dyadicValue (eventTerm M F Z s x) s :=
          (ENNReal.finsetSum_iSup_of_monotone fun x => hmono x).symm
      _ = ∑ x ∈ levelFinset (finsetLevel F),
            (if restrictStr F x = Z then cantorMass μ x else 0) :=
          Finset.sum_congr rfl fun x _ => iSup_dyadicValue_eventTerm hMsup F Z x
      _ = finsetEventMass μ F Z := by
          rw [sum_levelFinset_eq_sum_levelList,
            finsetEventMass_eq_listSum μ (fun i hi => lt_finsetLevel hi) Z]

end Kolmogorov
