/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.MonotoneAPriori
import KolmogorovMathlib.AlgorithmicRandomness.ComputableMeasure
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveNull
import KolmogorovMathlib.AlgorithmicProbability.UniversalSemimeasure
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorrMass
import KolmogorovMathlib.MonotoneComplexity.MonotoneFromPrefix

/-!
# Section 5.6 (Levin-Schnorr): the Kraft-type inequalities behind Lemma 1

Lemma 1 in the proof of SUV Theorem 90 (p. 146-147) says: "the `pᵢ` are pairwise
incompatible, so `∑ 2^(-l(pᵢ)) ≤ 1`".  In this repository that statement is available for
*continuous tree semimeasures* (`IsContinuousTreeSemimeasure.tsum_antichain_le`,
`AntichainSum.lean`) but not yet for the weight `2^(-KM_D(x))` itself.

The missing link is supplied here.  Running a computable stream map `D` on fair coin flips
gives the probabilistic generator `streamMapGenerator D` of `MonotoneAPriori.lean`, whose
generated tree semimeasure dominates `2^(-KM_D(x))` pointwise: the shortest program `p` for
`x` already forces the whole cylinder `Ω_p`, of uniform mass `2^(-l(p))`, into the event
"the output extends `x`".  The Kraft inequality for `2^(-KM)` over a prefix-free set of
strings is then an instance of the semimeasure one.

This is exactly the source's argument, with the "pairwise incompatible programs" step
replaced by the (equivalent, already proved) semimeasure bound.
-/

namespace Kolmogorov

open MeasureTheory
open scoped ENNReal

/-- **SUV p. 147 (proof of Theorem 90, Lemma 1).** The weight `2^(-KM_D(x))` of a shortest
monotone program for `x` is at most the continuous semimeasure generated by running `D` on
fair coin flips: a minimal program `p` for `x` forces the whole cylinder `Ω_p`, of uniform
mass `2^(-l(p)) = 2^(-KM_D(x))`, into the event "the output extends `x`". -/
lemma complexityWeight_KMOf_le_generatedTreeSemimeasure {D : BitStream → BitStream}
    (hD : IsComputableStreamMap D) (x : BitString) :
    complexityWeight (KMOf D x) ≤ generatedTreeSemimeasure (streamMapGenerator D hD) x := by
  rcases eq_or_ne (KMOf D x) ⊤ with h | h
  · rw [h, complexityWeight_top]
    exact bot_le
  · have hlt : KMOf D x < (((KMOf D x).toNat + 1 : ℕ) : ℕ∞) := by
      conv_lhs => rw [← ENat.natCast_toNat h]
      exact_mod_cast Nat.lt_succ_self _
    obtain ⟨p, hp, hplen⟩ := (KMOf_lt_iff D x _).1 hlt
    have hple : p.length ≤ (KMOf D x).toNat := by
      have : p.length < (KMOf D x).toNat + 1 := by exact_mod_cast hplen
      omega
    have hcw : complexityWeight (KMOf D x) = (2 : ℝ≥0∞)⁻¹ ^ (KMOf D x).toNat := by
      conv_lhs => rw [← ENat.natCast_toNat h]
      rw [complexityWeight_coe]
    calc complexityWeight (KMOf D x) = (2 : ℝ≥0∞)⁻¹ ^ (KMOf D x).toNat := hcw
      _ ≤ (2 : ℝ≥0∞)⁻¹ ^ p.length := pow_le_pow_right_of_le_one' (by norm_num) hple
      _ ≤ generatedTreeSemimeasure (streamMapGenerator D hD) x :=
          inv_two_pow_le_generatedTreeSemimeasure_streamMapGenerator hD hp

/-- **Kraft inequality for monotone complexity** (SUV p. 147, Lemma 1 of Theorem 90): over a
prefix-free set of strings the weights `2^(-KM_D(x))` sum to at most `1`.  This is the
source's "the `pᵢ` are pairwise incompatible, so `∑ 2^(-l(pᵢ)) ≤ 1`". -/
theorem tsum_antichain_complexityWeight_KMOf_le_one {D : BitStream → BitStream}
    (hD : IsComputableStreamMap D) (S : Set BitString)
    (hanti : ∀ y ∈ S, ∀ z ∈ S, y <+: z → y = z) :
    ∑' x : S, complexityWeight (KMOf D (x : BitString)) ≤ 1 :=
  le_trans (ENNReal.tsum_le_tsum fun x => complexityWeight_KMOf_le_generatedTreeSemimeasure hD x)
    ((generatedTreeSemimeasure_isContinuousTreeSemimeasure _).tsum_antichain_le S hanti)

/-- **Kraft inequality for a priori complexity** (SUV p. 148, Lemma 1 of Theorem 91):
`∑ᵢ 2^(-KA(xᵢ)) ≤ 1` over a prefix-free family, because this is the sum of the a priori
masses of pairwise disjoint intervals `Ω_{xᵢ}`. -/
theorem tsum_antichain_universalContinuousSemimeasure_le_one (S : Set BitString)
    (hanti : ∀ y ∈ S, ∀ z ∈ S, y <+: z → y = z) :
    ∑' x : S, universalContinuousSemimeasure (x : BitString) ≤ 1 :=
  universalContinuousSemimeasure_isLowerSemicomputableContinuousSemimeasure.1.tsum_antichain_le
    S hanti

/-! ### Reading `KA ≤ KM + O(1)` multiplicatively

`exists_const_KA_le_KMOf` (SUV Theorem 85(e)) is stated with real logarithms.  Section 5.6
needs it in the totally defined `ℝ≥0∞` form `2^(-KM(x)) ≤ 2^c · 2^(-KA(x))`, i.e. with
`2^(-KA(x)) = universalContinuousSemimeasure x`.
-/

/-- **SUV Theorem 85(e), multiplicative form.** There is a constant `c` with
`2^(-KM_D(x)) ≤ 2^c · M(x)` for every `x`, where `M` is the universal continuous
semimeasure (`2^(-KA)`).  This is `exists_const_KA_le_KMOf` exponentiated; the proof goes
through the generated semimeasure directly, so no logarithms appear. -/
theorem exists_const_complexityWeight_KMOf_le_universalContinuousSemimeasure
    {D : BitStream → BitStream} (hD : IsComputableStreamMap D) :
    ∃ c : ℝ≥0∞, c ≠ ⊤ ∧ ∀ x : BitString,
      complexityWeight (KMOf D x) ≤ c * universalContinuousSemimeasure x := by
  obtain ⟨c, hc_top, hc⟩ := universalContinuousSemimeasure_isMaximal
    (generatedTreeSemimeasure (streamMapGenerator D hD))
    (generatedTreeSemimeasure_isLowerSemicomputableContinuousSemimeasure _)
  exact ⟨c, hc_top, fun x =>
    le_trans (complexityWeight_KMOf_le_generatedTreeSemimeasure hD x) (hc x)⟩

/-- The same bound with a *natural* exponent, which is the shape Section 5.6 uses:
`2^(-KM_D(x)) ≤ 2^c · M(x)` for some `c : ℕ`. -/
theorem exists_nat_complexityWeight_KMOf_le_universalContinuousSemimeasure
    {D : BitStream → BitStream} (hD : IsComputableStreamMap D) :
    ∃ c : ℕ, ∀ x : BitString,
      complexityWeight (KMOf D x) ≤ (2 : ℝ≥0∞) ^ c * universalContinuousSemimeasure x := by
  obtain ⟨c, hc_top, hc⟩ := exists_const_complexityWeight_KMOf_le_universalContinuousSemimeasure hD
  obtain ⟨n, hn⟩ := ENNReal.exists_nat_gt hc_top
  have hn2 : n < 2 ^ n := Nat.lt_two_pow_self
  have hle : (n : ℝ≥0∞) ≤ (2 : ℝ≥0∞) ^ n := by
    calc (n : ℝ≥0∞) ≤ ((2 ^ n : ℕ) : ℝ≥0∞) := by exact_mod_cast hn2.le
      _ = (2 : ℝ≥0∞) ^ n := by push_cast; ring
  refine ⟨n, fun x => le_trans (hc x) ?_⟩
  gcongr
  exact le_trans hn.le hle

/-! ### Effectivity of the strict comparison `2^c · p(x) < (dyadic rational)`

SUV p. 146 justifies the enumerability of the deficiency set `D_c` in one sentence: "since
`p` is computable and `KM` is upper semicomputable, the difference is lower semicomputable".
Split into its two halves, that sentence is (i) the comparison of the *computable* real
`2^c · p(x)` with a dyadic rational is a `Σ₁` condition, and (ii) the complexity is upper
semicomputable (`KMOf_isRE_lt`, SUV 85(b)) resp. the semimeasure lower semicomputable.
Half (i) is the same for all three complexity variants of Theorems 90-92 and is isolated
here.
-/

/-- The complexity weight turns sums into products: `2^(-(a+b)) = 2^(-a) · 2^(-b)`. -/
lemma complexityWeight_add' (a b : ℕ∞) :
    complexityWeight (a + b) = complexityWeight a * complexityWeight b := by
  induction a using ENat.recTopCoe with
  | top => simp
  | coe m =>
      induction b using ENat.recTopCoe with
      | top => simp
      | coe k =>
          rw [← Nat.cast_add, complexityWeight_coe, complexityWeight_coe, complexityWeight_coe,
            pow_add]

/-! ### Conditioning never hurts -/

/-- `C(x | y) ≤ C(x) + O(1)`: a decompressor may simply ignore its condition.  This is the
elementary fact behind SUV's passage from the conditional criteria of Theorems 95-96 to the
unconditional ones of Theorems 97-98 (pp. 152-154). -/
theorem exists_const_condK_le_plainK {V : Map} (hV : isOptimalConditional V) :
    ∃ c : ℕ, ∀ x y : BitString, condK V x y ≤ plainK V x + (c : ℕ∞) := by
  have hD : isDecompressor (fun p : BitString × BitString => V (p.1, [])) :=
    hV.1.comp (Computable.pair Computable.fst (Computable.const []))
  obtain ⟨c, hc⟩ := hV.2 _ hD
  refine ⟨c, fun x y => ?_⟩
  have hcondeq : condK (fun p : BitString × BitString => V (p.1, [])) x y = plainK V x := rfl
  rw [← hcondeq]
  exact hc x y

/-! ### Dyadic bookkeeping and the lower semicomputability of a computable measure -/

/-- `dyadicValue` is monotone in its numerator. -/
lemma dyadicValue_mono_nat {j k : ℕ} (h : j ≤ k) (s : ℕ) :
    dyadicValue j s ≤ dyadicValue k s := dyadicValue_mono_num h s

/-- The dyadic value `2 ^ (-s)` is finite. -/
lemma dyadicValue_one_ne_top (s : ℕ) : dyadicValue 1 s ≠ ⊤ := (dyadicValue_lt_top 1 s).ne

/-- `2^(-u)` is eventually below any positive bound. -/
lemma exists_inv_two_pow_lt {ε : ℝ≥0∞} (hε : ε ≠ 0) :
    ∃ u : ℕ, ((2 : ℝ≥0∞)⁻¹) ^ u < ε := by
  obtain ⟨m, hm⟩ := ENNReal.exists_inv_nat_lt hε
  refine ⟨m + 1, lt_of_le_of_lt ?_ hm⟩
  have hnat : m ≤ 2 ^ (m + 1) := by
    have h1 : m < 2 ^ m := Nat.lt_two_pow_self
    have h2 : (2 : ℕ) ^ m ≤ 2 ^ (m + 1) := Nat.pow_le_pow_right (by norm_num) (Nat.le_succ m)
    omega
  have hcast : ((2 : ℝ≥0∞)⁻¹) ^ (m + 1) = (((2 ^ (m + 1) : ℕ) : ℝ≥0∞))⁻¹ := by
    rw [← ENNReal.inv_pow]
    congr 1
    push_cast
    ring
  rw [hcast]
  exact ENNReal.inv_le_inv.2 (by exact_mod_cast hnat)

/-- Monotonising an approximation (`makeMono`, `UniversalSemimeasure.lean`) does not raise a
uniform upper bound. -/
lemma dyadicValue_makeMono_le {approx : ℕ → BitString → BitString → ℕ}
    {v : BitString → BitString → ℝ≥0∞}
    (h : ∀ (s : ℕ) (out ctx : BitString), dyadicValue (approx s out ctx) s ≤ v out ctx)
    (s : ℕ) (out ctx : BitString) :
    dyadicValue (makeMono approx s out ctx) s ≤ v out ctx := by
  induction s with
  | zero => exact h 0 out ctx
  | succ s ih =>
      change dyadicValue (max (2 * makeMono approx s out ctx) (approx (s + 1) out ctx)) (s + 1)
        ≤ v out ctx
      rcases le_total (2 * makeMono approx s out ctx) (approx (s + 1) out ctx) with hle | hle
      · rw [max_eq_right hle]
        exact h (s + 1) out ctx
      · rw [max_eq_left hle, dyadicValue_two_mul_succ]
        exact ih

/-- **The cylinder mass of a computable measure is lower semicomputable.**  SUV p. 146, the
"`p` is computable" half of the enumerability of the deficiency set, in the `IsLSC` form that
the Kraft-Chaitin engine consumes.  The two-sided dyadic approximation `a` of
`IsComputableMeasure` gives the *lower* approximation `a x s - 1` over `2^s`, which is turned
into a monotone one by `makeMono`. -/
theorem isLSC_cantorMass {μ : Measure CantorSeq} (hμ : IsComputableMeasure μ) :
    IsLSC fun (x : BitString) (_ : BitString) => cantorMass μ x := by
  obtain ⟨a, ha_comp, ha⟩ := hμ
  set raw : ℕ → BitString → BitString → ℕ := fun s x _ => a x s - 1 with hrawdef
  have hraw_le : ∀ (s : ℕ) (x ctx : BitString),
      dyadicValue (raw s x ctx) s ≤ cantorMass μ x := by
    intro s x _
    rcases Nat.eq_zero_or_pos (a x s) with h0 | hpos
    · have : raw s x [] = 0 := by simp [hrawdef, h0]
      simp only [hrawdef]
      rw [h0]
      simp [dyadicValue]
    · obtain ⟨m, hm⟩ : ∃ m, a x s = m + 1 := ⟨a x s - 1, by omega⟩
      have h1 := (ha x s).1
      rw [hm, dyadicValue_add] at h1
      have h2 : dyadicValue m s ≤ cantorMass μ x :=
        (ENNReal.add_le_add_iff_right (dyadicValue_one_ne_top s)).1 h1
      simpa [hrawdef, hm] using h2
  have hraw_ge : ∀ (s : ℕ) (x ctx : BitString),
      cantorMass μ x ≤ dyadicValue (raw s x ctx) s + dyadicValue 2 s := by
    intro s x _
    have hle : a x s ≤ (a x s - 1) + 1 := by omega
    calc cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s := (ha x s).2
      _ ≤ dyadicValue ((a x s - 1) + 1) s + dyadicValue 1 s := by
          gcongr
          exact dyadicValue_mono_nat hle s
      _ = dyadicValue (a x s - 1) s + (dyadicValue 1 s + dyadicValue 1 s) := by
          rw [dyadicValue_add, add_assoc]
      _ = dyadicValue (raw s x []) s + dyadicValue 2 s := by
          rw [← dyadicValue_add]
  refine ⟨makeMono raw, fun s out ctx => makeMono_mono raw s out ctx, ?_, ?_⟩
  · intro out ctx
    refine le_antisymm (iSup_le fun s =>
      dyadicValue_makeMono_le (v := fun x (_ : BitString) => cantorMass μ x)
        hraw_le s out ctx) ?_
    refine ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_
    obtain ⟨u, hu⟩ := exists_inv_two_pow_lt (ε := (ε : ℝ≥0∞)) (by exact_mod_cast hε.ne')
    have hsmall : dyadicValue 2 (u + 1) ≤ (ε : ℝ≥0∞) := by
      have h2 : dyadicValue 2 (u + 1) = ((2 : ℝ≥0∞)⁻¹) ^ u := by
        rw [show (2 : ℕ) = 2 * 1 by norm_num, dyadicValue_two_mul_succ,
          dyadicValue_one_eq_inv_two_pow']
      rw [h2]
      exact hu.le
    calc cantorMass μ out
        ≤ dyadicValue (raw (u + 1) out ctx) (u + 1) + dyadicValue 2 (u + 1) :=
          hraw_ge (u + 1) out ctx
      _ ≤ dyadicValue (makeMono raw (u + 1) out ctx) (u + 1) + (ε : ℝ≥0∞) := by
          gcongr
          · exact makeMono_ge raw (u + 1) out ctx
      _ ≤ (⨆ s, dyadicValue (makeMono raw s out ctx) s) + (ε : ℝ≥0∞) := by
          gcongr
          exact le_iSup (fun s => dyadicValue (makeMono raw s out ctx) s) (u + 1)
  · refine makeMono_computable raw ?_
    have hsub : Computable₂ (fun x y : ℕ => x - y) := Primrec₂.to_comp Primrec.nat_sub
    have h1 : Computable fun p : ℕ × BitString × BitString => a p.2.1 p.1 :=
      ha_comp.comp (Computable.fst.comp Computable.snd) Computable.fst
    exact hsub.comp h1 (Computable.const 1)

/-- The decidable matrix of the `Σ₁` condition behind
`isRE_two_pow_mul_cantorMass_lt_dyadicValue` is computable in the approximation `a`. -/
private lemma computable_dyadicMatrixCheck {a : BitString → ℕ → ℕ} (ha_comp : Computable₂ a) :
    Computable fun p : (ℕ × BitString × ℕ × ℕ) × ℕ =>
      decide (2 ^ p.1.1 * (a p.1.2.1 p.2 + 1) * 2 ^ p.1.2.2.2 < p.1.2.2.1 * 2 ^ p.2) := by
  have hmul : Computable₂ (fun x y : ℕ => x * y) := Primrec₂.to_comp Primrec.nat_mul
  have hltb : Computable₂ (fun x y : ℕ => decide (x < y)) :=
    Primrec₂.to_comp (PrimrecPred.decide Primrec.nat_lt)
  have hpow : Computable fun n : ℕ => 2 ^ n := Primrec.to_comp primrec_two_pow_aux
  have hsucc : Computable fun n : ℕ => n + 1 := Primrec.to_comp Primrec.succ
  have hA : Computable fun p : (ℕ × BitString × ℕ × ℕ) × ℕ => a p.1.2.1 p.2 :=
    ha_comp.comp (Computable.fst.comp (Computable.snd.comp Computable.fst)) Computable.snd
  exact hltb.comp
    (hmul.comp
      (hmul.comp (hpow.comp (Computable.fst.comp Computable.fst)) (hsucc.comp hA))
      (hpow.comp (Computable.snd.comp (Computable.snd.comp (Computable.snd.comp
        Computable.fst)))))
    (hmul.comp
      (Computable.fst.comp (Computable.snd.comp (Computable.snd.comp Computable.fst)))
      (hpow.comp Computable.snd))

/-- The `Σ₁` closure of that matrix is r.e. -/
private lemma isRE_dyadicMatrix {a : BitString → ℕ → ℕ} (ha_comp : Computable₂ a) :
    IsRE fun q : ℕ × BitString × ℕ × ℕ =>
      ∃ t : ℕ, 2 ^ q.1 * (a q.2.1 t + 1) * 2 ^ q.2.2.2 < q.2.2.1 * 2 ^ t := by
  have hmatrix : IsRE fun p : (ℕ × BitString × ℕ × ℕ) × ℕ =>
      2 ^ p.1.1 * (a p.1.2.1 p.2 + 1) * 2 ^ p.1.2.2.2 < p.1.2.2.1 * 2 ^ p.2 :=
    isRE_of_computable_bool _ _ (fun _ => decide_eq_true_iff)
      (computable_dyadicMatrixCheck ha_comp)
  exact IsRE.exists_encodable (R := fun (q : ℕ × BitString × ℕ × ℕ) (t : ℕ) =>
    2 ^ q.1 * (a q.2.1 t + 1) * 2 ^ q.2.2.2 < q.2.2.1 * 2 ^ t) hmatrix

/-- **Effectivity of a computable measure.** SUV p. 146, the half of "the set
`D_c` is enumerable" that uses computability of `p`: for a computable measure `μ` the strict
inequality `2^c · μ(Ω_x) < k / 2^s` is recursively enumerable in `(c, x, k, s)`.

*Estimated size*: about 70 lines (the arithmetic translation `2^c·(a+1)/2^t < k/2^s ↔
2^c·(a+1)·2^s < k·2^t` can copy `two_pow_mul_inv_two_pow_lt_dyadicValue_iff` of
`LevinSchnorrTest.lean`, and the `∃ t` step is `ENNReal.lt_iff_exists_add_pos_lt`). -/
theorem isRE_two_pow_mul_cantorMass_lt_dyadicValue {μ : Measure CantorSeq}
    (hμ : IsComputableMeasure μ) :
    IsRE fun q : ℕ × BitString × ℕ × ℕ =>
      (2 : ℝ≥0∞) ^ q.1 * cantorMass μ q.2.1 < dyadicValue q.2.2.1 q.2.2.2 := by
  classical
  obtain ⟨a, ha_comp, ha⟩ := hμ
  -- Elementary arithmetic of `dyadicValue`.
  have hdadd : ∀ j k s : ℕ, dyadicValue (j + k) s = dyadicValue j s + dyadicValue k s := by
    intro j k s
    simp only [dyadicValue, Nat.cast_add]
    rw [ENNReal.add_div]
  -- `(a x t + 1)/2^t` is an upper approximation of `μ(Ω_x)`, accurate to `2·2^(-t)`.
  have hupper : ∀ (x : BitString) (t : ℕ), cantorMass μ x ≤ dyadicValue (a x t + 1) t := by
    intro x t
    rw [hdadd]
    exact (ha x t).2
  have hlower : ∀ (x : BitString) (t : ℕ),
      dyadicValue (a x t + 1) t ≤ cantorMass μ x + 2 * ((2 : ℝ≥0∞)⁻¹) ^ t := by
    intro x t
    rw [hdadd, dyadicValue_one_eq_inv_two_pow']
    have h1 := (ha x t).1
    rw [dyadicValue_one_eq_inv_two_pow'] at h1
    calc dyadicValue (a x t) t + ((2 : ℝ≥0∞)⁻¹) ^ t
        ≤ (cantorMass μ x + ((2 : ℝ≥0∞)⁻¹) ^ t) + ((2 : ℝ≥0∞)⁻¹) ^ t := by gcongr
      _ = cantorMass μ x + 2 * ((2 : ℝ≥0∞)⁻¹) ^ t := by rw [add_assoc, two_mul]
  have hmass_ne_top : ∀ x : BitString, cantorMass μ x ≠ ⊤ := by
    intro x
    refine ne_top_of_le_ne_top ?_ (hupper x 0)
    rw [dyadicValue]
    exact ENNReal.div_ne_top (by simp) (by norm_num)
  -- `2^(-u)` is eventually below any positive bound.
  have hsmallpow : ∀ ε : ℝ≥0∞, ε ≠ 0 → ∃ u : ℕ, ((2 : ℝ≥0∞)⁻¹) ^ u < ε := by
    intro ε hε
    obtain ⟨m, hm⟩ := ENNReal.exists_inv_nat_lt hε
    refine ⟨m + 1, lt_of_le_of_lt ?_ hm⟩
    have hnat : m ≤ 2 ^ (m + 1) := by
      have h1 : m < 2 ^ m := Nat.lt_two_pow_self
      have h2 : (2 : ℕ) ^ m ≤ 2 ^ (m + 1) :=
        Nat.pow_le_pow_right (by norm_num) (Nat.le_succ m)
      omega
    have hcast : ((2 : ℝ≥0∞)⁻¹) ^ (m + 1) = (((2 ^ (m + 1) : ℕ) : ℝ≥0∞))⁻¹ := by
      rw [← ENNReal.inv_pow]
      congr 1
      push_cast
      ring
    rw [hcast]
    exact ENNReal.inv_le_inv.2 (by exact_mod_cast hnat)
  -- The strict comparison is an `∃ t` statement about the approximations.
  have key : ∀ (c : ℕ) (x : BitString) (k s : ℕ),
      ((2 : ℝ≥0∞) ^ c * cantorMass μ x < dyadicValue k s
        ↔ ∃ t : ℕ, (2 : ℝ≥0∞) ^ c * dyadicValue (a x t + 1) t < dyadicValue k s) := by
    intro c x k s
    constructor
    · intro h
      have hPne : (2 : ℝ≥0∞) ^ c * cantorMass μ x ≠ ⊤ :=
        ENNReal.mul_ne_top (ENNReal.pow_ne_top (by norm_num)) (hmass_ne_top x)
      have hgap : dyadicValue k s - (2 : ℝ≥0∞) ^ c * cantorMass μ x ≠ 0 :=
        (tsub_pos_iff_lt.2 h).ne'
      obtain ⟨u, hu⟩ := hsmallpow _ hgap
      refine ⟨c + 1 + u, ?_⟩
      have hcancel : (2 : ℝ≥0∞) ^ (c + 1) * ((2 : ℝ≥0∞)⁻¹) ^ (c + 1 + u)
          = ((2 : ℝ≥0∞)⁻¹) ^ u := by
        rw [pow_add ((2 : ℝ≥0∞)⁻¹) (c + 1) u, ← mul_assoc, ← mul_pow,
          ENNReal.mul_inv_cancel (by norm_num) (by norm_num), one_pow, one_mul]
      calc (2 : ℝ≥0∞) ^ c * dyadicValue (a x (c + 1 + u) + 1) (c + 1 + u)
          ≤ (2 : ℝ≥0∞) ^ c
              * (cantorMass μ x + 2 * ((2 : ℝ≥0∞)⁻¹) ^ (c + 1 + u)) := by
            gcongr
            exact hlower x (c + 1 + u)
        _ = (2 : ℝ≥0∞) ^ c * cantorMass μ x
              + (2 : ℝ≥0∞) ^ (c + 1) * ((2 : ℝ≥0∞)⁻¹) ^ (c + 1 + u) := by
            rw [mul_add, pow_succ]
            ring
        _ = (2 : ℝ≥0∞) ^ c * cantorMass μ x + ((2 : ℝ≥0∞)⁻¹) ^ u := by rw [hcancel]
        _ < (2 : ℝ≥0∞) ^ c * cantorMass μ x
              + (dyadicValue k s - (2 : ℝ≥0∞) ^ c * cantorMass μ x) :=
            ENNReal.add_lt_add_left hPne hu
        _ = dyadicValue k s := add_tsub_cancel_of_le h.le
    · rintro ⟨t, ht⟩
      refine lt_of_le_of_lt ?_ ht
      gcongr
      exact hupper x t
  -- Comparing two dyadic rationals is a statement about natural numbers.
  have arith : ∀ c k s j t : ℕ,
      ((2 : ℝ≥0∞) ^ c * dyadicValue j t < dyadicValue k s ↔ 2 ^ c * j * 2 ^ s < k * 2 ^ t) := by
    intro c k s j t
    have h2t : ((2 : ℝ≥0∞) ^ t) ≠ 0 := by positivity
    have h2tt : ((2 : ℝ≥0∞) ^ t) ≠ ⊤ := ENNReal.pow_ne_top (by norm_num)
    have h2s : ((2 : ℝ≥0∞) ^ s) ≠ 0 := by positivity
    have h2st : ((2 : ℝ≥0∞) ^ s) ≠ ⊤ := ENNReal.pow_ne_top (by norm_num)
    rw [dyadicValue, dyadicValue, ← mul_div_assoc,
      ENNReal.div_lt_iff (Or.inl h2t) (Or.inl h2tt), div_eq_mul_inv, mul_right_comm,
      ← div_eq_mul_inv, ENNReal.lt_div_iff_mul_lt (Or.inl h2s) (Or.inl h2st),
      show ((2 : ℝ≥0∞) ^ c * (j : ℝ≥0∞) * 2 ^ s) = ((2 ^ c * j * 2 ^ s : ℕ) : ℝ≥0∞) by
        push_cast; ring,
      show ((k : ℝ≥0∞) * 2 ^ t) = ((k * 2 ^ t : ℕ) : ℝ≥0∞) by push_cast; ring]
    exact_mod_cast Iff.rfl
  refine (isRE_dyadicMatrix ha_comp).of_iff fun q => ?_
  rw [key q.1 q.2.1 q.2.2.1 q.2.2.2]
  constructor
  · rintro ⟨t, ht⟩
    exact ⟨t, (arith q.1 q.2.2.1 q.2.2.2 (a q.2.1 t + 1) t).2 ht⟩
  · rintro ⟨t, ht⟩
    exact ⟨t, (arith q.1 q.2.2.1 q.2.2.2 (a q.2.1 t + 1) t).1 ht⟩

/-- **Upper semicomputability of prefix complexity.** The prefix analogue of
`KMOf_isRE_lt` (SUV Theorem 85(b)): for a decompressor `U` the strict upper graph
`{(x, n) | K_U(x) < n}` is recursively enumerable.

*Estimated size*: about 25 lines. -/
theorem isRE_KPPlain_lt {U : Map} (hU : isDecompressor U) :
    IsRE fun q : BitString × ℕ => KPPlain U q.1 < (q.2 : ℕ∞) := by
  classical
  have hgraph : IsRE fun t : (BitString × ℕ) × BitString => t.1.1 ∈ U (t.2, []) := by
    have hmap : Computable fun t : (BitString × ℕ) × BitString =>
        ((t.2, ([] : BitString)), t.1.1) :=
      Computable.pair (Computable.pair Computable.snd (Computable.const []))
        (Computable.fst.comp Computable.fst)
    exact (Partrec.graphIsRe U hU).comp_computable hmap
  have hbool : Computable fun t : (BitString × ℕ) × BitString =>
      decide (t.2.length < t.1.2) := by
    refine Primrec.to_comp ?_
    exact PrimrecPred.decide (Primrec.nat_lt.comp
      (Primrec.list_length.comp Primrec.snd) (Primrec.snd.comp Primrec.fst))
  refine (IsRE.exists_encodable (R := fun (q : BitString × ℕ) (p : BitString) =>
    decide (p.length < q.2) = true ∧ q.1 ∈ U (p, []))
    (hgraph.and_computable hbool)).of_iff fun q => ?_
  rw [KPPlain, KP_eq_condK, condK, sInf_lt_iff]
  constructor
  · rintro ⟨p, hlen, hprod⟩
    refine ⟨((p.length : ℕ) : ℕ∞), ⟨p, hprod, rfl⟩, ?_⟩
    exact_mod_cast of_decide_eq_true hlen
  · rintro ⟨m, ⟨p, hprod, rfl⟩, hlt⟩
    refine ⟨p, ?_, hprod⟩
    exact decide_eq_true (by exact_mod_cast hlt)

/-- The `ℕ`-indexed reformulation used for `KM` and `K`: the weight `2^(-K(x))` exceeds a
value `v` exactly when some natural `n` with `K(x) < n + 1` already has `2^(-n) > v`.  This is
the bridge that turns *upper* semicomputability of a complexity into *lower* semicomputability
of its weight (SUV p. 146). -/
lemma lt_complexityWeight_iff_exists_nat {v : ℝ≥0∞} {K : ℕ∞} :
    v < complexityWeight K ↔ ∃ n : ℕ, K < ((n + 1 : ℕ) : ℕ∞) ∧ v < dyadicValue 1 n := by
  constructor
  · intro h
    have hne : K ≠ ⊤ := by
      intro htop
      rw [htop, complexityWeight_top] at h
      exact absurd h (not_lt.2 (zero_le))
    refine ⟨K.toNat, ?_, ?_⟩
    · conv_lhs => rw [← ENat.natCast_toNat hne]
      exact_mod_cast Nat.lt_succ_self _
    · rw [dyadicValue_one_eq_inv_two_pow', ← complexityWeight_coe, ENat.natCast_toNat hne]
      exact h
  · rintro ⟨n, hn, hlt⟩
    have hne : K ≠ ⊤ := ne_top_of_lt hn
    have hlt' : K.toNat < n + 1 := by
      rw [← ENat.natCast_toNat hne] at hn
      exact_mod_cast hn
    have hle : K ≤ (n : ℕ∞) := by
      conv_lhs => rw [← ENat.natCast_toNat hne]
      exact_mod_cast Nat.lt_succ_iff.1 hlt'
    calc v < dyadicValue 1 n := hlt
      _ = complexityWeight ((n : ℕ∞)) := by
          rw [dyadicValue_one_eq_inv_two_pow', complexityWeight_coe]
      _ ≤ complexityWeight K := complexityWeight_le_of_le hle

end Kolmogorov
