/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.Basic
import KolmogorovMathlib.MonotoneComplexity.EffectiveOpenBridge

/-!
# Lower semicomputability of `sup_{x ⊑ ω} m(x)/p(x)`

SUV Problem 147 (Section 5.6, p. 150) needs the supremum of the prefix ratios to be a lower
semicomputable function on Cantor space; the source's justification is the single clause
"lower semicomputability follows from that of `m` and computability of `μ`" (p. 150).

This module carries that out.  The point is that the superlevel set

`{ω : q < sup_{x ⊑ ω} m(x)/p(x)} = ⋃ {Ω_x : q < m(x)/p(x)}`

is generated by a set of *strings* that is enumerable uniformly in the rational threshold
`q`: the strict inequality `q · p(x) < m(x)` is witnessed at a finite stage of the lower
approximation of `m` and the upper approximation of `p`, and at that stage it is an
inequality between natural numbers,

`q.num · (a(x,s) + 1) < mApprox(s,x) · q.den`.

No convergence of quotients is ever needed, only the two monotone one-sided approximations.

## Main results

* `exists_computable_enum_cantorOpen_ratBitCode` — the rational-indexed analogue of
  `isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE`;
* `isLowerSemicomputableFun_prefixSupRatio` — the lemma.
-/

namespace Kolmogorov

open MeasureTheory Set

open scoped ENNReal

/-! ### Rational parameters carried as strings -/

/-- Left inverse of the shared coding `ratBitCode` of `SharedCoding.lean`. -/
def ratBitDecode (y : BitString) : ℚ := ratOfCode (bitStringToNat y)

/-- Decoding the bit encoding of a rational returns that rational. -/
@[simp] lemma ratBitDecode_ratBitCode (q : ℚ) : ratBitDecode (ratBitCode q) = q := by
  rw [ratBitDecode, ratBitCode, bitStringToNat_natToBitString, ratOfCode_ratCode]

/-- Decoding a bit-encoded rational is computable. -/
lemma computable_ratBitDecode : Computable ratBitDecode :=
  computable_ratOfCode.comp computable_bitStringToNat

/-! ### A rational-indexed effectively open family

Verbatim `isUniformlyEffectiveOpen_cantorOpen_natCode_of_isRE` with the index type `ℕ`
replaced by `ℚ` and `natCode` by `ratCode`; the output is exactly the enumeration data that
`IsLowerSemicomputableFun` asks for.
-/

/-- A recursively enumerable relation admits a computable enumeration of the cylinders generating
its
open set at each rational threshold. -/
theorem exists_computable_enum_cantorOpen_ratBitCode {R : BitString → BitString → Prop}
    (hR : IsRE fun t : BitString × BitString => R t.1 t.2) :
    ∃ enum : ℚ → ℕ → Option BitString, Computable (fun p : ℚ × ℕ => enum p.1 p.2) ∧
      ∀ q : ℚ, ⋃ i, (enum q i).elim ∅ cantorCylinder = cantorOpen R (ratBitCode q) := by
  rcases hR with ⟨f, hf, hfR⟩
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hf
  have hc' : ∀ p y, (c.eval (Encodable.encode (p, y))).Dom ↔ R p y := by
    intro p y
    have h_eq : c.eval (Encodable.encode (p, y)) = (f (p, y)).map Encodable.encode := by
      have hc_app : c.eval (Encodable.encode (p, y)) =
          (fun n => Part.bind (Encodable.decode n : Option (BitString × BitString))
            fun A => (f A).map Encodable.encode) (Encodable.encode (p, y)) := by
        rw [hc]
      rw [hc_app]
      simp
    rw [h_eq]
    simp [hfR]
  refine ⟨fun q i => cantorOpenREEnumerator c (ratBitCode q) i, ?_, fun q => ?_⟩
  · exact (computable_cantorOpenREEnumerator c).comp
      (computable_ratBitCode.comp Computable.fst) Computable.snd
  · rw [range_cantorOpenREEnumerator c (ratBitCode q)]
    have hReq : (fun p y => (c.eval (Encodable.encode (p, y))).Dom) = R := by
      ext p y
      exact hc' p y
    rw [hReq]

/-! ### The arithmetic bridge -/

/-- The integer comparison `q.num * B < A * q.den` expresses the inequality
`q * (B / 2 ^ s) < A / 2 ^ s` between dyadic values. -/
lemma natLt_iff_mul_dyadicValue_lt {q : ℚ} (hq : 0 ≤ q) (A B s : ℕ) :
    q.num.toNat * B < A * q.den ↔
      ENNReal.ofReal (q : ℝ) * dyadicValue B s < dyadicValue A s := by
  have hden : (0 : ℤ) < (q.den : ℤ) := by exact_mod_cast q.pos
  have hnum : (q.num.toNat : ℤ) = q.num := Int.toNat_of_nonneg (Rat.num_nonneg.mpr hq)
  have hstep1 : (q.num.toNat * B < A * q.den) ↔ ((q : ℝ) * (B : ℝ) < (A : ℝ)) := by
    rw [← Nat.cast_lt (α := ℤ)]
    push_cast
    rw [hnum]
    constructor
    · intro h
      have h' : (q.num : ℝ) * (B : ℝ) < (A : ℝ) * (q.den : ℝ) := by exact_mod_cast h
      have hd : (0 : ℝ) < (q.den : ℝ) := by exact_mod_cast q.pos
      have hqe : (q : ℝ) = (q.num : ℝ) / (q.den : ℝ) := by
        rw [Rat.cast_def]
      rw [hqe, div_mul_eq_mul_div, div_lt_iff₀ hd]
      exact h'
    · intro h
      have hd : (0 : ℝ) < (q.den : ℝ) := by exact_mod_cast q.pos
      have hqe : (q : ℝ) = (q.num : ℝ) / (q.den : ℝ) := by
        rw [Rat.cast_def]
      rw [hqe, div_mul_eq_mul_div, div_lt_iff₀ hd] at h
      exact_mod_cast h
  have hstep2 : ((q : ℝ) * (B : ℝ) < (A : ℝ)) ↔
      ENNReal.ofReal (q : ℝ) * (B : ℝ≥0∞) < (A : ℝ≥0∞) := by
    have hqr : (0 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
    have hmul : ENNReal.ofReal ((q : ℝ) * (B : ℝ))
        = ENNReal.ofReal (q : ℝ) * (B : ℝ≥0∞) := by
      rw [ENNReal.ofReal_mul hqr, ENNReal.ofReal_natCast]
    rcases Nat.eq_zero_or_pos A with hA | hA
    · subst hA
      simp only [Nat.cast_zero]
      constructor
      · intro h
        exact absurd h (not_lt.mpr (by positivity))
      · intro h
        exact absurd h (not_lt.mpr (zero_le))
    · have hApos : (0 : ℝ) < (A : ℝ) := by exact_mod_cast hA
      rw [← ENNReal.ofReal_lt_ofReal_iff hApos, hmul, ENNReal.ofReal_natCast]
  have hstep3 : (ENNReal.ofReal (q : ℝ) * (B : ℝ≥0∞) < (A : ℝ≥0∞)) ↔
      ENNReal.ofReal (q : ℝ) * dyadicValue B s < dyadicValue A s := by
    have hpow0 : ((2 : ℝ≥0∞) ^ s) ≠ 0 := by positivity
    have hpowt : ((2 : ℝ≥0∞) ^ s) ≠ ⊤ := ENNReal.pow_ne_top (by norm_num)
    rw [dyadicValue, dyadicValue, ← mul_div_assoc,
      ENNReal.lt_div_iff_mul_lt (Or.inl hpow0) (Or.inl hpowt),
      ENNReal.div_mul_cancel hpow0 hpowt]
  rw [hstep1, hstep2, hstep3]

/-! ### The stage characterisation of the strict inequality -/

/-- Some finite stage certifies the integer inequality exactly when `q` is below the ratio
`m p / μ⟦p⟧`. -/
lemma exists_stage_iff_ofReal_lt_ratio {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    {m : BitString → ℝ≥0∞} {mApprox : ℕ → BitString → BitString → ℕ}
    (hmono : ∀ s out ctx, dyadicValue (mApprox s out ctx) s
      ≤ dyadicValue (mApprox (s + 1) out ctx) (s + 1))
    (hsup : ∀ out ctx, ⨆ s, dyadicValue (mApprox s out ctx) s = m out)
    {q : ℚ} (hq : 0 ≤ q) (p : BitString) :
    (∃ s : ℕ, q.num.toNat * (a p s + 1) < mApprox s p [] * q.den) ↔
      ENNReal.ofReal (q : ℝ) < m p / cantorMass μ p := by
  have hQne : ENNReal.ofReal (q : ℝ) ≠ ⊤ := ENNReal.ofReal_ne_top
  have hPne : cantorMass μ p ≠ ⊤ := measure_ne_top μ _
  have hdiv : ENNReal.ofReal (q : ℝ) < m p / cantorMass μ p ↔
      ENNReal.ofReal (q : ℝ) * cantorMass μ p < m p :=
    ENNReal.lt_div_iff_mul_lt (Or.inr hQne) (Or.inl hPne)
  have hupper : ∀ s : ℕ, cantorMass μ p ≤ dyadicValue (a p s + 1) s := by
    intro s
    rw [dyadicValue_add]
    exact (ha p s).2
  have hAmono : Monotone fun s : ℕ => dyadicValue (mApprox s p []) s :=
    monotone_nat_of_le_succ fun s => hmono s p []
  have hAle : ∀ s : ℕ, dyadicValue (mApprox s p []) s ≤ m p := by
    intro s
    rw [← hsup p []]
    exact le_iSup (fun s => dyadicValue (mApprox s p []) s) s
  rw [hdiv]
  constructor
  · rintro ⟨s, hs⟩
    have hkey := (natLt_iff_mul_dyadicValue_lt hq (mApprox s p []) (a p s + 1) s).mp hs
    calc ENNReal.ofReal (q : ℝ) * cantorMass μ p
        ≤ ENNReal.ofReal (q : ℝ) * dyadicValue (a p s + 1) s := by gcongr; exact hupper s
      _ < dyadicValue (mApprox s p []) s := hkey
      _ ≤ m p := hAle s
  · intro hlt
    have hM : ENNReal.ofReal (q : ℝ) * cantorMass μ p
        < ⨆ s, dyadicValue (mApprox s p []) s := by rwa [hsup p []]
    obtain ⟨s₀, hs₀⟩ := lt_iSup_iff.mp hM
    have hinf : ⨅ t : ℕ, dyadicValue (a p (s₀ + t) + 1) (s₀ + t) = cantorMass μ p := by
      refine le_antisymm ?_ (le_iInf fun t => hupper (s₀ + t))
      refine ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_
      obtain ⟨u, hu⟩ := exists_inv_two_pow_lt (ε := ((ε : ℝ≥0∞))) (by simpa using hε.ne')
      refine le_trans (iInf_le _ (u + 1)) ?_
      have hs : u + 1 ≤ s₀ + (u + 1) := Nat.le_add_left _ _
      have hb : dyadicValue (a p (s₀ + (u + 1)) + 1) (s₀ + (u + 1))
          ≤ cantorMass μ p + (2 : ℝ≥0∞) * dyadicValue 1 (s₀ + (u + 1)) := by
        rw [dyadicValue_add]
        have h1 := (ha p (s₀ + (u + 1))).1
        have h2 : cantorMass μ p + (2 : ℝ≥0∞) * dyadicValue 1 (s₀ + (u + 1))
            = (cantorMass μ p + dyadicValue 1 (s₀ + (u + 1)))
              + dyadicValue 1 (s₀ + (u + 1)) := by ring
        rw [h2]
        exact add_le_add h1 le_rfl
      refine le_trans hb (add_le_add le_rfl ?_)
      have h2inv : (2 : ℝ≥0∞) * (2 : ℝ≥0∞)⁻¹ = 1 :=
        ENNReal.mul_inv_cancel (by norm_num) (by norm_num)
      have hd : (2 : ℝ≥0∞) * dyadicValue 1 (s₀ + (u + 1)) = (2 : ℝ≥0∞)⁻¹ ^ (s₀ + u) := by
        rw [dyadicValue_one_eq_inv_two_pow']
        rw [show s₀ + (u + 1) = (s₀ + u) + 1 by omega, pow_succ]
        rw [← mul_assoc, mul_comm (2 : ℝ≥0∞) ((2 : ℝ≥0∞)⁻¹ ^ (s₀ + u)), mul_assoc,
          h2inv, mul_one]
      rw [hd]
      refine le_trans ?_ hu.le
      have hsplit : ((2 : ℝ≥0∞)⁻¹) ^ (s₀ + u)
          = ((2 : ℝ≥0∞)⁻¹) ^ u * ((2 : ℝ≥0∞)⁻¹) ^ s₀ := by
        rw [← pow_add]
        congr 1
        omega
      calc ((2 : ℝ≥0∞)⁻¹) ^ (s₀ + u)
          = ((2 : ℝ≥0∞)⁻¹) ^ u * ((2 : ℝ≥0∞)⁻¹) ^ s₀ := hsplit
        _ ≤ ((2 : ℝ≥0∞)⁻¹) ^ u * 1 := by
            gcongr
            calc ((2 : ℝ≥0∞)⁻¹) ^ s₀ ≤ (1 : ℝ≥0∞) ^ s₀ := by gcongr; simp
              _ = 1 := one_pow _
        _ = ((2 : ℝ≥0∞)⁻¹) ^ u := mul_one _
    have hmulinf : ENNReal.ofReal (q : ℝ) * ⨅ t : ℕ, dyadicValue (a p (s₀ + t) + 1) (s₀ + t)
        = ⨅ t : ℕ, ENNReal.ofReal (q : ℝ) * dyadicValue (a p (s₀ + t) + 1) (s₀ + t) :=
      ENNReal.mul_iInf (fun h => absurd h hQne)
    rw [hinf] at hmulinf
    have hlt2 : (⨅ t : ℕ, ENNReal.ofReal (q : ℝ) * dyadicValue (a p (s₀ + t) + 1) (s₀ + t))
        < dyadicValue (mApprox s₀ p []) s₀ := by
      rw [← hmulinf]
      exact hs₀
    obtain ⟨t, ht⟩ := iInf_lt_iff.mp hlt2
    refine ⟨s₀ + t, ?_⟩
    refine (natLt_iff_mul_dyadicValue_lt hq (mApprox (s₀ + t) p []) (a p (s₀ + t) + 1)
      (s₀ + t)).mpr ?_
    exact lt_of_lt_of_le ht (hAmono (Nat.le_add_right s₀ t))

/-! ### The generating relation and its enumerability -/

/-- The strings generating the superlevel set `{ω : q < sup_{x ⊑ ω} m(x)/p(x)}`, with the
rational threshold `q` carried in the second argument through `ratBitCode`.  The first
disjunct makes the whole space appear at a negative threshold, as
`IsLowerSemicomputableFun` demands. -/
def prefixRatioRel (a : BitString → ℕ → ℕ) (mApprox : ℕ → BitString → BitString → ℕ)
    (p y : BitString) : Prop :=
  (ratBitDecode y < 0 ∧ p = []) ∨
    ∃ s : ℕ, (ratBitDecode y).num.toNat * (a p s + 1) < mApprox s p [] * (ratBitDecode y).den

/-- For computable approximations the relation certifying that the ratio exceeds a given rational is
recursively enumerable. -/
lemma isRE_prefixRatioRel {a : BitString → ℕ → ℕ} (ha : Computable₂ a)
    {mApprox : ℕ → BitString → BitString → ℕ}
    (hmc : Computable fun t : ℕ × BitString × BitString => mApprox t.1 t.2.1 t.2.2) :
    IsRE fun t : BitString × BitString => prefixRatioRel a mApprox t.1 t.2 := by
  classical
  have hmul : Computable₂ (fun u v : ℕ => u * v) := Primrec.nat_mul.to_comp
  have hlt : Computable₂ (fun u v : ℕ => decide (u < v)) := primrec_decide_nat_lt.to_comp
  have hqL : Computable fun t : BitString × BitString => ratBitDecode t.2 :=
    computable_ratBitDecode.comp Computable.snd
  have hneg : IsRE fun t : BitString × BitString => ratBitDecode t.2 < 0 ∧ t.1 = [] := by
    refine isRE_of_computable_bool _
      (fun t : BitString × BitString => decide (ratBitDecode t.2 < 0) && decide (t.1 = []))
      (fun _ => by simp) ?_
    have h1 : Computable fun t : BitString × BitString => decide (ratBitDecode t.2 < 0) :=
      computable₂_ratLt.comp hqL (Computable.const 0)
    have h2 : Computable fun t : BitString × BitString => decide (t.1 = []) :=
      Primrec.to_comp (PrimrecPred.decide (Primrec.eq.comp Primrec.fst (Primrec.const [])))
    exact Primrec.and.to_comp.comp h1 h2
  have hqR : Computable fun r : (BitString × BitString) × ℕ => ratBitDecode r.1.2 :=
    computable_ratBitDecode.comp (Computable.snd.comp Computable.fst)
  have hnum : Computable fun r : (BitString × BitString) × ℕ =>
      (ratBitDecode r.1.2).num.toNat :=
    ComputableReals.primrec_intToNat.to_comp.comp (computable_ratNum.comp hqR)
  have hden : Computable fun r : (BitString × BitString) × ℕ => (ratBitDecode r.1.2).den :=
    computable_ratDen.comp hqR
  have haS : Computable fun r : (BitString × BitString) × ℕ => a r.1.1 r.2 + 1 :=
    Primrec.succ.to_comp.comp (ha.comp (Computable.fst.comp Computable.fst) Computable.snd)
  have hmS : Computable fun r : (BitString × BitString) × ℕ => mApprox r.2 r.1.1 [] :=
    hmc.comp (Computable.pair Computable.snd
      (Computable.pair (Computable.fst.comp Computable.fst) (Computable.const [])))
  have hstage : IsRE fun r : (BitString × BitString) × ℕ =>
      (ratBitDecode r.1.2).num.toNat * (a r.1.1 r.2 + 1)
        < mApprox r.2 r.1.1 [] * (ratBitDecode r.1.2).den := by
    refine isRE_of_computable_bool _
      (fun r => decide ((ratBitDecode r.1.2).num.toNat * (a r.1.1 r.2 + 1)
        < mApprox r.2 r.1.1 [] * (ratBitDecode r.1.2).den))
      (fun _ => by rw [decide_eq_true_iff]) ?_
    exact hlt.comp (hmul.comp hnum haS) (hmul.comp hmS hden)
  have hex : IsRE fun t : BitString × BitString => ∃ s : ℕ,
      (ratBitDecode t.2).num.toNat * (a t.1 s + 1)
        < mApprox s t.1 [] * (ratBitDecode t.2).den :=
    IsRE.exists_encodable (R := fun (t : BitString × BitString) (s : ℕ) =>
      (ratBitDecode t.2).num.toNat * (a t.1 s + 1)
        < mApprox s t.1 [] * (ratBitDecode t.2).den) hstage
  exact (hneg.or hex).of_iff fun _ => Iff.rfl

/-! ### The superlevel sets -/

/-- The effective open set enumerated at the code of `q` consists of the sequences whose supremal
prefix ratio exceeds `q`, so that supremum is lower semicomputable. -/
lemma cantorOpen_prefixRatioRel {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    {m : BitString → ℝ≥0∞} {mApprox : ℕ → BitString → BitString → ℕ}
    (hmono : ∀ s out ctx, dyadicValue (mApprox s out ctx) s
      ≤ dyadicValue (mApprox (s + 1) out ctx) (s + 1))
    (hsup : ∀ out ctx, ⨆ s, dyadicValue (mApprox s out ctx) s = m out) (q : ℚ) :
    cantorOpen (prefixRatioRel a mApprox) (ratBitCode q)
      = {w : CantorSeq | (q : ℝ) < 0 ∨ ENNReal.ofReal (q : ℝ) < prefixSupRatio m μ w} := by
  rcases lt_or_ge q 0 with hq | hq
  · have hqr : (q : ℝ) < 0 := by exact_mod_cast hq
    have hall : {w : CantorSeq |
        (q : ℝ) < 0 ∨ ENNReal.ofReal (q : ℝ) < prefixSupRatio m μ w} = Set.univ := by
      ext w
      simp [hqr]
    rw [hall]
    refine Set.eq_univ_of_subset ?_ cantorCylinder_nil
    refine Set.subset_iUnion_of_subset ([] : BitString) ?_
    refine Set.subset_iUnion_of_subset ?_ (le_refl _)
    exact Or.inl ⟨by rwa [ratBitDecode_ratBitCode], rfl⟩
  · have hqr : ¬ ((q : ℝ) < 0) := by
      push Not
      exact_mod_cast hq
    have hmem : ∀ p : BitString, prefixRatioRel a mApprox p (ratBitCode q)
        ↔ ENNReal.ofReal (q : ℝ) < m p / cantorMass μ p := by
      intro p
      rw [prefixRatioRel, ratBitDecode_ratBitCode]
      rw [or_iff_right (by rintro ⟨h, -⟩; exact absurd h (not_lt.mpr hq))]
      exact exists_stage_iff_ofReal_lt_ratio ha hmono hsup hq p
    have hset : {w : CantorSeq |
          (q : ℝ) < 0 ∨ ENNReal.ofReal (q : ℝ) < prefixSupRatio m μ w}
        = prefixHitSet {p : BitString | ENNReal.ofReal (q : ℝ) < m p / cantorMass μ p} := by
      ext w
      simp only [Set.mem_ofPred_eq, hqr, false_or, prefixHitSet, prefixSupRatio, lt_iSup_iff]
    rw [hset, prefixHitSet_eq_iUnion_cantorCylinder, cantorOpen]
    exact Set.iUnion_congr fun p => by rw [hmem p]; rfl

/-! ### The lemma -/

/-- **SUV Problem 147 (Section 5.6, p. 150)**: the function `ω ↦ sup_{x ⊑ ω} m(x)/p(x)` is
lower semicomputable, for any lower semicomputable semimeasure `m` and computable `μ`. -/
theorem isLowerSemicomputableFun_prefixSupRatio_of_lsc {μ : Measure CantorSeq}
    [IsFiniteMeasure μ] (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞}
    (hm : IsLowerSemicomputableSemimeasure m) :
    IsLowerSemicomputableFun (prefixSupRatio m μ) := by
  obtain ⟨a, ha, hab⟩ := hμ
  obtain ⟨mApprox, hmono, hsup, hmc⟩ := hm.2
  obtain ⟨enum, henum, heq⟩ :=
    exists_computable_enum_cantorOpen_ratBitCode (isRE_prefixRatioRel ha hmc)
  refine ⟨enum, henum, fun q => ?_⟩
  rw [heq q]
  exact (cantorOpen_prefixRatioRel hab hmono hsup q).symm

/-- SUV Problem 147 (Section 5.6, p. 150), the form used by
`problem_147_isExpectationBoundedRandomnessTest_prefixSupRatio`. -/
theorem isLowerSemicomputableFun_prefixSupRatio {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞} (hm : IsUniversalSemimeasure m) :
    IsLowerSemicomputableFun (prefixSupRatio m μ) :=
  isLowerSemicomputableFun_prefixSupRatio_of_lsc hμ hm.1

end Kolmogorov
