/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.PrefixRatioLSC

/-!
# Lower semicomputability of `∑_{x ⊑ ω} m(x)/p(x)`

SUV Problem 146 (Section 5.6, p. 150), the semicomputability half: "lower semicomputability
follows from that of `m` and computability of `μ`".

The argument is the one of `LevinSchnorr/PrefixRatioLSC.lean`, with one extra idea.  The
superlevel set is again generated by a set of strings,

`{ω : q < ∑_{x ⊑ ω} m(x)/p(x)} = ⋃ {Ω_x : q < ∑_{i ≤ |x|} m(x↾i)/p(x↾i)}`,

and the finite sum is again approximated from below at finite stages.  The extra idea is that
the stages are chosen **independently for each `i`**: the witness is a `List ℕ` of stages, one
per prefix.  That removes any need for the stage approximations to be monotone or to be
compared at a *common* stage, which is what makes the sum harder than the supremum: the
`∑`/`⨆` interchange becomes the elementary `sum_iSup_eq_iSup_sum` below.

At a fixed list of stages the value is an explicit *rational* number (a sum of quotients of
natural numbers), so the comparison with the threshold is decidable, with no common
denominator ever formed.

## Main results

* `sum_iSup_eq_iSup_sum` — a finite sum of suprema is the supremum over tuples of stages;
* `iSup_ofReal_natRatDiv_eq` — the stage quotients converge to `m(x)/p(x)`;
* `isLowerSemicomputableFun_prefixSumRatio_of_lsc` — the lemma.
-/

namespace Kolmogorov

open MeasureTheory Set

open scoped ENNReal NNReal

/-! ### Rational stage values -/

/-- `A / (B + 1)` as a rational.  The shift keeps the denominator positive; it is used with
`B = a(x, s)`, so that the denominator is the upper approximation `a(x, s) + 1` of the
cylinder mass. -/
def natRatDiv (A B : ℕ) : ℚ := (A : ℚ) / ((B + 1 : ℕ) : ℚ)

/-- The rational quotient `A / (B + 1)` used to approximate ratios of masses is nonnegative. -/
lemma natRatDiv_nonneg (A B : ℕ) : (0 : ℚ) ≤ natRatDiv A B := by
  rw [natRatDiv]
  positivity

/-- The rational quotient `A / (B + 1)` is computable in both numerator and denominator. -/
lemma computable₂_natRatDiv : Computable₂ natRatDiv :=
  computable_of_num_den (f := fun p : ℕ × ℕ => natRatDiv p.1 p.2)
    (N := fun p : ℕ × ℕ => (p.1 : ℤ)) (D := fun p : ℕ × ℕ => p.2 + 1)
    (ComputableReals.primrec_natCastInt.to_comp.comp Computable.fst)
    (Primrec.succ.to_comp.comp Computable.snd)
    (fun _ => Nat.succ_pos _) (fun _ => by simp only [natRatDiv]; push_cast; ring)

/-- The extended-real value of the rational quotient `A / (B + 1)` is the quotient of the casts. -/
lemma ofReal_natRatDiv (A B : ℕ) :
    ENNReal.ofReal ((natRatDiv A B : ℚ) : ℝ) = (A : ℝ≥0∞) / ((B + 1 : ℕ) : ℝ≥0∞) := by
  have hcast : ((natRatDiv A B : ℚ) : ℝ) = (A : ℝ) / ((B + 1 : ℕ) : ℝ) := by
    rw [natRatDiv]
    push_cast
    ring
  have hpos : (0 : ℝ) < ((B + 1 : ℕ) : ℝ) := by positivity
  rw [hcast, ENNReal.ofReal_div_of_pos hpos, ENNReal.ofReal_natCast, ENNReal.ofReal_natCast]

/-- The ratio of two dyadic values at the same scale is the ratio of their numerators. -/
lemma dyadicValue_div_dyadicValue (A B s : ℕ) :
    dyadicValue A s / dyadicValue B s = (A : ℝ≥0∞) / (B : ℝ≥0∞) := by
  have h0 : ((2 : ℝ≥0∞) ^ s)⁻¹ ≠ 0 := by
    simp
  have ht : ((2 : ℝ≥0∞) ^ s)⁻¹ ≠ ⊤ := by
    simp
  rw [dyadicValue, dyadicValue, div_eq_mul_inv ((A : ℝ≥0∞)), div_eq_mul_inv ((B : ℝ≥0∞)),
    ENNReal.mul_div_mul_right _ _ h0 ht]

/-! ### A finite sum of suprema is a supremum over tuples of stages -/

/-- A finite sum of suprema of `ℝ≥0∞`-valued families equals the supremum over the choices of one
stage per summand. -/
lemma sum_iSup_eq_iSup_sum (g : ℕ → ℕ → ℝ≥0∞) (n : ℕ) :
    ∑ i ∈ Finset.range n, (⨆ s : ℕ, g i s)
      = ⨆ S : ℕ → ℕ, ∑ i ∈ Finset.range n, g i (S i) := by
  classical
  induction n with
  | zero => simp
  | succ k ih =>
    rw [Finset.sum_range_succ, ih, ENNReal.iSup_add]
    simp only [ENNReal.add_iSup]
    refine le_antisymm (iSup_le fun S => iSup_le fun s => ?_) (iSup_le fun S => ?_)
    · refine le_iSup_of_le (Function.update S k s) ?_
      rw [Finset.sum_range_succ, Function.update_self]
      refine add_le_add (le_of_eq (Finset.sum_congr rfl fun i hi => ?_)) le_rfl
      rw [Function.update_of_ne (Finset.mem_range.mp hi).ne]
    · refine le_iSup_of_le S (le_iSup_of_le (S k) ?_)
      rw [Finset.sum_range_succ]

/-! ### The stage quotients converge to `m(x)/p(x)` -/

/-- Every stage of the rational approximation stays below the true ratio `m y / μ⟦y⟧`. -/
lemma ofReal_natRatDiv_le {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    {m : BitString → ℝ≥0∞} {mApprox : ℕ → BitString → BitString → ℕ}
    (hsup : ∀ out ctx, ⨆ s, dyadicValue (mApprox s out ctx) s = m out) (y : BitString)
    (s : ℕ) :
    ENNReal.ofReal ((natRatDiv (mApprox s y []) (a y s) : ℚ) : ℝ)
      ≤ m y / cantorMass μ y := by
  rw [ofReal_natRatDiv, ← dyadicValue_div_dyadicValue _ _ s]
  refine ENNReal.div_le_div ?_ ?_
  · rw [← hsup y []]
    exact le_iSup (fun s => dyadicValue (mApprox s y []) s) s
  · rw [dyadicValue_add]
    exact (ha y s).2

/-- The stages of the rational approximation converge upward to the ratio `m y / μ⟦y⟧`. -/
lemma iSup_ofReal_natRatDiv_eq {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    {m : BitString → ℝ≥0∞} {mApprox : ℕ → BitString → BitString → ℕ}
    (hmono : ∀ s out ctx, dyadicValue (mApprox s out ctx) s
      ≤ dyadicValue (mApprox (s + 1) out ctx) (s + 1))
    (hsup : ∀ out ctx, ⨆ s, dyadicValue (mApprox s out ctx) s = m out) (y : BitString) :
    (⨆ s : ℕ, ENNReal.ofReal ((natRatDiv (mApprox s y []) (a y s) : ℚ) : ℝ))
      = m y / cantorMass μ y := by
  refine le_antisymm (iSup_le fun s => ofReal_natRatDiv_le ha hsup y s) ?_
  by_contra hcon
  rw [not_le] at hcon
  obtain ⟨q, hq0, hq1, hq2⟩ := ENNReal.lt_iff_exists_rat_btwn.mp hcon
  have hqe : ((Real.toNNReal (q : ℝ) : NNReal) : ℝ≥0∞) = ENNReal.ofReal (q : ℝ) := rfl
  rw [hqe] at hq1 hq2
  obtain ⟨s, hs⟩ := (exists_stage_iff_ofReal_lt_ratio ha hmono hsup hq0 y).mpr hq2
  have hkey := (natLt_iff_mul_dyadicValue_lt hq0 (mApprox s y []) (a y s + 1) s).mp hs
  have hBpos : dyadicValue (a y s + 1) s ≠ 0 := by
    rw [dyadicValue, Ne, ENNReal.div_eq_zero_iff]
    rw [not_or]
    exact ⟨by exact_mod_cast Nat.succ_ne_zero (a y s), ENNReal.pow_ne_top (by norm_num)⟩
  have hBtop : dyadicValue (a y s + 1) s ≠ ⊤ := dyadicValue_ne_top _ s
  have hlt : ENNReal.ofReal (q : ℝ)
      < dyadicValue (mApprox s y []) s / dyadicValue (a y s + 1) s :=
    (ENNReal.lt_div_iff_mul_lt (Or.inl hBpos) (Or.inl hBtop)).mpr hkey
  rw [dyadicValue_div_dyadicValue] at hlt
  have hle : ENNReal.ofReal ((natRatDiv (mApprox s y []) (a y s) : ℚ) : ℝ)
      ≤ ⨆ t : ℕ, ENNReal.ofReal ((natRatDiv (mApprox t y []) (a y t) : ℚ) : ℝ) :=
    le_iSup (fun t => ENNReal.ofReal ((natRatDiv (mApprox t y []) (a y t) : ℚ) : ℝ)) s
  rw [ofReal_natRatDiv] at hle
  exact absurd (lt_of_lt_of_le hlt hle) (not_lt.mpr hq1.le)

/-! ### The stage value of a finite prefix chain -/

/-- The ample-excess partial sum of `x` evaluated at the list of stages `S`: one stage per
prefix of `x`, chosen independently.  This is an explicit rational number. -/
def sumStage (a : BitString → ℕ → ℕ) (mApprox : ℕ → BitString → BitString → ℕ)
    (x : BitString) (S : List ℕ) : ℚ :=
  ∑ i ∈ Finset.range (x.length + 1),
    natRatDiv (mApprox (S.getD i 0) (x.take i) []) (a (x.take i) (S.getD i 0))

/-- The accumulator recursion that adds `f y` at each step computes the partial sum over
`Finset.range n`. -/
lemma natRec_sum_range_monoid {M : Type*} [AddCommMonoid M] (f : ℕ → M) (n : ℕ) :
    Nat.rec (motive := fun _ => M) 0 (fun y IH => IH + f y) n = ∑ i ∈ Finset.range n, f i := by
  induction n with
  | zero => simp
  | succ k ih => rw [Finset.sum_range_succ, ← ih]

/-- The staged rational partial sum along the prefixes of `x` is computable in `x` and the list of
stages. -/
lemma computable₂_sumStage {a : BitString → ℕ → ℕ} (ha : Computable₂ a)
    {mApprox : ℕ → BitString → BitString → ℕ}
    (hmc : Computable fun t : ℕ × BitString × BitString => mApprox t.1 t.2.1 t.2.2) :
    Computable₂ (sumStage a mApprox) := by
  have hlen : Computable (fun p : BitString × List ℕ => p.1.length + 1) :=
    Primrec.succ.to_comp.comp (Computable.list_length.comp Computable.fst)
  have hidx : Computable (fun w : (BitString × List ℕ) × (ℕ × ℚ) => w.2.1) :=
    Computable.fst.comp Computable.snd
  have hS : Computable (fun w : (BitString × List ℕ) × (ℕ × ℚ) => w.1.2.getD w.2.1 0) :=
    (Primrec.list_getD 0).to_comp.comp (Computable.snd.comp Computable.fst) hidx
  have htake : Computable (fun w : (BitString × List ℕ) × (ℕ × ℚ) => w.1.1.take w.2.1) :=
    Primrec.list_take.to_comp.comp hidx (Computable.fst.comp Computable.fst)
  have haval : Computable (fun w : (BitString × List ℕ) × (ℕ × ℚ) =>
      a (w.1.1.take w.2.1) (w.1.2.getD w.2.1 0)) := ha.comp htake hS
  have hmval : Computable (fun w : (BitString × List ℕ) × (ℕ × ℚ) =>
      mApprox (w.1.2.getD w.2.1 0) (w.1.1.take w.2.1) []) :=
    hmc.comp (Computable.pair hS (Computable.pair htake (Computable.const [])))
  have hterm : Computable (fun w : (BitString × List ℕ) × (ℕ × ℚ) =>
      natRatDiv (mApprox (w.1.2.getD w.2.1 0) (w.1.1.take w.2.1) [])
        (a (w.1.1.take w.2.1) (w.1.2.getD w.2.1 0))) :=
    computable₂_natRatDiv.comp hmval haval
  have hh : Computable₂ (fun (p : BitString × List ℕ) (r : ℕ × ℚ) =>
      r.2 + natRatDiv (mApprox (p.2.getD r.1 0) (p.1.take r.1) [])
        (a (p.1.take r.1) (p.2.getD r.1 0))) :=
    (computable₂_ratAdd.comp (Computable.snd.comp Computable.snd) hterm).to₂
  refine (Computable.nat_rec (σ := ℚ) hlen (Computable.const 0) hh).of_eq ?_
  rintro ⟨x, S⟩
  exact natRec_sum_range_monoid
    (fun i => natRatDiv (mApprox (S.getD i 0) (x.take i) []) (a (x.take i) (S.getD i 0)))
    (x.length + 1)

/-- The partial sum `∑_{i ≤ |x|} m(x↾i)/p(x↾i)` of the prefix ratios along `x`. -/
noncomputable def ratioPartial (m : BitString → ℝ≥0∞) (μ : Measure CantorSeq) (x : BitString) :
    ℝ≥0∞ :=
  ∑ i ∈ Finset.range (x.length + 1), m (x.take i) / cantorMass μ (x.take i)

/-- The staged rational partial sum is the sum of the stage-wise ratio approximations over all
prefixes of `x`. -/
lemma ofReal_sumStage (a : BitString → ℕ → ℕ) (mApprox : ℕ → BitString → BitString → ℕ)
    (x : BitString) (S : List ℕ) :
    ENNReal.ofReal ((sumStage a mApprox x S : ℚ) : ℝ)
      = ∑ i ∈ Finset.range (x.length + 1),
          ENNReal.ofReal
            ((natRatDiv (mApprox (S.getD i 0) (x.take i) []) (a (x.take i) (S.getD i 0)) :
              ℚ) : ℝ) := by
  have hcast : ((sumStage a mApprox x S : ℚ) : ℝ)
      = ∑ i ∈ Finset.range (x.length + 1),
          ((natRatDiv (mApprox (S.getD i 0) (x.take i) []) (a (x.take i) (S.getD i 0)) :
            ℚ) : ℝ) := by
    rw [sumStage]
    push_cast
    ring
  rw [hcast, ENNReal.ofReal_sum_of_nonneg]
  exact fun i _ => by exact_mod_cast natRatDiv_nonneg _ _

/-- Some choice of stages makes the rational partial sum exceed `q` exactly when `q` is below the
true partial ratio sum over the prefixes of `x`. -/
lemma exists_list_iff_ofReal_lt_ratioPartial {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    {m : BitString → ℝ≥0∞} {mApprox : ℕ → BitString → BitString → ℕ}
    (hmono : ∀ s out ctx, dyadicValue (mApprox s out ctx) s
      ≤ dyadicValue (mApprox (s + 1) out ctx) (s + 1))
    (hsup : ∀ out ctx, ⨆ s, dyadicValue (mApprox s out ctx) s = m out)
    {q : ℚ} (hq : 0 ≤ q) (x : BitString) :
    (∃ S : List ℕ, q < sumStage a mApprox x S) ↔
      ENNReal.ofReal (q : ℝ) < ratioPartial m μ x := by
  have hqr : (0 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hq
  constructor
  · rintro ⟨S, hS⟩
    have h1 : ENNReal.ofReal (q : ℝ)
        < ENNReal.ofReal ((sumStage a mApprox x S : ℚ) : ℝ) := by
      rw [ENNReal.ofReal_lt_ofReal_iff_of_nonneg hqr]
      exact_mod_cast hS
    refine lt_of_lt_of_le h1 ?_
    rw [ofReal_sumStage, ratioPartial]
    exact Finset.sum_le_sum fun i _ => ofReal_natRatDiv_le ha hsup _ _
  · intro h
    rw [ratioPartial,
      Finset.sum_congr rfl (fun i _ => (iSup_ofReal_natRatDiv_eq ha hmono hsup (x.take i)).symm),
      sum_iSup_eq_iSup_sum] at h
    obtain ⟨S, hS⟩ := lt_iSup_iff.mp h
    refine ⟨(List.range (x.length + 1)).map S, ?_⟩
    have hget : ∀ i ∈ Finset.range (x.length + 1),
        ((List.range (x.length + 1)).map S).getD i 0 = S i := by
      intro i hi
      rw [List.getD_eq_getElem?_getD, List.getElem?_map,
        List.getElem?_range (Finset.mem_range.mp hi)]
      rfl
    have hgoal : ((q : ℚ) : ℝ)
        < ((sumStage a mApprox x ((List.range (x.length + 1)).map S) : ℚ) : ℝ) := by
      rw [← ENNReal.ofReal_lt_ofReal_iff_of_nonneg hqr, ofReal_sumStage]
      refine lt_of_lt_of_le hS (le_of_eq (Finset.sum_congr rfl fun i hi => ?_))
      rw [hget i hi]
    exact_mod_cast hgoal

/-! ### The generating relation -/

/-- The strings generating the superlevel set `{ω : q < ∑_{x ⊑ ω} m(x)/p(x)}`, with the
rational threshold carried in the second argument through `ratBitCode`. -/
def prefixSumRel (a : BitString → ℕ → ℕ) (mApprox : ℕ → BitString → BitString → ℕ)
    (p y : BitString) : Prop :=
  (ratBitDecode y < 0 ∧ p = []) ∨ ∃ S : List ℕ, ratBitDecode y < sumStage a mApprox p S

/-- For computable approximations the relation "`x` witnesses that the partial ratio sum exceeds the
rational coded by the first argument" is recursively enumerable. -/
lemma isRE_prefixSumRel {a : BitString → ℕ → ℕ} (ha : Computable₂ a)
    {mApprox : ℕ → BitString → BitString → ℕ}
    (hmc : Computable fun t : ℕ × BitString × BitString => mApprox t.1 t.2.1 t.2.2) :
    IsRE fun t : BitString × BitString => prefixSumRel a mApprox t.1 t.2 := by
  classical
  have hqL : Computable fun t : BitString × BitString => ratBitDecode t.2 :=
    computable_ratBitDecode.comp Computable.snd
  have hneg : IsRE fun t : BitString × BitString => ratBitDecode t.2 < 0 ∧ t.1 = [] := by
    refine isRE_of_computable_bool _
      (fun t : BitString × BitString => decide (ratBitDecode t.2 < 0) && decide (t.1 = []))
      (fun _ => by simp) ?_
    have h1 : Computable fun t : BitString × BitString => decide (ratBitDecode t.2 < 0) :=
      computable₂_ratLt.comp hqL (Computable.const 0)
    have h2 : Computable fun t : BitString × BitString => decide (t.1 = []) :=
      Primrec.to_comp (PrimrecPred.decide (Primrec.eq.comp Primrec.fst (Primrec.const [])))
    exact Primrec.and.to_comp.comp h1 h2
  have hqR : Computable fun r : (BitString × BitString) × List ℕ => ratBitDecode r.1.2 :=
    computable_ratBitDecode.comp (Computable.snd.comp Computable.fst)
  have hval : Computable fun r : (BitString × BitString) × List ℕ =>
      sumStage a mApprox r.1.1 r.2 :=
    (computable₂_sumStage ha hmc).comp (Computable.fst.comp Computable.fst) Computable.snd
  have hstage : IsRE fun r : (BitString × BitString) × List ℕ =>
      ratBitDecode r.1.2 < sumStage a mApprox r.1.1 r.2 := by
    refine isRE_of_computable_bool _
      (fun r => decide (ratBitDecode r.1.2 < sumStage a mApprox r.1.1 r.2))
      (fun _ => by rw [decide_eq_true_iff]) ?_
    exact computable₂_ratLt.comp hqR hval
  have hex : IsRE fun t : BitString × BitString =>
      ∃ S : List ℕ, ratBitDecode t.2 < sumStage a mApprox t.1 S :=
    IsRE.exists_encodable (R := fun (t : BitString × BitString) (S : List ℕ) =>
      ratBitDecode t.2 < sumStage a mApprox t.1 S) hstage
  exact (hneg.or hex).of_iff fun _ => Iff.rfl

/-! ### The superlevel sets -/

/-- Along the prefixes of a sequence the partial ratio sum is the sum of `m / μ` over all prefixes
up
to length `n`. -/
lemma ratioPartial_cantorPrefix (m : BitString → ℝ≥0∞) (μ : Measure CantorSeq) (w : CantorSeq)
    (n : ℕ) :
    ratioPartial m μ (cantorPrefix w n)
      = ∑ i ∈ Finset.range (n + 1),
          m (cantorPrefix w i) / cantorMass μ (cantorPrefix w i) := by
  rw [ratioPartial, cantorPrefix_length]
  refine Finset.sum_congr rfl fun i hi => ?_
  rw [_root_.cantorPrefix_take w i n (Nat.lt_succ_iff.mp (Finset.mem_range.mp hi))]

/-- A sequence has a prefix at which the partial ratio sum exceeds `v` exactly when its total ratio
sum exceeds `v`. -/
lemma prefixHitSet_ratioPartial (m : BitString → ℝ≥0∞) (μ : Measure CantorSeq) (v : ℝ≥0∞) :
    prefixHitSet {x : BitString | v < ratioPartial m μ x}
      = {w : CantorSeq | v < prefixSumRatio m μ w} := by
  ext w
  simp only [prefixHitSet, Set.mem_ofPred_eq, prefixSumRatio, ENNReal.tsum_eq_iSup_nat,
    lt_iSup_iff]
  constructor
  · rintro ⟨n, hn⟩
    rw [ratioPartial_cantorPrefix] at hn
    exact ⟨n + 1, hn⟩
  · rintro ⟨N, hN⟩
    rcases Nat.eq_zero_or_pos N with rfl | hNpos
    · simp at hN
    · refine ⟨N - 1, ?_⟩
      rw [ratioPartial_cantorPrefix, show N - 1 + 1 = N by omega]
      exact hN

/-- The effective open set enumerated at the code of `q` is the set of sequences whose prefix ratio
sum exceeds `q` (all sequences when `q` is negative), so the prefix ratio sum is lower
semicomputable. -/
lemma cantorOpen_prefixSumRel {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    {m : BitString → ℝ≥0∞} {mApprox : ℕ → BitString → BitString → ℕ}
    (hmono : ∀ s out ctx, dyadicValue (mApprox s out ctx) s
      ≤ dyadicValue (mApprox (s + 1) out ctx) (s + 1))
    (hsup : ∀ out ctx, ⨆ s, dyadicValue (mApprox s out ctx) s = m out) (q : ℚ) :
    cantorOpen (prefixSumRel a mApprox) (ratBitCode q)
      = {w : CantorSeq | (q : ℝ) < 0 ∨ ENNReal.ofReal (q : ℝ) < prefixSumRatio m μ w} := by
  rcases lt_or_ge q 0 with hq | hq
  · have hqr : (q : ℝ) < 0 := by exact_mod_cast hq
    have hall : {w : CantorSeq |
        (q : ℝ) < 0 ∨ ENNReal.ofReal (q : ℝ) < prefixSumRatio m μ w} = Set.univ := by
      ext w
      simp [hqr]
    rw [hall]
    refine Set.eq_univ_of_subset ?_ cantorCylinder_nil
    refine Set.subset_iUnion_of_subset ([] : BitString) ?_
    refine Set.subset_iUnion_of_subset ?_ (le_refl _)
    exact Or.inl ⟨by rwa [ratBitDecode_ratBitCode], rfl⟩
  · have hqr : ¬ ((q : ℝ) < 0) := by
      rw [not_lt]
      exact_mod_cast hq
    have hmem : ∀ p : BitString, prefixSumRel a mApprox p (ratBitCode q)
        ↔ ENNReal.ofReal (q : ℝ) < ratioPartial m μ p := by
      intro p
      rw [prefixSumRel, ratBitDecode_ratBitCode]
      rw [or_iff_right (by rintro ⟨h, -⟩; exact absurd h (not_lt.mpr hq))]
      exact exists_list_iff_ofReal_lt_ratioPartial ha hmono hsup hq p
    have hset : {w : CantorSeq |
          (q : ℝ) < 0 ∨ ENNReal.ofReal (q : ℝ) < prefixSumRatio m μ w}
        = prefixHitSet {x : BitString | ENNReal.ofReal (q : ℝ) < ratioPartial m μ x} := by
      rw [prefixHitSet_ratioPartial]
      ext w
      simp only [Set.mem_ofPred_eq, hqr, false_or]
    rw [hset, prefixHitSet_eq_iUnion_cantorCylinder, cantorOpen]
    exact Set.iUnion_congr fun p => by rw [hmem p]; rfl

/-! ### The lemma -/

/-- **SUV Problem 146 (Section 5.6, p. 150)**: the function `ω ↦ ∑_{x ⊑ ω} m(x)/p(x)` is
lower semicomputable, for any lower semicomputable semimeasure `m` and computable `μ`. -/
theorem isLowerSemicomputableFun_prefixSumRatio_of_lsc {μ : Measure CantorSeq}
    [IsFiniteMeasure μ] (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞}
    (hm : IsLowerSemicomputableSemimeasure m) :
    IsLowerSemicomputableFun (prefixSumRatio m μ) := by
  obtain ⟨a, ha, hab⟩ := hμ
  obtain ⟨mApprox, hmono, hsup, hmc⟩ := hm.2
  obtain ⟨enum, henum, heq⟩ :=
    exists_computable_enum_cantorOpen_ratBitCode (isRE_prefixSumRel ha hmc)
  refine ⟨enum, henum, fun q => ?_⟩
  rw [heq q]
  exact (cantorOpen_prefixSumRel hab hmono hsup q).symm

/-- SUV Problem 146 (Section 5.6, p. 150), the form used by
`problem_146_isExpectationBoundedRandomnessTest_prefixSumRatio`. -/
theorem isLowerSemicomputableFun_prefixSumRatio {μ : Measure CantorSeq} [IsFiniteMeasure μ]
    (hμ : IsComputableMeasure μ) {m : BitString → ℝ≥0∞} (hm : IsUniversalSemimeasure m) :
    IsLowerSemicomputableFun (prefixSumRatio m μ) :=
  isLowerSemicomputableFun_prefixSumRatio_of_lsc hμ hm.1

end Kolmogorov
