import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.MixedFamilyRun
import KolmogorovMathlib.Restricted.FamilyCurve

/-!
# Mixed-family version decoding

The mixed anchored executor rebuilds models in a good family `𝒢`, while its
event stream enumerates forbidden descriptions from a possibly larger family
`ℬ`.  This file gives the corresponding fixed-family version decoder.  Both
families are fixed parameters of the partial-recursive procedure, so no family
data is encoded at run time.
-/

namespace Kolmogorov

open Nat.Partrec (Code)

private lemma exists_codeFor_map (U : Map)
    (hU : IsOptimalPrefixConditional U) :
    ∃ c : Code, IsCodeFor c U :=
  Nat.Partrec.Code.exists_code.mp hU.isDecompressor

/- Keep the large product encodings and code-level executor components opaque
during the partial-recursiveness compositions. -/
attribute [local irreducible] Primcodable.prod Primcodable.list
attribute [local irreducible]
  restrictedEffectiveLiveCodesAfterDelete
  restrictedEffectiveDeleteCode
  restrictedSelectorField
  restrictedEffectiveDensityFailsBool
  restrictedEffectiveFirstFailedScale
  restrictedDecodedCoverCard
  restrictedEffectiveSampledRunStepPost
  restrictedEffectiveSampledStateCode
  restrictedEffectiveSampledRunStepInput
  restrictedEffectiveRebuildSuffixInput
  restrictedEffectiveSampledRunStep
  restrictedAnchoredInitialFromCode
  restrictedAnchoredSizesFromCode
  restrictedSampledBadCodeStream
  restrictedSampledBadCodesUpToTime
  restrictedSampledBadCodesRaw
  anchoredDecodedSteps
  anchoredDecodedSlack
  anchoredDecodedAmbientLength
  anchoredDecodedLength
  anchoredModelListAt

/-- Event-indexed decoder trace for a `𝒢` rebuild driven by the `ℬ` bad
stream. -/
noncomputable def anchoredDecoderTraceAgainst
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 m : ℕ) : Part BitString :=
  let Nst := anchoredDecodedSteps gridCode
  let Δ := anchoredDecodedSlack gridCode
  let amb := anchoredDecodedAmbientLength gridCode
  (Nat.rfind (fun τ => Part.some (decide (m ≤
      (restrictedSampledBadCodeStream c gridCode ℬ.toPre Nst Δ
        τ).length)))).bind
    (fun τ => (restrictedAnchoredInitialFromCode 𝒢 q0 gridCode Nst Δ
        amb).bind
      (fun st0 => restrictedEventPrefixRun 𝒢 q0
        (restrictedAnchoredSizesFromCode gridCode Nst Δ amb) st0
        (restrictedSampledBadCodeStream c gridCode ℬ.toPre Nst Δ τ) m))

/-- Change-counting trace for the mixed decoder. -/
noncomputable def anchoredChangeTraceAgainst
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 s : ℕ) :
    ℕ → Part (ℕ × List BitString)
  | 0 => (anchoredDecoderTraceAgainst 𝒢 ℬ c gridCode q0 0).map
      (fun code => (0, anchoredModelListAt s code))
  | m + 1 =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c gridCode q0 s m).bind
        (fun p =>
          (anchoredDecoderTraceAgainst 𝒢 ℬ c gridCode q0
            (m + 1)).map (fun code =>
              if anchoredModelListAt s code = p.2 then (p.1, p.2)
              else (p.1 + 1, anchoredModelListAt s code)))

/-- Fixed-`𝒢`, fixed-`ℬ` version decoder.  Its input is the same four-field
bundle as the one-family decoder. -/
noncomputable def anchoredVersionDecoderAgainst
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (bundle : BitString) : Part BitString :=
  let parts := decodeListCode bundle
  let gridCode := parts.getD 0 []
  let q0 := bitsToNat (parts.getD 1 [])
  let s := bitsToNat (parts.getD 2 [])
  let v := bitsToNat (parts.getD 3 [])
  (Nat.rfind (fun m =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c gridCode q0 s m).map
        (fun p => decide (v ≤ p.1)))).bind
    (fun m =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c gridCode q0 s m).map
        (fun p => uniformCodeOfList p.2))

/-- Coupled all-index output with good models in `𝒢` and a common survivor
avoiding the forbidden profile generated by `ℬ`. -/
structure RestrictedCoupledOutputAgainst
    (𝒢 ℬ : DescriptionFamily) (U : Map)
    (n k c : ℕ) (t : ℕ → ℕ) where
  ambientLength : ℕ
  n_le_ambient : n ≤ ambientLength
  ambient_le : ambientLength ≤ n + logSlack c n
  goodSets : ℕ → Finset BitString
  mem_family : ∀ s (_hs : s ≤ k), 𝒢.mem (goodSets s)
  size_bound : ∀ s (_hs : s ≤ k),
    (goodSets s).card ≤ 2 ^ (t s + sqrtSlack c n)
  complexity_bound : ∀ s (_hs : s ≤ k)
      (hS : (goodSets s).Nonempty),
    setComplexity U (goodSets s) hS ≤
      (s + sqrtSlack c n : ENat)
  candidates : Finset BitString
  candidates_nonempty : candidates.Nonempty
  candidate_len : ∀ x ∈ candidates, x.length = ambientLength
  candidate_mem : ∀ x ∈ candidates, ∀ s (_hs : s ≤ k),
    x ∈ goodSets s
  candidate_complexity : ∀ x ∈ candidates,
    KPPlain U x ≤ (k + sqrtSlack c n : ENat)
  survivor : BitString
  survivor_mem : survivor ∈ candidates
  survivor_not_bad :
    survivor ∉ restrictedProfileBadSet ℬ U candidates k
      (sqrtSlack c n) t

/-- On the diagonal, a mixed-family output is exactly an ordinary coupled
output. -/
def RestrictedCoupledOutputAgainst.toDiagonal
    {𝒜 : DescriptionFamily} {U : Map}
    {n k c : ℕ} {t : ℕ → ℕ}
    (output : RestrictedCoupledOutputAgainst 𝒜 𝒜 U n k c t) :
    RestrictedCoupledOutput 𝒜 U n k c t where
  ambientLength := output.ambientLength
  n_le_ambient := output.n_le_ambient
  ambient_le := output.ambient_le
  goodSets := output.goodSets
  mem_family := output.mem_family
  size_bound := output.size_bound
  complexity_bound := output.complexity_bound
  candidates := output.candidates
  candidates_nonempty := output.candidates_nonempty
  candidate_len := output.candidate_len
  candidate_mem := output.candidate_mem
  candidate_complexity := output.candidate_complexity
  survivor := output.survivor
  survivor_mem := output.survivor_mem
  survivor_not_bad := output.survivor_not_bad

/-- A mixed coupled output realizes the target curve in both families when
the rebuilding family is contained in the forbidden-description family. -/
lemma RestrictedCoupledOutputAgainst.profiles
    {𝒢 ℬ : DescriptionFamily} {U : Map}
    {n k c : ℕ} {t : ℕ → ℕ}
    (output : RestrictedCoupledOutputAgainst 𝒢 ℬ U n k c t)
    (hsub : ∀ S, 𝒢.mem S → ℬ.mem S) :
    RestrictedProfileWithinCurve 𝒢 U output.survivor k t
        (sqrtSlack c n) ∧
      RestrictedProfileWithinCurve ℬ U output.survivor k t
        (sqrtSlack c n) := by
  have hupperG :
      ∀ i : ℕ, i ≤ k →
        InDescriptionProfileIn 𝒢 U output.survivor
          (i + sqrtSlack c n) (t i + sqrtSlack c n) := by
    intro i hi
    have hx := output.candidate_mem output.survivor
      output.survivor_mem i hi
    have hS : (output.goodSets i).Nonempty :=
      ⟨output.survivor, hx⟩
    refine ⟨output.goodSets i, hS, output.mem_family i hi,
      hx, output.complexity_bound i hi hS, output.size_bound i hi⟩
  have hupperB :
      ∀ i : ℕ, i ≤ k →
        InDescriptionProfileIn ℬ U output.survivor
          (i + sqrtSlack c n) (t i + sqrtSlack c n) :=
    fun i hi => inDescriptionProfileIn_mono_family hsub (hupperG i hi)
  have hlowerB :
      ∀ i : ℕ, i ≤ k →
        ¬ InDescriptionProfileIn ℬ U output.survivor i
            (t i - (sqrtSlack c n + 1)) ∨
          t i ≤ sqrtSlack c n := by
    intro i hi
    by_cases hsmall : t i ≤ sqrtSlack c n
    · exact Or.inr hsmall
    · refine Or.inl ?_
      intro hprof
      apply output.survivor_not_bad
      exact ((restrictedProfileBadSet_spec ℬ U output.candidates k
        (sqrtSlack c n) t).2 output.survivor
          output.survivor_mem).mpr
        ⟨i, hi, Nat.lt_of_not_ge hsmall, hprof⟩
  have hlowerG :
      ∀ i : ℕ, i ≤ k →
        ¬ InDescriptionProfileIn 𝒢 U output.survivor i
            (t i - (sqrtSlack c n + 1)) ∨
          t i ≤ sqrtSlack c n := by
    intro i hi
    rcases hlowerB i hi with hnot | hsmall
    · exact Or.inl (fun hprof =>
        hnot (inDescriptionProfileIn_mono_family hsub hprof))
    · exact Or.inr hsmall
  exact ⟨⟨hupperG, hlowerG⟩, ⟨hupperB, hlowerB⟩⟩

/-- The mixed trace definitionally recovers the one-family trace on the
diagonal. -/
@[simp] lemma anchoredDecoderTraceAgainst_self
    (𝒜 : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 m : ℕ) :
    anchoredDecoderTraceAgainst 𝒜 𝒜 c gridCode q0 m =
      anchoredDecoderTrace 𝒜 c gridCode q0 m := rfl

/-- Diagonal compatibility of change counting. -/
@[simp] lemma anchoredChangeTraceAgainst_self
    (𝒜 : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 s m : ℕ) :
    anchoredChangeTraceAgainst 𝒜 𝒜 c gridCode q0 s m =
      anchoredChangeTrace 𝒜 c gridCode q0 s m := by
  induction m with
  | zero => rfl
  | succ m ih =>
      rw [anchoredChangeTraceAgainst, anchoredChangeTrace, ih,
        anchoredDecoderTraceAgainst_self]

/-- Diagonal compatibility of the fixed-family version decoder. -/
@[simp] lemma anchoredVersionDecoderAgainst_self
    (𝒜 : DescriptionFamily) (c : Code) (bundle : BitString) :
    anchoredVersionDecoderAgainst 𝒜 𝒜 c bundle =
      anchoredVersionDecoder 𝒜 c bundle := by
  unfold anchoredVersionDecoderAgainst anchoredVersionDecoder
  simp only [anchoredChangeTraceAgainst_self]

/-- The mixed decoder trace is partial recursive for fixed families. -/
lemma anchoredDecoderTraceAgainst_partrec
    (𝒢 ℬ : DescriptionFamily) (c : Code) :
    Partrec (fun p : (BitString × ℕ) × ℕ =>
      anchoredDecoderTraceAgainst 𝒢 ℬ c p.1.1 p.1.2 p.2) := by
  let P := (BitString × ℕ) × ℕ
  have hgrid : Computable (fun p : P => p.1.1) :=
    Computable.fst.comp Computable.fst
  have hq0 : Computable (fun p : P => p.1.2) :=
    Computable.snd.comp Computable.fst
  have hm : Computable (fun p : P => p.2) := Computable.snd
  have hsteps : Computable (fun p : P =>
      anchoredDecodedSteps p.1.1) :=
    anchoredDecodedSteps_primrec.to_comp.comp hgrid
  have hΔ : Computable (fun p : P =>
      anchoredDecodedSlack p.1.1) :=
    anchoredDecodedSlack_primrec.to_comp.comp hgrid
  have hamb : Computable (fun p : P =>
      anchoredDecodedAmbientLength p.1.1) :=
    anchoredDecodedAmbientLength_primrec.to_comp.comp hgrid
  have hgridR : Computable (fun r : P × ℕ => r.1.1.1) :=
    hgrid.comp Computable.fst
  have hstepsR : Computable (fun r : P × ℕ =>
      anchoredDecodedSteps r.1.1.1) :=
    hsteps.comp Computable.fst
  have hΔR : Computable (fun r : P × ℕ =>
      anchoredDecodedSlack r.1.1.1) :=
    hΔ.comp Computable.fst
  have hstream : Computable (fun r : P × ℕ =>
      restrictedSampledBadCodeStream c r.1.1.1 ℬ.toPre
        (anchoredDecodedSteps r.1.1.1)
        (anchoredDecodedSlack r.1.1.1) r.2) :=
    (restrictedSampledBadCodeStream_computable_all c ℬ.toPre).comp
      (Computable.pair
        (Computable.pair (Computable.pair hgridR hstepsR) hΔR)
        Computable.snd)
  have hmR : Computable (fun r : P × ℕ => r.1.2) :=
    hm.comp Computable.fst
  have hcheck : Computable₂ (fun (p : P) (τ : ℕ) =>
      decide (p.2 ≤
        (restrictedSampledBadCodeStream c p.1.1 ℬ.toPre
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1) τ).length)) :=
    ((PrimrecPred.decide Primrec.nat_le).to_comp.to₂.comp hmR
      (Computable.list_length.comp hstream)).to₂
  have hfind : Partrec (fun p : P => Nat.rfind (fun τ =>
      Part.some (decide (p.2 ≤
        (restrictedSampledBadCodeStream c p.1.1 ℬ.toPre
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1) τ).length)))) :=
    Partrec.rfind hcheck.partrec₂
  have hinitInput : Computable (fun p : P =>
      ((((p.1.2, p.1.1), anchoredDecodedSteps p.1.1),
        anchoredDecodedSlack p.1.1),
        anchoredDecodedAmbientLength p.1.1)) :=
    Computable.pair
      (Computable.pair
        (Computable.pair (Computable.pair hq0 hgrid) hsteps) hΔ)
      hamb
  have hinit : Partrec (fun p : P =>
      restrictedAnchoredInitialFromCode 𝒢 p.1.2 p.1.1
        (anchoredDecodedSteps p.1.1)
        (anchoredDecodedSlack p.1.1)
        (anchoredDecodedAmbientLength p.1.1)) :=
    (restrictedAnchoredInitialFromCode_partrec_all 𝒢).comp hinitInput
  have hsizesR : Computable (fun r : P × ℕ =>
      restrictedAnchoredSizesFromCode r.1.1.1
        (anchoredDecodedSteps r.1.1.1)
        (anchoredDecodedSlack r.1.1.1)
        (anchoredDecodedAmbientLength r.1.1.1)) :=
    restrictedAnchoredSizesFromCode_computable_all.comp
      (Computable.pair
        (Computable.pair (Computable.pair hgridR hstepsR) hΔR)
        (hamb.comp Computable.fst))
  have hinitR : Partrec (fun r : P × ℕ =>
      restrictedAnchoredInitialFromCode 𝒢 r.1.1.2 r.1.1.1
        (anchoredDecodedSteps r.1.1.1)
        (anchoredDecodedSlack r.1.1.1)
        (anchoredDecodedAmbientLength r.1.1.1)) :=
    hinit.comp Computable.fst
  have hprefixInput :
      Computable (fun r : (P × ℕ) × BitString =>
        ((((r.1.1.1.2,
            restrictedAnchoredSizesFromCode r.1.1.1.1
              (anchoredDecodedSteps r.1.1.1.1)
              (anchoredDecodedSlack r.1.1.1.1)
              (anchoredDecodedAmbientLength r.1.1.1.1)),
            r.2),
          restrictedSampledBadCodeStream c r.1.1.1.1 ℬ.toPre
            (anchoredDecodedSteps r.1.1.1.1)
            (anchoredDecodedSlack r.1.1.1.1) r.1.2),
          r.1.1.2)) :=
    Computable.pair
      (Computable.pair
        (Computable.pair
          (Computable.pair
            (hq0.comp (Computable.fst.comp Computable.fst))
            (hsizesR.comp Computable.fst))
          Computable.snd)
        (hstream.comp Computable.fst))
      (hm.comp (Computable.fst.comp Computable.fst))
  have hprefix : Partrec₂
      (fun (r : P × ℕ) (st0 : BitString) =>
        restrictedEventPrefixRun 𝒢 r.1.1.2
          (restrictedAnchoredSizesFromCode r.1.1.1
            (anchoredDecodedSteps r.1.1.1)
            (anchoredDecodedSlack r.1.1.1)
            (anchoredDecodedAmbientLength r.1.1.1)) st0
          (restrictedSampledBadCodeStream c r.1.1.1 ℬ.toPre
            (anchoredDecodedSteps r.1.1.1)
            (anchoredDecodedSlack r.1.1.1) r.2)
          r.1.2) :=
    ((restrictedEventPrefixRun_partrec_all 𝒢).comp hprefixInput).to₂
  have hbody : Partrec₂ (fun (p : P) (τ : ℕ) =>
      (restrictedAnchoredInitialFromCode 𝒢 p.1.2 p.1.1
        (anchoredDecodedSteps p.1.1)
        (anchoredDecodedSlack p.1.1)
        (anchoredDecodedAmbientLength p.1.1)).bind
      (fun st0 => restrictedEventPrefixRun 𝒢 p.1.2
        (restrictedAnchoredSizesFromCode p.1.1
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1)
          (anchoredDecodedAmbientLength p.1.1)) st0
        (restrictedSampledBadCodeStream c p.1.1 ℬ.toPre
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1) τ) p.2)) :=
    (Partrec.bind hinitR hprefix).to₂
  exact (Partrec.bind hfind hbody).of_eq (fun _ => rfl)

/-- Mixed-family change counting is partial recursive. -/
lemma anchoredChangeTraceAgainst_partrec
    (𝒢 ℬ : DescriptionFamily) (c : Code) :
    Partrec (fun p : ((BitString × ℕ) × ℕ) × ℕ =>
      anchoredChangeTraceAgainst 𝒢 ℬ c
        p.1.1.1 p.1.1.2 p.1.2 p.2) := by
  let P := ((BitString × ℕ) × ℕ) × ℕ
  have hgrid : Computable (fun p : P => p.1.1.1) :=
    Computable.fst.comp (Computable.fst.comp Computable.fst)
  have hq0 : Computable (fun p : P => p.1.1.2) :=
    Computable.snd.comp (Computable.fst.comp Computable.fst)
  have hs : Computable (fun p : P => p.1.2) :=
    Computable.snd.comp Computable.fst
  have hcount : Computable (fun p : P => p.2) :=
    Computable.snd
  have htraceBase : Partrec (fun p : P =>
      anchoredDecoderTraceAgainst 𝒢 ℬ c
        p.1.1.1 p.1.1.2 0) :=
    (anchoredDecoderTraceAgainst_partrec 𝒢 ℬ c).comp
      (Computable.pair
        (Computable.pair hgrid hq0) (Computable.const 0))
  have hbase : Partrec (fun p : P =>
      (anchoredDecoderTraceAgainst 𝒢 ℬ c
        p.1.1.1 p.1.1.2 0).map
          (fun code => (0, anchoredModelListAt p.1.2 code))) :=
    Partrec.map htraceBase
      ((Primrec.pair (Primrec.const 0)
        (anchoredModelListAt_primrec.comp
          (Primrec.snd.comp
            (Primrec.fst.comp Primrec.fst))
          Primrec.snd)).to_comp.to₂)
  have htraceStep : Partrec
      (fun r : P × (ℕ × (ℕ × List BitString)) =>
        anchoredDecoderTraceAgainst 𝒢 ℬ c
          r.1.1.1.1 r.1.1.1.2 (r.2.1 + 1)) :=
    (anchoredDecoderTraceAgainst_partrec 𝒢 ℬ c).comp
      (Computable.pair
        (Computable.pair
          (hgrid.comp Computable.fst)
          (hq0.comp Computable.fst))
        (Computable.succ.comp
          (Computable.fst.comp Computable.snd)))
  have hstepPost : Computable₂
      (fun (r : P × (ℕ × (ℕ × List BitString)))
        (code : BitString) =>
        if anchoredModelListAt r.1.1.2 code = r.2.2.2 then
          (r.2.2.1, r.2.2.2)
        else
          (r.2.2.1 + 1,
            anchoredModelListAt r.1.1.2 code)) := by
    have hscale : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          x.1.1.1.2) :=
      Primrec.snd.comp
        (Primrec.fst.comp (Primrec.fst.comp Primrec.fst))
    have hmodel : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          anchoredModelListAt x.1.1.1.2 x.2) :=
      anchoredModelListAt_primrec.comp hscale Primrec.snd
    have hprevCount : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          x.1.2.2.1) :=
      Primrec.fst.comp
        (Primrec.snd.comp (Primrec.snd.comp Primrec.fst))
    have hprevList : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          x.1.2.2.2) :=
      Primrec.snd.comp
        (Primrec.snd.comp (Primrec.snd.comp Primrec.fst))
    exact ((Primrec.ite (Primrec.eq.comp hmodel hprevList)
      (Primrec.pair hprevCount hprevList)
      (Primrec.pair
        (Primrec.nat_add.comp hprevCount (Primrec.const 1))
        hmodel)).to_comp).to₂
  have hstep : Partrec₂
      (fun (p : P) (r : ℕ × (ℕ × List BitString)) =>
        (anchoredDecoderTraceAgainst 𝒢 ℬ c
          p.1.1.1 p.1.1.2 (r.1 + 1)).map
            (fun code =>
              if anchoredModelListAt p.1.2 code = r.2.2 then
                (r.2.1, r.2.2)
              else
                (r.2.1 + 1,
                  anchoredModelListAt p.1.2 code))) :=
    (Partrec.map htraceStep hstepPost).to₂
  refine (Partrec.nat_rec hcount hbase hstep).of_eq ?_
  rintro ⟨⟨⟨grid, q0⟩, sc⟩, m⟩
  induction m with
  | zero => rfl
  | succ m ih =>
      simp only []
      rw [show anchoredChangeTraceAgainst 𝒢 ℬ c
          grid q0 sc (m + 1) =
          (anchoredChangeTraceAgainst 𝒢 ℬ c
            grid q0 sc m).bind (fun p =>
              (anchoredDecoderTraceAgainst 𝒢 ℬ c
                grid q0 (m + 1)).map (fun code =>
                  if anchoredModelListAt sc code = p.2 then
                    (p.1, p.2)
                  else
                    (p.1 + 1,
                      anchoredModelListAt sc code))) from rfl,
        ← ih]

/-- The fixed-family mixed version decoder is partial recursive. -/
lemma anchoredVersionDecoderAgainst_partrec
    (𝒢 ℬ : DescriptionFamily) (c : Code) :
    Partrec (anchoredVersionDecoderAgainst 𝒢 ℬ c) := by
  have hparts : Computable
      (fun bundle : BitString => decodeListCode bundle) :=
    decodeListCode_primrec.to_comp
  have hpart (i : ℕ) : Computable
      (fun bundle : BitString =>
        (decodeListCode bundle).getD i []) :=
    (Primrec.list_getD []).to_comp.comp hparts
      (Computable.const i)
  have hgrid : Computable (fun bundle : BitString =>
      (decodeListCode bundle).getD 0 []) :=
    hpart 0
  have hq0 : Computable (fun bundle : BitString =>
      bitsToNat ((decodeListCode bundle).getD 1 [])) :=
    bitsToNat_primrec.to_comp.comp (hpart 1)
  have hs : Computable (fun bundle : BitString =>
      bitsToNat ((decodeListCode bundle).getD 2 [])) :=
    bitsToNat_primrec.to_comp.comp (hpart 2)
  have hv : Computable (fun bundle : BitString =>
      bitsToNat ((decodeListCode bundle).getD 3 [])) :=
    bitsToNat_primrec.to_comp.comp (hpart 3)
  have hchangeInput : Computable
      (fun r : BitString × ℕ =>
        ((((decodeListCode r.1).getD 0 [],
          bitsToNat ((decodeListCode r.1).getD 1 [])),
          bitsToNat ((decodeListCode r.1).getD 2 [])),
          r.2)) :=
    Computable.pair
      (Computable.pair
        (Computable.pair
          (hgrid.comp Computable.fst)
          (hq0.comp Computable.fst))
        (hs.comp Computable.fst))
      Computable.snd
  have hchange : Partrec (fun r : BitString × ℕ =>
      anchoredChangeTraceAgainst 𝒢 ℬ c
        ((decodeListCode r.1).getD 0 [])
        (bitsToNat ((decodeListCode r.1).getD 1 []))
        (bitsToNat ((decodeListCode r.1).getD 2 []))
        r.2) :=
    (anchoredChangeTraceAgainst_partrec 𝒢 ℬ c).comp
      hchangeInput
  have hcheckPost : Computable₂
      (fun (r : BitString × ℕ)
        (p : ℕ × List BitString) =>
        decide
          (bitsToNat ((decodeListCode r.1).getD 3 []) ≤
            p.1)) :=
    ((PrimrecPred.decide Primrec.nat_le).to_comp.to₂.comp
      (hv.comp (Computable.fst.comp Computable.fst))
      (Computable.fst.comp Computable.snd)).to₂
  have hcheck : Partrec₂
      (fun (bundle : BitString) (m : ℕ) =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c
          ((decodeListCode bundle).getD 0 [])
          (bitsToNat ((decodeListCode bundle).getD 1 []))
          (bitsToNat ((decodeListCode bundle).getD 2 []))
          m).map (fun p => decide
            (bitsToNat ((decodeListCode bundle).getD 3 []) ≤
              p.1))) :=
    (Partrec.map hchange hcheckPost).to₂
  have hfind : Partrec (fun bundle : BitString =>
      Nat.rfind (fun m =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c
          ((decodeListCode bundle).getD 0 [])
          (bitsToNat ((decodeListCode bundle).getD 1 []))
          (bitsToNat ((decodeListCode bundle).getD 2 []))
          m).map (fun p => decide
            (bitsToNat ((decodeListCode bundle).getD 3 []) ≤
              p.1)))) :=
    Partrec.rfind hcheck
  have houtputPost : Computable₂
      (fun (_r : BitString × ℕ)
        (p : ℕ × List BitString) =>
        uniformCodeOfList p.2) :=
    (uniformCodeOfList_primrec.to_comp.comp
      (Computable.snd.comp Computable.snd)).to₂
  have hbody : Partrec₂
      (fun (bundle : BitString) (m : ℕ) =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c
          ((decodeListCode bundle).getD 0 [])
          (bitsToNat ((decodeListCode bundle).getD 1 []))
          (bitsToNat ((decodeListCode bundle).getD 2 []))
          m).map (fun p => uniformCodeOfList p.2)) :=
    (Partrec.map hchange houtputPost).to₂
  exact (Partrec.bind hfind hbody).of_eq (fun _ => rfl)

/-- On a genuine grid, the mixed decoder replays every available prefix of
the `ℬ` event stream through the `𝒢` executor. -/
lemma anchoredDecoderTraceAgainst_replay
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (grid : RestrictedCurveGrid n k N target)
    (hN : N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1)
    (T m : ℕ) (code : BitString)
    (hm : m ≤ (restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) T).length)
    (hfold :
      (restrictedEffectiveAnchoredInitialState 𝒢
          (n + logSlack 8 n) (sqrtSlack 8 n) grid).bind
        (fun st0 => restrictedEventPrefixRun 𝒢
          (𝒢.overhead (n + logSlack 8 n))
          (restrictedEffectiveAnchoredSizes
            (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
          (restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N
            (sqrtSlack 8 n) T) m) = Part.some code) :
    anchoredDecoderTraceAgainst 𝒢 ℬ c
      (restrictedCurveGridCode grid)
      (𝒢.overhead (n + logSlack 8 n)) m = Part.some code := by
  have hex : ∃ τ, m ≤ (restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) τ).length :=
    ⟨T, hm⟩
  have hfind : Nat.rfind (fun τ => Part.some (decide (m ≤
      (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) τ).length))) =
      Part.some (Nat.find hex) :=
    Part.eq_some_iff.mpr (Nat.mem_rfind.mpr
      ⟨by simpa using Nat.find_spec hex,
        fun {j} hj => by simpa using Nat.find_min hex hj⟩)
  have hprefix : restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N (sqrtSlack 8 n)
        (Nat.find hex) <+:
      restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T :=
    restrictedSampledBadCodeStream_prefix_of_le _ _ _ _ _
      (Nat.find_min' hex hm)
  have hrun : (fun st0 : BitString => restrictedEventPrefixRun 𝒢
        (𝒢.overhead (n + logSlack 8 n))
        (restrictedEffectiveAnchoredSizes
          (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) (Nat.find hex)) m) =
      (fun st0 : BitString => restrictedEventPrefixRun 𝒢
        (𝒢.overhead (n + logSlack 8 n))
        (restrictedEffectiveAnchoredSizes
          (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) T) m) :=
    funext fun st0 => restrictedEventPrefixRun_congr 𝒢 _ _ _ m
      (fun i hi => (prefix_getD_eq hprefix
        (lt_of_lt_of_le hi (Nat.find_spec hex))).symm)
  unfold anchoredDecoderTraceAgainst
  simp only [anchoredDecodedSteps_eq grid hN,
    anchoredDecodedSlack_eq grid,
    anchoredDecodedAmbientLength_eq grid]
  rw [hfind, Part.bind_some]
  simp only [restrictedAnchoredSizesFromCode_eq grid,
    restrictedAnchoredInitialFromCode_eq 𝒢 grid]
  rw [hrun]
  exact hfold

/-- Evaluation of the mixed version decoder on its explicit bundle. -/
lemma anchoredVersionDecoderAgainst_eval
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (g q0b sb vb : BitString) :
    anchoredVersionDecoderAgainst 𝒢 ℬ c
      (listCode [g, q0b, sb, vb]) =
      (Nat.rfind (fun m =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c g
          (bitsToNat q0b) (bitsToNat sb) m).map
            (fun p => decide (bitsToNat vb ≤ p.1)))).bind
        (fun m =>
          (anchoredChangeTraceAgainst 𝒢 ℬ c g
            (bitsToNat q0b) (bitsToNat sb) m).map
              (fun p => uniformCodeOfList p.2)) := by
  unfold anchoredVersionDecoderAgainst
  rw [decodeListCode_listCode]
  rfl

/-- Binding a partial value to `Part.some` does not change it. -/
private lemma part_bind_some_against {α : Type} (p : Part α) :
    p.bind Part.some = p := by
  ext a
  simp

/-- The mixed run, indexed by individual `ℬ` events, forms a genuine
`RestrictedRunChain` of `𝒢` states. -/
lemma exists_restrictedAnchoredEventChain_against
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (ambientLength Δ : ℕ)
    (grid : RestrictedCurveGrid n k N target)
    (hnambient : n ≤ ambientLength) (T : ℕ) :
    ∃ (chain : RestrictedRunChain 𝒢 (N + 1) ambientLength
        (2 * 𝒢.overhead ambientLength)
        (restrictedAnchoredTarget ambientLength Δ grid)
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N Δ T).length)
      (codes : ℕ → BitString),
      (∀ m,
        (restrictedEffectiveAnchoredInitialState 𝒢
            ambientLength Δ grid).bind
          (fun st0 => restrictedEventPrefixRun 𝒢
            (𝒢.overhead ambientLength)
            (restrictedEffectiveAnchoredSizes
              ambientLength Δ grid) st0
            (restrictedSampledBadCodeStream c
              (restrictedCurveGridCode grid) ℬ.toPre N Δ T) m) =
              Part.some (codes m) ∧
        DecodesToRestrictedSampledRunState
          (codes m) (chain.states m)) ∧
      (∀ m, chain.bads m =
        (decodeCoverCodeList
          ((restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N Δ T).getD
              m [])).toFinset) ∧
      (chain.states 0).B 0 =
        stringsOfLength ambientLength ∧
      (chain.states 0).live 0 =
        stringsOfLength ambientLength := by
  classical
  set gridCode := restrictedCurveGridCode grid
  set events := restrictedSampledBadCodeStream c
    gridCode ℬ.toPre N Δ T
  set q0 := 𝒢.overhead ambientLength
  set sizes :=
    restrictedEffectiveAnchoredSizes ambientLength Δ grid
  set tt := restrictedAnchoredTarget ambientLength Δ grid
  have hlen : sizes.length = (N + 1) + 1 := by
    simp [sizes]
  have hpowers : ∀ s ≤ N + 1,
      sizes.getD s 0 = 2 ^ tt s := fun s hs =>
    restrictedEffectiveAnchoredSizes_getD
      ambientLength Δ grid s hs
  have hmono : ∀ s < N + 1, tt (s + 1) ≤ tt s :=
    restrictedAnchoredTarget_mono
      ambientLength Δ grid hnambient
  have hbadDecode : ∀ m,
      decodeCoverCodeList (events.getD m []) =
        canonicalFinsetList
          ((decodeCoverCodeList (events.getD m [])).toFinset) :=
    fun m =>
      restrictedSampledBadCodeStream_getD_canonical
        ℬ c gridCode N Δ T m
  have hdata : ∀ m : ℕ, ∃ p : BitString ×
      RestrictedSampledRunState 𝒢 (N + 1) ambientLength
        (2 * 𝒢.overhead ambientLength) tt,
      (restrictedEffectiveAnchoredInitialState 𝒢
          ambientLength Δ grid).bind
        (fun st0 => restrictedEventPrefixRun 𝒢 q0 sizes
          st0 events m) = Part.some p.1 ∧
      DecodesToRestrictedSampledRunState p.1 p.2 ∧
      (m = 0 →
        p.2.B 0 = stringsOfLength ambientLength ∧
        p.2.live 0 = stringsOfLength ambientLength) := by
    intro m
    induction m with
    | zero =>
        obtain ⟨code0, st0, hrun0, hdec0, hB0, hlive0⟩ :=
          restrictedEffectiveAnchoredInitialState_spec 𝒢
            ambientLength Δ grid hnambient
        refine ⟨(code0, st0), ?_, hdec0,
          fun _ => ⟨hB0, hlive0⟩⟩
        simpa [restrictedEventPrefixRun_zero,
          part_bind_some_against] using hrun0
    | succ m ih =>
        obtain ⟨⟨cd, st⟩, hfold, hdec, _⟩ := ih
        obtain ⟨output, next, q, hstepEq, hnextDec,
            _hspec⟩ :=
          restrictedEffectiveSampledRun_step_spec 𝒢
            (N + 1) ambientLength tt sizes hlen hpowers
            hmono hdec (hbadDecode m)
        refine ⟨(output, next), ?_, hnextDec,
          fun h => absurd h (Nat.succ_ne_zero m)⟩
        have hsplit :
            (restrictedEffectiveAnchoredInitialState 𝒢
              ambientLength Δ grid).bind (fun st0 =>
                restrictedEventPrefixRun 𝒢 q0 sizes st0
                  events (m + 1)) =
            ((restrictedEffectiveAnchoredInitialState 𝒢
              ambientLength Δ grid).bind (fun st0 =>
                restrictedEventPrefixRun 𝒢 q0 sizes st0
                  events m)).bind (fun state =>
                    restrictedEffectiveSampledRunStep 𝒢 q0 sizes
                      state (events.getD m [])) := by
          rw [Part.bind_assoc]
          rfl
        rw [hsplit, hfold, Part.bind_some, hstepEq]
  choose data hd1 hd2 hd3 using hdata
  have hedge : ∀ m : ℕ, ∃ q,
      RestrictedSampledRunStepSpec
        ((data m).2) ((data (m + 1)).2)
        ((decodeCoverCodeList
          (events.getD m [])).toFinset) q := by
    intro m
    obtain ⟨output, next, q, hstepEq, hnextDec, hspec⟩ :=
      restrictedEffectiveSampledRun_step_spec 𝒢
        (N + 1) ambientLength tt sizes hlen hpowers
        hmono (hd2 m) (hbadDecode m)
    have hsplit :
        (restrictedEffectiveAnchoredInitialState 𝒢
          ambientLength Δ grid).bind (fun st0 =>
            restrictedEventPrefixRun 𝒢 q0 sizes st0
              events (m + 1)) =
        ((restrictedEffectiveAnchoredInitialState 𝒢
          ambientLength Δ grid).bind (fun st0 =>
            restrictedEventPrefixRun 𝒢 q0 sizes st0
              events m)).bind (fun state =>
                restrictedEffectiveSampledRunStep 𝒢 q0 sizes
                  state (events.getD m [])) := by
      rw [Part.bind_assoc]
      rfl
    have hout : output = (data (m + 1)).1 := by
      have hfold1 := hd1 (m + 1)
      rw [hsplit, hd1 m, Part.bind_some, hstepEq] at hfold1
      exact Part.some_injective hfold1
    refine ⟨q,
      stepSpec_transfer (fun s hs => ⟨rfl, rfl⟩)
        ?_ hspec⟩
    intro s hs
    exact decodesTo_eq_B_live
      (hout ▸ hnextDec) (hd2 (m + 1)) hs
  choose edges hedges using hedge
  exact ⟨⟨fun m => (data m).2,
      fun m => (decodeCoverCodeList
        (events.getD m [])).toFinset,
      edges, fun m _ => hedges m⟩,
    fun m => (data m).1,
    fun m => ⟨hd1 m, hd2 m⟩,
    fun m => rfl,
    (hd3 0 rfl).1, (hd3 0 rfl).2⟩

/-- The mixed decoder returns the terminal `𝒢` model at a version ordinal
bounded by the rebuild count of the `𝒢` chain driven by `ℬ` events. -/
lemma anchoredVersionDecoderAgainst_terminal
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (grid : RestrictedCurveGrid n k N target)
    (hN : N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1)
    (T : ℕ)
    (chain : RestrictedRunChain 𝒢 (N + 1)
      (n + logSlack 8 n)
      (2 * 𝒢.overhead (n + logSlack 8 n))
      (restrictedAnchoredTarget (n + logSlack 8 n)
        (sqrtSlack 8 n) grid)
      (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length)
    (codes : ℕ → BitString)
    (hfold : ∀ m,
      (restrictedEffectiveAnchoredInitialState 𝒢
          (n + logSlack 8 n) (sqrtSlack 8 n) grid).bind
        (fun st0 => restrictedEventPrefixRun 𝒢
          (𝒢.overhead (n + logSlack 8 n))
          (restrictedEffectiveAnchoredSizes
            (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
          (restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N
            (sqrtSlack 8 n) T) m) = Part.some (codes m) ∧
      DecodesToRestrictedSampledRunState
        (codes m) (chain.states m))
    (s : ℕ) (hs : s ≤ N)
    (hS : ((chain.states
      (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length).B (s + 1)).Nonempty) :
    ∃ v, v ≤ (chain.rebuildSteps s).card ∧
      anchoredVersionDecoderAgainst 𝒢 ℬ c
        (listCode [restrictedCurveGridCode grid,
          Nat.bits (𝒢.overhead (n + logSlack 8 n)),
          Nat.bits s, Nat.bits v]) =
        Part.some ((codedUniformOn ((chain.states
          (restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N
            (sqrtSlack 8 n) T).length).B (s + 1)) hS).code) := by
  classical
  have htrace : ∀ m,
      m ≤ (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length →
      anchoredChangeTraceAgainst 𝒢 ℬ c
          (restrictedCurveGridCode grid)
          (𝒢.overhead (n + logSlack 8 n)) s m =
        Part.some (anchoredListChangeCount s codes m,
          anchoredModelListAt s (codes m)) := by
    intro m hm
    induction m with
    | zero =>
        rw [anchoredChangeTraceAgainst,
          anchoredDecoderTraceAgainst_replay
            𝒢 ℬ c grid hN T 0 (codes 0)
            (by omega) (hfold 0).1,
          Part.map_some]
        rfl
    | succ m ih =>
        rw [anchoredChangeTraceAgainst, ih (by omega),
          Part.bind_some,
          anchoredDecoderTraceAgainst_replay
            𝒢 ℬ c grid hN T (m + 1) (codes (m + 1))
            (by omega) (hfold (m + 1)).1,
          Part.map_some]
        by_cases hEq :
            anchoredModelListAt s (codes (m + 1)) =
              anchoredModelListAt s (codes m)
        · rw [if_pos hEq]
          rw [show anchoredListChangeCount s codes (m + 1) =
              anchoredListChangeCount s codes m by
                rw [anchoredListChangeCount, if_pos hEq],
            hEq]
        · rw [if_neg hEq]
          rw [show anchoredListChangeCount s codes (m + 1) =
              anchoredListChangeCount s codes m + 1 by
                rw [anchoredListChangeCount, if_neg hEq]]
  have hcount_le : ∀ m,
      m ≤ (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length →
      anchoredListChangeCount s codes m ≤
        ((Finset.range m).filter
          (fun a => chain.edges a ≤ s)).card := by
    intro m hm
    induction m with
    | zero => simp [anchoredListChangeCount]
    | succ m ih =>
        have hstep := ih (by omega)
        have hsub :
            (Finset.range m).filter
                (fun a => chain.edges a ≤ s) ⊆
              (Finset.range (m + 1)).filter
                (fun a => chain.edges a ≤ s) :=
          Finset.filter_subset_filter _
            (fun x hx => Finset.mem_range.mpr
              (Nat.lt_succ_of_lt (Finset.mem_range.mp hx)))
        by_cases hEq :
            anchoredModelListAt s (codes (m + 1)) =
              anchoredModelListAt s (codes m)
        · rw [anchoredListChangeCount, if_pos hEq]
          exact hstep.trans (Finset.card_le_card hsub)
        · rw [anchoredListChangeCount, if_neg hEq]
          have hedge : chain.edges m ≤ s := by
            by_contra hgt
            have hpres :=
              ((chain.spec m (by omega)).2.2.1
                (s + 1) (by omega)).1
            have h1 :=
              anchoredModelListAt_eq (hfold m).2 s hs
            have h2 :=
              anchoredModelListAt_eq (hfold (m + 1)).2 s hs
            rw [h1, h2, hpres] at hEq
            exact hEq rfl
          have hmem : m ∈
              (Finset.range (m + 1)).filter
                (fun a => chain.edges a ≤ s) :=
            Finset.mem_filter.mpr
              ⟨Finset.mem_range.mpr (by omega), hedge⟩
          have hnot : m ∉
              (Finset.range m).filter
                (fun a => chain.edges a ≤ s) := by
            intro hmm
            exact absurd
              (Finset.mem_range.mp (Finset.mem_filter.mp hmm).1)
              (by omega)
          have hins :
              insert m ((Finset.range m).filter
                (fun a => chain.edges a ≤ s)) ⊆
              (Finset.range (m + 1)).filter
                (fun a => chain.edges a ≤ s) := by
            intro x hx
            rcases Finset.mem_insert.mp hx with rfl | hx'
            · exact hmem
            · exact hsub hx'
          calc
            anchoredListChangeCount s codes m + 1
                ≤ ((Finset.range m).filter
                    (fun a => chain.edges a ≤ s)).card + 1 := by
                  omega
            _ = (insert m ((Finset.range m).filter
                    (fun a => chain.edges a ≤ s))).card :=
                  (Finset.card_insert_of_notMem hnot).symm
            _ ≤ ((Finset.range (m + 1)).filter
                    (fun a => chain.edges a ≤ s)).card :=
                  Finset.card_le_card hins
  set v := anchoredListChangeCount s codes
    (restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) T).length with hv
  have hvexists :
      ∃ m, v ≤ anchoredListChangeCount s codes m :=
    ⟨(restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) T).length, le_rfl⟩
  set mstar := Nat.find hvexists with hmstar
  have hmstarM : mstar ≤
      (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length :=
    Nat.find_min' hvexists le_rfl
  have hcntstar :
      anchoredListChangeCount s codes mstar = v := by
    have h1 : v ≤ anchoredListChangeCount s codes mstar :=
      Nat.find_spec hvexists
    have h2 : anchoredListChangeCount s codes mstar ≤ v :=
      anchoredListChangeCount_mono s codes hmstarM
    omega
  have hbelow : ∀ m' < mstar,
      anchoredListChangeCount s codes m' < v := by
    intro m' hm'
    have h := Nat.find_min hvexists hm'
    omega
  have hconst : ∀ m, mstar ≤ m →
      m ≤ (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length →
      anchoredModelListAt s (codes m) =
        anchoredModelListAt s (codes mstar) := by
    intro m hm hmM
    induction hm with
    | refl => rfl
    | @step m' hm' ih =>
        have hm'M : m' ≤
            (restrictedSampledBadCodeStream c
              (restrictedCurveGridCode grid) ℬ.toPre N
              (sqrtSlack 8 n) T).length := by
          omega
        have hcm' :
            anchoredListChangeCount s codes m' = v := by
          have h1 : v ≤
              anchoredListChangeCount s codes m' := by
            rw [← hcntstar]
            exact anchoredListChangeCount_mono s codes hm'
          have h2 :
              anchoredListChangeCount s codes m' ≤ v :=
            anchoredListChangeCount_mono s codes hm'M
          omega
        have hcm'1 :
            anchoredListChangeCount s codes (m' + 1) = v := by
          have h1 : v ≤
              anchoredListChangeCount s codes (m' + 1) := by
            rw [← hcm']
            exact anchoredListChangeCount_succ_le s codes m'
          have h2 :
              anchoredListChangeCount s codes (m' + 1) ≤ v :=
            anchoredListChangeCount_mono s codes hmM
          omega
        have hEq :=
          (anchoredListChangeCount_succ_eq_iff s codes m').mp
            (by omega)
        exact hEq.trans (ih hm'M)
  have hrfind : Nat.rfind (fun m =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c
        (restrictedCurveGridCode grid)
        (𝒢.overhead (n + logSlack 8 n)) s m).map
          (fun p => decide (v ≤ p.1))) =
      Part.some mstar := by
    rw [Part.eq_some_iff]
    refine Nat.mem_rfind.mpr ⟨?_, ?_⟩
    · rw [htrace mstar hmstarM, Part.map_some]
      simp [hcntstar]
    · intro q hq
      rw [htrace q (by omega), Part.map_some]
      simp only [Part.mem_some_iff]
      have h := hbelow q hq
      simp [Nat.not_le.mpr h]
  refine ⟨v, ?_, ?_⟩
  · exact (hcount_le _ le_rfl).trans (le_of_eq rfl)
  · rw [anchoredVersionDecoderAgainst_eval,
      bitsToNat_bits, bitsToNat_bits, bitsToNat_bits,
      hrfind, Part.bind_some, htrace mstar hmstarM,
      Part.map_some]
    congr 1
    have hlist : anchoredModelListAt s (codes
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) T).length) =
        anchoredModelListAt s (codes mstar) :=
      hconst _ hmstarM le_rfl
    rw [← hlist]
    exact uniformCodeOfList_anchoredModelListAt_eq
      (hfold _).2 s hs hS

/-- `sqrtSlack` is a multiple of `√(n·len n) + 1`. -/
private lemma mixedSqrtSlack_eq_mul (m n : ℕ) :
    sqrtSlack m n = m * (Nat.sqrt (n * (Nat.bits n).length) + 1) := by
  unfold sqrtSlack
  ring

/-- Binary size is subadditive under multiplication. -/
private lemma mixedSize_mul_le (a b : ℕ) :
    Nat.size (a * b) ≤ Nat.size a + Nat.size b := by
  rcases Nat.eq_zero_or_pos a with rfl | ha
  · simp
  rcases Nat.eq_zero_or_pos b with rfl | hb
  · simp
  apply Nat.size_le.mpr
  calc
    a * b < 2 ^ Nat.size a * 2 ^ Nat.size b :=
      Nat.mul_lt_mul_of_lt_of_le (Nat.lt_size_self a)
        (Nat.le_of_lt (Nat.lt_size_self b)) (by positivity)
    _ = 2 ^ (Nat.size a + Nat.size b) := (pow_add 2 _ _).symm

/-- A number has at most as many binary digits as its value. -/
private lemma mixedBits_len_le_self (a : ℕ) :
    (Nat.bits a).length ≤ a := by
  rw [Nat.size_eq_bits_len]
  exact Nat.size_le.mpr Nat.lt_two_pow_self

/-- The arithmetic cost of a mixed decoder bundle depends only on the
good-family overhead and its version exponent. -/
private lemma mixedDecoderBundleCost_le
    (𝒢 : DescriptionFamily)
    {n k N : ℕ} {target : ℕ → ℕ}
    (grid : RestrictedCurveGrid n k N target)
    (hN : N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1)
    (hkn : k ≤ n)
    {c_over c_P : ℕ}
    (hover : ∀ m, (Nat.bits (𝒢.overhead m)).length ≤ logSlack c_over m)
    (hP : anchoredVersionExp 𝒢 n N ≤ sqrtSlack c_P n)
    {s v : ℕ} (hs : s ≤ N)
    (hv : v ≤ 2 ^ (grid.i s + anchoredVersionExp 𝒢 n N))
    (c_lg c_L c_F : ℕ) :
    ((Nat.bits (𝒢.overhead (n + logSlack 8 n))).length +
        2 * (Nat.bits (Nat.bits
          (𝒢.overhead (n + logSlack 8 n))).length).length + c_lg) +
      ((Nat.bits s).length +
        2 * (Nat.bits (Nat.bits s).length).length + c_lg) +
      ((Nat.bits v).length +
        2 * (Nat.bits (Nat.bits v).length).length + c_lg) +
        c_L * 5 + c_F ≤
      grid.i s +
        sqrtSlack (c_P + 15 * c_over + 3 * c_lg + 5 * c_L + c_F +
          2 * Nat.size (c_P + 1) + 40) n := by
  set L := (Nat.bits n).length with hL
  set S := Nat.sqrt (n * L) with hS
  have hLsize : L = Nat.size n := Nat.size_eq_bits_len n
  have hn2 : n < 2 ^ L := by
    rw [hLsize]
    exact Nat.lt_size_self n
  have hLS : L ≤ S := by
    apply Nat.le_sqrt.mpr
    have hLn : L ≤ n := by
      rw [hLsize]
      exact Nat.size_le.mpr Nat.lt_two_pow_self
    exact Nat.mul_le_mul_right _ hLn
  have hambBits : (Nat.bits (n + logSlack 8 n)).length ≤ L + 4 := by
    rw [Nat.size_eq_bits_len]
    apply Nat.size_le.mpr
    have hlog : logSlack 8 n = 8 * L + 8 := by
      unfold logSlack
      rfl
    have hLpow : L + 1 ≤ 2 ^ L := Nat.lt_two_pow_self
    have hpow4 : (2 : ℕ) ^ (L + 4) = 16 * 2 ^ L := by
      rw [pow_add]
      ring
    omega
  have hq0 :
      (Nat.bits (𝒢.overhead (n + logSlack 8 n))).length ≤
        c_over * (L + 4) + c_over := by
    refine (hover (n + logSlack 8 n)).trans ?_
    unfold logSlack
    exact Nat.add_le_add_right
      (Nat.mul_le_mul_left c_over hambBits) c_over
  have hsn : s ≤ n + 1 := by
    have hNle : N ≤ n + 1 := by
      rw [hN]
      exact Nat.add_le_add_right
        ((Nat.sqrt_le_self _).trans (Nat.div_le_self n _)) 1
    omega
  have hsbits : (Nat.bits s).length ≤ L + 1 := by
    rw [Nat.size_eq_bits_len]
    apply Nat.size_le.mpr
    have hpow1 : (2 : ℕ) ^ (L + 1) = 2 * 2 ^ L := by
      rw [pow_add]
      ring
    omega
  have hisn : grid.i s ≤ n := (grid.i_le_k s hs).trans hkn
  have hvbits :
      (Nat.bits v).length ≤
        grid.i s + anchoredVersionExp 𝒢 n N + 1 := by
    rw [Nat.size_eq_bits_len]
    apply Nat.size_le.mpr
    calc
      v ≤ 2 ^ (grid.i s + anchoredVersionExp 𝒢 n N) := hv
      _ < 2 ^ (grid.i s + anchoredVersionExp 𝒢 n N + 1) :=
        Nat.pow_lt_pow_right (by omega) (by omega)
  have hvlen_le :
      (Nat.bits v).length ≤ n + sqrtSlack c_P n + 1 := by
    refine hvbits.trans ?_
    have := hP
    omega
  have hprod :
      n + sqrtSlack c_P n + 1 ≤
        (c_P + 1) * ((n + 1) * (L + 1)) := by
    have h1 :
        sqrtSlack c_P n ≤ c_P * ((n + 1) * (L + 1)) := by
      rw [mixedSqrtSlack_eq_mul]
      apply Nat.mul_le_mul_left
      have hSn : S + 1 ≤ (n + 1) * (L + 1) := by
        have hSle : S ≤ n * L := by
          have := Nat.sqrt_le_self (n * L)
          omega
        calc
          S + 1 ≤ n * L + 1 := by omega
          _ ≤ (n + 1) * (L + 1) := by
            have h :
                (n + 1) * (L + 1) = n * L + n + L + 1 := by
              ring
            omega
      exact hSn
    have h2 : n + 1 ≤ (n + 1) * (L + 1) :=
      Nat.le_mul_of_pos_right _ (by omega)
    calc
      n + sqrtSlack c_P n + 1
          ≤ (n + 1) + c_P * ((n + 1) * (L + 1)) := by omega
      _ ≤ (n + 1) * (L + 1) +
          c_P * ((n + 1) * (L + 1)) := by omega
      _ = (c_P + 1) * ((n + 1) * (L + 1)) := by ring
  have hvdlog :
      (Nat.bits (Nat.bits v).length).length ≤
        Nat.size (c_P + 1) + (L + 1) + (L + 1) + 2 := by
    rw [Nat.size_eq_bits_len]
    have hmono := Nat.size_le_size (hvlen_le.trans hprod)
    refine hmono.trans ?_
    have h1 :=
      mixedSize_mul_le (c_P + 1) ((n + 1) * (L + 1))
    have h2 := mixedSize_mul_le (n + 1) (L + 1)
    have h3 : Nat.size (n + 1) ≤ L + 1 := by
      apply Nat.size_le.mpr
      have hpow1 : (2 : ℕ) ^ (L + 1) = 2 * 2 ^ L := by
        rw [pow_add]
        ring
      omega
    have h4 : Nat.size (L + 1) ≤ L + 1 :=
      Nat.size_le.mpr Nat.lt_two_pow_self
    omega
  have hq0dlog :
      (Nat.bits (Nat.bits
        (𝒢.overhead (n + logSlack 8 n))).length).length ≤
        c_over * (L + 4) + c_over :=
    (mixedBits_len_le_self _).trans hq0
  have hsdlog :
      (Nat.bits (Nat.bits s).length).length ≤ L + 1 :=
    (mixedBits_len_le_self _).trans hsbits
  rw [mixedSqrtSlack_eq_mul, ← hS]
  have hq0S :
      c_over * (L + 4) + c_over ≤
        5 * c_over * (S + 1) := by
    have h1 : L + 4 ≤ 4 * (S + 1) := by omega
    calc
      c_over * (L + 4) + c_over
          ≤ c_over * (4 * (S + 1)) + c_over * (S + 1) := by
        have := Nat.mul_le_mul_left c_over h1
        have h2 : c_over ≤ c_over * (S + 1) :=
          Nat.le_mul_of_pos_right _ (by omega)
        omega
      _ = 5 * c_over * (S + 1) := by ring
  have hExpS :
      anchoredVersionExp 𝒢 n N ≤ c_P * (S + 1) := by
    refine hP.trans ?_
    rw [mixedSqrtSlack_eq_mul, ← hS]
  have hLS1 : L + 1 ≤ S + 1 := by omega
  have hvdlogS :
      Nat.size (c_P + 1) + (L + 1) + (L + 1) + 2 ≤
        (Nat.size (c_P + 1) + 4) * (S + 1) := by
    have h1 :
        Nat.size (c_P + 1) ≤ Nat.size (c_P + 1) * (S + 1) :=
      Nat.le_mul_of_pos_right _ (by omega)
    have e :
        (Nat.size (c_P + 1) + 4) * (S + 1) =
          Nat.size (c_P + 1) * (S + 1) + 4 * (S + 1) := by
      ring
    omega
  have step1 :
      ((Nat.bits (𝒢.overhead (n + logSlack 8 n))).length +
          2 * (Nat.bits (Nat.bits
            (𝒢.overhead (n + logSlack 8 n))).length).length + c_lg) +
        ((Nat.bits s).length +
          2 * (Nat.bits (Nat.bits s).length).length + c_lg) +
        ((Nat.bits v).length +
          2 * (Nat.bits (Nat.bits v).length).length + c_lg) +
          c_L * 5 + c_F
        ≤ (5 * c_over * (S + 1) +
            2 * (5 * c_over * (S + 1)) + c_lg) +
          ((S + 1) + 2 * (S + 1) + c_lg) +
          ((grid.i s + c_P * (S + 1) + 1) +
            2 * ((Nat.size (c_P + 1) + 4) * (S + 1)) + c_lg) +
          c_L * 5 + c_F := by
    have b1 := hq0.trans hq0S
    have b2 := hq0dlog.trans hq0S
    have b3 := hsbits.trans hLS1
    have b4 := hsdlog.trans hLS1
    have b5 :
        (Nat.bits v).length ≤
          grid.i s + c_P * (S + 1) + 1 := by
      refine hvbits.trans ?_
      have := hExpS
      omega
    have b6 := hvdlog.trans hvdlogS
    omega
  have step2 :
      (5 * c_over * (S + 1) +
          2 * (5 * c_over * (S + 1)) + c_lg) +
        ((S + 1) + 2 * (S + 1) + c_lg) +
        ((grid.i s + c_P * (S + 1) + 1) +
          2 * ((Nat.size (c_P + 1) + 4) * (S + 1)) + c_lg) +
        c_L * 5 + c_F ≤
      grid.i s +
        (c_P + 15 * c_over + 3 * c_lg + 5 * c_L + c_F +
          2 * Nat.size (c_P + 1) + 40) * (S + 1) := by
    have hpos : 1 ≤ S + 1 := by omega
    have hclg : c_lg ≤ c_lg * (S + 1) :=
      Nat.le_mul_of_pos_right _ (by omega)
    have hcL : c_L * 5 ≤ 5 * c_L * (S + 1) := by
      have : c_L * 5 ≤ c_L * 5 * (S + 1) :=
        Nat.le_mul_of_pos_right _ (by omega)
      calc
        c_L * 5 ≤ c_L * 5 * (S + 1) := this
        _ = 5 * c_L * (S + 1) := by ring
    have hcF : c_F ≤ c_F * (S + 1) :=
      Nat.le_mul_of_pos_right _ (by omega)
    nlinarith only [hclg, hcL, hcF, hpos]
  exact step1.trans step2

private lemma sum_toFinset_le_list_sum' {α : Type*} [DecidableEq α]
    (values : α → ℕ) : ∀ items : List α,
    ∑ item ∈ items.toFinset, values item ≤ (items.map values).sum := by
  intro items
  induction items with
  | nil => simp
  | cons item items ih =>
      by_cases hitem : item ∈ items
      · have hle : (items.map values).sum ≤
            values item + (items.map values).sum := by omega
        simpa [hitem] using ih.trans hle
      · simpa [hitem] using Nat.add_le_add_left ih (values item)

private lemma sum_biUnion_le' {α β : Type*} [DecidableEq β] (s : Finset α)
    (t : α → Finset β) (f : β → ℕ) :
    ∑ w ∈ s.biUnion t, f w ≤ ∑ a ∈ s, ∑ w ∈ t a, f w := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.biUnion_insert, Finset.sum_insert ha]
      calc ∑ w ∈ t a ∪ s.biUnion t, f w
          ≤ ∑ w ∈ t a ∪ (s.biUnion t \ t a), f w := by
            have hsub : t a ∪ s.biUnion t ⊆ t a ∪ (s.biUnion t \ t a) := by
              intro x hx
              rcases Finset.mem_union.mp hx with h | h
              · exact Finset.mem_union_left _ h
              · by_cases hxa : x ∈ t a
                · exact Finset.mem_union_left _ hxa
                · exact Finset.mem_union_right _ (Finset.mem_sdiff.mpr ⟨h, hxa⟩)
            exact Finset.sum_le_sum_of_subset hsub
        _ = ∑ w ∈ t a, f w + ∑ w ∈ s.biUnion t \ t a, f w :=
            Finset.sum_union Finset.disjoint_sdiff
        _ ≤ ∑ w ∈ t a, f w + ∑ w ∈ s.biUnion t, f w :=
            Nat.add_le_add_left (Finset.sum_le_sum_of_subset Finset.sdiff_subset) _
        _ ≤ ∑ w ∈ t a, f w + ∑ a' ∈ s, ∑ w ∈ t a', f w :=
            Nat.add_le_add_left ih _

private lemma mul_pow_le_pow_add_against {a b e f : ℕ} (ha : a ≤ 2 ^ e)
    (hb : b ≤ 2 ^ f) : a * b ≤ 2 ^ (e + f) := by
  calc a * b ≤ 2 ^ e * 2 ^ f := Nat.mul_le_mul ha hb
    _ = 2 ^ (e + f) := (pow_add 2 e f).symm

private lemma version_count_arith_against {I Δm mesh LN Lob NN OB s : ℕ}
    (hNN : NN + 1 ≤ 2 ^ LN) (hOB : OB ≤ 2 ^ Lob) (hs : s ≤ NN) :
    (s + 1) * (NN * 2 ^ (I + 1) + 1 +
        2 * OB ^ (s + 1) * (NN * 2 ^ (I + Δm + mesh + 4))) ≤
      2 ^ (I + ((NN + 1) * Lob + 2 * LN + Δm + mesh + 9)) := by
  set E : ℕ := I + (NN + 1) * Lob + LN + Δm + mesh + 5 with hE
  have hNN' : NN ≤ 2 ^ LN := by omega
  have hOBpow : OB ^ (s + 1) ≤ 2 ^ ((NN + 1) * Lob) := by
    calc OB ^ (s + 1) ≤ (2 ^ Lob) ^ (s + 1) := Nat.pow_le_pow_left hOB _
      _ = 2 ^ (Lob * (s + 1)) := by rw [← pow_mul]
      _ ≤ 2 ^ ((NN + 1) * Lob) := by
          apply Nat.pow_le_pow_right (by omega)
          calc Lob * (s + 1) ≤ Lob * (NN + 1) :=
                Nat.mul_le_mul_left _ (by omega)
            _ = (NN + 1) * Lob := Nat.mul_comm _ _
  have h1 : NN * 2 ^ (I + 1) ≤ 2 ^ E := by
    refine le_trans (mul_pow_le_pow_add_against hNN' le_rfl) ?_
    exact Nat.pow_le_pow_right (by omega) (by omega)
  have h2 : (1 : ℕ) ≤ 2 ^ E := Nat.one_le_two_pow
  have h3 : 2 * OB ^ (s + 1) * (NN * 2 ^ (I + Δm + mesh + 4)) ≤ 2 ^ E := by
    have ha : 2 * OB ^ (s + 1) ≤ 2 ^ (1 + (NN + 1) * Lob) :=
      mul_pow_le_pow_add_against (by omega) hOBpow
    have hb : NN * 2 ^ (I + Δm + mesh + 4) ≤
        2 ^ (LN + (I + Δm + mesh + 4)) :=
      mul_pow_le_pow_add_against hNN' le_rfl
    refine le_trans (mul_pow_le_pow_add_against ha hb) ?_
    exact Nat.pow_le_pow_right (by omega) (by omega)
  have hbr : NN * 2 ^ (I + 1) + 1 +
      2 * OB ^ (s + 1) * (NN * 2 ^ (I + Δm + mesh + 4)) ≤ 2 ^ (E + 2) := by
    have h4 : (2:ℕ) ^ (E + 2) = 4 * 2 ^ E := by
      rw [pow_add]
      ring
    omega
  calc (s + 1) * (NN * 2 ^ (I + 1) + 1 +
        2 * OB ^ (s + 1) * (NN * 2 ^ (I + Δm + mesh + 4)))
      ≤ 2 ^ LN * 2 ^ (E + 2) :=
        Nat.mul_le_mul (by omega) hbr
    _ = 2 ^ (LN + (E + 2)) := (pow_add 2 LN (E + 2)).symm
    _ ≤ 2 ^ (I + ((NN + 1) * Lob + 2 * LN + Δm + mesh + 9)) :=
        Nat.pow_le_pow_right (by omega) (by omega)

lemma mixedLargeEventCount_le
    (ℬ : DescriptionFamily) (c : Nat.Partrec.Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (grid : RestrictedCurveGrid n k N target)
    (Δ T s : ℕ) (_hs : s ≤ N) :
  let events := restrictedSampledBadCodeStream c
    (restrictedCurveGridCode grid) ℬ.toPre N Δ T
  let isL := fun m => decide (∃ l, l < N ∧
    grid.i (l + 1) ≤ grid.i s ∧
    events.getD m [] ∈ familyStageModelCodesList c
      (grid.i (l + 1)) ℬ.toPre (grid.j l - (Δ + 1)) T)
  ((Finset.range events.length).filter
    fun a => isL a = true).card ≤ N * 2 ^ (grid.i s + 1) := by
  intro events isL
  set M := events.length
  have hgetD_inj : ∀ {a a' : ℕ}, a < M → a' < M →
      events.getD a [] = events.getD a' [] → a = a' := by
    intro a a' ha ha' hEq
    rw [List.getD_eq_getElem _ _ ha, List.getD_eq_getElem _ _ ha'] at hEq
    have hnodup := restrictedSampledBadCodeStream_nodup c
      (restrictedCurveGridCode grid) ℬ.toPre N Δ T
    have hinj := List.nodup_iff_injective_get.mp hnodup
    have h2 := hinj (show events.get ⟨a, ha⟩ = events.get ⟨a', ha'⟩ by simpa using hEq)
    simpa using h2
  have hmapsTo : ∀ a ∈ (Finset.range M).filter (fun a => isL a = true),
      events.getD a [] ∈ (((List.range N).filter (fun l =>
        grid.i (l + 1) ≤ grid.i s)).toFinset.biUnion (fun l =>
          (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
            (grid.j l - (Δ + 1)) T).toFinset)) := by
    intro a ha
    rw [Finset.mem_filter] at ha
    have hprop : ∃ l, l < N ∧ grid.i (l + 1) ≤ grid.i s ∧
        events.getD a [] ∈ familyStageModelCodesList c (grid.i (l + 1))
          ℬ.toPre (grid.j l - (Δ + 1)) T := of_decide_eq_true ha.2
    obtain ⟨l, hlN, hle, hmem⟩ := hprop
    refine Finset.mem_biUnion.mpr ⟨l, ?_, List.mem_toFinset.mpr hmem⟩
    rw [List.mem_toFinset, List.mem_filter]
    exact ⟨List.mem_range.mpr hlN, by simpa using hle⟩
  have hinj : Set.InjOn (fun a => events.getD a [])
      ↑((Finset.range M).filter fun a => isL a = true) := by
    intro a ha a' ha' hEq
    have ha1 : a ∈ (Finset.range M).filter fun a => isL a = true := ha
    have ha2 : a' ∈ (Finset.range M).filter fun a => isL a = true := ha'
    rw [Finset.mem_filter, Finset.mem_range] at ha1 ha2
    exact hgetD_inj ha1.1 ha2.1 hEq
  calc ((Finset.range M).filter fun a => isL a = true).card
      ≤ (((List.range N).filter (fun l =>
          grid.i (l + 1) ≤ grid.i s)).toFinset.biUnion (fun l =>
            (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
              (grid.j l - (Δ + 1)) T).toFinset)).card :=
        Finset.card_le_card_of_injOn _ hmapsTo hinj
    _ ≤ ∑ l ∈ ((List.range N).filter (fun l =>
          grid.i (l + 1) ≤ grid.i s)).toFinset,
          (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
            (grid.j l - (Δ + 1)) T).toFinset.card :=
        Finset.card_biUnion_le
    _ ≤ ∑ _l ∈ ((List.range N).filter (fun l =>
          grid.i (l + 1) ≤ grid.i s)).toFinset, 2 ^ (grid.i s + 1) := by
        apply Finset.sum_le_sum
        intro l hl
        rw [List.mem_toFinset, List.mem_filter] at hl
        have hle : grid.i (l + 1) ≤ grid.i s := by
          have := hl.2
          simpa using this
        calc (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
              (grid.j l - (Δ + 1)) T).toFinset.card
            ≤ (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
                (grid.j l - (Δ + 1)) T).length := List.toFinset_card_le _
          _ ≤ 2 ^ (grid.i (l + 1) + 1) :=
              familyStageModelCodesList_length_le c _ ℬ.toPre _ T
          _ ≤ 2 ^ (grid.i s + 1) :=
              Nat.pow_le_pow_right (by omega) (by omega)
    _ = (((List.range N).filter (fun l =>
          grid.i (l + 1) ≤ grid.i s)).toFinset).card *
          2 ^ (grid.i s + 1) := by
        rw [Finset.sum_const, smul_eq_mul]
    _ ≤ N * 2 ^ (grid.i s + 1) := by
        apply Nat.mul_le_mul_right
        calc (((List.range N).filter (fun l =>
              grid.i (l + 1) ≤ grid.i s)).toFinset).card
            ≤ ((List.range N).filter (fun l =>
                grid.i (l + 1) ≤ grid.i s)).length :=
              List.toFinset_card_le _
          _ ≤ (List.range N).length := List.length_filter_le _ _
          _ = N := List.length_range

lemma mixedSmallEventDecodedVolume_le
    (ℬ : DescriptionFamily) (c : Nat.Partrec.Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (grid : RestrictedCurveGrid n k N target)
    (hstrict : ∀ i < k, target (i + 1) < target i)
    (Δ T s : ℕ) (hs : s ≤ N) :
  let events := restrictedSampledBadCodeStream c
    (restrictedCurveGridCode grid) ℬ.toPre N Δ T
  let isL := fun m => decide (∃ l, l < N ∧
    grid.i (l + 1) ≤ grid.i s ∧
    events.getD m [] ∈ familyStageModelCodesList c
      (grid.i (l + 1)) ℬ.toPre (grid.j l - (Δ + 1)) T)
  ∑ a ∈ (Finset.range events.length).filter
      (fun a => isL a = false),
      (decodeCoverCodeList (events.getD a [])).toFinset.card ≤
    N * 2 ^ (grid.i s + (grid.j s - (Δ + 1)) +
      Δ + (n / N + 1) + 4) := by
  intro events isL
  set M := events.length
  have hgetD_inj : ∀ {a a' : ℕ}, a < M → a' < M →
      events.getD a [] = events.getD a' [] → a = a' := by
    intro a a' ha ha' hEq
    rw [List.getD_eq_getElem _ _ ha, List.getD_eq_getElem _ _ ha'] at hEq
    have hnodup := restrictedSampledBadCodeStream_nodup c
      (restrictedCurveGridCode grid) ℬ.toPre N Δ T
    have hinj := List.nodup_iff_injective_get.mp hnodup
    have h2 := hinj (show events.get ⟨a, ha⟩ = events.get ⟨a', ha'⟩ by simpa using hEq)
    simpa using h2
  have hinj2 : Set.InjOn (fun a => events.getD a [])
      ↑((Finset.range M).filter (fun a => isL a = false)) := by
    intro a ha a' ha' hEq
    have ha1 : a ∈ (Finset.range M).filter (fun a => isL a = false) := ha
    have ha2 : a' ∈ (Finset.range M).filter (fun a => isL a = false) := ha'
    rw [Finset.mem_filter, Finset.mem_range] at ha1 ha2
    exact hgetD_inj ha1.1 ha2.1 hEq
  have hstep1 : ∑ a ∈ (Finset.range M).filter (fun a => isL a = false),
      (decodeCoverCodeList (events.getD a [])).toFinset.card =
      ∑ w ∈ ((Finset.range M).filter (fun a => isL a = false)).image
        (fun a => events.getD a []),
        (decodeCoverCodeList w).toFinset.card := by
    rw [Finset.sum_image hinj2]
  rw [hstep1]
  have himg : ((Finset.range M).filter (fun a => isL a = false)).image
      (fun a => events.getD a []) ⊆
      (((List.range N).filter (fun l =>
        ¬ grid.i (l + 1) ≤ grid.i s)).toFinset.biUnion (fun l =>
          (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
            (grid.j l - (Δ + 1)) T).toFinset)) := by
    intro w hw
    obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hw
    rw [Finset.mem_filter, Finset.mem_range] at ha
    obtain ⟨haM, hnotL⟩ := ha
    have hmem : events.getD a [] ∈ events := by
      rw [List.getD_eq_getElem _ _ haM]
      exact List.getElem_mem haM
    have hraw := restrictedSampledBadCodeStream_mem_raw c (restrictedCurveGridCode grid)
      ℬ.toPre N Δ T hmem
    rw [restrictedSampledBadCodesRaw, List.mem_flatMap] at hraw
    obtain ⟨l, hlrange, hlmem⟩ := hraw
    have hlN : l < N := List.mem_range.mp hlrange
    rw [decode_restrictedCurveGridCode_sample_eq grid
        (show l + 1 ≤ N by omega),
      decode_restrictedCurveGridCode_sample_eq grid
        (show l ≤ N by omega)] at hlmem
    have hgt : ¬ grid.i (l + 1) ≤ grid.i s := by
      intro hle
      have htrue : isL a = true :=
        decide_eq_true ⟨l, hlN, hle, hlmem⟩
      rw [hnotL] at htrue
      exact absurd htrue (by decide)
    refine Finset.mem_biUnion.mpr ⟨l, ?_, List.mem_toFinset.mpr hlmem⟩
    rw [List.mem_toFinset, List.mem_filter]
    exact ⟨List.mem_range.mpr hlN, by simpa using hgt⟩
  calc ∑ w ∈ ((Finset.range M).filter
        (fun a => isL a = false)).image (fun a => events.getD a []),
        (decodeCoverCodeList w).toFinset.card
      ≤ ∑ w ∈ (((List.range N).filter (fun l =>
          ¬ grid.i (l + 1) ≤ grid.i s)).toFinset.biUnion (fun l =>
            (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
              (grid.j l - (Δ + 1)) T).toFinset)),
          (decodeCoverCodeList w).toFinset.card :=
        Finset.sum_le_sum_of_subset himg
    _ ≤ ∑ l ∈ ((List.range N).filter (fun l =>
          ¬ grid.i (l + 1) ≤ grid.i s)).toFinset,
          ∑ w ∈ (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
            (grid.j l - (Δ + 1)) T).toFinset,
            (decodeCoverCodeList w).toFinset.card :=
        sum_biUnion_le' _ _ _
    _ ≤ ∑ _l ∈ ((List.range N).filter (fun l =>
          ¬ grid.i (l + 1) ≤ grid.i s)).toFinset,
          2 ^ (grid.i s + (grid.j s - (Δ + 1)) + Δ + (n / N + 1) + 4) := by
        apply Finset.sum_le_sum
        intro l hl
        rw [List.mem_toFinset, List.mem_filter] at hl
        have hlN : l < N := List.mem_range.mp hl.1
        have hgt : grid.i s < grid.i (l + 1) := by
          have := hl.2
          simp at this
          omega
        calc ∑ w ∈ (familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
              (grid.j l - (Δ + 1)) T).toFinset,
              (decodeCoverCodeList w).toFinset.card
            ≤ ((familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
                (grid.j l - (Δ + 1)) T).map fun w =>
                  (decodeCoverCodeList w).toFinset.card).sum :=
              sum_toFinset_le_list_sum' _ _
          _ ≤ 2 ^ (grid.i (l + 1) + 1) * 2 ^ (grid.j l - (Δ + 1)) :=
              familyStageModelCodesList_decoded_volume_le c _ ℬ.toPre _ T
          _ = 2 ^ (grid.i (l + 1) + 1 + (grid.j l - (Δ + 1))) :=
              (pow_add 2 _ _).symm
          _ ≤ 2 ^ (grid.i s + (grid.j s - (Δ + 1)) + Δ +
                (n / N + 1) + 4) :=
              Nat.pow_le_pow_right (by omega)
                (restrictedCurveGrid_sStage_exponent_le grid hstrict hs hlN hgt)
    _ = (((List.range N).filter (fun l =>
          ¬ grid.i (l + 1) ≤ grid.i s)).toFinset).card *
          2 ^ (grid.i s + (grid.j s - (Δ + 1)) + Δ + (n / N + 1) + 4) := by
        rw [Finset.sum_const, smul_eq_mul]
    _ ≤ N * 2 ^ (grid.i s + (grid.j s - (Δ + 1)) + Δ +
          (n / N + 1) + 4) := by
        apply Nat.mul_le_mul_right
        calc (((List.range N).filter (fun l =>
              ¬ grid.i (l + 1) ≤ grid.i s)).toFinset).card
            ≤ ((List.range N).filter (fun l =>
                ¬ grid.i (l + 1) ≤ grid.i s)).length :=
              List.toFinset_card_le _
          _ ≤ (List.range N).length := List.length_filter_le _ _
          _ = N := List.length_range

theorem exists_restrictedAnchoredEventChain_with_count_against
    (𝒢 ℬ : DescriptionFamily) (c : Nat.Partrec.Code)
    {n k N : ℕ} {target : ℕ → ℕ} (grid : RestrictedCurveGrid n k N target)
    (hN : N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1)
    (hkn : k ≤ n) (htarget : target 0 ≤ n)
    (hstrict : ∀ i < k, target (i + 1) < target i) (T : ℕ) :
    ∃ (chain : RestrictedRunChain 𝒢 (N + 1) (n + logSlack 8 n)
        (2 * 𝒢.overhead (n + logSlack 8 n))
        (restrictedAnchoredTarget (n + logSlack 8 n) (sqrtSlack 8 n) grid)
        (restrictedSampledBadCodeStream c (restrictedCurveGridCode grid)
          ℬ.toPre N (sqrtSlack 8 n) T).length)
      (codes : ℕ → BitString),
      (∀ m,
        (restrictedEffectiveAnchoredInitialState 𝒢 (n + logSlack 8 n)
            (sqrtSlack 8 n) grid).bind
          (fun st0 => restrictedEventPrefixRun 𝒢
            (𝒢.overhead (n + logSlack 8 n))
            (restrictedEffectiveAnchoredSizes (n + logSlack 8 n)
              (sqrtSlack 8 n) grid) st0
            (restrictedSampledBadCodeStream c (restrictedCurveGridCode grid)
              ℬ.toPre N (sqrtSlack 8 n) T) m) = Part.some (codes m) ∧
        DecodesToRestrictedSampledRunState (codes m) (chain.states m)) ∧
      (∀ m, chain.bads m = (decodeCoverCodeList
        ((restrictedSampledBadCodeStream c (restrictedCurveGridCode grid)
          ℬ.toPre N (sqrtSlack 8 n) T).getD m [])).toFinset) ∧
      (chain.states 0).B 0 = stringsOfLength (n + logSlack 8 n) ∧
      (chain.states 0).live 0 = stringsOfLength (n + logSlack 8 n) ∧
      ∀ s ≤ N, (chain.rebuildSteps s).card ≤
        2 ^ (grid.i s + anchoredVersionExp 𝒢 n N) := by
  classical
  set Δ := sqrtSlack 8 n with hΔdef
  set gridCode := restrictedCurveGridCode grid with hgridCodeDef
  set events := restrictedSampledBadCodeStream c gridCode ℬ.toPre N Δ T
    with heventsDef
  set M := events.length with hMdef
  set OB := 2 * 𝒢.overhead (n + logSlack 8 n) with hOBdef
  have hnamb : n ≤ n + logSlack 8 n := Nat.le_add_right _ _
  obtain ⟨chain, codes, hfold, hbads, hB0, hlive0⟩ :=
    exists_restrictedAnchoredEventChain_against 𝒢 ℬ c (n + logSlack 8 n) Δ grid
      hnamb T
  refine ⟨chain, codes, hfold, hbads, hB0, hlive0, ?_⟩
  intro s hsN
  have hbadsub : ∀ m : ℕ, m < M → chain.bads m ⊆
      restrictedAnchoredProcessedBadUnion c ℬ Δ grid (T + 1) := by
    intro m hm x hx
    rw [hbads m, List.mem_toFinset] at hx
    rw [restrictedAnchoredProcessedBadUnion_eq_codes,
      restrictedAnchoredProcessedBadCodes_succ]
    refine (mem_restrictedDecodedBadCodesUnion_iff _ x).mpr
      ⟨events.getD m [], ?_, List.mem_toFinset.mpr hx⟩
    rw [List.getD_eq_getElem _ _ hm]
    exact List.getElem_mem hm
  have hUcard : 2 * (restrictedAnchoredProcessedBadUnion c ℬ Δ grid
      (T + 1)).card < 2 ^ (n + logSlack 8 n) := by
    calc 2 * (restrictedAnchoredProcessedBadUnion c ℬ Δ grid (T + 1)).card
        ≤ 2 * ((List.range N).map fun s' =>
            2 ^ (grid.i (s' + 1) + 1) *
              2 ^ (grid.j s' - (Δ + 1))).sum :=
          Nat.mul_le_mul_left 2
            (restrictedAnchoredProcessedBadUnion_card_le c ℬ Δ grid T)
      _ < 2 ^ (n + logSlack 8 n) :=
          restrictedCurveGrid_bad_volume_padding_half grid hN hkn htarget
            hstrict
  have hroot : ∀ m ≤ M, 2 ^ (restrictedAnchoredTarget (n + logSlack 8 n) Δ
      grid) 0 ≤ 2 * ((chain.states m).live 0).card := by
    intro m hm
    have hwin := chain.window_live_eq (Nat.zero_le m) hm
      (fun m' _ _ => Nat.zero_le _)
    rw [hwin, hlive0]
    have hsub : (Finset.Ico 0 m).biUnion chain.bads ⊆
        restrictedAnchoredProcessedBadUnion c ℬ Δ grid (T + 1) := by
      intro x hx
      obtain ⟨a, ha, hxa⟩ := Finset.mem_biUnion.mp hx
      rw [Finset.mem_Ico] at ha
      exact hbadsub a (by omega) hxa
    have hcardsub := Finset.card_le_card hsub
    have hcube : (stringsOfLength (n + logSlack 8 n)).card =
        2 ^ (n + logSlack 8 n) := cardStringsOfLength _
    have hsdiff := Finset.card_le_card_sdiff_add_card
      (s := stringsOfLength (n + logSlack 8 n))
      (t := (Finset.Ico 0 m).biUnion chain.bads)
    rw [restrictedAnchoredTarget_zero]
    omega
  have hmono : ∀ r < N + 1,
      restrictedAnchoredTarget (n + logSlack 8 n) Δ grid (r + 1) ≤
        restrictedAnchoredTarget (n + logSlack 8 n) Δ grid r :=
    restrictedAnchoredTarget_mono _ _ grid hnamb
  have hOB1 : 1 ≤ OB := by
    have := 𝒢.overhead_pos (n + logSlack 8 n)
    omega
  set isL : ℕ → Bool := fun m => decide (∃ l, l < N ∧
    grid.i (l + 1) ≤ grid.i s ∧ events.getD m [] ∈
      familyStageModelCodesList c (grid.i (l + 1)) ℬ.toPre
        (grid.j l - (Δ + 1)) T) with hisL
  have hLcard : ((Finset.range M).filter fun a => isL a = true).card ≤
      N * 2 ^ (grid.i s + 1) :=
    mixedLargeEventCount_le ℬ c grid Δ T s hsN
  have hSsum : ∑ a ∈ (Finset.range M).filter (fun a => isL a = false),
      (chain.bads a).card ≤
      N * 2 ^ (grid.i s + (grid.j s - (Δ + 1)) + Δ + (n / N + 1) + 4) := by
    have hsumeq : ∑ a ∈ (Finset.range M).filter (fun a => isL a = false),
        (chain.bads a).card =
        ∑ a ∈ (Finset.range M).filter (fun a => isL a = false),
        (decodeCoverCodeList (events.getD a [])).toFinset.card := by
      apply Finset.sum_congr rfl
      intro x hx
      rw [hbads x]
    rw [hsumeq]
    exact mixedSmallEventDecodedVolume_le ℬ c grid hstrict Δ T s hsN
  have hmain := chain.rebuildSteps_card_mul_le hroot hmono hOB1
    (show s < N + 1 by omega) isL hLcard hSsum
  rw [restrictedAnchoredTarget_succ] at hmain
  have hVSsplit : N * 2 ^ (grid.i s + (grid.j s - (Δ + 1)) + Δ +
      (n / N + 1) + 4) =
      N * 2 ^ (grid.i s + Δ + (n / N + 1) + 4) *
        2 ^ (grid.j s - (Δ + 1)) := by
    rw [mul_assoc, ← pow_add]
    congr 2
    omega
  rw [hVSsplit] at hmain
  have hfact : (s + 1) * ((N * 2 ^ (grid.i s + 1) + 1) *
      2 ^ (grid.j s - (Δ + 1)) +
      2 * OB ^ (s + 1) *
        (N * 2 ^ (grid.i s + Δ + (n / N + 1) + 4) *
          2 ^ (grid.j s - (Δ + 1)))) =
      ((s + 1) * (N * 2 ^ (grid.i s + 1) + 1 +
        2 * OB ^ (s + 1) *
          (N * 2 ^ (grid.i s + Δ + (n / N + 1) + 4)))) *
        2 ^ (grid.j s - (Δ + 1)) := by
    ring
  rw [hfact] at hmain
  have hcount := Nat.le_of_mul_le_mul_right hmain (pow_pos (by omega) _)
  have hNN : N + 1 ≤ 2 ^ (Nat.bits (N + 1)).length := by
    rw [Nat.size_eq_bits_len]
    exact (Nat.lt_size_self (N + 1)).le
  have hOBsize : OB ≤ 2 ^ (Nat.bits OB).length := by
    rw [Nat.size_eq_bits_len]
    exact (Nat.lt_size_self OB).le
  have harith := version_count_arith_against (I := grid.i s) (Δm := Δ)
    (mesh := n / N + 1) (LN := (Nat.bits (N + 1)).length)
    (Lob := (Nat.bits OB).length) (NN := N) (OB := OB) (s := s)
    hNN hOBsize hsN
  refine hcount.trans (harith.trans (Nat.pow_le_pow_right (by omega) ?_))
  have hexp : anchoredVersionExp 𝒢 n N =
      (N + 2) * (Nat.bits OB).length +
        2 * (Nat.bits (N + 1)).length + Δ + (n / N + 1) + 9 := rfl
  rw [hexp]
  have hmul : (N + 1) * (Nat.bits OB).length ≤
      (N + 2) * (Nat.bits OB).length :=
    Nat.mul_le_mul_right _ (by omega)
  omega

/-- Every terminal sampled model in a mixed run has a version-coded
description whose overhead is controlled solely by the good family. -/
theorem restrictedAnchoredState_model_complexity_against
    (U : Map) (hU : IsOptimalPrefixConditional U)
    (𝒢 ℬ : DescriptionFamily) (hPoly : 𝒢.HasPolynomialOverhead)
    (c : Code) (_hc : IsCodeFor c U) :
    ∃ c_ver : ℕ, ∀ {n k N : ℕ} {t : ℕ → ℕ}
      (grid : RestrictedCurveGrid n k N t)
      (_hN : N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1)
      (_hkn : k ≤ n) (_ht0 : t 0 ≤ n)
      (_hstrict : ∀ i : ℕ, i < k → t (i + 1) < t i)
      (T : ℕ) (output : BitString)
      (state : RestrictedSampledRunState 𝒢 (N + 1)
          (n + logSlack 8 n)
          (2 * 𝒢.overhead (n + logSlack 8 n))
          (restrictedAnchoredTarget (n + logSlack 8 n)
            (sqrtSlack 8 n) grid)),
      restrictedEffectiveAnchoredSampledRunAgainst 𝒢 ℬ c
          (n + logSlack 8 n) (sqrtSlack 8 n) grid (T + 1) =
            Part.some output →
      DecodesToRestrictedSampledRunState output state →
      ∀ s (_hs : s ≤ N) (hS : (state.B (s + 1)).Nonempty),
        setComplexity U (state.B (s + 1)) hS ≤
          (grid.i s + sqrtSlack c_ver n +
            KPPlain U (restrictedCurveGridCode grid) : ENat) := by
  classical
  obtain ⟨c_F, hF⟩ := KPPlain_partrec_map_le U hU
    (anchoredVersionDecoderAgainst 𝒢 ℬ c)
    (anchoredVersionDecoderAgainst_partrec 𝒢 ℬ c)
  obtain ⟨c_L, hLc⟩ := KPPlain_listCode_le U hU
  obtain ⟨c_lg, hlg⟩ := KPPlain_le_length_add_log U hU
  obtain ⟨c_P, hPex⟩ := anchoredVersionExp_le_sqrtSlack 𝒢 hPoly
  obtain ⟨c_over, hover⟩ := 𝒢.overhead_bits_le_logSlack hPoly
  refine ⟨c_P + 15 * c_over + 3 * c_lg + 5 * c_L + c_F +
    2 * Nat.size (c_P + 1) + 40, ?_⟩
  intro n k N t grid hN hkn ht0 hstrict T output state hrun hdec
    s hs hS
  obtain ⟨chain, codes, hfold, _hbads, _hB0, _hlive0, hcount⟩ :=
    exists_restrictedAnchoredEventChain_with_count_against 𝒢 ℬ c grid
      hN hkn ht0 hstrict T
  have hboundary :=
    restrictedEffectiveAnchoredSampledRunAgainst_eq_eventPrefix
      𝒢 ℬ c (n + logSlack 8 n) (sqrtSlack 8 n) grid (le_refl T)
  have hout :
      output = codes ((restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length) := by
    rw [hboundary] at hrun
    exact Part.some_injective (hrun.symm.trans (hfold _).1)
  have hdec' :
      DecodesToRestrictedSampledRunState
        (codes ((restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) T).length)) state :=
    hout ▸ hdec
  have hBeq := decodesTo_eq_B_live hdec'
    ((hfold ((restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) T).length)).2) (s := s + 1) (by omega)
  have hS' :
      ((chain.states ((restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T).length)).B (s + 1)).Nonempty := by
    rw [← hBeq.1]
    exact hS
  obtain ⟨v, hvle, heval⟩ :=
    anchoredVersionDecoderAgainst_terminal 𝒢 ℬ c grid hN T
      chain codes hfold s hs hS'
  have hv2 :
      v ≤ 2 ^ (grid.i s + anchoredVersionExp 𝒢 n N) :=
    hvle.trans (hcount s hs)
  have hmem :
      (codedUniformOn ((chain.states
        ((restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) T).length)).B (s + 1)) hS').code ∈
        anchoredVersionDecoderAgainst 𝒢 ℬ c
          (listCode [restrictedCurveGridCode grid,
            Nat.bits (𝒢.overhead (n + logSlack 8 n)),
            Nat.bits s, Nat.bits v]) := by
    rw [heval]
    exact Part.mem_some_iff.mpr rfl
  have hKP1 := hF _ _ hmem
  have hKP2 := hLc [restrictedCurveGridCode grid,
    Nat.bits (𝒢.overhead (n + logSlack 8 n)), Nat.bits s, Nat.bits v]
  have hq0c :
      KPPlain U (Nat.bits (𝒢.overhead (n + logSlack 8 n))) ≤
        (((Nat.bits (𝒢.overhead (n + logSlack 8 n))).length +
          2 * (Nat.bits (Nat.bits
            (𝒢.overhead (n + logSlack 8 n))).length).length +
          c_lg : ℕ) : ENat) := by
    have h := hlg (Nat.bits (𝒢.overhead (n + logSlack 8 n)))
    push_cast
    exact h
  have hsc :
      KPPlain U (Nat.bits s) ≤
        (((Nat.bits s).length +
          2 * (Nat.bits (Nat.bits s).length).length +
          c_lg : ℕ) : ENat) := by
    have h := hlg (Nat.bits s)
    push_cast
    exact h
  have hvc :
      KPPlain U (Nat.bits v) ≤
        (((Nat.bits v).length +
          2 * (Nat.bits (Nat.bits v).length).length +
          c_lg : ℕ) : ENat) := by
    have h := hlg (Nat.bits v)
    push_cast
    exact h
  have hNat :=
    mixedDecoderBundleCost_le 𝒢 grid hN hkn hover
      (hPex n N hN) hs hv2 c_lg c_L c_F
  have hset :
      setComplexity U (state.B (s + 1)) hS =
        KPPlain U ((codedUniformOn ((chain.states
          ((restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N
            (sqrtSlack 8 n) T).length)).B (s + 1)) hS').code) := by
    unfold setComplexity
    congr 1
    exact codedUniformOn_code_congr hS hS' hBeq.1
  rw [hset]
  have hsum :
      (([restrictedCurveGridCode grid,
        Nat.bits (𝒢.overhead (n + logSlack 8 n)),
        Nat.bits s, Nat.bits v]).map fun x => KPPlain U x).sum =
        KPPlain U (restrictedCurveGridCode grid) +
          (KPPlain U (Nat.bits (𝒢.overhead (n + logSlack 8 n))) +
            (KPPlain U (Nat.bits s) + KPPlain U (Nat.bits v))) := by
    simp [List.sum_cons]
  calc
    KPPlain U ((codedUniformOn ((chain.states
        ((restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) T).length)).B (s + 1)) hS').code)
        ≤ KPPlain U (listCode [restrictedCurveGridCode grid,
            Nat.bits (𝒢.overhead (n + logSlack 8 n)),
            Nat.bits s, Nat.bits v]) + (c_F : ENat) := hKP1
    _ ≤ ((([restrictedCurveGridCode grid,
          Nat.bits (𝒢.overhead (n + logSlack 8 n)),
          Nat.bits s, Nat.bits v]).map fun x => KPPlain U x).sum +
          ((c_L * 5 : ℕ) : ENat)) + (c_F : ENat) := by
      gcongr
      simpa using hKP2
    _ = KPPlain U (restrictedCurveGridCode grid) +
          (KPPlain U (Nat.bits (𝒢.overhead (n + logSlack 8 n))) +
            (KPPlain U (Nat.bits s) + KPPlain U (Nat.bits v))) +
          ((c_L * 5 : ℕ) : ENat) + (c_F : ENat) := by
      rw [hsum]
    _ ≤ KPPlain U (restrictedCurveGridCode grid) +
          ((((Nat.bits (𝒢.overhead (n + logSlack 8 n))).length +
            2 * (Nat.bits (Nat.bits
              (𝒢.overhead (n + logSlack 8 n))).length).length +
            c_lg : ℕ) : ENat) +
          ((((Nat.bits s).length +
            2 * (Nat.bits (Nat.bits s).length).length +
            c_lg : ℕ) : ENat) +
          (((Nat.bits v).length +
            2 * (Nat.bits (Nat.bits v).length).length +
            c_lg : ℕ) : ENat))) +
          ((c_L * 5 : ℕ) : ENat) + (c_F : ENat) := by
      gcongr
    _ = KPPlain U (restrictedCurveGridCode grid) +
          ((((Nat.bits (𝒢.overhead (n + logSlack 8 n))).length +
            2 * (Nat.bits (Nat.bits
              (𝒢.overhead (n + logSlack 8 n))).length).length + c_lg) +
          ((Nat.bits s).length +
            2 * (Nat.bits (Nat.bits s).length).length + c_lg) +
          ((Nat.bits v).length +
            2 * (Nat.bits (Nat.bits v).length).length + c_lg) +
          c_L * 5 + c_F : ℕ) : ENat) := by
      push_cast
      ring
    _ ≤ KPPlain U (restrictedCurveGridCode grid) +
          ((grid.i s +
            sqrtSlack (c_P + 15 * c_over + 3 * c_lg +
              5 * c_L + c_F + 2 * Nat.size (c_P + 1) + 40) n :
              ℕ) : ENat) := by
      gcongr
    _ = (grid.i s +
          sqrtSlack (c_P + 15 * c_over + 3 * c_lg +
            5 * c_L + c_F + 2 * Nat.size (c_P + 1) + 40) n +
          KPPlain U (restrictedCurveGridCode grid) : ENat) := by
      push_cast
      ring

/-- The mixed structural run, version decoder, and static grid interpolation
assemble into a common all-index output. -/
theorem exists_restricted_coupled_output_against
    (U : Map) (hU : IsOptimalPrefixConditional U)
    (𝒢 ℬ : DescriptionFamily) (hPoly : 𝒢.HasPolynomialOverhead) :
    ∃ c_run : ℕ, ∀ (c_grid n k N : ℕ) (t : ℕ → ℕ)
        (grid : RestrictedCurveGrid n k N t),
      N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1 →
      KPPlain U (restrictedCurveGridCode grid) ≤
        (sqrtSlack c_grid n : ENat) →
      k ≤ n →
      t 0 ≤ n →
      t k = 0 →
      (∀ i : ℕ, i < k → t (i + 1) < t i) →
      Nonempty (RestrictedCoupledOutputAgainst 𝒢 ℬ U n k
        (c_grid + 8 + c_run) t) := by
  classical
  obtain ⟨c, hc⟩ := exists_codeFor_map U hU
  obtain ⟨c_two, htwo⟩ := KP_le_setComplexity_add_condKP U hU
  obtain ⟨c_idx, hidx⟩ := KP_le_log_card_given_setCode U hU
  obtain ⟨c_ver, hver⟩ :=
    restrictedAnchoredState_model_complexity_against
      U hU 𝒢 ℬ hPoly c hc
  refine ⟨c_ver + c_two + c_idx + 9, ?_⟩
  intro c_grid n k N t grid hN hgrid hkn ht0 _htk hstrict
  obtain ⟨T, output, state, hrun, hdec,
      survivor, hsurvivor, hsurvivorAvoid⟩ :=
    exists_restricted_anchored_structural_output_for_code_against
      U 𝒢 ℬ c hc grid hN hkn ht0 hstrict
  have hbound :=
    hver grid hN hkn ht0 hstrict T output state hrun hdec
  set cfin := c_grid + 8 + (c_ver + c_two + c_idx + 9)
    with hcfin
  have hslack_le :
      sqrtSlack (c_grid + c_ver) n ≤ sqrtSlack cfin n :=
    sqrtSlack_mono_left (by omega) n
  have hcomplexity :
      ∀ s (_hs : s ≤ N) (hS : (state.B (s + 1)).Nonempty),
        setComplexity U (state.B (s + 1)) hS ≤
          (grid.i s + sqrtSlack cfin n : ENat) := by
    intro s hs hS
    have hraw := hbound s hs hS
    calc
      setComplexity U (state.B (s + 1)) hS
          ≤ (grid.i s + sqrtSlack c_ver n : ENat) +
              KPPlain U (restrictedCurveGridCode grid) := by
            exact_mod_cast hraw
      _ ≤ (grid.i s + sqrtSlack c_ver n : ENat) +
              sqrtSlack c_grid n := by
            gcongr
      _ = (grid.i s : ENat) +
              ((sqrtSlack c_ver n : ENat) +
                sqrtSlack c_grid n) := by
            ac_rfl
      _ = (grid.i s : ENat) +
              (sqrtSlack (c_grid + c_ver) n : ENat) := by
            exact_mod_cast (show
              grid.i s + (sqrtSlack c_ver n + sqrtSlack c_grid n) =
                grid.i s + sqrtSlack (c_grid + c_ver) n by
              rw [← sqrtSlack_add c_grid c_ver n]
              omega)
      _ ≤ (grid.i s + sqrtSlack cfin n : ENat) := by
            exact_mod_cast Nat.add_le_add_left hslack_le (grid.i s)
  have hcandidate :
      ∀ x ∈ state.live (N + 1),
        KPPlain U x ≤ (k + sqrtSlack cfin n : ENat) := by
    intro x hx
    have hxB : x ∈ state.B (N + 1) :=
      state.live_subset (N + 1) le_rfl hx
    have hSne : (state.B (N + 1)).Nonempty := ⟨x, hxB⟩
    have hsetC :
        setComplexity U (state.B (N + 1)) hSne ≤
          ((k + sqrtSlack (c_grid + c_ver) n : ℕ) : ENat) := by
      have h := hbound N le_rfl hSne
      rw [grid.i_end] at h
      calc
        setComplexity U (state.B (N + 1)) hSne
            ≤ (k + sqrtSlack c_ver n : ENat) +
                KPPlain U (restrictedCurveGridCode grid) := by
              exact_mod_cast h
        _ ≤ (k + sqrtSlack c_ver n : ENat) +
                sqrtSlack c_grid n := by
              gcongr
        _ = ((k + sqrtSlack (c_grid + c_ver) n : ℕ) :
                ENat) := by
              exact_mod_cast (show
                k + sqrtSlack c_ver n + sqrtSlack c_grid n =
                  k + sqrtSlack (c_grid + c_ver) n by
                rw [← sqrtSlack_add c_grid c_ver n]
                omega)
    have hcard : (state.B (N + 1)).card ≤ 1 := by
      have hsb := state.size_bound (N + 1) le_rfl
      have htar :
          restrictedAnchoredTarget (n + logSlack 8 n)
            (sqrtSlack 8 n) grid (N + 1) = 0 := by
        rw [restrictedAnchoredTarget_succ, grid.j_end]
        omega
      rw [htar] at hsb
      simpa using hsb
    have hbits :
        (Nat.bits (state.B (N + 1)).card).length ≤ 1 := by
      have h1 : (Nat.bits 1).length = 1 := by decide
      exact (length_natBits_mono hcard).trans (le_of_eq h1)
    have hKPcond :
        KP U x (codedUniformOn (state.B (N + 1)) hSne).code ≤
          ((1 + c_idx : ℕ) : ENat) := by
      refine (hidx _ hSne x hxB).trans ?_
      have :
          (Nat.bits (state.B (N + 1)).card).length + c_idx ≤
            1 + c_idx :=
        Nat.add_le_add_right hbits c_idx
      exact_mod_cast this
    calc
      KPPlain U x
          ≤ setComplexity U (state.B (N + 1)) hSne +
              KP U x (codedUniformOn
                (state.B (N + 1)) hSne).code +
              (c_two : ENat) :=
            htwo (state.B (N + 1)) hSne x hxB
      _ ≤ ((k + sqrtSlack (c_grid + c_ver) n : ℕ) : ENat) +
              ((1 + c_idx : ℕ) : ENat) + (c_two : ENat) := by
            gcongr
      _ = ((k + sqrtSlack (c_grid + c_ver) n +
              (1 + c_idx) + c_two : ℕ) : ENat) := by
            push_cast
            rfl
      _ ≤ ((k + sqrtSlack cfin n : ℕ) : ENat) := by
            apply Nat.cast_le.mpr
            have habs :
                sqrtSlack (c_grid + c_ver) n +
                    (1 + c_idx + c_two) ≤
                  sqrtSlack cfin n :=
              sqrtSlack_add_const_le n (by omega)
            omega
  have havoids :
      survivor ∉ restrictedProfileBadSet ℬ U
        (state.live (N + 1)) k (sqrtSlack cfin n) t := by
    intro hmem
    exact hsurvivorAvoid
      (restrictedProfileBadSet_antitone ℬ U
        (state.live (N + 1)) k
        (sqrtSlack_mono_left (by omega) n) t hmem)
  have hlive_le :
      ∀ {s₁ s₂ : ℕ}, s₁ ≤ s₂ → s₂ ≤ N + 1 →
        state.live s₂ ⊆ state.live s₁ := by
    intro s₁ s₂ h12
    induction h12 with
    | refl => exact fun _ _ hx => hx
    | @step m hm ih =>
        intro hm1 x hx
        exact ih (by omega) (state.live_monotonic m (by omega) hx)
  have hmesh : n / N + 1 ≤ sqrtSlack cfin n := by
    rw [hN]
    exact (restrictedCurveGrid_mesh_le_sqrtSlack n).trans
      (sqrtSlack_mono_left (by omega) n)
  let pred : ℕ → ℕ := restrictedCurveGridPredecessor grid hstrict
  refine ⟨{
    ambientLength := n + logSlack 8 n
    n_le_ambient := Nat.le_add_right _ _
    ambient_le := Nat.add_le_add_left
      (logSlack_mono_left (by omega) n) n
    goodSets := fun idx => state.B (pred idx + 1)
    mem_family := ?_
    size_bound := ?_
    complexity_bound := ?_
    candidates := state.live (N + 1)
    candidates_nonempty := ⟨survivor, hsurvivor⟩
    candidate_len := fun x hx =>
      state.live_ambient (N + 1) le_rfl x hx
    candidate_mem := ?_
    candidate_complexity := hcandidate
    survivor := survivor
    survivor_mem := hsurvivor
    survivor_not_bad := havoids }⟩
  · intro idx hidx
    have hp :=
      restrictedCurveGridPredecessor_spec grid hstrict idx hidx
    change pred idx < N ∧
      grid.i (pred idx) ≤ idx ∧
      grid.j (pred idx) ≤ t idx + (n / N + 1) at hp
    exact state.mem_family (pred idx + 1) (by omega)
  · intro idx hidx
    have hp :=
      restrictedCurveGridPredecessor_spec grid hstrict idx hidx
    change pred idx < N ∧
      grid.i (pred idx) ≤ idx ∧
      grid.j (pred idx) ≤ t idx + (n / N + 1) at hp
    calc
      (state.B (pred idx + 1)).card
          ≤ 2 ^ restrictedAnchoredTarget (n + logSlack 8 n)
              (sqrtSlack 8 n) grid (pred idx + 1) :=
            state.size_bound (pred idx + 1) (by omega)
      _ ≤ 2 ^ grid.j (pred idx) := by
            apply Nat.pow_le_pow_right (by norm_num)
            rw [restrictedAnchoredTarget_succ]
            exact Nat.sub_le _ _
      _ ≤ 2 ^ (t idx + sqrtSlack cfin n) := by
            apply Nat.pow_le_pow_right (by norm_num)
            exact hp.2.2.trans
              (Nat.add_le_add_left hmesh (t idx))
  · intro idx hidx hS
    have hp :=
      restrictedCurveGridPredecessor_spec grid hstrict idx hidx
    change pred idx < N ∧
      grid.i (pred idx) ≤ idx ∧
      grid.j (pred idx) ≤ t idx + (n / N + 1) at hp
    calc
      setComplexity U (state.B (pred idx + 1)) hS
          ≤ (grid.i (pred idx) + sqrtSlack cfin n : ENat) :=
            hcomplexity (pred idx) (Nat.le_of_lt hp.1) hS
      _ ≤ (idx + sqrtSlack cfin n : ENat) := by
            exact_mod_cast
              Nat.add_le_add_right hp.2.1 (sqrtSlack cfin n)
  · intro x hx idx hidx
    have hp :=
      restrictedCurveGridPredecessor_spec grid hstrict idx hidx
    change pred idx < N ∧
      grid.i (pred idx) ≤ idx ∧
      grid.j (pred idx) ≤ t idx + (n / N + 1) at hp
    exact state.live_subset (pred idx + 1) (by omega)
      (hlive_le (Nat.succ_le_succ (Nat.le_of_lt hp.1)) le_rfl hx)

/-- Joint restricted-curve realization: rebuilding in `𝒢` and excluding bad
descriptions from `ℬ` produces one string realizing the curve in both
families. -/
theorem prop_family_curve_against
    (U : Map) (hU : IsOptimalPrefixConditional U)
    (𝒢 ℬ : DescriptionFamily)
    (hPoly : 𝒢.HasPolynomialOverhead)
    (hsub : ∀ S, 𝒢.mem S → ℬ.mem S) :
    ∃ c : ℕ, ∀ (n k : ℕ) (t : ℕ → ℕ),
      k ≤ n →
      t 0 ≤ n →
      t k = 0 →
      (∀ i : ℕ, i < k → t (i + 1) < t i) →
      ∃ x : BitString, ∃ n' : ℕ,
        x.length = n' ∧
        n ≤ n' ∧
        n' ≤ n + logSlack c n ∧
        KPPlain U x ≤ (k + sqrtSlack c n : ENat) ∧
        RestrictedProfileWithinCurve 𝒢 U x k t
          (sqrtSlack c n) ∧
        RestrictedProfileWithinCurve ℬ U x k t
          (sqrtSlack c n) := by
  obtain ⟨c_grid, hgrid⟩ :=
    exists_encoded_restricted_curve_grid U hU
  obtain ⟨c_run, hrun⟩ :=
    exists_restricted_coupled_output_against U hU 𝒢 ℬ hPoly
  refine ⟨c_grid + 8 + c_run, ?_⟩
  intro n k t hkn ht0 htk hstrict
  obtain ⟨N, grid, hN, hgridComplexity⟩ :=
    hgrid n k t hkn ht0 htk hstrict
  obtain ⟨output⟩ :=
    hrun c_grid n k N t grid hN hgridComplexity
      hkn ht0 htk hstrict
  obtain ⟨hprofileG, hprofileB⟩ := output.profiles hsub
  exact ⟨output.survivor, output.ambientLength,
    output.candidate_len output.survivor output.survivor_mem,
    output.n_le_ambient, output.ambient_le,
    output.candidate_complexity output.survivor output.survivor_mem,
    hprofileG, hprofileB⟩

end Kolmogorov
