import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.MixedFamilyRun
import KolmogorovMathlib.Restricted.FamilyCurve.VersionClose
import KolmogorovMathlib.Restricted.FamilyCurve

/-!
# The mixed-family version decoder

The curve-realization run is normally taken inside one description family; the joint statement
needs a run that *rebuilds* in a family `𝒢` while avoiding the bad descriptions of a second
family `ℬ`.  This part builds the decoder for that mixed run.

`anchoredDecoderTraceAgainst` is the event-indexed trace of a `𝒢`-rebuild driven by the `ℬ`
bad stream, `anchoredChangeTraceAgainst` counts its changes, and
`anchoredVersionDecoderAgainst` is the version decoder reading the same four-field bundle as
the one-family decoder.  The three `_self` lemmas check that on the diagonal `𝒢 = ℬ` these
definitionally recover the one-family notions, the `_partrec` lemmas make them effective, and
`anchoredDecoderTraceAgainst_replay`, `anchoredVersionDecoderAgainst_eval` and
`exists_restrictedAnchoredEventChain_against` show the run is a genuine event chain.

`RestrictedCoupledOutputAgainst` is the output structure — good models in `𝒢`, a common
survivor avoiding the forbidden descriptions of `ℬ` — with `toDiagonal` and `profiles`
relating it to the one-family case.  The counting is in `Part02`, the assembly in `Part03`.
-/



namespace Kolmogorov

open Nat.Partrec (Code)

/- Keep the large product encodings and code-level executor components opaque
during the partial-recursiveness compositions. -/
attribute [local irreducible] Primcodable.prod Primcodable.list
attribute [local irreducible]
  restrictedEffectiveLiveCodesAfterDelete
  restrictedEffectiveDeleteCode
  restrictedSelectorField
  restrictedEffectiveDensityFailsBool
  restrictedEffectiveFirstFailedScale
  restrictedDecodedCoverCard
  restrictedEffectiveSampledRunStepPost
  restrictedEffectiveSampledStateCode
  restrictedEffectiveSampledRunStepInput
  restrictedEffectiveRebuildSuffixInput
  restrictedEffectiveSampledRunStep
  restrictedAnchoredInitialFromCode
  restrictedAnchoredSizesFromCode
  restrictedSampledBadCodeStream
  restrictedSampledBadCodesUpToTime
  restrictedSampledBadCodesRaw
  anchoredDecodedSteps
  anchoredDecodedSlack
  anchoredDecodedAmbientLength
  anchoredDecodedLength
  anchoredModelListAt

/-- Event-indexed decoder trace for a `𝒢` rebuild driven by the `ℬ` bad
stream. -/
noncomputable def anchoredDecoderTraceAgainst
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 m : ℕ) : Part BitString :=
  let Nst := anchoredDecodedSteps gridCode
  let Δ := anchoredDecodedSlack gridCode
  let amb := anchoredDecodedAmbientLength gridCode
  (Nat.rfind (fun τ => Part.some (decide (m ≤
      (restrictedSampledBadCodeStream c gridCode ℬ.toPre Nst Δ
        τ).length)))).bind
    (fun τ => (restrictedAnchoredInitialFromCode 𝒢 q0 gridCode Nst Δ
        amb).bind
      (fun st0 => restrictedEventPrefixRun 𝒢 q0
        (restrictedAnchoredSizesFromCode gridCode Nst Δ amb) st0
        (restrictedSampledBadCodeStream c gridCode ℬ.toPre Nst Δ τ) m))

/-- Change-counting trace for the mixed decoder. -/
noncomputable def anchoredChangeTraceAgainst
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 s : ℕ) :
    ℕ → Part (ℕ × List BitString)
  | 0 => (anchoredDecoderTraceAgainst 𝒢 ℬ c gridCode q0 0).map
      (fun code => (0, anchoredModelListAt s code))
  | m + 1 =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c gridCode q0 s m).bind
        (fun p =>
          (anchoredDecoderTraceAgainst 𝒢 ℬ c gridCode q0
            (m + 1)).map (fun code =>
              if anchoredModelListAt s code = p.2 then (p.1, p.2)
              else (p.1 + 1, anchoredModelListAt s code)))

/-- Fixed-`𝒢`, fixed-`ℬ` version decoder.  Its input is the same four-field
bundle as the one-family decoder. -/
noncomputable def anchoredVersionDecoderAgainst
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (bundle : BitString) : Part BitString :=
  let parts := decodeListCode bundle
  let gridCode := parts.getD 0 []
  let q0 := bitsToNat (parts.getD 1 [])
  let s := bitsToNat (parts.getD 2 [])
  let v := bitsToNat (parts.getD 3 [])
  (Nat.rfind (fun m =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c gridCode q0 s m).map
        (fun p => decide (v ≤ p.1)))).bind
    (fun m =>
      (anchoredChangeTraceAgainst 𝒢 ℬ c gridCode q0 s m).map
        (fun p => uniformCodeOfList p.2))

/-- Coupled all-index output with good models in `𝒢` and a common survivor
avoiding the forbidden profile generated by `ℬ`. -/
structure RestrictedCoupledOutputAgainst
    (𝒢 ℬ : DescriptionFamily) (U : Map)
    (n k c : ℕ) (t : ℕ → ℕ) where
  ambientLength : ℕ
  n_le_ambient : n ≤ ambientLength
  ambient_le : ambientLength ≤ n + logSlack c n
  goodSets : ℕ → Finset BitString
  mem_family : ∀ s (_hs : s ≤ k), 𝒢.mem (goodSets s)
  size_bound : ∀ s (_hs : s ≤ k),
    (goodSets s).card ≤ 2 ^ (t s + sqrtSlack c n)
  complexity_bound : ∀ s (_hs : s ≤ k)
      (hS : (goodSets s).Nonempty),
    setComplexity U (goodSets s) hS ≤
      (s + sqrtSlack c n : ENat)
  candidates : Finset BitString
  candidates_nonempty : candidates.Nonempty
  candidate_len : ∀ x ∈ candidates, x.length = ambientLength
  candidate_mem : ∀ x ∈ candidates, ∀ s (_hs : s ≤ k),
    x ∈ goodSets s
  candidate_complexity : ∀ x ∈ candidates,
    KPPlain U x ≤ (k + sqrtSlack c n : ENat)
  survivor : BitString
  survivor_mem : survivor ∈ candidates
  survivor_not_bad :
    survivor ∉ restrictedProfileBadSet ℬ U candidates k
      (sqrtSlack c n) t

/-- On the diagonal, a mixed-family output is exactly an ordinary coupled
output. -/
def RestrictedCoupledOutputAgainst.toDiagonal
    {𝒜 : DescriptionFamily} {U : Map}
    {n k c : ℕ} {t : ℕ → ℕ}
    (output : RestrictedCoupledOutputAgainst 𝒜 𝒜 U n k c t) :
    RestrictedCoupledOutput 𝒜 U n k c t where
  ambientLength := output.ambientLength
  n_le_ambient := output.n_le_ambient
  ambient_le := output.ambient_le
  goodSets := output.goodSets
  mem_family := output.mem_family
  size_bound := output.size_bound
  complexity_bound := output.complexity_bound
  candidates := output.candidates
  candidates_nonempty := output.candidates_nonempty
  candidate_len := output.candidate_len
  candidate_mem := output.candidate_mem
  candidate_complexity := output.candidate_complexity
  survivor := output.survivor
  survivor_mem := output.survivor_mem
  survivor_not_bad := output.survivor_not_bad

/-- A mixed coupled output realizes the target curve in both families when
the rebuilding family is contained in the forbidden-description family. -/
lemma RestrictedCoupledOutputAgainst.profiles
    {𝒢 ℬ : DescriptionFamily} {U : Map}
    {n k c : ℕ} {t : ℕ → ℕ}
    (output : RestrictedCoupledOutputAgainst 𝒢 ℬ U n k c t)
    (hsub : ∀ S, 𝒢.mem S → ℬ.mem S) :
    RestrictedProfileWithinCurve 𝒢 U output.survivor k t
        (sqrtSlack c n) ∧
      RestrictedProfileWithinCurve ℬ U output.survivor k t
        (sqrtSlack c n) := by
  have hupperG :
      ∀ i : ℕ, i ≤ k →
        InDescriptionProfileIn 𝒢 U output.survivor
          (i + sqrtSlack c n) (t i + sqrtSlack c n) := by
    intro i hi
    have hx := output.candidate_mem output.survivor
      output.survivor_mem i hi
    have hS : (output.goodSets i).Nonempty :=
      ⟨output.survivor, hx⟩
    refine ⟨output.goodSets i, hS, output.mem_family i hi,
      hx, output.complexity_bound i hi hS, output.size_bound i hi⟩
  have hupperB :
      ∀ i : ℕ, i ≤ k →
        InDescriptionProfileIn ℬ U output.survivor
          (i + sqrtSlack c n) (t i + sqrtSlack c n) :=
    fun i hi => inDescriptionProfileIn_mono_family hsub (hupperG i hi)
  have hlowerB :
      ∀ i : ℕ, i ≤ k →
        ¬ InDescriptionProfileIn ℬ U output.survivor i
            (t i - (sqrtSlack c n + 1)) ∨
          t i ≤ sqrtSlack c n := by
    intro i hi
    by_cases hsmall : t i ≤ sqrtSlack c n
    · exact Or.inr hsmall
    · refine Or.inl ?_
      intro hprof
      apply output.survivor_not_bad
      exact ((restrictedProfileBadSet_spec ℬ U output.candidates k
        (sqrtSlack c n) t).2 output.survivor
          output.survivor_mem).mpr
        ⟨i, hi, Nat.lt_of_not_ge hsmall, hprof⟩
  have hlowerG :
      ∀ i : ℕ, i ≤ k →
        ¬ InDescriptionProfileIn 𝒢 U output.survivor i
            (t i - (sqrtSlack c n + 1)) ∨
          t i ≤ sqrtSlack c n := by
    intro i hi
    rcases hlowerB i hi with hnot | hsmall
    · exact Or.inl (fun hprof =>
        hnot (inDescriptionProfileIn_mono_family hsub hprof))
    · exact Or.inr hsmall
  exact ⟨⟨hupperG, hlowerG⟩, ⟨hupperB, hlowerB⟩⟩

/-- The mixed trace definitionally recovers the one-family trace on the
diagonal. -/
@[simp] lemma anchoredDecoderTraceAgainst_self
    (𝒜 : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 m : ℕ) :
    anchoredDecoderTraceAgainst 𝒜 𝒜 c gridCode q0 m =
      anchoredDecoderTrace 𝒜 c gridCode q0 m := rfl

/-- Diagonal compatibility of change counting. -/
@[simp] lemma anchoredChangeTraceAgainst_self
    (𝒜 : DescriptionFamily) (c : Code)
    (gridCode : BitString) (q0 s m : ℕ) :
    anchoredChangeTraceAgainst 𝒜 𝒜 c gridCode q0 s m =
      anchoredChangeTrace 𝒜 c gridCode q0 s m := by
  induction m with
  | zero => rfl
  | succ m ih =>
      rw [anchoredChangeTraceAgainst, anchoredChangeTrace, ih,
        anchoredDecoderTraceAgainst_self]

/-- Diagonal compatibility of the fixed-family version decoder. -/
@[simp] lemma anchoredVersionDecoderAgainst_self
    (𝒜 : DescriptionFamily) (c : Code) (bundle : BitString) :
    anchoredVersionDecoderAgainst 𝒜 𝒜 c bundle =
      anchoredVersionDecoder 𝒜 c bundle := by
  unfold anchoredVersionDecoderAgainst anchoredVersionDecoder
  simp only [anchoredChangeTraceAgainst_self]

/-- The mixed decoder trace is partial recursive for fixed families. -/
lemma anchoredDecoderTraceAgainst_partrec
    (𝒢 ℬ : DescriptionFamily) (c : Code) :
    Partrec (fun p : (BitString × ℕ) × ℕ =>
      anchoredDecoderTraceAgainst 𝒢 ℬ c p.1.1 p.1.2 p.2) := by
  let P := (BitString × ℕ) × ℕ
  have hgrid : Computable (fun p : P => p.1.1) :=
    Computable.fst.comp Computable.fst
  have hq0 : Computable (fun p : P => p.1.2) :=
    Computable.snd.comp Computable.fst
  have hm : Computable (fun p : P => p.2) := Computable.snd
  have hsteps : Computable (fun p : P =>
      anchoredDecodedSteps p.1.1) :=
    anchoredDecodedSteps_primrec.to_comp.comp hgrid
  have hΔ : Computable (fun p : P =>
      anchoredDecodedSlack p.1.1) :=
    anchoredDecodedSlack_primrec.to_comp.comp hgrid
  have hamb : Computable (fun p : P =>
      anchoredDecodedAmbientLength p.1.1) :=
    anchoredDecodedAmbientLength_primrec.to_comp.comp hgrid
  have hgridR : Computable (fun r : P × ℕ => r.1.1.1) :=
    hgrid.comp Computable.fst
  have hstepsR : Computable (fun r : P × ℕ =>
      anchoredDecodedSteps r.1.1.1) :=
    hsteps.comp Computable.fst
  have hΔR : Computable (fun r : P × ℕ =>
      anchoredDecodedSlack r.1.1.1) :=
    hΔ.comp Computable.fst
  have hstream : Computable (fun r : P × ℕ =>
      restrictedSampledBadCodeStream c r.1.1.1 ℬ.toPre
        (anchoredDecodedSteps r.1.1.1)
        (anchoredDecodedSlack r.1.1.1) r.2) :=
    (restrictedSampledBadCodeStream_computable_all c ℬ.toPre).comp
      (Computable.pair
        (Computable.pair (Computable.pair hgridR hstepsR) hΔR)
        Computable.snd)
  have hmR : Computable (fun r : P × ℕ => r.1.2) :=
    hm.comp Computable.fst
  have hcheck : Computable₂ (fun (p : P) (τ : ℕ) =>
      decide (p.2 ≤
        (restrictedSampledBadCodeStream c p.1.1 ℬ.toPre
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1) τ).length)) :=
    ((PrimrecPred.decide Primrec.nat_le).to_comp.to₂.comp hmR
      (Computable.list_length.comp hstream)).to₂
  have hfind : Partrec (fun p : P => Nat.rfind (fun τ =>
      Part.some (decide (p.2 ≤
        (restrictedSampledBadCodeStream c p.1.1 ℬ.toPre
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1) τ).length)))) :=
    Partrec.rfind hcheck.partrec₂
  have hinitInput : Computable (fun p : P =>
      ((((p.1.2, p.1.1), anchoredDecodedSteps p.1.1),
        anchoredDecodedSlack p.1.1),
        anchoredDecodedAmbientLength p.1.1)) :=
    Computable.pair
      (Computable.pair
        (Computable.pair (Computable.pair hq0 hgrid) hsteps) hΔ)
      hamb
  have hinit : Partrec (fun p : P =>
      restrictedAnchoredInitialFromCode 𝒢 p.1.2 p.1.1
        (anchoredDecodedSteps p.1.1)
        (anchoredDecodedSlack p.1.1)
        (anchoredDecodedAmbientLength p.1.1)) :=
    (restrictedAnchoredInitialFromCode_partrec_all 𝒢).comp hinitInput
  have hsizesR : Computable (fun r : P × ℕ =>
      restrictedAnchoredSizesFromCode r.1.1.1
        (anchoredDecodedSteps r.1.1.1)
        (anchoredDecodedSlack r.1.1.1)
        (anchoredDecodedAmbientLength r.1.1.1)) :=
    restrictedAnchoredSizesFromCode_computable_all.comp
      (Computable.pair
        (Computable.pair (Computable.pair hgridR hstepsR) hΔR)
        (hamb.comp Computable.fst))
  have hinitR : Partrec (fun r : P × ℕ =>
      restrictedAnchoredInitialFromCode 𝒢 r.1.1.2 r.1.1.1
        (anchoredDecodedSteps r.1.1.1)
        (anchoredDecodedSlack r.1.1.1)
        (anchoredDecodedAmbientLength r.1.1.1)) :=
    hinit.comp Computable.fst
  have hprefixInput :
      Computable (fun r : (P × ℕ) × BitString =>
        ((((r.1.1.1.2,
            restrictedAnchoredSizesFromCode r.1.1.1.1
              (anchoredDecodedSteps r.1.1.1.1)
              (anchoredDecodedSlack r.1.1.1.1)
              (anchoredDecodedAmbientLength r.1.1.1.1)),
            r.2),
          restrictedSampledBadCodeStream c r.1.1.1.1 ℬ.toPre
            (anchoredDecodedSteps r.1.1.1.1)
            (anchoredDecodedSlack r.1.1.1.1) r.1.2),
          r.1.1.2)) :=
    Computable.pair
      (Computable.pair
        (Computable.pair
          (Computable.pair
            (hq0.comp (Computable.fst.comp Computable.fst))
            (hsizesR.comp Computable.fst))
          Computable.snd)
        (hstream.comp Computable.fst))
      (hm.comp (Computable.fst.comp Computable.fst))
  have hprefix : Partrec₂
      (fun (r : P × ℕ) (st0 : BitString) =>
        restrictedEventPrefixRun 𝒢 r.1.1.2
          (restrictedAnchoredSizesFromCode r.1.1.1
            (anchoredDecodedSteps r.1.1.1)
            (anchoredDecodedSlack r.1.1.1)
            (anchoredDecodedAmbientLength r.1.1.1)) st0
          (restrictedSampledBadCodeStream c r.1.1.1 ℬ.toPre
            (anchoredDecodedSteps r.1.1.1)
            (anchoredDecodedSlack r.1.1.1) r.2)
          r.1.2) :=
    ((restrictedEventPrefixRun_partrec_all 𝒢).comp hprefixInput).to₂
  have hbody : Partrec₂ (fun (p : P) (τ : ℕ) =>
      (restrictedAnchoredInitialFromCode 𝒢 p.1.2 p.1.1
        (anchoredDecodedSteps p.1.1)
        (anchoredDecodedSlack p.1.1)
        (anchoredDecodedAmbientLength p.1.1)).bind
      (fun st0 => restrictedEventPrefixRun 𝒢 p.1.2
        (restrictedAnchoredSizesFromCode p.1.1
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1)
          (anchoredDecodedAmbientLength p.1.1)) st0
        (restrictedSampledBadCodeStream c p.1.1 ℬ.toPre
          (anchoredDecodedSteps p.1.1)
          (anchoredDecodedSlack p.1.1) τ) p.2)) :=
    (Partrec.bind hinitR hprefix).to₂
  exact (Partrec.bind hfind hbody).of_eq (fun _ => rfl)

/-- Mixed-family change counting is partial recursive. -/
lemma anchoredChangeTraceAgainst_partrec
    (𝒢 ℬ : DescriptionFamily) (c : Code) :
    Partrec (fun p : ((BitString × ℕ) × ℕ) × ℕ =>
      anchoredChangeTraceAgainst 𝒢 ℬ c
        p.1.1.1 p.1.1.2 p.1.2 p.2) := by
  let P := ((BitString × ℕ) × ℕ) × ℕ
  have hgrid : Computable (fun p : P => p.1.1.1) :=
    Computable.fst.comp (Computable.fst.comp Computable.fst)
  have hq0 : Computable (fun p : P => p.1.1.2) :=
    Computable.snd.comp (Computable.fst.comp Computable.fst)
  have hs : Computable (fun p : P => p.1.2) :=
    Computable.snd.comp Computable.fst
  have hcount : Computable (fun p : P => p.2) :=
    Computable.snd
  have htraceBase : Partrec (fun p : P =>
      anchoredDecoderTraceAgainst 𝒢 ℬ c
        p.1.1.1 p.1.1.2 0) :=
    (anchoredDecoderTraceAgainst_partrec 𝒢 ℬ c).comp
      (Computable.pair
        (Computable.pair hgrid hq0) (Computable.const 0))
  have hbase : Partrec (fun p : P =>
      (anchoredDecoderTraceAgainst 𝒢 ℬ c
        p.1.1.1 p.1.1.2 0).map
          (fun code => (0, anchoredModelListAt p.1.2 code))) :=
    Partrec.map htraceBase
      ((Primrec.pair (Primrec.const 0)
        (anchoredModelListAt_primrec.comp
          (Primrec.snd.comp
            (Primrec.fst.comp Primrec.fst))
          Primrec.snd)).to_comp.to₂)
  have htraceStep : Partrec
      (fun r : P × (ℕ × (ℕ × List BitString)) =>
        anchoredDecoderTraceAgainst 𝒢 ℬ c
          r.1.1.1.1 r.1.1.1.2 (r.2.1 + 1)) :=
    (anchoredDecoderTraceAgainst_partrec 𝒢 ℬ c).comp
      (Computable.pair
        (Computable.pair
          (hgrid.comp Computable.fst)
          (hq0.comp Computable.fst))
        (Computable.succ.comp
          (Computable.fst.comp Computable.snd)))
  have hstepPost : Computable₂
      (fun (r : P × (ℕ × (ℕ × List BitString)))
        (code : BitString) =>
        if anchoredModelListAt r.1.1.2 code = r.2.2.2 then
          (r.2.2.1, r.2.2.2)
        else
          (r.2.2.1 + 1,
            anchoredModelListAt r.1.1.2 code)) := by
    have hscale : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          x.1.1.1.2) :=
      Primrec.snd.comp
        (Primrec.fst.comp (Primrec.fst.comp Primrec.fst))
    have hmodel : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          anchoredModelListAt x.1.1.1.2 x.2) :=
      anchoredModelListAt_primrec.comp hscale Primrec.snd
    have hprevCount : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          x.1.2.2.1) :=
      Primrec.fst.comp
        (Primrec.snd.comp (Primrec.snd.comp Primrec.fst))
    have hprevList : Primrec
        (fun x :
          (P × (ℕ × (ℕ × List BitString))) × BitString =>
          x.1.2.2.2) :=
      Primrec.snd.comp
        (Primrec.snd.comp (Primrec.snd.comp Primrec.fst))
    exact ((Primrec.ite (Primrec.eq.comp hmodel hprevList)
      (Primrec.pair hprevCount hprevList)
      (Primrec.pair
        (Primrec.nat_add.comp hprevCount (Primrec.const 1))
        hmodel)).to_comp).to₂
  have hstep : Partrec₂
      (fun (p : P) (r : ℕ × (ℕ × List BitString)) =>
        (anchoredDecoderTraceAgainst 𝒢 ℬ c
          p.1.1.1 p.1.1.2 (r.1 + 1)).map
            (fun code =>
              if anchoredModelListAt p.1.2 code = r.2.2 then
                (r.2.1, r.2.2)
              else
                (r.2.1 + 1,
                  anchoredModelListAt p.1.2 code))) :=
    (Partrec.map htraceStep hstepPost).to₂
  refine (Partrec.nat_rec hcount hbase hstep).of_eq ?_
  rintro ⟨⟨⟨grid, q0⟩, sc⟩, m⟩
  induction m with
  | zero => rfl
  | succ m ih =>
      simp only []
      rw [show anchoredChangeTraceAgainst 𝒢 ℬ c
          grid q0 sc (m + 1) =
          (anchoredChangeTraceAgainst 𝒢 ℬ c
            grid q0 sc m).bind (fun p =>
              (anchoredDecoderTraceAgainst 𝒢 ℬ c
                grid q0 (m + 1)).map (fun code =>
                  if anchoredModelListAt sc code = p.2 then
                    (p.1, p.2)
                  else
                    (p.1 + 1,
                      anchoredModelListAt sc code))) from rfl,
        ← ih]

/-- The fixed-family mixed version decoder is partial recursive. -/
lemma anchoredVersionDecoderAgainst_partrec
    (𝒢 ℬ : DescriptionFamily) (c : Code) :
    Partrec (anchoredVersionDecoderAgainst 𝒢 ℬ c) := by
  have hparts : Computable
      (fun bundle : BitString => decodeListCode bundle) :=
    decodeListCode_primrec.to_comp
  have hpart (i : ℕ) : Computable
      (fun bundle : BitString =>
        (decodeListCode bundle).getD i []) :=
    (Primrec.list_getD []).to_comp.comp hparts
      (Computable.const i)
  have hgrid : Computable (fun bundle : BitString =>
      (decodeListCode bundle).getD 0 []) :=
    hpart 0
  have hq0 : Computable (fun bundle : BitString =>
      bitsToNat ((decodeListCode bundle).getD 1 [])) :=
    bitsToNat_primrec.to_comp.comp (hpart 1)
  have hs : Computable (fun bundle : BitString =>
      bitsToNat ((decodeListCode bundle).getD 2 [])) :=
    bitsToNat_primrec.to_comp.comp (hpart 2)
  have hv : Computable (fun bundle : BitString =>
      bitsToNat ((decodeListCode bundle).getD 3 [])) :=
    bitsToNat_primrec.to_comp.comp (hpart 3)
  have hchangeInput : Computable
      (fun r : BitString × ℕ =>
        ((((decodeListCode r.1).getD 0 [],
          bitsToNat ((decodeListCode r.1).getD 1 [])),
          bitsToNat ((decodeListCode r.1).getD 2 [])),
          r.2)) :=
    Computable.pair
      (Computable.pair
        (Computable.pair
          (hgrid.comp Computable.fst)
          (hq0.comp Computable.fst))
        (hs.comp Computable.fst))
      Computable.snd
  have hchange : Partrec (fun r : BitString × ℕ =>
      anchoredChangeTraceAgainst 𝒢 ℬ c
        ((decodeListCode r.1).getD 0 [])
        (bitsToNat ((decodeListCode r.1).getD 1 []))
        (bitsToNat ((decodeListCode r.1).getD 2 []))
        r.2) :=
    (anchoredChangeTraceAgainst_partrec 𝒢 ℬ c).comp
      hchangeInput
  have hcheckPost : Computable₂
      (fun (r : BitString × ℕ)
        (p : ℕ × List BitString) =>
        decide
          (bitsToNat ((decodeListCode r.1).getD 3 []) ≤
            p.1)) :=
    ((PrimrecPred.decide Primrec.nat_le).to_comp.to₂.comp
      (hv.comp (Computable.fst.comp Computable.fst))
      (Computable.fst.comp Computable.snd)).to₂
  have hcheck : Partrec₂
      (fun (bundle : BitString) (m : ℕ) =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c
          ((decodeListCode bundle).getD 0 [])
          (bitsToNat ((decodeListCode bundle).getD 1 []))
          (bitsToNat ((decodeListCode bundle).getD 2 []))
          m).map (fun p => decide
            (bitsToNat ((decodeListCode bundle).getD 3 []) ≤
              p.1))) :=
    (Partrec.map hchange hcheckPost).to₂
  have hfind : Partrec (fun bundle : BitString =>
      Nat.rfind (fun m =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c
          ((decodeListCode bundle).getD 0 [])
          (bitsToNat ((decodeListCode bundle).getD 1 []))
          (bitsToNat ((decodeListCode bundle).getD 2 []))
          m).map (fun p => decide
            (bitsToNat ((decodeListCode bundle).getD 3 []) ≤
              p.1)))) :=
    Partrec.rfind hcheck
  have houtputPost : Computable₂
      (fun (_r : BitString × ℕ)
        (p : ℕ × List BitString) =>
        uniformCodeOfList p.2) :=
    (uniformCodeOfList_primrec.to_comp.comp
      (Computable.snd.comp Computable.snd)).to₂
  have hbody : Partrec₂
      (fun (bundle : BitString) (m : ℕ) =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c
          ((decodeListCode bundle).getD 0 [])
          (bitsToNat ((decodeListCode bundle).getD 1 []))
          (bitsToNat ((decodeListCode bundle).getD 2 []))
          m).map (fun p => uniformCodeOfList p.2)) :=
    (Partrec.map hchange houtputPost).to₂
  exact (Partrec.bind hfind hbody).of_eq (fun _ => rfl)

/-- On a genuine grid, the mixed decoder replays every available prefix of
the `ℬ` event stream through the `𝒢` executor. -/
lemma anchoredDecoderTraceAgainst_replay
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (grid : RestrictedCurveGrid n k N target)
    (hN : N = Nat.sqrt (n / (Nat.log2 n + 1)) + 1)
    (T m : ℕ) (code : BitString)
    (hm : m ≤ (restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) T).length)
    (hfold :
      (restrictedEffectiveAnchoredInitialState 𝒢
          (n + logSlack 8 n) (sqrtSlack 8 n) grid).bind
        (fun st0 => restrictedEventPrefixRun 𝒢
          (𝒢.overhead (n + logSlack 8 n))
          (restrictedEffectiveAnchoredSizes
            (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
          (restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N
            (sqrtSlack 8 n) T) m) = Part.some code) :
    anchoredDecoderTraceAgainst 𝒢 ℬ c
      (restrictedCurveGridCode grid)
      (𝒢.overhead (n + logSlack 8 n)) m = Part.some code := by
  have hex : ∃ τ, m ≤ (restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N
      (sqrtSlack 8 n) τ).length :=
    ⟨T, hm⟩
  have hfind : Nat.rfind (fun τ => Part.some (decide (m ≤
      (restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) τ).length))) =
      Part.some (Nat.find hex) :=
    Part.eq_some_iff.mpr (Nat.mem_rfind.mpr
      ⟨by simpa using Nat.find_spec hex,
        fun {j} hj => by simpa using Nat.find_min hex hj⟩)
  have hprefix : restrictedSampledBadCodeStream c
      (restrictedCurveGridCode grid) ℬ.toPre N (sqrtSlack 8 n)
        (Nat.find hex) <+:
      restrictedSampledBadCodeStream c
        (restrictedCurveGridCode grid) ℬ.toPre N
        (sqrtSlack 8 n) T :=
    restrictedSampledBadCodeStream_prefix_of_le _ _ _ _ _
      (Nat.find_min' hex hm)
  have hrun : (fun st0 : BitString => restrictedEventPrefixRun 𝒢
        (𝒢.overhead (n + logSlack 8 n))
        (restrictedEffectiveAnchoredSizes
          (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) (Nat.find hex)) m) =
      (fun st0 : BitString => restrictedEventPrefixRun 𝒢
        (𝒢.overhead (n + logSlack 8 n))
        (restrictedEffectiveAnchoredSizes
          (n + logSlack 8 n) (sqrtSlack 8 n) grid) st0
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N
          (sqrtSlack 8 n) T) m) :=
    funext fun st0 => restrictedEventPrefixRun_congr 𝒢 _ _ _ m
      (fun i hi => (prefix_getD_eq hprefix
        (lt_of_lt_of_le hi (Nat.find_spec hex))).symm)
  unfold anchoredDecoderTraceAgainst
  simp only [anchoredDecodedSteps_eq grid hN,
    anchoredDecodedSlack_eq grid,
    anchoredDecodedAmbientLength_eq grid]
  rw [hfind, Part.bind_some]
  simp only [restrictedAnchoredSizesFromCode_eq grid,
    restrictedAnchoredInitialFromCode_eq 𝒢 grid]
  rw [hrun]
  exact hfold

/-- Evaluation of the mixed version decoder on its explicit bundle. -/
lemma anchoredVersionDecoderAgainst_eval
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    (g q0b sb vb : BitString) :
    anchoredVersionDecoderAgainst 𝒢 ℬ c
      (listCode [g, q0b, sb, vb]) =
      (Nat.rfind (fun m =>
        (anchoredChangeTraceAgainst 𝒢 ℬ c g
          (bitsToNat q0b) (bitsToNat sb) m).map
            (fun p => decide (bitsToNat vb ≤ p.1)))).bind
        (fun m =>
          (anchoredChangeTraceAgainst 𝒢 ℬ c g
            (bitsToNat q0b) (bitsToNat sb) m).map
              (fun p => uniformCodeOfList p.2)) := by
  unfold anchoredVersionDecoderAgainst
  rw [decodeListCode_listCode]
  rfl

/-- The mixed run, indexed by individual `ℬ` events, forms a genuine
`RestrictedRunChain` of `𝒢` states. -/
lemma exists_restrictedAnchoredEventChain_against
    (𝒢 ℬ : DescriptionFamily) (c : Code)
    {n k N : ℕ} {target : ℕ → ℕ}
    (ambientLength Δ : ℕ)
    (grid : RestrictedCurveGrid n k N target)
    (hnambient : n ≤ ambientLength) (T : ℕ) :
    ∃ (chain : RestrictedRunChain 𝒢 (N + 1) ambientLength
        (2 * 𝒢.overhead ambientLength)
        (restrictedAnchoredTarget ambientLength Δ grid)
        (restrictedSampledBadCodeStream c
          (restrictedCurveGridCode grid) ℬ.toPre N Δ T).length)
      (codes : ℕ → BitString),
      (∀ m,
        (restrictedEffectiveAnchoredInitialState 𝒢
            ambientLength Δ grid).bind
          (fun st0 => restrictedEventPrefixRun 𝒢
            (𝒢.overhead ambientLength)
            (restrictedEffectiveAnchoredSizes
              ambientLength Δ grid) st0
            (restrictedSampledBadCodeStream c
              (restrictedCurveGridCode grid) ℬ.toPre N Δ T) m) =
              Part.some (codes m) ∧
        DecodesToRestrictedSampledRunState
          (codes m) (chain.states m)) ∧
      (∀ m, chain.bads m =
        (decodeCoverCodeList
          ((restrictedSampledBadCodeStream c
            (restrictedCurveGridCode grid) ℬ.toPre N Δ T).getD
              m [])).toFinset) ∧
      (chain.states 0).B 0 =
        stringsOfLength ambientLength ∧
      (chain.states 0).live 0 =
        stringsOfLength ambientLength := by
  classical
  set gridCode := restrictedCurveGridCode grid
  set events := restrictedSampledBadCodeStream c
    gridCode ℬ.toPre N Δ T
  set q0 := 𝒢.overhead ambientLength
  set sizes :=
    restrictedEffectiveAnchoredSizes ambientLength Δ grid
  set tt := restrictedAnchoredTarget ambientLength Δ grid
  have hlen : sizes.length = (N + 1) + 1 := by
    simp [sizes]
  have hpowers : ∀ s ≤ N + 1,
      sizes.getD s 0 = 2 ^ tt s := fun s hs =>
    restrictedEffectiveAnchoredSizes_getD
      ambientLength Δ grid s hs
  have hmono : ∀ s < N + 1, tt (s + 1) ≤ tt s :=
    restrictedAnchoredTarget_mono
      ambientLength Δ grid hnambient
  have hbadDecode : ∀ m,
      decodeCoverCodeList (events.getD m []) =
        canonicalFinsetList
          ((decodeCoverCodeList (events.getD m [])).toFinset) :=
    fun m =>
      restrictedSampledBadCodeStream_getD_canonical
        ℬ c gridCode N Δ T m
  have hdata : ∀ m : ℕ, ∃ p : BitString ×
      RestrictedSampledRunState 𝒢 (N + 1) ambientLength
        (2 * 𝒢.overhead ambientLength) tt,
      (restrictedEffectiveAnchoredInitialState 𝒢
          ambientLength Δ grid).bind
        (fun st0 => restrictedEventPrefixRun 𝒢 q0 sizes
          st0 events m) = Part.some p.1 ∧
      DecodesToRestrictedSampledRunState p.1 p.2 ∧
      (m = 0 →
        p.2.B 0 = stringsOfLength ambientLength ∧
        p.2.live 0 = stringsOfLength ambientLength) := by
    intro m
    induction m with
    | zero =>
        obtain ⟨code0, st0, hrun0, hdec0, hB0, hlive0⟩ :=
          restrictedEffectiveAnchoredInitialState_spec 𝒢
            ambientLength Δ grid hnambient
        refine ⟨(code0, st0), ?_, hdec0,
          fun _ => ⟨hB0, hlive0⟩⟩
        simpa [restrictedEventPrefixRun_zero,
          part_bind_some] using hrun0
    | succ m ih =>
        obtain ⟨⟨cd, st⟩, hfold, hdec, _⟩ := ih
        obtain ⟨output, next, q, hstepEq, hnextDec,
            _hspec⟩ :=
          restrictedEffectiveSampledRun_step_spec 𝒢
            (N + 1) ambientLength tt sizes hlen hpowers
            hmono hdec (hbadDecode m)
        refine ⟨(output, next), ?_, hnextDec,
          fun h => absurd h (Nat.succ_ne_zero m)⟩
        have hsplit :
            (restrictedEffectiveAnchoredInitialState 𝒢
              ambientLength Δ grid).bind (fun st0 =>
                restrictedEventPrefixRun 𝒢 q0 sizes st0
                  events (m + 1)) =
            ((restrictedEffectiveAnchoredInitialState 𝒢
              ambientLength Δ grid).bind (fun st0 =>
                restrictedEventPrefixRun 𝒢 q0 sizes st0
                  events m)).bind (fun state =>
                    restrictedEffectiveSampledRunStep 𝒢 q0 sizes
                      state (events.getD m [])) := by
          rw [Part.bind_assoc]
          rfl
        rw [hsplit, hfold, Part.bind_some, hstepEq]
  choose data hd1 hd2 hd3 using hdata
  have hedge : ∀ m : ℕ, ∃ q,
      RestrictedSampledRunStepSpec
        ((data m).2) ((data (m + 1)).2)
        ((decodeCoverCodeList
          (events.getD m [])).toFinset) q := by
    intro m
    obtain ⟨output, next, q, hstepEq, hnextDec, hspec⟩ :=
      restrictedEffectiveSampledRun_step_spec 𝒢
        (N + 1) ambientLength tt sizes hlen hpowers
        hmono (hd2 m) (hbadDecode m)
    have hsplit :
        (restrictedEffectiveAnchoredInitialState 𝒢
          ambientLength Δ grid).bind (fun st0 =>
            restrictedEventPrefixRun 𝒢 q0 sizes st0
              events (m + 1)) =
        ((restrictedEffectiveAnchoredInitialState 𝒢
          ambientLength Δ grid).bind (fun st0 =>
            restrictedEventPrefixRun 𝒢 q0 sizes st0
              events m)).bind (fun state =>
                restrictedEffectiveSampledRunStep 𝒢 q0 sizes
                  state (events.getD m [])) := by
      rw [Part.bind_assoc]
      rfl
    have hout : output = (data (m + 1)).1 := by
      have hfold1 := hd1 (m + 1)
      rw [hsplit, hd1 m, Part.bind_some, hstepEq] at hfold1
      exact Part.some_injective hfold1
    refine ⟨q,
      stepSpec_transfer (fun s hs => ⟨rfl, rfl⟩)
        ?_ hspec⟩
    intro s hs
    exact decodesTo_eq_B_live
      (hout ▸ hnextDec) (hd2 (m + 1)) hs
  choose edges hedges using hedge
  exact ⟨⟨fun m => (data m).2,
      fun m => (decodeCoverCodeList
        (events.getD m [])).toFinset,
      edges, fun m _ => hedges m⟩,
    fun m => (data m).1,
    fun m => ⟨hd1 m, hd2 m⟩,
    fun m => rfl,
    (hd3 0 rfl).1, (hd3 0 rfl).2⟩

end Kolmogorov
