/-
Copyright (c) 2024 Alexey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey
-/
import KolmogorovMathlib.AlgorithmicProbability.UniversalSemimeasure.Defs

namespace Kolmogorov

open scoped ENNReal

/-- **The dovetailed `evaln`-budget enumeration of all lower-semicomputable
approximations.**

The `i`-th component runs the `i`-th partial-recursive `Code` (decoded from `i`)
with time budget `s` on every input `Encodable.encode (s', out, ctx)` for `s' ≤ s`,
and reports, scaled to the common denominator `2^s`, the largest dyadic value
`v · 2^(s-s')` it observes. Because `evaln` is monotone in the budget and complete
(`evaln_complete`/`evaln_mono`), the stage supremum
`⨆ s, dyadicValue (approxEnum i s out ctx) s` reproduces the limit
`⨆ s, dyadicValue (approx s out ctx) s` of *any* jointly computable `approx`, once
`i` is the code of (the totalisation of) `approx` (see `exists_approxEnum`). It is
a genuine computable family (`approxEnum_computable`), built from `primrec_evaln`.

Marked `irreducible` so the heavy `evaln`/`Finset.sup` body never participates in
downstream definitional unfolding (only its computability and sup-preservation
lemmas are used). -/
@[irreducible] def approxEnum : ℕ → ℕ → BitString → BitString → ℕ :=
  fun i s out ctx =>
    (Finset.range (s + 1)).sup (fun s' =>
      match Nat.Partrec.Code.evaln s
          ((Encodable.decode (α := Nat.Partrec.Code) i).getD Nat.Partrec.Code.zero)
          (Encodable.encode (s', out, ctx)) with
      | some v => v * 2 ^ (s - s')
      | none => 0)

/-- The monotonic wrapper for an approximation to ensure `dyadicValue` is non-decreasing. -/
def makeMono (approx : ℕ → BitString → BitString → ℕ) : ℕ → BitString → BitString → ℕ
  | 0, out, ctx => approx 0 out ctx
  | (s+1), out, ctx => max (2 * makeMono approx s out ctx) (approx (s+1) out ctx)

/-- A sanitised LSC approximation generated by truncating `makeMono (approxEnum i)` to unit mass. -/
noncomputable def lscEnum (i : ℕ) : BitString → BitString → ℝ≥0∞ :=
  truncG (makeMono (approxEnum i)) 0

/-- **Diagonal dyadic numerator of a uniform mixture approximation.**

Given a uniform stagewise numerator family `a i s out ctx` for a countable family
of l.s.c. functions, the stage-`S` numerator of the `dyadicWeight`-mixture is the
diagonal partial sum (over the first `S/2` components, each read at substage `S/2`)
rescaled to the common denominator `2^S`. The exponent `S - (i+1) - S/2` is
nonnegative because `i < S/2` forces `(i+1) + S/2 ≤ 2*(S/2) ≤ S`. -/
def mixtureDyadicApprox (a : ℕ → ℕ → BitString → BitString → ℕ) :
    ℕ → BitString → BitString → ℕ :=
  fun S out ctx =>
    ∑ i ∈ Finset.range (S / 2), a i (S / 2) out ctx * 2 ^ (S - (i + 1) - S / 2)

end Kolmogorov
