/-
Copyright (c) 2026 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovCounterexamples.Problem59CnOnlyExponent

/-!
# Deprecated aliases: Problem59CnOnlyExponent

Old names of declarations in the `KolmogorovCounterexamples.Problem59CnOnlyExponent`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Bad := Kolmogorov.shiftDecompressorOutput

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Bad_computable := Kolmogorov.shiftDecompressorOutput_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Bad_hit := Kolmogorov.shiftDecompressorOutput_hit

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Code := Kolmogorov.lengthTaggedCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Code_injective := Kolmogorov.lengthTaggedCode_injective

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59D := Kolmogorov.shiftDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59D_isDecompressor := Kolmogorov.shiftDecompressor_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Family := Kolmogorov.refutationFamily

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Family_card := Kolmogorov.refutationFamily_card

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Proj := Kolmogorov.conditionProjection

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59Proj_partrec := Kolmogorov.conditionProjection_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59_exists_complex_mem := Kolmogorov.exists_incompressible_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise59_Cn_only_unprovable :=
  Kolmogorov.information_conservation_Cn_only_exponent_unprovable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise59_conservation_Cn_only_false :=
  Kolmogorov.information_conservation_Cn_only_exponent_false
