import KolmogorovMathlib.AlgorithmicStatistics.CodedComputability
import KolmogorovMathlib.AlgorithmicStatistics.CodedFiniteDistribution
import KolmogorovMathlib.AlgorithmicStatistics.Conservation
import KolmogorovMathlib.AlgorithmicStatistics.Deficiency
import KolmogorovMathlib.AlgorithmicStatistics.DeficiencyValue
import KolmogorovMathlib.AlgorithmicStatistics.DescriptionProfileInvariance
import KolmogorovMathlib.AlgorithmicStatistics.NonStochastic
import KolmogorovMathlib.AlgorithmicStatistics.NonStochasticMassWeak
import KolmogorovMathlib.AlgorithmicStatistics.NormalizedCodedFiniteDistribution
import KolmogorovMathlib.AlgorithmicStatistics.Selector
import KolmogorovMathlib.AlgorithmicStatistics.Stochasticity
import KolmogorovMathlib.AlgorithmicStatistics.StochasticityProfile
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedCornerBallModels
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileCardinality
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalBetaRegime
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.Deficiencies
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.DescriptionShift
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.ModelsToSets2
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.Realization.FinalWindow
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.Realization.Part01
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.Snapshots.Part02
import KolmogorovMathlib.AlgorithmicStatistics.TwoPart.Snapshots.RichChunks

/-!
# Deprecated aliases: AlgorithmicStatistics

Old names of declarations in the `KolmogorovMathlib.AlgorithmicStatistics`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.DeficiencyLe := Kolmogorov.CodedFiniteDistribution.DeficiencyLe

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.DeficiencyLe.mono_beta := Kolmogorov.CodedFiniteDistribution.DeficiencyLe.mono_beta

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.IsNonStochastic := Kolmogorov.CodedFiniteDistribution.IsNonStochastic

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.IsStochastic := Kolmogorov.CodedFiniteDistribution.IsStochastic

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.IsStochastic.map := Kolmogorov.CodedFiniteDistribution.IsStochastic.map

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.IsStochastic.mono_alpha :=
  Kolmogorov.CodedFiniteDistribution.IsStochastic.mono_alpha

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.IsStochastic.mono_beta := Kolmogorov.CodedFiniteDistribution.IsStochastic.mono_beta

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.RatMass.ge_invPow2 := Kolmogorov.RatMass.geInvPow2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15e_allStrings_primrec :=
  Kolmogorov.CodedFiniteDistribution.allStrings_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15e_decodeFirst_primrec :=
  Kolmogorov.CodedFiniteDistribution.decodeFirst_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15e_decodeSecond_primrec :=
  Kolmogorov.CodedFiniteDistribution.decodeSecond_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dedup_primrec := Kolmogorov.dedup_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.length_natBits_le_of_lt_pow := Kolmogorov.length_natBits_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.bits_len_le_of_lt_two_pow := Kolmogorov.length_natBits_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.decodeNatCode := Kolmogorov.CodedFiniteDistribution.decodeNatCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.decodeNatCode_natCode :=
  Kolmogorov.CodedFiniteDistribution.decodeNatCode_natCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.decodeNatCode_primrec :=
  Kolmogorov.CodedFiniteDistribution.decodeNatCode_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.produces_of_runOut_eq_some := Kolmogorov.runOut_sound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.runOut_mono := Kolmogorov.runOut_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.EnumeratesGroups := Kolmogorov.EnumeratesGroups

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.EnumeratesList := Kolmogorov.EnumeratesList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.IsLowerSemicomputableTest := Kolmogorov.IsLowerSemicomputableTest

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.IsSimpleCode := Kolmogorov.IsSimpleCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.PlainDeficiencyLe := Kolmogorov.PlainDeficiencyLe

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.Prop254a := Kolmogorov.HasIJDescription

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.Prop254b := Kolmogorov.HasSimpleEnumeratedList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.Prop254c := Kolmogorov.HasSimpleGroupedEnumeration

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.Prop254d := Kolmogorov.TailInEverySimpleEnumeration

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionCheck := Kolmogorov.bijectionCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionCheck_partrec := Kolmogorov.bijectionCheck_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionEvalFuel := Kolmogorov.bijectionEvalFuel

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionImageMap := Kolmogorov.bijectionImageMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionImageMap_partrec := Kolmogorov.bijectionImageMap_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionPost := Kolmogorov.bijectionPost

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionPost_partrec := Kolmogorov.bijectionPost_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionRun := Kolmogorov.bijectionRun

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bijectionRun_eq := Kolmogorov.bijectionRun_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.bits_length_le_succ := Kolmogorov.bits_length_le_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.codeFromList := Kolmogorov.codeFromList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.codeFromList_eq := Kolmogorov.codeFromList_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.codeFromList_primrec := Kolmogorov.codeFromList_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.countHalts_lt_pow := Kolmogorov.countHalts_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.countP_any_le := Kolmogorov.countP_any_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.countP_coveredBool_le := Kolmogorov.countP_coveredBool_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.countP_levelSetMemBool_le := Kolmogorov.countP_levelSetMemBool_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.countP_or_le := Kolmogorov.countP_or_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.deficiencyValue := Kolmogorov.deficiencyValue

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.descriptionProfile_invariant_of_simple_bijection :=
  Kolmogorov.descriptionProfile_invariant_of_simple_bijection

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.distribution_to_uniform_set_model :=
  Kolmogorov.distribution_to_uniform_set_model

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise345_deficiency_tail := Kolmogorov.fraction_deficiency_gt_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise348_distribution_to_set :=
  Kolmogorov.distribution_to_uniform_set_model

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise349_exists_non_random :=
  Kolmogorov.exists_not_martinLofRandom_computableMeasure

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise350_extreme_profile_nonstochastic :=
  Kolmogorov.isNonStochastic_of_extreme_profile

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise350_nonstochastic_of_extreme_profile :=
  Kolmogorov.isNonStochastic_of_extreme_profile_general

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise353_tail_strings_mutually_simple :=
  Kolmogorov.tail_strings_mutually_simple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise354_profile_invariant_under_simple_bijection :=
  Kolmogorov.descriptionProfile_invariant_of_simple_bijection

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise363_exists_nonstochastic_weak :=
  Kolmogorov.exists_isNonStochastic_weak

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise364FilterFn := Kolmogorov.uncoveredStrings

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise364GetFn := Kolmogorov.uncoveredStringAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise364PostFn := Kolmogorov.uncoveredStringPart

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise364SelectorFn := Kolmogorov.uncoveredStringSelector

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise365_nonstochastic_mass_weak :=
  Kolmogorov.nonStochasticMass_bounds_weak

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exercise366_profile_properties :=
  Kolmogorov.stochasticityProfile_properties

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exists_isNonStochastic_weak := Kolmogorov.exists_isNonStochastic_weak

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.exists_not_martinLofRandom_computableMeasure :=
  Kolmogorov.exists_not_martinLofRandom_computableMeasure

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.foldr_length_step := Kolmogorov.foldr_length_step

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.fraction_deficiency_gt_le := Kolmogorov.fraction_deficiency_gt_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.h_check5_computable := Kolmogorov.selector5HaltCheck_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.isNonStochastic_of_extreme_profile :=
  Kolmogorov.isNonStochastic_of_extreme_profile

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.isNonStochastic_of_extreme_profile_general :=
  Kolmogorov.isNonStochastic_of_extreme_profile_general

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.isStochastic_of_add_ge := Kolmogorov.isStochastic_of_add_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.length_filter_not := Kolmogorov.length_filter_not

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.logSlack_add_left := Kolmogorov.logSlack_add_left

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.logSlack_le_linear := Kolmogorov.logSlack_le_mul_add_two_mul

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.nonStochasticMass := Kolmogorov.nonStochasticMass

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.nonStochasticMass_bounds := Kolmogorov.nonStochasticMass_bounds

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.nonStochasticMass_bounds_weak := Kolmogorov.nonStochasticMass_bounds_weak

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.optimalityDeficiencyValue := Kolmogorov.optimalityDeficiencyValue

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.pack5 := Kolmogorov.pack5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.partrec_exercise364SelectorFn :=
  Kolmogorov.partrec_uncoveredStringSelector

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.plainDeficiencyValue := Kolmogorov.plainDeficiencyValue

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selAlpha5 := Kolmogorov.selector5Alpha

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selAlpha5_primrec := Kolmogorov.selector5Alpha_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selAlpha5_selectorInput5 := Kolmogorov.selector5Alpha_selectorInput5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selH5 := Kolmogorov.selector5HaltCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selH5_primrec := Kolmogorov.selector5HaltCount_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selH5_selectorInput5 := Kolmogorov.selector5HaltCount_selectorInput5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selIndex5 := Kolmogorov.selector5Index

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selIndex5_primrec := Kolmogorov.selector5Index_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selIndex5_selectorInput5 := Kolmogorov.selector5Index_selectorInput5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selMaxK5 := Kolmogorov.selector5MaxK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selMaxK5_primrec := Kolmogorov.selector5MaxK_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selMaxK5_selectorInput5 := Kolmogorov.selector5MaxK_selectorInput5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selNat5 := Kolmogorov.selector5Length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selNat5_primrec := Kolmogorov.selector5Length_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selNat5_selectorInput5 := Kolmogorov.selector5Length_selectorInput5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selectorInput5 := Kolmogorov.selectorInput5

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selectorInput5_length_le := Kolmogorov.selectorInput5_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.selector_length_arith_bridge := Kolmogorov.selector_length_arith_bridge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.size_add_le := Kolmogorov.size_add_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.sqrtLogSlack := Kolmogorov.sqrtLogSlack

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.stochasticityProfile_properties :=
  Kolmogorov.stochasticityProfile_properties

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.tailAfter_eq_foldr := Kolmogorov.tailAfter_eq_foldr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.tailAfter_primrec := Kolmogorov.tailAfter_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.tailStringsSelector := Kolmogorov.tailStringsSelector

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.tailStringsSelector_eval := Kolmogorov.tailStringsSelector_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.tailStringsSelector_partrec := Kolmogorov.tailStringsSelector_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.tail_strings_mutually_simple := Kolmogorov.tail_strings_mutually_simple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.theorem249_all_stochastic := Kolmogorov.isStochastic_of_add_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch14.theorem251_nonstochastic_mass := Kolmogorov.nonStochasticMass_bounds

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.bits_len_le_of_lt_two_pow := Kolmogorov.length_natBits_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.bucket1_pred := Kolmogorov.bucket1Pred

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.codedUniform_data_foldr := Kolmogorov.codedUniform_foldr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.decodeFirst_primrec' := Kolmogorov.CodedFiniteDistribution.decodeFirst_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.decodeNatCode := Kolmogorov.CodedFiniteDistribution.decodeNatCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.decodeNatCode_natCode := Kolmogorov.CodedFiniteDistribution.decodeNatCode_natCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.decodeNatCode_primrec := Kolmogorov.CodedFiniteDistribution.decodeNatCode_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.decodeSecond_primrec' := Kolmogorov.CodedFiniteDistribution.decodeSecond_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.deficiencies_theorem_tight_thm := Kolmogorov.deficiencies_theorem_tight_of_optimal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.emittedHalfRichChunks_fold_step := Kolmogorov.emittedHalfRichChunksFoldStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.emittedHalfRichChunks_step := Kolmogorov.emittedHalfRichChunksStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exists_nonstochastic_of_profile := Kolmogorov.first_nonstochastic_existence

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.fwNat_c_gen := Kolmogorov.fwNatCGen

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.fwNat_i := Kolmogorov.fwNatI

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.fwNat_m := Kolmogorov.fwNatM

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.fwNat_n := Kolmogorov.fwNatN

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.fwNat_version := Kolmogorov.fwNatVersion

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.k_P := Kolmogorov.kP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.length_natBits_le_of_lt_pow := Kolmogorov.length_natBits_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.m_P := Kolmogorov.mP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.m_P_eps := Kolmogorov.mPEps

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.n_P := Kolmogorov.nP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.optimal_stochasticity_imp_profile_thm :=
  Kolmogorov.isOptimalSetStochastic_imp_profile

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.pairCode_primrec := Kolmogorov.CodedFiniteDistribution.pairCode_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrec_allStrings := Kolmogorov.CodedFiniteDistribution.allStrings_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.produces_of_runOut_eq_some := Kolmogorov.runOut_sound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.prop_upward_fullCube := Kolmogorov.prop_upward

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.setOptimalityCardBound := Kolmogorov.setOptimality_card_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.strongModelOrdinalNoiseTransport := Kolmogorov.strongModel_ordinal_noise_transport

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.strongModelOrdinalNoiseTransport_fullCube :=
  Kolmogorov.strongModel_ordinal_noise_transport

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.strongModelOrdinalNoiseTransport_of_length_le_beta :=
  Kolmogorov.strongModelOrdinalNoiseTransport_of_n_le_beta

@[deprecated (since := "2026-09-08")]
alias memStringsOfLengthLe := mem_stringsOfLengthLe
