import KolmogorovMathlib.AlgorithmicRandomness.Cantor
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveLaws
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveNull
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveOpen
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveReal
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveSLLN
import KolmogorovMathlib.AlgorithmicRandomness.LSCAux
import KolmogorovMathlib.AlgorithmicRandomness.LSCCharacterizations.Characterization
import KolmogorovMathlib.AlgorithmicRandomness.LSCCharacterizations.DyadicEnumeration
import KolmogorovMathlib.AlgorithmicRandomness.LSCCharacterizations.MonotoneLimits
import KolmogorovMathlib.AlgorithmicRandomness.NatLogPrimrec
import KolmogorovMathlib.AlgorithmicRandomness.ProbabilityBounded

/-!
# Deprecated aliases: AlgorithmicRandomness

Old names of declarations in the `KolmogorovMathlib.AlgorithmicRandomness`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias IsComputableReal.add := Kolmogorov.ComputableReals.IsComputableReal.add

@[deprecated (since := "2026-09-08")]
alias IsComputableReal.mul := Kolmogorov.ComputableReals.IsComputableReal.mul

@[deprecated (since := "2026-09-08")]
alias IsComputableReal.sub := Kolmogorov.ComputableReals.IsComputableReal.sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Iter := Kolmogorov.NatLog.log2Iter

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Iter_eq_log2 := Kolmogorov.NatLog.log2Iter_eq_log2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Iter_spec := Kolmogorov.NatLog.log2Iter_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Iter_succ := Kolmogorov.NatLog.log2Iter_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Iter_succ' := Kolmogorov.NatLog.log2Iter_succ'

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Step := Kolmogorov.NatLog.log2Step

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2Step_primrec := Kolmogorov.NatLog.log2Step_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log2_eq_succ := Kolmogorov.NatLog.log2_eq_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lt_two_of_log2_eq_zero := Kolmogorov.NatLog.lt_two_of_log2_eq_zero

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.cantorPrefix_prefix_cantorPrefix := cantorPrefix_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.cantorPrefix_succ_append := Kolmogorov.cantorPrefix_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.devBitsToNat_lt := Kolmogorov.bitsToNat_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_le_dyadicValue_of_le := Kolmogorov.lscDyadicValue_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.filter_length := Kolmogorov.filterLength

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.g_cons := Kolmogorov.gCons

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.g_tail := Kolmogorov.gTail

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get2PowS := Kolmogorov.twoPowStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.getS := Kolmogorov.stageOf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.getX := Kolmogorov.stringOf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_2_pow_s := Kolmogorov.twoPowStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_A := Kolmogorov.getA

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_B := Kolmogorov.getB

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_approx := Kolmogorov.getApprox

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_cond := Kolmogorov.getCond

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_q_den := Kolmogorov.getQDen

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_q_num := Kolmogorov.getQNum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_s := Kolmogorov.stageOf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.get_x := Kolmogorov.stringOf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.int_lt_nat := Kolmogorov.intLtNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.int_mul_nat := Kolmogorov.intMulNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.isEffectivelyNull_not_tendsto_freqOne_uniform :=
  Kolmogorov.isEffectivelyNull_notTendsto_freqOne

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.isMonotoneLimit_of_isSum_proof := Kolmogorov.isMonotoneLimit_of_isSum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.isPrefix_cantorPrefix_of_le := cantorPrefix_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.isSum_of_isMonotoneLimit := Kolmogorov.isSum_of_isMonotoneLimit_proof

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Iter := Kolmogorov.NatLog.log2Iter

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Iter_eq_log2 := Kolmogorov.NatLog.log2Iter_eq_log2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Iter_spec := Kolmogorov.NatLog.log2Iter_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Iter_succ := Kolmogorov.NatLog.log2Iter_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Iter_succ' := Kolmogorov.NatLog.log2Iter_succ'

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Step := Kolmogorov.NatLog.log2Step

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2Step_primrec := Kolmogorov.NatLog.log2Step_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log2_eq_succ := Kolmogorov.NatLog.log2_eq_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.lscMem_cantorCylinder_prefix := Kolmogorov.mem_cantorCylinder_cantorPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.lt_two_of_log2_eq_zero := Kolmogorov.NatLog.lt_two_of_log2_eq_zero

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.myApprox := Kolmogorov.monotoneApprox

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.myEnum := Kolmogorov.dyadicEnum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.myMaxApprox := Kolmogorov.monotoneMaxApprox

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.myTerm := Kolmogorov.monotoneTerm

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_approx := Kolmogorov.monotoneApprox

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_approx_comp := Kolmogorov.monotoneApprox_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_approx_take := Kolmogorov.monotoneApprox_take

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_enum := Kolmogorov.dyadicEnum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_enum_comp := Kolmogorov.dyadicEnum_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_enum_int_comp := Kolmogorov.dyadicEnum_int_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_enum_spec := Kolmogorov.dyadicEnum_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_max_approx := Kolmogorov.monotoneMaxApprox

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_max_approx_comp := Kolmogorov.monotoneMaxApprox_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_max_approx_take := Kolmogorov.monotoneMaxApprox_take

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_term := Kolmogorov.monotoneTerm

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_term_comp := Kolmogorov.monotoneTerm_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.my_term_sum := Kolmogorov.monotoneTerm_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.n_le_two_pow := Kolmogorov.k_le_two_pow_k

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.nat_log2_primrec := Kolmogorov.NatLog.nat_log2_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.self_le_two_pow := Kolmogorov.k_le_two_pow_k

@[deprecated (since := "2026-09-08")]
alias isComputableReal_ratCast := Kolmogorov.ComputableReals.isComputableReal_ratCast
