import KolmogorovMathlib.AlgorithmicProbability.Coding
import KolmogorovMathlib.AlgorithmicProbability.CompatibleGraphs.APrioriMarginals
import KolmogorovMathlib.AlgorithmicProbability.CompatibleGraphs.Basic
import KolmogorovMathlib.AlgorithmicProbability.HaltingProbabilityApproximation
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinAllocator.FreeList
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinApplications.Part01
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinApplications.Part02
import KolmogorovMathlib.AlgorithmicProbability.KraftChaitinCore.LSCApproximation
import KolmogorovMathlib.AlgorithmicProbability.Simulation

/-!
# Deprecated aliases: AlgorithmicProbability

Old names of declarations in the `KolmogorovMathlib.AlgorithmicProbability`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.CodedFiniteDistribution.twoPow_primrec := Kolmogorov.primrec_two_pow_aux

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.ENNReal_sum_iSup := Kolmogorov.ENNReal_sum_iSup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approxSum := Kolmogorov.SemimeasureEmbedding.approxSum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approxSumRangeTerm :=
  Kolmogorov.SemimeasureEmbedding.approxSumRangeTerm

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum := Kolmogorov.SemimeasureEmbedding.approxSum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum_computable :=
  Kolmogorov.SemimeasureEmbedding.approx_sum_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum_eq := Kolmogorov.SemimeasureEmbedding.approx_sum_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum_eq_range_sum :=
  Kolmogorov.SemimeasureEmbedding.approx_sum_eq_range_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum_range_term :=
  Kolmogorov.SemimeasureEmbedding.approxSumRangeTerm

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum_range_term_computable :=
  Kolmogorov.SemimeasureEmbedding.approx_sum_range_term_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.approx_sum_range_term_eq :=
  Kolmogorov.SemimeasureEmbedding.approx_sum_range_term_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.boundedList := Kolmogorov.SemimeasureEmbedding.boundedList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.boundedList_computable :=
  Kolmogorov.SemimeasureEmbedding.boundedList_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.boundedList_nodup :=
  Kolmogorov.SemimeasureEmbedding.boundedList_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.boundedList_prefix :=
  Kolmogorov.SemimeasureEmbedding.boundedList_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.boundedList_primrec :=
  Kolmogorov.SemimeasureEmbedding.boundedList_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.boundedList_succ :=
  Kolmogorov.SemimeasureEmbedding.boundedList_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.dyadicValue_boundedList_sum :=
  Kolmogorov.SemimeasureEmbedding.dyadicValue_boundedList_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.embedFirst := Kolmogorov.SemimeasureEmbedding.embedFirst

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.embedFirst_pairCode :=
  Kolmogorov.SemimeasureEmbedding.embedFirst_pairCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.finset_sum_iSup_monotone :=
  Kolmogorov.SemimeasureEmbedding.finset_sum_iSup_monotone

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.isLSC_embedFirst :=
  Kolmogorov.SemimeasureEmbedding.isLSC_embedFirst

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.isLSC_sumPair := Kolmogorov.SemimeasureEmbedding.isLSC_sumPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.isLowerSemicomputableSemimeasure_embedFirst :=
  Kolmogorov.SemimeasureEmbedding.isLowerSemicomputableSemimeasure_embedFirst

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.isLowerSemicomputableSemimeasure_sumPair :=
  Kolmogorov.SemimeasureEmbedding.isLowerSemicomputableSemimeasure_sumPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.isSemimeasure_embedFirst :=
  Kolmogorov.SemimeasureEmbedding.isSemimeasure_embedFirst

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.isSemimeasure_sumPair :=
  Kolmogorov.SemimeasureEmbedding.isSemimeasure_sumPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.list_sum_eq_finset_sum :=
  Kolmogorov.SemimeasureEmbedding.list_sum_eq_finset_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.list_sum_eq_range_getElem? :=
  Kolmogorov.SemimeasureEmbedding.list_sum_eq_range_getElem?

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.lower_bound_pair_code :=
  Kolmogorov.SemimeasureEmbedding.lower_bound_pair_code

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.mem_boundedList :=
  Kolmogorov.SemimeasureEmbedding.mem_boundedList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.natListSum := Kolmogorov.SemimeasureEmbedding.natListSum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.natListSum_eq_sum :=
  Kolmogorov.SemimeasureEmbedding.natListSum_eq_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.sumPair := Kolmogorov.SemimeasureEmbedding.sumPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise101.upper_bound_sum_pair :=
  Kolmogorov.SemimeasureEmbedding.upper_bound_sum_pair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.M_def := Kolmogorov.M_def

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.M_def_eq_some := Kolmogorov.M_def_eq_some

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.allocString := Kolmogorov.allocString

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.allocString_spec := Kolmogorov.allocString_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approxM1 := Kolmogorov.approxM1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approxM2 := Kolmogorov.approxM2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approx_m1 := Kolmogorov.approxM1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approx_m1_body_computable := Kolmogorov.approx_m1_body_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approx_m1_computable := Kolmogorov.approx_m1_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approx_m2 := Kolmogorov.approxM2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approx_m2_body_computable := Kolmogorov.approx_m2_body_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.approx_m2_computable := Kolmogorov.approx_m2_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.aprioriMeasure_computable_grouping :=
  Kolmogorov.aprioriMeasure_computable_grouping

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.aprioriMeasure_pair_max_eq := Kolmogorov.aprioriMeasure_pair_max_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.aprioriMeasure_pair_sum_eq := Kolmogorov.aprioriMeasure_pair_sum_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.ch44b_dyadicValue_zero := Kolmogorov.dyadicValue_zero

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.contGraph_F_of_A := Kolmogorov.contGraph_F_of_A

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.continuousMap_graph_bijection := Kolmogorov.continuousMap_graph_bijection

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.continuous_F_of_A := Kolmogorov.continuous_F_of_A

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.descLengths_getElem_length_lt := Kolmogorov.descLengths_getElem_length_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.dyadicValue_ite := Kolmogorov.dyadicValue_ite

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.dyadicValue_sup := Kolmogorov.dyadicValue_sup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.dyadicValue_zero := Kolmogorov.dyadicValue_zero

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise100_leftmost_allocation :=
  Kolmogorov.kraftChaitin_leftmost_allocation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise101_pair_max := Kolmogorov.aprioriMeasure_pair_max_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise101_pair_sum := Kolmogorov.aprioriMeasure_pair_sum_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise102_computable_grouping :=
  Kolmogorov.aprioriMeasure_computable_grouping

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise94_computable_lowerSemicomputable :=
  Kolmogorov.isLowerSemicomputable_of_isComputableReal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise95_computable_iff :=
  Kolmogorov.isComputableReal_iff_lowerSemicomputable_and_neg

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.existsUnique_continuousMap_of_compatibleGraph :=
  Kolmogorov.existsUnique_continuousMap_of_compatibleGraph

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_alloc_overlap_or_free_prefix :=
  Kolmogorov.exists_alloc_overlap_or_free_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.foldl_leftValue_aux := Kolmogorov.foldl_leftValue_aux

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.gReq := Kolmogorov.gReq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.g_ne_zero_imp := Kolmogorov.g_ne_zero_imp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.g_req := Kolmogorov.gReq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.getElem_free'_part1 := Kolmogorov.getElem_free'_part1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.getElem_free'_part2 := Kolmogorov.getElem_free'_part2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.getElem_free'_part3 := Kolmogorov.getElem_free'_part3

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.isComputableReal_iff_lowerSemicomputable_and_neg :=
  Kolmogorov.isComputableReal_iff_lowerSemicomputable_and_neg

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.isLowerSemicomputable_of_isComputableReal :=
  Kolmogorov.isLowerSemicomputable_of_isComputableReal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.isPrefixDecompressor_M_def := Kolmogorov.isPrefixDecompressor_M_def

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.kraftChaitin_leftmost_allocation :=
  Kolmogorov.kraftChaitin_leftmost_allocation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue := Kolmogorov.leftValue

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_append := Kolmogorov.leftValue_append

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_cons_false := Kolmogorov.leftValue_cons_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_cons_true := Kolmogorov.leftValue_cons_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_ge_of_prefixFree_and_le :=
  Kolmogorov.leftValue_ge_of_prefixFree_and_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_le_of_prefix := Kolmogorov.leftValue_le_of_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_le_of_state := Kolmogorov.leftValue_le_of_state

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_lt_pow := Kolmogorov.leftValue_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_newNode_pad := Kolmogorov.leftValue_newNode_pad

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.leftValue_replicate_false := Kolmogorov.leftValue_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.lowerSemicomputableSeq_iff_enumerable_rationalPairs :=
  Kolmogorov.lowerSemicomputableSeq_iff_enumerable_rationalPairs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.replicate_false_trichotomy := Kolmogorov.replicate_false_trichotomy

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem45_lowerSemicomputableSeq_iff :=
  Kolmogorov.lowerSemicomputableSeq_iff_enumerable_rationalPairs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem54_existsUnique :=
  Kolmogorov.existsUnique_continuousMap_of_compatibleGraph

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem54_graph_bijection := Kolmogorov.continuousMap_graph_bijection

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.aprioriMeasure_dominates_self_via_programSimulation :=
  Kolmogorov.aprioriMeasure_dominates_self

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_add_nat := Kolmogorov.dyadicValue_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_eq_mul := Kolmogorov.dyadicValue_eq_mul_inv_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_pow_mul := Kolmogorov.dyadicValue_two_pow_mul_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_two_mul := Kolmogorov.dyadicValue_two_mul_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_two_pow_mul := Kolmogorov.dyadicValue_two_pow_mul_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_two_pow_sub' := Kolmogorov.dyadicValue_two_pow_sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.dyadicValue_zero_num := Kolmogorov.dyadicValue_zero

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.le_of_inv_two_pow_le := Kolmogorov.inv_two_pow_exponent_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.list_take_primrec := Kolmogorov.KraftChaitin.take_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.lscDyadicValue_add := Kolmogorov.dyadicValue_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.lscDyadicValue_two_mul := Kolmogorov.dyadicValue_two_mul_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.lscDyadicValue_zero := Kolmogorov.dyadicValue_zero

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrec_two_pow := Kolmogorov.primrec_two_pow_aux

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.stageDyadicValue_zero := Kolmogorov.dyadicValue_zero
