/-
Copyright (c) 2026 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovMathlib.CommonInformation.AffineIncidence
import KolmogorovMathlib.CommonInformation.ChainHistogram
import KolmogorovMathlib.CommonInformation.ChainNonextractability
import KolmogorovMathlib.CommonInformation.ConditionalIndependence.Part01
import KolmogorovMathlib.CommonInformation.ConditionalIndependenceChains.Existence
import KolmogorovMathlib.CommonInformation.FiniteQuadruple
import KolmogorovMathlib.CommonInformation.IncidenceConsequences
import KolmogorovMathlib.CommonInformation.IncidenceCoverArithmetic
import KolmogorovMathlib.CommonInformation.IncidenceProfile
import KolmogorovMathlib.CommonInformation.IncidenceRegion
import KolmogorovMathlib.CommonInformation.IncidenceRegionUniformity
import KolmogorovMathlib.CommonInformation.IncidenceWitnessSelector
import KolmogorovMathlib.CommonInformation.NoFourCycleDensity
import KolmogorovMathlib.CommonInformation.QuadraticIncidenceCodecs
import KolmogorovMathlib.CommonInformation.RegionConsequences
import KolmogorovMathlib.CommonInformation.RegionEnvelopes
import KolmogorovMathlib.CommonInformation.RegionLower.Part01
import KolmogorovMathlib.CommonInformation.RegionLower.Part02
import KolmogorovMathlib.CommonInformation.Relativized
import KolmogorovMathlib.CommonInformation.WorstCase
import KolmogorovMathlib.CommonInformation.WorstCaseRegion

/-!
# Deprecated aliases: CommonInformation

Old names of declarations in the `KolmogorovMathlib.CommonInformation`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.AffineIncidence.noFourCycle := Kolmogorov.AffineIncidence.no_four_cycle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.chainHistogram_marginal_1_2_right := Kolmogorov.chainHistogram_marginal_2_1_W

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.commonInformationRegion_subset_upperEnvelope :=
  Kolmogorov.common_information_universal_upper

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condK_extend_condition_le := Kolmogorov.condK_condPair_left_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_308_coefficient_two_sharp := Kolmogorov.coefficient_two_sharp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_308_sharp_slack_folding := Kolmogorov.coefficient_two_sharp_slack_folding

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_308_small_arithmetic :=
  Kolmogorov.small_common_string_nonextractability_arithmetic

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_308_small_common_string_nonextractability :=
  Kolmogorov.small_common_string_nonextractability

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_308_small_slack_folding :=
  Kolmogorov.small_common_string_nonextractability_slack_folding

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_309_incident_edge_profile := Kolmogorov.incident_edge_profile

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_310_every_highComplexity_incident_edge :=
  Kolmogorov.highComplexity_incident_edge_muchnik_obstruction

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_311_region_witness := Kolmogorov.quadratic_incidence_region_witness

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_312_incidence_region_criterion :=
  Kolmogorov.incidence_region_capacity_criterion

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_312_incidence_region_uniformity := Kolmogorov.incidence_region_uniformity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_313_relativized_obstruction :=
  Kolmogorov.relativized_incidence_obstruction

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_314_conditionally_independent_uniform_pair :=
  Kolmogorov.exists_quadDist_condIndep_uniform_pair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_314_not_independent := Kolmogorov.not_alphaBetaIndep_of_prAgree_ne_half

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_315_chain_of_ge_3_8 := Kolmogorov.exists_indepChain_of_three_eighths_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_315_conditional_independence_chains := Kolmogorov.exists_indepChain

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exercise_316_nonextractability := Kolmogorov.chain_pair_nonextractability

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.noFourCycle_rectangleFamilyEdges_card_le_pow_of_noFourCycle :=
  Kolmogorov.noFourCycle_rectangleFamilyEdges_card_le_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.pairPlainK_incidentCommonWitness_capacity_le :=
  Kolmogorov.pairPlainK_incidentCommonWitness_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_217_conditionally_independent_not_independent :=
  Kolmogorov.exists_quadDist_condIndep_not_indep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_223_muchnik_nonextractability := Kolmogorov.muchnik_nonextractability

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_224_common_information_threeFace_containment :=
  Kolmogorov.common_information_threeFace_containment

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_224_muchnik_worst_case_region := Kolmogorov.muchnik_worst_case_region

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_225_common_information_lower_envelope_achieved :=
  Kolmogorov.common_information_lower_envelope_achieved

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_225_common_information_profile_upper :=
  Kolmogorov.common_information_profile_upper

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_225_common_information_universal_lower :=
  Kolmogorov.common_information_universal_lower

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_225_common_information_universal_upper :=
  Kolmogorov.common_information_universal_upper

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_225_common_information_upper_envelope_achieved :=
  Kolmogorov.common_information_upper_envelope_achieved

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_225_conditional_values_close :=
  Kolmogorov.common_information_conditional_values_close

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_226_arithmetic := Kolmogorov.minimal_region_nonextractability_arithmetic

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_226_minimal_region_nonextractability :=
  Kolmogorov.minimal_region_nonextractability

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_226_slack_folding :=
  Kolmogorov.minimal_region_nonextractability_slack_folding

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_arithmetic := Kolmogorov.incidence_nonextractability_arithmetic

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_incidence_nonextractability := Kolmogorov.incidence_nonextractability

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_incidence_nonextractability_core :=
  Kolmogorov.incidence_nonextractability_core

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_incidence_nonextractability_of_profile_values :=
  Kolmogorov.incidence_nonextractability_of_profile_values

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_incidence_region_containment := Kolmogorov.incidence_region_containment

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_large_z_case := Kolmogorov.incidence_nonextractability_large_z

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_227_weighted_profile_values := Kolmogorov.incidence_weighted_profile_values

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_228_conditional_independence_bound :=
  Kolmogorov.conditional_independence_nonextractability_bound
