/-
Copyright (c) 2026 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovMathlib.Complexity.ConditionalComplexity.AverageBounds.Expectation
import KolmogorovMathlib.Complexity.ConditionalComplexity.AverageBounds.Tail
import KolmogorovMathlib.Complexity.ConditionalComplexity.Continuity
import KolmogorovMathlib.Complexity.IncompressibleStrings.Deficiency
import KolmogorovMathlib.Complexity.IncompressibleStrings.SplitDecompressors
import KolmogorovMathlib.Complexity.InfiniteSequences.MonotoneComparison
import KolmogorovMathlib.Complexity.InfiniteSequences.MonotoneGap
import KolmogorovMathlib.Complexity.InfiniteSequences.PrefixComplexity
import KolmogorovMathlib.Complexity.Information.ConservationBounds
import KolmogorovMathlib.Complexity.Information.MutualInformation
import KolmogorovMathlib.Complexity.Information.RandomConservation
import KolmogorovMathlib.Complexity.KolmogorovLevin.LogarithmicGap
import KolmogorovMathlib.Complexity.KolmogorovLevin.Refinements
import KolmogorovMathlib.Complexity.KolmogorovLevin.ShortDescriptions
import KolmogorovMathlib.Complexity.PairComplexity.Basic
import KolmogorovMathlib.Complexity.PairComplexity.ConditionalMinimality
import KolmogorovMathlib.Complexity.PairComplexity.LogarithmicTerms.ConditionalBounds
import KolmogorovMathlib.Complexity.PairComplexity.LogarithmicTerms.PlainBounds
import KolmogorovMathlib.Complexity.PairComplexity.Overhead
import KolmogorovMathlib.Complexity.RandomConditions.Bound.HeavyStringsEnumeration
import KolmogorovMathlib.Complexity.RandomConditions.Bound.StageComputability
import KolmogorovMathlib.Complexity.RandomConditions.Enumeration
import KolmogorovMathlib.Complexity.SelfComplexity.TokenGame.BoardMachinery
import KolmogorovMathlib.Complexity.SelfComplexity.TokenGame.LowerBound

/-!
# Deprecated aliases: Complexity

Old names of declarations in the `KolmogorovMathlib.Complexity`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum1_sub_stage1 := Kolmogorov.dichotomyEnum1_sub_stage1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum2 := Kolmogorov.dichotomyEnum2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum2_mem := Kolmogorov.dichotomyEnum2_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum2_mono := Kolmogorov.dichotomyEnum2_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum2_primrec := Kolmogorov.dichotomyEnum2_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum2_sub_stage2 := Kolmogorov.dichotomyEnum2_sub_stage2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomySnapshotY := Kolmogorov.dichotomySnapshotY

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomySnapshotY_eq_enum2 := Kolmogorov.dichotomySnapshotY_eq_enum2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomySnapshotY_mem := Kolmogorov.dichotomySnapshotY_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomySnapshotY_mono := Kolmogorov.dichotomySnapshotY_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomySnapshotY_primrec := Kolmogorov.dichotomySnapshotY_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage1 := Kolmogorov.dichotomyStage1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage1_computable := Kolmogorov.dichotomyStage1_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage1_mono := Kolmogorov.dichotomyStage1_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage1_nodup := Kolmogorov.dichotomyStage1_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage2 := Kolmogorov.dichotomyStage2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage2_computable := Kolmogorov.dichotomyStage2_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage2_mem_enum2 := Kolmogorov.dichotomyStage2_mem_enum2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage2_mono := Kolmogorov.dichotomyStage2_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage2_nodup := Kolmogorov.dichotomyStage2_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyStage2_sub_snapshotY := Kolmogorov.dichotomyStage2_sub_snapshotY

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomy_card_bound := Kolmogorov.dichotomy_card_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.drop_findIdx_replicate_false_cons_true :=
  Kolmogorov.drop_findIdx_replicate_false_cons_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.evalPairCode := Kolmogorov.evalPairCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.evalPairCode_partrec := Kolmogorov.evalPairCode_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.eval_F_p_ex50 := Kolmogorov.eval_F_p_cinfGap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_D_body := Kolmogorov.overheadDecoderBody

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_D_code := Kolmogorov.overheadCodeDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_D_compose := Kolmogorov.overheadComposedDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_req := Kolmogorov.overheadRequest

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_sel_len := Kolmogorov.overheadSelLength

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_sel_n := Kolmogorov.overheadSelIndex

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_sel_w := Kolmogorov.overheadSelWord

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_step2 := Kolmogorov.overheadOuterStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex19_step3 := Kolmogorov.overheadInnerStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex41_count_fn := Kolmogorov.randomCondCountFn

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex41_not_mem := Kolmogorov.randomCondNotMem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex41_not_mem_primrec := Kolmogorov.randomCondNotMem_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Black := Kolmogorov.gameBlack

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Blk := Kolmogorov.gameBlk

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Col := Kolmogorov.gameCol

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Col_primrec := Kolmogorov.gameCol_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Dead := Kolmogorov.gameDead

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Dead_primrec := Kolmogorov.gameDead_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Decoder := Kolmogorov.gameDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Free := Kolmogorov.gameFree

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Free_primrec := Kolmogorov.gameFree_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Log := Kolmogorov.gameLog

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Log_eq := Kolmogorov.gameLog_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Max := Kolmogorov.gameMax

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Max_le_of_mem := Kolmogorov.gameMax_le_of_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Max_mem := Kolmogorov.gameMax_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Max_mono := Kolmogorov.gameMax_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Max_primrec := Kolmogorov.gameMax_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Row := Kolmogorov.gameRow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45RowEnum := Kolmogorov.gameRowEnum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45RowEnum_length := Kolmogorov.gameRowEnum_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Str := Kolmogorov.gameStr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Tokens := Kolmogorov.gameTokens

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45Top := Kolmogorov.gameTop

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45WCol := Kolmogorov.gameWCol

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45WCol_lt := Kolmogorov.gameWCol_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45_final := Kolmogorov.exists_condK_cVal_within_log_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45_row_bound := Kolmogorov.game_row_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45_upper := Kolmogorov.condK_cVal_le_log_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex45_winner := Kolmogorov.exists_game_winner

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex49Base := Kolmogorov.logPrefixBase

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex49Q := Kolmogorov.logPrefixQ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_H_func := Kolmogorov.cinfGapHalting

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_H_nat := Kolmogorov.cinfGapHaltingNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_T := Kolmogorov.cinfGapStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_map := Kolmogorov.cinfGapMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_p_time := Kolmogorov.cinfGapHaltTime

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_prefix_fn := Kolmogorov.cinfGapPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_progs := Kolmogorov.cinfGapPrograms

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_x := Kolmogorov.cinfGapSequence

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_ym := Kolmogorov.cinfGapWord

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_ym_outputs := Kolmogorov.cinfGapOutputs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex50_ym_stage := Kolmogorov.cinfGapOutputStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex52Decode := Kolmogorov.minfDecode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex52Q := Kolmogorov.minfQ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex54_decode := Kolmogorov.infOftenDecode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex54_decompressor := Kolmogorov.infOftenDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex54_findK := Kolmogorov.infOftenFindK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex54_natToBits := Kolmogorov.infOftenNatToBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aAcceptable := Kolmogorov.randomPairAcceptable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aCandidateList := Kolmogorov.randomPairCandidateList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aCheck := Kolmogorov.randomPairCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aCount := Kolmogorov.randomPairCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aDecoder := Kolmogorov.randomPairDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aGet := Kolmogorov.randomPairGet

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aStage := Kolmogorov.randomPairStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aStageList := Kolmogorov.randomPairStageList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aStep := Kolmogorov.randomPairStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aStepP := Kolmogorov.randomPairStepArgs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59aT1 := Kolmogorov.randomPairArgs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59a_count_fn := Kolmogorov.randomPairCountFn

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59a_probability_bound := Kolmogorov.randomPair_probability_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59bDecompressor := Kolmogorov.dropConditionDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59b_drop_condition := Kolmogorov.condK_le_condK_pair_add_two_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59cDecompressor := Kolmogorov.relativizedConservationDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59c_compose := Kolmogorov.relativized_conservation_compose

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.ex59dDecompressor := Kolmogorov.differenceDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise16_triple := Kolmogorov.plainK_triple_le_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise17_no_single_log := Kolmogorov.not_plainK_pair_le_add_single_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise19_overhead_characterization :=
  Kolmogorov.pair_overhead_characterization

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise21_symmetric_logs := Kolmogorov.plainK_pair_le_add_logs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise22_log_of_sum := Kolmogorov.plainK_pair_le_add_log_of_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise23_decompressor := Kolmogorov.pairSelfComplexityDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise23_mapFn := Kolmogorov.pairSelfComplexityMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise23_pair_with_complexity := Kolmogorov.plainK_pair_self_plainK_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise24Map := Kolmogorov.pairLevelMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise24_two_n := Kolmogorov.plainK_pair_le_two_mul

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise25_continuity := Kolmogorov.condK_append_bit_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise25_intermediate := Kolmogorov.exists_condK_eq_of_le_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise26_fixed_condition :=
  Kolmogorov.plainK_sub_condK_le_two_mul_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise27_pair_condition := Kolmogorov.condK_pair_pair_le_condK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise28_program_complexity :=
  Kolmogorov.condK_eq_min_program_complexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise29_total_conditional := Kolmogorov.condK_le_totalCondK_le_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise33_two_conditions :=
  Kolmogorov.exists_incompressible_two_conditions

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise34_triangle := Kolmogorov.condK_triangle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise35_sharp_symmetry :=
  Kolmogorov.plainK_add_condK_le_plainK_pair_add_three_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise36_dichotomy := Kolmogorov.rectangle_dichotomy

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise37_unavoidable_above := Kolmogorov.exists_plainK_pair_ge_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise37_unavoidable_below := Kolmogorov.exists_plainK_pair_le_sub_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise38_one_bit_flip := Kolmogorov.plainK_flipBit_le_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise39_many_descriptions := Kolmogorov.condK_le_of_many_descriptions

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise40_few_shortest_descriptions :=
  Kolmogorov.card_shortestDescriptions_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Acceptable := Kolmogorov.randomCondAcceptable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41CandidateList := Kolmogorov.randomCondCandidateList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Check := Kolmogorov.randomCondCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Count := Kolmogorov.randomCondCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Decoder := Kolmogorov.randomCondDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Get := Kolmogorov.randomCondGet

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41MemSnapshot_primrec := Kolmogorov.randomCondMemSnapshot_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Stage := Kolmogorov.randomCondStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41StageList := Kolmogorov.randomCondStageList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Stage_mono := Kolmogorov.randomCondStage_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Stage_nodup := Kolmogorov.randomCondStage_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41Step := Kolmogorov.randomCondStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise41_probability_bound :=
  Kolmogorov.condK_le_of_probability_condK_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise42_average := Kolmogorov.average_condK_eq_condK_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise42_tail := Kolmogorov.fraction_condK_lt_condK_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise43_short_conditional := Kolmogorov.plainK_le_of_condK_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise44_self_conditional := Kolmogorov.plainK_eq_condK_self_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise45_complexity_of_complexity :=
  Kolmogorov.exists_condK_cVal_within_log_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise48_computable_iff_bounded :=
  Kolmogorov.computable_iff_condK_prefix_bounded

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise49_log_prefixes_computable :=
  Kolmogorov.computable_of_plainK_prefix_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise50_Cinf_below_M := Kolmogorov.exists_cinf_lt_monotone

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise51_M_below_C := Kolmogorov.exists_monotone_lt_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise52_Cinf_le_two_Minf := Kolmogorov.cinf_le_two_mul_minf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise53_a_count := Kolmogorov.card_incompressible_mem_Icc

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise53_b_count_complexity := Kolmogorov.plainK_card_incompressible_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise53_c_halves := Kolmogorov.plainK_halves_of_incompressible

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise53_d_substrings := Kolmogorov.plainK_substring_of_incompressible

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise53_e_zero_runs := Kolmogorov.incompressible_contains_zero_run

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise54_infinitely_often :=
  Kolmogorov.exists_infinitely_many_prefix_plainK_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise54_matching_sequence :=
  Kolmogorov.exists_sequence_prefix_plainK_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise55_deficiency_comparison :=
  Kolmogorov.deficiency_comparison_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise58_conservation :=
  Kolmogorov.deterministic_information_conservation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise59_probabilistic_conservation :=
  Kolmogorov.levin_information_conservation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise59_probabilistic_conservation_book :=
  Kolmogorov.levin_information_conservation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise60_asymmetry := Kolmogorov.info_asymmetric_example

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise61_expected_information := Kolmogorov.expected_info_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise62_weaker_hypotheses :=
  Kolmogorov.mutual_information_weaker_hypotheses

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise63_information_chain := Kolmogorov.info_pair_chain_rule

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise64_conditionally_independent_not :=
  Kolmogorov.exists_conditionally_independent_not_independent

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise64_independent_not_conditionally :=
  Kolmogorov.exists_independent_not_conditionally_independent

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exercise65_markov_reversal := Kolmogorov.markov_reversal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_common_stage := Kolmogorov.exists_common_stage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_condK_eq_of_le_plainK := Kolmogorov.exists_condK_eq_of_le_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_conditionally_independent_not_independent :=
  Kolmogorov.exists_conditionally_independent_not_independent

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_goodPrefix := Kolmogorov.exists_goodPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_incompressible_two_conditions :=
  Kolmogorov.exists_incompressible_two_conditions

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_independent_not_conditionally_independent :=
  Kolmogorov.exists_independent_not_conditionally_independent

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_infinitely_many_prefix_plainK_le :=
  Kolmogorov.exists_infinitely_many_prefix_plainK_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_lexKey := Kolmogorov.exists_lexKey

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_limsup := Kolmogorov.exists_limsup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_mem_heavyEnum := Kolmogorov.exists_mem_heavyEnum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_min_program := Kolmogorov.exists_min_program

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_minimal_program_cVal := Kolmogorov.exists_minimal_program_cVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_plainK_pair_ge_add_log := Kolmogorov.exists_plainK_pair_ge_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_plainK_pair_le_sub_log := Kolmogorov.exists_plainK_pair_le_sub_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_program_le_cVal := Kolmogorov.exists_program_le_cVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_sat := Kolmogorov.exists_sat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_sequence_prefix_plainK_ge :=
  Kolmogorov.exists_sequence_prefix_plainK_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_stage_hit := Kolmogorov.exists_stage_hit

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.exists_threshold_of_limsup_le := Kolmogorov.exists_threshold_of_limsup_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.expected_info_le_log := Kolmogorov.expected_info_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.fExtract := Kolmogorov.fExtract

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.fExtractBody := Kolmogorov.fExtractBody

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.f_extract := Kolmogorov.fExtract

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.f_extract_body := Kolmogorov.fExtractBody

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.f_extract_body_partrec := Kolmogorov.f_extract_body_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.f_extract_partrec := Kolmogorov.f_extract_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.findIdx_decide_eq := Kolmogorov.findIdx_decide_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.findIdx_go_replicate_false_cons_true :=
  Kolmogorov.findIdx_go_replicate_false_cons_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.findIdx_replicate_false_cons_true :=
  Kolmogorov.findIdx_replicate_false_cons_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.finset_card_double_count := Kolmogorov.finset_card_double_count

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.flipBitAt := Kolmogorov.flipBitAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.flipBitAt_eq_set := Kolmogorov.flipBitAt_eq_set

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.flipBitAt_primrec := Kolmogorov.flipBitAt_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.fraction_condK_lt_condK_length_le :=
  Kolmogorov.fraction_condK_lt_condK_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.gacs_condK_complexity_eq_log :=
  Kolmogorov.exists_condK_cVal_within_log_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.getD_eq_of_prefix := Kolmogorov.getD_eq_of_prefix_of_lt_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.getD_xorStr := Kolmogorov.getD_xorStr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.goodPrefix := Kolmogorov.goodPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hasZeroRun := Kolmogorov.hasZeroRun

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hasZeroRun_iff := Kolmogorov.hasZeroRun_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hasZeroRun_primrec := Kolmogorov.hasZeroRun_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyDecoder := Kolmogorov.heavyDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyDecoder_isDecompressor := Kolmogorov.heavyDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyDecoder_produces := Kolmogorov.heavyDecoder_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum := Kolmogorov.heavyStringsEnum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum_eq_rec := Kolmogorov.heavyEnum_eq_rec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum_length_le := Kolmogorov.heavyEnum_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum_nodup := Kolmogorov.heavyEnum_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum_prefix_of_le := Kolmogorov.heavyEnum_prefix_of_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum_prefix_succ := Kolmogorov.heavyEnum_prefix_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyEnum_primrec := Kolmogorov.heavyEnum_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyI := Kolmogorov.heavyI

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyI_primrec := Kolmogorov.heavyI_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyS := Kolmogorov.heavyS

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyS_primrec := Kolmogorov.heavyS_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyT := Kolmogorov.heavyT

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavyT_primrec := Kolmogorov.heavyT_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.heavy_condK_bound := Kolmogorov.heavy_condK_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hitAt := Kolmogorov.hitAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hitAt_iff := Kolmogorov.hitAt_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hitAt_mono := Kolmogorov.hitAt_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.hitAt_primrec := Kolmogorov.hitAt_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.incompressibleFinset := Kolmogorov.incompressibleFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.incompressible_contains_zero_run :=
  Kolmogorov.incompressible_contains_zero_run

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.info := Kolmogorov.info

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.info_asymmetric_example := Kolmogorov.info_asymmetric_example

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.info_pair_chain_rule := Kolmogorov.info_pair_chain_rule

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.isHeavyAt := Kolmogorov.isHeavyAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.isHeavyAt_mono := Kolmogorov.isHeavyAt_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.isHeavyAt_primrec := Kolmogorov.isHeavyAt_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.isPrefix_of_isPrefix_append := Kolmogorov.isPrefix_of_isPrefix_append

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.length_filter_eq_card_toFinset_filter :=
  Kolmogorov.length_filter_eq_card_toFinset_filter

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.length_natBits_le_log := Kolmogorov.length_natBits_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.length_padTo := Kolmogorov.length_padTo

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.length_seqPrefix := Kolmogorov.length_seqPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.length_xorStr := Kolmogorov.length_xorStr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.levin_information_conservation :=
  Kolmogorov.levin_information_conservation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey := Kolmogorov.lexKey

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_append := Kolmogorov.lexKey_append

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_cons := Kolmogorov.lexKey_cons

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_inj := Kolmogorov.lexKey_inj

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_lt := Kolmogorov.lexKey_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_primrec := Kolmogorov.lexKey_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_take := Kolmogorov.lexKey_take

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lexKey_take_le := Kolmogorov.lexKey_take_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.list_countP_mono := Kolmogorov.list_countP_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.list_sum_map_add := Kolmogorov.list_sum_map_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.lowCount := Kolmogorov.lowCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mBodyL := Kolmogorov.mBodyL

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mBodyL_primrec := Kolmogorov.mBodyL_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mBodyR := Kolmogorov.mBodyR

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mBodyR_primrec := Kolmogorov.mBodyR_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mCheck := Kolmogorov.mCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mCheck_primrec := Kolmogorov.mCheck_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mFind := Kolmogorov.mFind

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mFind_primrec := Kolmogorov.mFind_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mLeft := Kolmogorov.mLeft

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mLeft_eq_true_of_sat := Kolmogorov.mLeft_eq_true_of_sat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mLeft_le_true := Kolmogorov.mLeft_le_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mLeft_primrec := Kolmogorov.mLeft_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mLevelCount := Kolmogorov.mLevelCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mRight := Kolmogorov.mRight

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mRight_eq_true_of_sat := Kolmogorov.mRight_eq_true_of_sat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mRight_le_true := Kolmogorov.mRight_le_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mRight_primrec := Kolmogorov.mRight_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mSearch := Kolmogorov.mSearch

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mSearch_partrec := Kolmogorov.mSearch_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mSearch_spec := Kolmogorov.mSearch_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mTrueLeft := Kolmogorov.mTrueLeft

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mTrueLeft_le_level := Kolmogorov.mTrueLeft_le_level

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mTrueLeft_strict := Kolmogorov.mTrueLeft_strict

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mTrueRight := Kolmogorov.mTrueRight

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mTrueRight_le_level := Kolmogorov.mTrueRight_le_level

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mTrueRight_strict := Kolmogorov.mTrueRight_strict

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.matchingSeq := Kolmogorov.matchingSeq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.matchingSeqAux := Kolmogorov.matchingSeqAux

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.matchingSeqAux_length := Kolmogorov.matchingSeqAux_length
