/-
Copyright (c) 2026 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovMathlib.Complexity.AlphabetComplexity.AlphabetChangeBound
import KolmogorovMathlib.Complexity.AlphabetComplexity.QAryDecompressors
import KolmogorovMathlib.Complexity.BusyBeaver
import KolmogorovMathlib.Complexity.CanonicalObjects.Counting
import KolmogorovMathlib.Complexity.CanonicalObjects.HubEquivalence
import KolmogorovMathlib.Complexity.CanonicalObjects.HubReductions
import KolmogorovMathlib.Complexity.Chaitin
import KolmogorovMathlib.Complexity.ConditionalComplexity.AverageBounds.Expectation
import KolmogorovMathlib.Complexity.ConditionalComplexity.AverageBounds.Tail
import KolmogorovMathlib.Complexity.ConditionalComplexity.Continuity
import KolmogorovMathlib.Complexity.DifferentDecompressors
import KolmogorovMathlib.Complexity.EnumerableFamilies.CalibratedBlocks
import KolmogorovMathlib.Complexity.EnumerableFamilies.CalibratedComplexity
import KolmogorovMathlib.Complexity.EnumerableFamilies.CountingBounds
import KolmogorovMathlib.Complexity.EnumerableFamilies.Enumeration.BlockCombinatorics
import KolmogorovMathlib.Complexity.EnumerableFamilies.Enumeration.BlockComputability
import KolmogorovMathlib.Complexity.GrowthEnumeration
import KolmogorovMathlib.Complexity.IncompressibleStrings.Deficiency
import KolmogorovMathlib.Complexity.IncompressibleStrings.SplitDecompressors
import KolmogorovMathlib.Complexity.InfiniteSequences.MonotoneComparison
import KolmogorovMathlib.Complexity.InfiniteSequences.MonotoneGap
import KolmogorovMathlib.Complexity.InfiniteSequences.PrefixComplexity
import KolmogorovMathlib.Complexity.Information.ConservationBounds
import KolmogorovMathlib.Complexity.KolmogorovLevin.LogarithmicGap
import KolmogorovMathlib.Complexity.KolmogorovLevin.Refinements
import KolmogorovMathlib.Complexity.KolmogorovLevin.ShortDescriptions
import KolmogorovMathlib.Complexity.LayeredDecompressors
import KolmogorovMathlib.Complexity.PairComplexity.Basic
import KolmogorovMathlib.Complexity.PairComplexity.ConditionalMinimality
import KolmogorovMathlib.Complexity.PairComplexity.LogarithmicTerms.ConditionalBounds
import KolmogorovMathlib.Complexity.PairComplexity.LogarithmicTerms.PlainBounds
import KolmogorovMathlib.Complexity.RandomConditions.Bound.HeavyStringsEnumeration
import KolmogorovMathlib.Complexity.RandomConditions.Bound.StageComputability
import KolmogorovMathlib.Complexity.RandomConditions.Enumeration
import KolmogorovMathlib.Complexity.SecondIncompleteness

/-!
# Deprecated aliases: Complexity

Old names of declarations in the `KolmogorovMathlib.Complexity`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.chaitinBound := Kolmogorov.FormalSystem.chaitin_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.chaitinIncompleteness :=
  Kolmogorov.FormalSystem.chaitin_incompleteness

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.enumBoundsComputable := Kolmogorov.FormalSystem.enumBounds_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.enumBoundsSound := Kolmogorov.FormalSystem.enumBounds_sound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.isBoundGtComputable := Kolmogorov.FormalSystem.isBoundGt_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.isBoundGtSearchComputable :=
  Kolmogorov.FormalSystem.isBoundGtSearch_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.FormalSystem.isBoundGtSearchPredicateComputable :=
  Kolmogorov.FormalSystem.isBoundGtSearchPredicate_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.KRFormalSystem.krInduction := Kolmogorov.KRFormalSystem.kr_induction

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.KRFormalSystem.secondIncompleteness :=
  Kolmogorov.KRFormalSystem.second_incompleteness

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.D_bin := Kolmogorov.D_bin

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.D_bin_partrec := Kolmogorov.D_bin_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.D_q := Kolmogorov.D_q

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.D_q_partrec := Kolmogorov.D_q_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.IsQOptimal := Kolmogorov.IsQOptimal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.IsRE.and_decidable := Kolmogorov.IsRE.and_decidable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.M_Exercise06 := Kolmogorov.growthDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.M_Exercise06_partrec := Kolmogorov.growthDecompressor_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.QMap := Kolmogorov.QMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.Thm15Reduces := Kolmogorov.CanonicalObjectReduces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.Thm15Reduces.refl := Kolmogorov.CanonicalObjectReduces.refl

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.Thm15Reduces.trans := Kolmogorov.CanonicalObjectReduces.trans

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4FoldStep := Kolmogorov.bitsToFin4FoldStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4FoldStep_primrec := Kolmogorov.bitsToFin4FoldStep_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4Fold_fst_of_even := Kolmogorov.bitsToFin4Fold_fst_of_even

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4List := Kolmogorov.bitsToFin4List

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4List_cons_cons := Kolmogorov.bitsToFin4List_cons_cons

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4List_fin4ListToBits := Kolmogorov.bitsToFin4List_fin4ListToBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4List_length_of_even := Kolmogorov.bitsToFin4List_length_of_even

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.bitsToFin4List_primrec := Kolmogorov.bitsToFin4List_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.busyBeaverOf_le_busyBeaver_shift :=
  Kolmogorov.busyBeaverOf_le_busyBeaver_shift

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.busyBeaver_dominates_partrec := Kolmogorov.busyBeaver_dominates_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.busyBeaver_shift_ge_apply := Kolmogorov.busyBeaver_shift_ge_apply

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.canonicalObject := Kolmogorov.canonicalObject

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.canonicalObject_complexity_eq := Kolmogorov.canonicalObject_complexity_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.canonicalObject_equivalence_two_decompressors :=
  Kolmogorov.canonicalObject_equivalence_two_decompressors

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.canonicalObject_mutual_reduction :=
  Kolmogorov.canonicalObject_mutual_reduction

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.card_Ioc_sum_boole_le := Kolmogorov.card_Ioc_sum_boole_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.card_plainK_eq_le_pow := Kolmogorov.card_plainK_eq_le_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.card_plainK_lt_mem_Icc := Kolmogorov.card_plainK_lt_mem_Icc

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2 := Kolmogorov.decompressor2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check := Kolmogorov.decompressor2Check

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_computable := Kolmogorov.decompressor2Check_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_def := Kolmogorov.decompressor2Check_def

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_fires := Kolmogorov.decompressor2Check_fires

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_isSome_computable :=
  Kolmogorov.decompressor2Check_isSome_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_ofOpt_partrec :=
  Kolmogorov.decompressor2Check_ofOpt_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_rfind_p_partrec :=
  Kolmogorov.decompressor2Check_rfind_p_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_rfind_partrec :=
  Kolmogorov.decompressor2Check_rfind_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2Check_spec := Kolmogorov.decompressor2Check_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.decompressor2_partrec := Kolmogorov.decompressor2_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.dropLast_primrec := Kolmogorov.dropLast_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enat_sInf_mem := Kolmogorov.enat_sInf_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumAccum := Kolmogorov.enumAccum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumFound := Kolmogorov.enumFound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumVList := Kolmogorov.enumVList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumVStep := Kolmogorov.enumVStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_list_length_mono := Kolmogorov.enumV_list_length_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_list_mem := Kolmogorov.enumV_list_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_list_nodup := Kolmogorov.enumV_list_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_list_prefix := Kolmogorov.enumV_list_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_list_primrec := Kolmogorov.enumV_list_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_list_sub := Kolmogorov.enumV_list_sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enumV_step_mem := Kolmogorov.enumV_step_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum := Kolmogorov.enumAccum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_getElem := Kolmogorov.enum_accum_getElem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_length_le := Kolmogorov.enum_accum_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_length_le_ncard := Kolmogorov.enum_accum_length_le_ncard

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_mem_A := Kolmogorov.enum_accum_mem_A

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_nodup := Kolmogorov.enum_accum_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_prefix := Kolmogorov.enum_accum_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_accum_primrec := Kolmogorov.enum_accum_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_found := Kolmogorov.enumFound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.enum_found_primrec := Kolmogorov.enum_found_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.evalnIsSome := Kolmogorov.evalnIsSome

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.evalnIsSomeArg := Kolmogorov.evalnIsSomeArg

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.evalnIsSomeArg_primrec := Kolmogorov.evalnIsSomeArg_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.evalnIsSome_computable := Kolmogorov.evalnIsSome_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.evalnIsSome_p_computable := Kolmogorov.evalnIsSome_p_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise01_lipschitz := Kolmogorov.plainK_dist_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise01_log := Kolmogorov.plainK_sub_plainK_le_two_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise02_count_range := Kolmogorov.card_plainK_lt_mem_Icc

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise02_layer_card := Kolmogorov.card_plainK_eq_le_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise02_layer_empty :=
  Kolmogorov.exists_isOptimalConditional_infinite_empty_complexityLayer

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise03_average := Kolmogorov.sum_cVal_allStrings_within_const

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise04_four_letters := Kolmogorov.plainK_fourLetterAlphabet_eq_half

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise05_q_letters := Kolmogorov.abs_qPlainK_mul_logb_sub_cVal_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise06_growth :=
  Kolmogorov.plainK_le_log_card_of_isEnumerableFamily_of_growth

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise08_different_decompressors :=
  Kolmogorov.canonicalObject_equivalence_two_decompressors

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise11_busyBeaver_shift := Kolmogorov.busyBeaver_shift_ge_apply

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ListToBits := Kolmogorov.fin4ListToBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ListToBits_bitsToFin4List_of_even :=
  Kolmogorov.fin4ListToBits_bitsToFin4List_of_even

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ListToBits_length := Kolmogorov.fin4ListToBits_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ListToBits_primrec := Kolmogorov.fin4ListToBits_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ToBits := Kolmogorov.fin4ToBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ToBits_length := Kolmogorov.fin4ToBits_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fin4ToBits_primrec := Kolmogorov.fin4ToBits_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.findIdx_getElem_eq := Kolmogorov.findIdx_getElem_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.firstAppearsAt_spec := Kolmogorov.firstAppearsAt_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.growth_sum_le := Kolmogorov.growth_sum_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.haltTime := Kolmogorov.haltTimeNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.haltingList_of_busyBeaver_bound :=
  Kolmogorov.haltingList_of_busyBeaver_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.haltingProgramsBounded := Kolmogorov.haltingProgramsBounded

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.list_sum_map_eq_finset_sum := Kolmogorov.list_sum_map_eq_finset_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.list_sum_map_le := Kolmogorov.list_sum_map_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.maxHaltTime := Kolmogorov.maxHaltTimeNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.mem_enum_accum_of_mem_found := Kolmogorov.mem_enum_accum_of_mem_found

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objBusyBeaver := Kolmogorov.objBusyBeaver

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objComplexityCount := Kolmogorov.objComplexityCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objComplexityGraph := Kolmogorov.objComplexityGraph

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objComplexityList := Kolmogorov.objComplexityList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objFirstIncompressible := Kolmogorov.objFirstIncompressible

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objHaltingCount := Kolmogorov.objHaltingCount

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objHaltingList := Kolmogorov.objHaltingList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objMaxTime := Kolmogorov.objMaxTime

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.objSlowestProgram := Kolmogorov.objSlowestProgram

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.pBlock := Kolmogorov.pBlock

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.pBlock_nodup := Kolmogorov.pBlock_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.pBlock_primrec := Kolmogorov.pBlock_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.pBlock_stable := Kolmogorov.pBlock_stable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.pairToFin4 := Kolmogorov.pairToFin4

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.pairToFin4_primrec := Kolmogorov.pairToFin4_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.plainK_dist_le := Kolmogorov.plainK_dist_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.plainK_fourLetterAlphabet_eq_half :=
  Kolmogorov.plainK_fourLetterAlphabet_eq_half

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.plainK_sub_plainK_le_two_log := Kolmogorov.plainK_sub_plainK_le_two_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock := Kolmogorov.qBlock

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_length := Kolmogorov.qBlock_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_length_le := Kolmogorov.qBlock_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_level_unique := Kolmogorov.qBlock_level_unique

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_mem_enumV := Kolmogorov.qBlock_mem_enumV

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_mem_pBlock := Kolmogorov.qBlock_mem_pBlock

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_nodup := Kolmogorov.qBlock_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_notMem_qUsed := Kolmogorov.qBlock_notMem_qUsed

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_primrec := Kolmogorov.qBlock_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_stable := Kolmogorov.qBlock_stable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qBlock_subset_qUsed := Kolmogorov.qBlock_subset_qUsed

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qCondK := Kolmogorov.qCondK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qPlainK := Kolmogorov.qPlainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qStage := Kolmogorov.qStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qStage_iff := Kolmogorov.qStage_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qStage_le := Kolmogorov.qStage_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qStage_mono := Kolmogorov.qStage_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qStage_primrec := Kolmogorov.qStage_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qUsed := Kolmogorov.qUsed

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qUsed_length_lt := Kolmogorov.qUsed_length_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qUsed_primrec := Kolmogorov.qUsed_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qUsed_stable := Kolmogorov.qUsed_stable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.qUsed_succ := Kolmogorov.qUsed_succ

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.rfind_eq_of_spec := Kolmogorov.rfind_eq_of_spec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.simpleStrings_isSimple := Kolmogorov.simpleStrings_isSimple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.sum_Ioc_pow := Kolmogorov.sum_Ioc_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.sum_range_computable := Kolmogorov.sum_range_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem07_a :=
  Kolmogorov.isEnumerableFamily_complexityBelow_and_card_lt_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem07_b :=
  Kolmogorov.plainK_lt_of_mem_of_isEnumerableFamily_of_card_lt_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem08_a := Kolmogorov.isUpperSemicomputable_plainK_and_card_lt_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem08_b :=
  Kolmogorov.plainK_le_of_isUpperSemicomputable_of_card_lt_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem09 := Kolmogorov.plainK_within_const_of_calibrated

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem09_direction1 :=
  Kolmogorov.plainK_le_of_isUpperSemicomputable_of_card_le_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem09_direction2 :=
  Kolmogorov.le_plainK_of_two_pow_le_card_of_nonGrowth

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem10 := Kolmogorov.simpleStrings_isSimple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem10_check := Kolmogorov.enumeratedLongString

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem10_enumerable :=
  Kolmogorov.isEnumerableSet_two_mul_plainK_lt_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem10_infinite := Kolmogorov.infinite_compl_two_mul_plainK_lt_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem11 := Kolmogorov.busyBeaver_dominates_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem12 := Kolmogorov.busyBeaverOf_le_busyBeaver_shift

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem13 := Kolmogorov.haltingList_of_busyBeaver_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem15_complexity := Kolmogorov.canonicalObject_complexity_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.theorem15_equivalence := Kolmogorov.canonicalObject_mutual_reduction

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15_boundedOutputStage_eq :=
  Kolmogorov.boundedOutputStage_eq_completedBoundedOutput

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15_countHalts_maxHaltingStage := Kolmogorov.countHalts_maxHaltingStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15_haltTime_le := Kolmogorov.haltTime_le_of_haltsWithin

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15_haltsWithin_haltTime := Kolmogorov.haltsWithin_haltTime

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.thm15_maxHaltingStage_le_of_countHalts :=
  Kolmogorov.maxHaltingStage_le_of_countHalts_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.D_cond := Kolmogorov.D_cond

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.D_cond_fn := Kolmogorov.D_cond_fn

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.D_cond_fn_computable := Kolmogorov.D_cond_fn_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.D_cond_partrec := Kolmogorov.D_cond_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.D_ones := Kolmogorov.D_ones

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.D_ones_partrec := Kolmogorov.D_ones_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.D_sim := Kolmogorov.ShortDescriptions.D_sim

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.D_sim_isDecompressor :=
  Kolmogorov.ShortDescriptions.D_sim_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual := Kolmogorov.ShortDescriptions.accumQual

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual_card_le :=
  Kolmogorov.ShortDescriptions.accumQual_card_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual_computable :=
  Kolmogorov.ShortDescriptions.accumQual_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual_le_of_le :=
  Kolmogorov.ShortDescriptions.accumQual_le_of_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual_nodup :=
  Kolmogorov.ShortDescriptions.accumQual_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual_prefix :=
  Kolmogorov.ShortDescriptions.accumQual_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.accumQual_primrec :=
  Kolmogorov.ShortDescriptions.accumQual_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.bitsToNat_app_replicate_false :=
  Kolmogorov.ShortDescriptions.bitsToNat_app_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.bitsToNat_replicate_false :=
  Kolmogorov.ShortDescriptions.bitsToNat_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.checkQual := Kolmogorov.ShortDescriptions.checkQual

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.checkQual_primrec :=
  Kolmogorov.ShortDescriptions.checkQual_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.condK_le_of_produces :=
  Kolmogorov.ShortDescriptions.condK_le_of_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.decodeBits_app_replicate_false :=
  Kolmogorov.decodeBits_append_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.decodeBits_replicate_false :=
  Kolmogorov.ShortDescriptions.decodeBits_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.descCountAt := Kolmogorov.ShortDescriptions.descCountAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.descCountAt_primrec :=
  Kolmogorov.ShortDescriptions.descCountAt_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.descriptionsLe_subset :=
  Kolmogorov.ShortDescriptions.descriptionsLe_subset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.evalDAt := Kolmogorov.ShortDescriptions.evalDAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.evalDAt_primrec :=
  Kolmogorov.ShortDescriptions.evalDAt_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.k_le_n_of_many_desc :=
  Kolmogorov.ShortDescriptions.k_le_n_of_many_desc

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.padBits := Kolmogorov.ShortDescriptions.padBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.padBits_bitsToNat :=
  Kolmogorov.ShortDescriptions.padBits_bitsToNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.padBits_decodeBits :=
  Kolmogorov.ShortDescriptions.padBits_decodeBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.padBits_length :=
  Kolmogorov.ShortDescriptions.padBits_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.stageQual := Kolmogorov.ShortDescriptions.stageQual

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.stageQual_primrec :=
  Kolmogorov.ShortDescriptions.stageQual_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.Exercise39Helpers.stageQual_subset_accumQual :=
  Kolmogorov.ShortDescriptions.stageQual_subset_accumQual

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.StageP := Kolmogorov.StageP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.StepP := Kolmogorov.StepP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.T1 := Kolmogorov.T1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.average_condK_eq_condK_length := Kolmogorov.average_condK_eq_condK_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.bitsToNat_append_false := Kolmogorov.bitsToNat_append_single_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.bitsToNat_inj_of_length_eq := Kolmogorov.bitsToNat_inj_of_length_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.bitsToNat_lt_two_pow := Kolmogorov.bitsToNat_lt_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.bitsToNat_padTo := Kolmogorov.bitsToNat_padTo

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.bitsToNat_replicate_false := Kolmogorov.bitsToNat_append_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.cCondPair := Kolmogorov.cCondPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.cCondPair_lt_imp_condK_le := Kolmogorov.cCondPair_lt_imp_condK_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.cPair := Kolmogorov.cPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.cPairVal := Kolmogorov.cPairVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.cTriple := Kolmogorov.cTriple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.cTripleVal := Kolmogorov.cTripleVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.candStage := Kolmogorov.candStage

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.candStage_nodup := Kolmogorov.candStage_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.candStage_primrec := Kolmogorov.candStage_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_incompressible_mem_Icc := Kolmogorov.card_incompressible_mem_Icc

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_lt_of_condK_le := Kolmogorov.card_lt_of_condK_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_noRunFinset := Kolmogorov.card_noRunFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_noRunFinset_le := Kolmogorov.card_noRunFinset_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_noRunFinset_step := Kolmogorov.card_noRunFinset_step

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_pairCodesFinset := Kolmogorov.card_pairCodesFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_pairsFinset := Kolmogorov.card_pairsFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.card_shortestDescriptions_le := Kolmogorov.card_shortestDescriptions_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.computable_iff_condK_prefix_bounded :=
  Kolmogorov.computable_iff_condK_prefix_bounded

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.computable_of_plainK_prefix_le_log :=
  Kolmogorov.computable_of_plainK_prefix_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condDeficiency := Kolmogorov.condDeficiency

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condInfo := Kolmogorov.condInfo

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_append_bit_eq := Kolmogorov.condK_append_bit_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_cond_swapPairCode_le := Kolmogorov.condK_cond_swapPairCode_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_dichotomyD1_le := Kolmogorov.condK_dichotomyD1_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_dichotomyD2_le := Kolmogorov.condK_dichotomyD2_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_eq_condCVal := Kolmogorov.condK_eq_condCVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_eq_min_program_complexity :=
  Kolmogorov.condK_eq_min_program_complexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_le_of_many_descriptions := Kolmogorov.condK_le_of_many_descriptions

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_le_of_probability_condK_le :=
  Kolmogorov.condK_le_of_probability_condK_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_le_of_produces := Kolmogorov.condK_le_of_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_le_totalCondK_le_plainK := Kolmogorov.condK_le_totalCondK_le_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_minimal_upperSemicomputable :=
  Kolmogorov.condK_minimal_upperSemicomputable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_ne_top_of_opt := Kolmogorov.condK_ne_top_of_opt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_pair_pair_le_condK := Kolmogorov.condK_pair_pair_le_condK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.condK_triangle := Kolmogorov.condK_triangle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countAdviceDecoder := Kolmogorov.countAdviceDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countAdviceDecoder_isDecompressor :=
  Kolmogorov.countAdviceDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countP_allStrings_eq_card := Kolmogorov.countP_allStrings_eq_card

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countP_hit_le := Kolmogorov.countP_hit_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countP_lt_countP := Kolmogorov.countP_lt_countP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countProgramDecoder := Kolmogorov.countProgramDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countProgramDecoder_isDecompressor :=
  Kolmogorov.countProgramDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countY := Kolmogorov.countY

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countY_mono := Kolmogorov.countY_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.countY_primrec := Kolmogorov.countY_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.decodeFirst_z := Kolmogorov.decodeFirst_z

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.decodeSecond_z := Kolmogorov.decodeSecond_z

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.decodeTriple := Kolmogorov.decodeTriple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.decodeTriple_primrec := Kolmogorov.decodeTriple_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dedup_eq_foldr := Kolmogorov.dedup_eq_foldr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.deficiency := Kolmogorov.plainDeficiency

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.deficiencyMap := Kolmogorov.deficiencyMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.deficiencyMap_partrec := Kolmogorov.deficiencyMap_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.deficiency_bound_helper := Kolmogorov.deficiency_bound_helper

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.deficiency_comparison_le_log := Kolmogorov.deficiency_comparison_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.descriptionsLe := Kolmogorov.descriptionsLe

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.deterministic_information_conservation :=
  Kolmogorov.deterministic_information_conservation

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD1 := Kolmogorov.dichotomyD1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD1_decompressor := Kolmogorov.dichotomyD1_decompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD1_elem_eval := Kolmogorov.dichotomyD1_elem_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD1_eval := Kolmogorov.dichotomyD1_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD1_getD_eval := Kolmogorov.dichotomyD1_getD_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD2 := Kolmogorov.dichotomyD2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD2_decompressor := Kolmogorov.dichotomyD2_decompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD2_elem_eval := Kolmogorov.dichotomyD2_elem_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD2_eval := Kolmogorov.dichotomyD2_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyD2_getD_eval := Kolmogorov.dichotomyD2_getD_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum1 := Kolmogorov.dichotomyEnum1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum1_mem := Kolmogorov.dichotomyEnum1_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.dichotomyEnum1_primrec := Kolmogorov.dichotomyEnum1_primrec
