import KolmogorovMathlib.Complexity.AlphabetComplexity.QAryDecompressors
import KolmogorovMathlib.Complexity.ChaitinCorollaries
import KolmogorovMathlib.Complexity.ConditionalComplexity.AverageBounds.Expectation
import KolmogorovMathlib.Complexity.ConditionalComplexity.AverageBounds.Tail
import KolmogorovMathlib.Complexity.ConditionalComplexity.Continuity
import KolmogorovMathlib.Complexity.Incompressibility
import KolmogorovMathlib.Complexity.IncompressibleStrings.Deficiency
import KolmogorovMathlib.Complexity.IncompressibleStrings.SplitDecompressors
import KolmogorovMathlib.Complexity.InfiniteSequences.MonotoneComparison
import KolmogorovMathlib.Complexity.InfiniteSequences.MonotoneGap
import KolmogorovMathlib.Complexity.InfiniteSequences.PrefixComplexity
import KolmogorovMathlib.Complexity.Information.MutualInformation
import KolmogorovMathlib.Complexity.KolmogorovLevin.LogarithmicGap
import KolmogorovMathlib.Complexity.KolmogorovLevin.Refinements
import KolmogorovMathlib.Complexity.KolmogorovLevin.ShortDescriptions
import KolmogorovMathlib.Complexity.NatComplexity
import KolmogorovMathlib.Complexity.PairComplexity.Basic
import KolmogorovMathlib.Complexity.PairComplexity.ConditionalMinimality
import KolmogorovMathlib.Complexity.PairComplexity.LogarithmicTerms.ConditionalBounds
import KolmogorovMathlib.Complexity.PairComplexity.LogarithmicTerms.PlainBounds
import KolmogorovMathlib.Complexity.PairComplexity.Overhead
import KolmogorovMathlib.Complexity.Properties
import KolmogorovMathlib.Complexity.RandomConditions.Bound.HeavyStringsEnumeration
import KolmogorovMathlib.Complexity.RandomConditions.Bound.StageComputability
import KolmogorovMathlib.Complexity.SecondIncompletenessCorollaries
import KolmogorovMathlib.Complexity.SelfComplexity.TokenGame.BoardMachinery
import KolmogorovMathlib.Complexity.SelfComplexity.TokenGame.LowerBound
import KolmogorovMathlib.Complexity.Uncomputability

/-!
# Deprecated aliases: Complexity

Old names of declarations in the `KolmogorovMathlib.Complexity`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.matchingSeqAux_prefix := Kolmogorov.matchingSeqAux_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_candStage_iff := Kolmogorov.mem_candStage_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_conditionalOutputSnapshot_mono :=
  Kolmogorov.mem_conditionalOutputSnapshot_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_ex45RowEnum := Kolmogorov.mem_gameRowEnum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_ex45Tokens := Kolmogorov.mem_gameTokens

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_heavyEnum_isHeavyAt := Kolmogorov.mem_heavyEnum_isHeavyAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_heavyEnum_of_cand := Kolmogorov.mem_heavyEnum_of_cand

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_noRunFinset := Kolmogorov.mem_noRunFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.mem_noRunList := Kolmogorov.mem_noRunList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.min_log_add_le := Kolmogorov.min_log_add_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.natBits_length_le_log_add_one := Kolmogorov.length_natBits_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.nat_bits_len_le_log_succ := Kolmogorov.length_natBits_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.nat_bits_length_log_log_bound := Kolmogorov.nat_bits_length_log_log_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.nat_bits_length_p_bound := Kolmogorov.nat_bits_length_p_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.noRunFinset := Kolmogorov.noRunFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.noRunFinset_subset := Kolmogorov.noRunFinset_subset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.noRunList := Kolmogorov.noRunList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.noRunList_nodup := Kolmogorov.noRunList_nodup

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.noRunList_primrec := Kolmogorov.noRunList_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.not_plainK_pair_le_add_single_log :=
  Kolmogorov.not_plainK_pair_le_add_single_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.oneBitFlipDecompressor := Kolmogorov.oneBitFlipDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.oneBitFlipDecompressor_isDecompressor :=
  Kolmogorov.oneBitFlipDecompressor_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.oneBitFlipDecompressor_produces :=
  Kolmogorov.oneBitFlipDecompressor_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.oneBitFlip_overhead_bound := Kolmogorov.oneBitFlip_overhead_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.onesZerosSeq := Kolmogorov.onesZerosSeq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.padString := Kolmogorov.padString

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.padString_length := Kolmogorov.padString_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.padTo := Kolmogorov.padTo

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.pairCodeWithLengthBits := Kolmogorov.pairCodeWithLengthBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.pairCodeWithLengthBits_computable :=
  Kolmogorov.pairCodeWithLengthBits_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.pairCodesFinset := Kolmogorov.pairCodesFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.pairsFinset := Kolmogorov.pairsFinset

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.parsePair := Kolmogorov.parsePair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.parsePair_computable := Kolmogorov.parsePair_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.parsePair_encode := Kolmogorov.parsePair_encode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_add_condK_le_plainK_pair_add_three_log :=
  Kolmogorov.plainK_add_condK_le_plainK_pair_add_three_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_card_incompressible_ge := Kolmogorov.plainK_card_incompressible_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_eq_condK_self_plainK := Kolmogorov.plainK_eq_condK_self_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_flipBit_le_add_log := Kolmogorov.plainK_flipBit_le_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_halves_of_incompressible :=
  Kolmogorov.plainK_halves_of_incompressible

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_le_of_condK_lt := Kolmogorov.plainK_le_of_condK_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_add_log_add_logLog_add_two_logLogLog :=
  Kolmogorov.plainK_pair_le_add_log_add_logLog_add_two_logLogLog

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_add_log_add_two_logLog :=
  Kolmogorov.plainK_pair_le_add_log_add_two_logLog

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_add_log_of_add := Kolmogorov.plainK_pair_le_add_log_of_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_add_logs := Kolmogorov.plainK_pair_le_add_logs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_add_two_log := Kolmogorov.plainK_pair_le_add_two_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_add_two_log_add_condK :=
  Kolmogorov.plainK_pair_le_add_two_log_add_condK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_le_two_mul := Kolmogorov.plainK_pair_le_two_mul

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_pair_self_plainK_eq := Kolmogorov.plainK_pair_self_plainK_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_sub_condK_le_two_mul_plainK :=
  Kolmogorov.plainK_sub_condK_le_two_mul_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_substring_of_incompressible :=
  Kolmogorov.plainK_substring_of_incompressible

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.plainK_triple_le_add_log := Kolmogorov.plainK_triple_le_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.prefixDecompressor := Kolmogorov.prefixDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.prefixDecompressor_isDecompressor :=
  Kolmogorov.prefixDecompressor_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.prefixSplitDecoder := Kolmogorov.prefixSplitDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.prefixSplitDecoder_isDecompressor :=
  Kolmogorov.prefixSplitDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.primrecPred_of_primrec_decide := Kolmogorov.primrecPred_of_primrec_decide

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.primrec_decide_of_primrecPred := Kolmogorov.primrec_decide_of_primrecPred

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.produces_deficiencyMap := Kolmogorov.produces_deficiencyMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.programComplexity := Kolmogorov.programComplexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_k := Kolmogorov.proj_k

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_l := Kolmogorov.proj_l

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_lk := Kolmogorov.proj_lk

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_n := Kolmogorov.proj_n

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_p := Kolmogorov.proj_p

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_pz_x := Kolmogorov.proj_pz_x

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_1 := Kolmogorov.proj_step_1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_1_1 := Kolmogorov.proj_step_1_1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_2 := Kolmogorov.proj_step_2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_lk := Kolmogorov.proj_step_lk

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_p122 := Kolmogorov.proj_step_p122

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_z1 := Kolmogorov.proj_step_z1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_step_z2 := Kolmogorov.proj_step_z2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_x := Kolmogorov.proj_x

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_z := Kolmogorov.proj_z

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_z1 := Kolmogorov.proj_z1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.proj_z2 := Kolmogorov.proj_z2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.rectangle_dichotomy := Kolmogorov.rectangle_dichotomy

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runIndexDecoder := Kolmogorov.runIndexDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runIndexDecoder_isDecompressor :=
  Kolmogorov.runIndexDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runIndex_produces := Kolmogorov.runIndex_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runOutC := Kolmogorov.runOutC

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runOutC_complete := Kolmogorov.runOutC_complete

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runOutC_mono := Kolmogorov.runOutC_mono

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runOutC_primrec := Kolmogorov.runOutC_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.runOutC_sound := Kolmogorov.runOutC_sound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.selfCondDecompressor := Kolmogorov.selfCondDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.selfCondDecompressor_partrec := Kolmogorov.selfCondDecompressor_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqC := Kolmogorov.seqC

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqCinf := Kolmogorov.seqCinf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqM := Kolmogorov.seqM

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqMinf := Kolmogorov.seqMinf

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqPrefix := Kolmogorov.seqPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqPrefix_computable := Kolmogorov.seqPrefix_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqPrefix_matchingSeq := Kolmogorov.seqPrefix_matchingSeq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqPrefix_onesZeros := Kolmogorov.seqPrefix_onesZeros

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.seqPrefix_take := Kolmogorov.seqPrefix_take

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.shortCondDecompressor := Kolmogorov.shortCondDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.shortCondDecompressor_computable :=
  Kolmogorov.shortCondDecompressor_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.shortestDescriptions := Kolmogorov.shortestDescriptions

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.substringDecoder := Kolmogorov.substringDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.substringDecoder_isDecompressor :=
  Kolmogorov.substringDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.suffixSplitDecoder := Kolmogorov.suffixSplitDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.suffixSplitDecoder_isDecompressor :=
  Kolmogorov.suffixSplitDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.sum_countP_swap := Kolmogorov.sum_countP_swap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.sum_filter_length_le := Kolmogorov.sum_filter_length_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.sum_if_eq_mem := Kolmogorov.sum_if_eq_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.sum_map_const_nat := Kolmogorov.sum_map_const_nat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.sum_map_ite_eq_countP := Kolmogorov.sum_map_ite_one_zero_eq_countP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.sum_map_mul_right := Kolmogorov.sum_map_mul_right

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.symmLogsDecompressor := Kolmogorov.symmLogsDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.symmLogsDecompressor_isDecompressor :=
  Kolmogorov.symmLogsDecompressor_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_first_S1 := Kolmogorov.t16_first_S1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_first_S2 := Kolmogorov.t16_first_S2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_map2 := Kolmogorov.t16_map2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_pair2 := Kolmogorov.t16_pair2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_A := Kolmogorov.t16_second_A

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_B := Kolmogorov.t16_second_B

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_S1 := Kolmogorov.t16_second_S1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_S2 := Kolmogorov.t16_second_S2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_lenB := Kolmogorov.t16_second_lenB

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_lenp := Kolmogorov.t16_second_lenp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_rest1 := Kolmogorov.t16_second_rest1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_second_rest2 := Kolmogorov.t16_second_rest2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_A := Kolmogorov.t16_third_A

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_B := Kolmogorov.t16_third_B

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_C := Kolmogorov.t16_third_C

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_S1 := Kolmogorov.t16_third_S1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_S2 := Kolmogorov.t16_third_S2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_lenB := Kolmogorov.t16_third_lenB

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_lenC := Kolmogorov.t16_third_lenC

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_lenp := Kolmogorov.t16_third_lenp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_rest1 := Kolmogorov.t16_third_rest1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_rest2 := Kolmogorov.t16_third_rest2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.t16_third_rest3 := Kolmogorov.t16_third_rest3

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem16_first := Kolmogorov.plainK_pair_le_add_two_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem16_first_decompressor := Kolmogorov.pairSelfDelimitingFirst

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem16_second := Kolmogorov.plainK_pair_le_add_log_add_two_logLog

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem16_second_decompressor := Kolmogorov.pairSelfDelimitingSecond

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem16_third :=
  Kolmogorov.plainK_pair_le_add_log_add_logLog_add_two_logLogLog

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem16_third_decompressor := Kolmogorov.pairSelfDelimitingThird

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem19 := Kolmogorov.condK_minimal_upperSemicomputable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.theorem20 := Kolmogorov.plainK_pair_le_add_two_log_add_condK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.totalCondComplexity := Kolmogorov.totalCondComplexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.triangleDecoder := Kolmogorov.triangleDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.triangleDecoder_isDecompressor :=
  Kolmogorov.triangleDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.triangleDecoder_produces := Kolmogorov.triangleDecoder_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleDecompressor := Kolmogorov.tripleDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleDecompressor_isDecompressor :=
  Kolmogorov.tripleDecompressor_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleList := Kolmogorov.tripleList

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleList_comp := Kolmogorov.tripleList_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleProj1 := Kolmogorov.tripleProj1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleProj1_comp := Kolmogorov.tripleProj1_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleProj2 := Kolmogorov.tripleProj2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleProj2_comp := Kolmogorov.tripleProj2_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleProj3 := Kolmogorov.tripleProj3

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleProj3_comp := Kolmogorov.tripleProj3_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleSel1 := Kolmogorov.tripleSel1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleSel1_comp := Kolmogorov.tripleSel1_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleSel2 := Kolmogorov.tripleSel2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleSel2_comp := Kolmogorov.tripleSel2_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleSel3 := Kolmogorov.tripleSel3

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleSel3_comp := Kolmogorov.tripleSel3_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleStep2 := Kolmogorov.tripleStep2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.tripleStep3 := Kolmogorov.tripleStep3

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.two_pow_size_le := Kolmogorov.two_pow_size_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.unpadString := Kolmogorov.unpadString

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.unpadString_computable := Kolmogorov.unpadString_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.unpadString_padString := Kolmogorov.unpadString_padString

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.validPrefix := Kolmogorov.validPrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.validPrefix_step := Kolmogorov.validPrefix_step

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.xorStr := Kolmogorov.xorStr

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.xorStr_primrec := Kolmogorov.xorStr_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.xorStr_xorStr_left := Kolmogorov.xorStr_xorStr_left

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.xorStr_xorStr_right := Kolmogorov.xorStr_xorStr_right

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.zeroPadDecoder := Kolmogorov.zeroPadDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.zeroPadDecoder_isDecompressor := Kolmogorov.zeroPadDecoder_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.padBits := Kolmogorov.ShortDescriptions.padBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.plainK_V_ne_top := Kolmogorov.plainK_ne_top

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.plainK_ne_top_local := Kolmogorov.plainK_ne_top

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.ShortDescriptions.decodeBits_app_replicate_false :=
  Kolmogorov.decodeBits_append_replicate_false

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.cardCompressibleWordsLt := Kolmogorov.card_compressibleWordsLt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.cardGeneratedWordsLe := Kolmogorov.card_generatedWordsLe

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.cardStringsOfLength := Kolmogorov.card_stringsOfLength

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.chaitinGeneralized := Kolmogorov.chaitin_generalized

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKComp := Kolmogorov.condK_comp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKEqTopIff := Kolmogorov.condK_eq_top_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKGtIff := Kolmogorov.condK_gt_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKLeIff := Kolmogorov.condK_le_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKLeIsRe := Kolmogorov.condK_le_isRE

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKLePlainK := Kolmogorov.condK_le_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKMapLe := Kolmogorov.condK_map_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.condKSelf := Kolmogorov.condK_self

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.existsComplexInjective := Kolmogorov.exists_complex_injective

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.existsComplexString := Kolmogorov.exists_complex_string

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.existsIncompressibleString := Kolmogorov.exists_incompressible_string

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.existsPlainKNatGt := Kolmogorov.exists_plainKNat_gt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.gacs_condK_complexity_eq_log := Kolmogorov.exists_condK_cVal_within_log_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.growthLemma := Kolmogorov.growth_lemma

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.independenceExample_plainK_ne_top := Kolmogorov.plainK_ne_top

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.memStringsOfLength := Kolmogorov.mem_stringsOfLength

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.natBits_length_le_log_add_one := Kolmogorov.length_natBits_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.nat_bits_len_le_log_succ := Kolmogorov.length_natBits_le_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.noComputableUnboundedLowerBound := Kolmogorov.not_computable_unbounded_lowerBound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.notComputablePlainKNat := Kolmogorov.not_computable_plainKNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.padBits := Kolmogorov.ShortDescriptions.padBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKGtIsCore := Kolmogorov.plainK_gt_isCore

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKLeLength := Kolmogorov.plainK_le_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKMapLe := Kolmogorov.plainK_map_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKNatCompLe := Kolmogorov.plainKNat_comp_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKNatFindComplexLe := Kolmogorov.plainKNat_findComplex_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKNatGtIsCore := Kolmogorov.plainKNat_gt_isCore

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKNatInvariance := Kolmogorov.plainKNat_invariance

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainKNatLeLength := Kolmogorov.plainKNat_le_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainK_V_ne_top := Kolmogorov.plainK_ne_top

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainK_ne_top_local := Kolmogorov.plainK_ne_top

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrec_dropLast := Kolmogorov.dropLast_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.producesIsRe := Kolmogorov.produces_isRE

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.producesUnique := Kolmogorov.produces_unique

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.secondIncompletenessGeneralized := Kolmogorov.second_incompleteness_generalized
