/-
Copyright (c) 2026 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovMathlib.Foundation.Arslanov
import KolmogorovMathlib.Foundation.BigOperators
import KolmogorovMathlib.Foundation.EffectiveNotions
import KolmogorovMathlib.Foundation.FixedPointFree.ArslanovCompleteness
import KolmogorovMathlib.Foundation.FixedPointFree.HighComplexityTask
import KolmogorovMathlib.Foundation.ListUtil
import KolmogorovMathlib.Foundation.NatEncoding
import KolmogorovMathlib.Foundation.PrimrecExtras
import KolmogorovMathlib.Foundation.RSeparability
import KolmogorovMathlib.Foundation.RecursivelyEnumerable

/-!
# Deprecated aliases: Foundation

Old names of declarations in the `KolmogorovMathlib.Foundation`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.SolvesDiagonal := Kolmogorov.SolvesDiagonal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.SolvesFixedPointFree := Kolmogorov.SolvesFixedPointFree

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.SolvesHighComplexity := Kolmogorov.SolvesHighComplexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.arslanovHaltingSet := Kolmogorov.arslanovHaltingSet

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.arslanov_completeness := Kolmogorov.arslanov_completeness

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.arslanov_solvesHighComplexity_iff_halting :=
  Kolmogorov.arslanov_solvesHighComplexity_iff_halting

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise12_a_compressible := Kolmogorov.isRSeparable_compressibleStrings

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise12_a_upperGraph := Kolmogorov.isRSeparable_upperGraph_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise12_b_manyOne := Kolmogorov.isRSeparable_of_manyOneReducible

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise12_c_not_rSeparable :=
  Kolmogorov.exists_isEnumerableSet_not_isRSeparable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise13_diagonal_of_highComplexity :=
  Kolmogorov.solvesDiagonal_of_solvesHighComplexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise13_highComplexity_of_diagonal :=
  Kolmogorov.solvesHighComplexity_of_solvesDiagonal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise14_diagonal_of_fixedPointFree :=
  Kolmogorov.solvesDiagonal_of_fixedPointFree

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise14_fixedPointFree_of_diagonal :=
  Kolmogorov.fixedPointFree_of_solvesDiagonal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exercise15_arslanov :=
  Kolmogorov.arslanov_solvesHighComplexity_iff_halting

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exists_manyOne_reduction_to_halting :=
  Kolmogorov.exists_manyOne_reduction_to_halting

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.exists_string_operator := Kolmogorov.exists_string_operator

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.fixedPointFree_of_solvesDiagonal :=
  Kolmogorov.fixedPointFree_of_solvesDiagonal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.isRE_plainKNat_le_pair := Kolmogorov.isRE_plainKNat_le_pair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.oraclePrefix := Kolmogorov.oraclePrefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.oraclePrefix_prefix := Kolmogorov.oraclePrefix_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.recursiveIn_charFun_of_isRE := Kolmogorov.recursiveIn_charFun_of_isRE

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.recursiveIn_of_forall_oracle_recursiveIn :=
  Kolmogorov.recursiveIn_of_forall_oracle_recursiveIn

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.solvesDiagonal_of_fixedPointFree :=
  Kolmogorov.solvesDiagonal_of_fixedPointFree

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.solvesDiagonal_of_solvesHighComplexity :=
  Kolmogorov.solvesDiagonal_of_solvesHighComplexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.solvesHighComplexity_of_solvesDiagonal :=
  Kolmogorov.solvesHighComplexity_of_solvesDiagonal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch01.solvesHighComplexity_recursiveIn_halting :=
  Kolmogorov.solvesHighComplexity_recursiveIn_halting

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log_add_one_le := Kolmogorov.log_succ_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.log_succ_le := Kolmogorov.log_succ_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch02.nat_log_succ_le := Kolmogorov.log_succ_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsDecidableSet := Kolmogorov.IsDecidableSet

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsDecompressorIn := Kolmogorov.IsDecompressorIn

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsEnumerableFamily := Kolmogorov.IsEnumerableFamily

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsEnumerableSet := Kolmogorov.IsEnumerableSet

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsOptimalConditionalIn := Kolmogorov.IsOptimalConditionalIn

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsPostSimple := Kolmogorov.IsPostSimple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsRSeparable := Kolmogorov.IsRSeparable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsUpperSemicomputable := Kolmogorov.IsUpperSemicomputable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.IsUpperSemicomputable₂ := Kolmogorov.IsUpperSemicomputable₂

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.cVal := Kolmogorov.cVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.charOracle := Kolmogorov.charOracle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.condCVal := Kolmogorov.condCVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.haltingOracle := Kolmogorov.haltingOracle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.haltingSemicharacteristic := Kolmogorov.haltingSemicharacteristic

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.mapToNatFun := Kolmogorov.mapToNatFun

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.natToBits := Kolmogorov.natBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.totalOracle := Kolmogorov.totalOracle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.bitsGValid := Kolmogorov.bitsG_valid

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.decodeBitsComputable := Kolmogorov.decodeBits_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.exactLengthPrograms_card := Kolmogorov.length_exactLengthPrograms

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.le_foldr_max_mem := Kolmogorov.le_foldr_max_of_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.length_natBits_le_self := Kolmogorov.length_natBits_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.listSum_range_eq_sum := Kolmogorov.sum_list_range_eq_finset_sum'

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.log_add_one_le := Kolmogorov.log_succ_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.natBitsComputable := Kolmogorov.natBits_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.natBitsInjective := Kolmogorov.natBits_injective

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.nat_log_succ_le := Kolmogorov.log_succ_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrecBitsG := Kolmogorov.primrec_bitsG

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrecDecodeBits := Kolmogorov.primrec_decodeBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrecDecodeStep := Kolmogorov.primrec_decodeStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrecNatBits := Kolmogorov.primrec_natBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrec_list_all := Kolmogorov.list_all_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.primrec_list_any := Kolmogorov.list_any_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.sum_list_range_eq_finset_sum := Kolmogorov.sum_list_range_eq_finset_sum'
