/-
Copyright (c) 2026 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovMathlib.Prefix.BlockingReadMachines
import KolmogorovMathlib.Prefix.Encoding
import KolmogorovMathlib.Prefix.ExtensionTheorem
import KolmogorovMathlib.Prefix.Machine
import KolmogorovMathlib.Prefix.NumericalValues
import KolmogorovMathlib.Prefix.PairComplexity
import KolmogorovMathlib.Prefix.PrefixStableComplexity
import KolmogorovMathlib.Prefix.Properties.Part01
import KolmogorovMathlib.Prefix.SelfDelimitingMachines
import KolmogorovMathlib.Prefix.StableDecompressors
import KolmogorovMathlib.Prefix.TwoStage
import KolmogorovMathlib.Prefix.UpperSemicomputableBound

/-!
# Deprecated aliases: Prefix

Old names of declarations in the `KolmogorovMathlib.Prefix`
material, kept so that code written against an earlier version of the
library still compiles.

Generated by `scripts/gen_deprecated.py` from the public rows of
`docs/history/phase3_renames.tsv`; do not edit by hand.
-/

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.CodedFiniteDistribution.natCode_primrec := Kolmogorov.primrec_natCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.EExtends_streamTake_inr := Kolmogorov.EExtends_streamTake

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.BlockingComputes := Kolmogorov.BlockingComputes

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.EExtends := Kolmogorov.EExtends

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.EExtends_refl := Kolmogorov.EExtends_refl

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.EExtends_streamTake := Kolmogorov.EExtends_streamTake

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.EExtends_streamTake_inr := Kolmogorov.EExtends_streamTake

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.EExtends_trans := Kolmogorov.EExtends_trans

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageCheck :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageCheck_computable :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageCheck_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageMap :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageMap_partrec :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageMap_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageMap_produces :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageMap_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageOut :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageOut

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageOut_computable :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageOut_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageS1 :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageS1

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageS1_computable :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageS1_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageS2 :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageS2

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.Exercise110.plainPrefixTwoStageS2_computable :=
  Kolmogorov.PlainPrefixTwoStage.plainPrefixTwoStageS2_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.F_of_A := Kolmogorov.F_of_A

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.F_of_A_eq_some := Kolmogorov.F_of_A_eq_some

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.F_of_A_inl_eq_some := Kolmogorov.F_of_A_inl_eq_some

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.F_of_A_inr_eq_some := Kolmogorov.F_of_A_inr_eq_some

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsArrivalSchedule := Kolmogorov.IsArrivalSchedule

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsCompatibleGraph := Kolmogorov.IsCompatibleGraph

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsOptimalPrefixStable := Kolmogorov.IsOptimalPrefixStable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsPrefixFreeFun := Kolmogorov.IsPrefixFreeFun

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsPrefixStableDecompressor := Kolmogorov.IsPrefixStableDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsPrefixStableFun := Kolmogorov.IsPrefixStableFun

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsPrefixStableMachine := Kolmogorov.IsPrefixStableMachine

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsRobustProgram := Kolmogorov.IsRobustProgram

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.IsRobustProgram_eq_of_eval_eq := Kolmogorov.IsRobustProgram_eq_of_eval_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.KPTriple := Kolmogorov.KPTriple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.KP_le_of_plainK_le_sub := Kolmogorov.KP_le_of_plainK_le_sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.KP_pair_bound_le := Kolmogorov.KP_pair_bound_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBAction := Kolmogorov.NBAction

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBAction.equivSum := Kolmogorov.NBAction.equivSum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBComputes := Kolmogorov.NBComputes

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBOutputs := Kolmogorov.NBOutputs

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBOutputs_eq_of_eval_eq := Kolmogorov.NBOutputs_eq_of_eval_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBStep := Kolmogorov.NBStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.NBStep_eq_of_eval_eq := Kolmogorov.NBStep_eq_of_eval_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.SeqE := Kolmogorov.SeqE

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actMap := Kolmogorov.actMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actMap_partrec := Kolmogorov.actMap_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearchOut := Kolmogorov.actSearchOut

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearchOut_computable := Kolmogorov.actSearchOut_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearch_cond_computable := Kolmogorov.actSearch_cond_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearch_evaln_computable := Kolmogorov.actSearch_evaln_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearch_if_computable := Kolmogorov.actSearch_if_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearch_map_computable := Kolmogorov.actSearch_map_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearch_map_out_computable := Kolmogorov.actSearch_map_out_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.actSearch_then_computable := Kolmogorov.actSearch_then_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.average_KP_eq_length_add_KP := Kolmogorov.average_KP_eq_length_add_KP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.bits_len_le_log2_add_two := Kolmogorov.bits_len_le_log2_add_two

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.bitstring_eq_decide_computable :=
  Kolmogorov.bitstring_eq_decide_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.blockingRead_iff_computable_prefixFree :=
  Kolmogorov.blockingRead_iff_computable_prefixFree

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.bool_or_decide := Kolmogorov.bool_or_decide

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.bool_or_not_eq_decide_imp := Kolmogorov.bool_or_not_eq_decide_imp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.cNatVal := Kolmogorov.cNatVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.checkAll := Kolmogorov.checkAll

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.checkAll_partrec := Kolmogorov.checkAll_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.checkStep := Kolmogorov.checkStep

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.checkStepOut := Kolmogorov.checkStepOut

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.checkStepOut_computable := Kolmogorov.checkStepOut_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.checkStep_partrec := Kolmogorov.checkStep_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.complexityWeight_KPPlain := Kolmogorov.complexityWeight_KPPlain

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.condKP_le_program_KP := Kolmogorov.condKP_le_program_KP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.condKP_self_plainK_eq := Kolmogorov.condKP_self_plainK_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.condKP_triangle := Kolmogorov.condKP_triangle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.condK_prefixExtensionMap_le_condK_V :=
  Kolmogorov.condK_prefixExtensionMap_le_condK_V

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.condK_stabMap_le := Kolmogorov.condK_stabMap_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.contGraph := Kolmogorov.contGraph

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.continuous_natBotTopology_iff := Kolmogorov.continuous_natBotTopology_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.cylinder := Kolmogorov.sequenceCylinder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.cylinder_mem := Kolmogorov.cylinder_mem

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.decode_bitstring_computable := Kolmogorov.decode_bitstring_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.deconstructConcatPair := Kolmogorov.deconstructConcatPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.deconstructConcatPair_computable :=
  Kolmogorov.deconstructConcatPair_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.deconstructConcatPair_eval := Kolmogorov.deconstructConcatPair_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.eTopology := Kolmogorov.eTopology

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.eTopology_isBasis := Kolmogorov.eTopology_isBasis

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.ennreal_sum_lower_bound := Kolmogorov.ennreal_sum_lower_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.evalProgDecompressor := Kolmogorov.evalProgDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.evalProgDecompressor_isDecompressor :=
  Kolmogorov.evalProgDecompressor_isDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.evalProgDecompressor_isPrefixDecompressor :=
  Kolmogorov.evalProgDecompressor_isPrefixDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.evalProgDecompressor_isPrefixMachine :=
  Kolmogorov.evalProgDecompressor_isPrefixMachine

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.evalProgDecompressor_produces := Kolmogorov.evalProgDecompressor_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise105_pair_with_bound := Kolmogorov.KP_pair_bound_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise106_average_prefix_complexity :=
  Kolmogorov.average_KP_eq_length_add_KP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise107_plain_pair_prefix_bound :=
  Kolmogorov.plainK_pair_le_KP_add_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise108_high_prefix_complexity := Kolmogorov.KP_le_of_plainK_le_sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise109_converse_false := Kolmogorov.not_program_KP_le_condKP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise109_le_program_complexity := Kolmogorov.condKP_le_program_KP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise110_plain_pair_cond_bound :=
  Kolmogorov.plainK_pair_le_KP_add_condK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise111_triangle := Kolmogorov.condKP_triangle

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise114_f_A := Kolmogorov.tripleCodeOfNestedPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise114_f_B := Kolmogorov.tripleCodeOfSwappedPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise114_triple_inequality := Kolmogorov.two_mul_KP_triple_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise115_pair_increase := Kolmogorov.exists_extension_KP_pair_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise116_extension_weak := Kolmogorov.exists_extension_KP_ge_sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise97_robustness_undecidable := Kolmogorov.robustness_undecidable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise98_minimalRestrict_not_computable :=
  Kolmogorov.exists_prefixStable_minimalRestrict_not_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exercise99_no_log_bound := Kolmogorov.not_KP_le_length_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_extension_KP_ge := Kolmogorov.exists_extension_KP_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_extension_KP_ge_sub := Kolmogorov.exists_extension_KP_ge_sub

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_extension_KP_pair_ge := Kolmogorov.exists_extension_KP_pair_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_le_card_mul_le_sum := Kolmogorov.exists_le_card_mul_le_sum

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_non_robust_program := Kolmogorov.exists_non_robust_program

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_optimal_prefixStable_decompressor :=
  Kolmogorov.exists_optimal_prefixStable_decompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_prefixStable_minimalRestrict_not_computable :=
  Kolmogorov.exists_prefixStable_minimalRestrict_not_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_robust_program := Kolmogorov.exists_robust_program

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.exists_stabTriple_of_produces := Kolmogorov.exists_stabTriple_of_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.extDropMap := Kolmogorov.extDropMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.extDropMap_aprioriMeasure_ge := Kolmogorov.extDropMap_aprioriMeasure_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.extDropMap_isPrefixDecompressor :=
  Kolmogorov.extDropMap_isPrefixDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.extDropMap_opt_computable := Kolmogorov.extDropMap_opt_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.fFromAct := Kolmogorov.fFromAct

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.fFromAct_partrec := Kolmogorov.fFromAct_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.finset_sum_tsum_comm := Kolmogorov.finset_sum_tsum_comm

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.foldr_and_eq_true := Kolmogorov.foldr_and_eq_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.isOpen_eTopology_extends := Kolmogorov.isOpen_eTopology_extends

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.isOpen_eTopology_stream := Kolmogorov.isOpen_eTopology_stream

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.isOpen_iUnion_of_isOpen := Kolmogorov.isOpen_iUnion_of_isOpen

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.kCondVal := Kolmogorov.kCondVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.kNat := Kolmogorov.kNat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.kNatVal := Kolmogorov.kNatVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.kNatVal_hasPrefixComplexityValue :=
  Kolmogorov.kNatVal_hasPrefixComplexityValue

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.kVal := Kolmogorov.kVal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.log2_add_two_add_le := Kolmogorov.log2_add_two_add_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.log2_lt_of_lt_pow := Kolmogorov.log2_lt_of_lt_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.mem_checkAll_iff := Kolmogorov.mem_checkAll_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.mem_fFromAct_iff := Kolmogorov.mem_fFromAct_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.minimalRestrict := Kolmogorov.minimalRestrict

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natBotLe := Kolmogorov.natBotLe

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natBotTopology := Kolmogorov.natBotTopology

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natDiffDecompressor := Kolmogorov.natDiffDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natDiffDecompressorOpt := Kolmogorov.natDiffDecompressorOpt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natDiffDecompressor_computable :=
  Kolmogorov.natDiffDecompressor_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natDiffDecompressor_isPrefixDecompressor :=
  Kolmogorov.natDiffDecompressor_isPrefixDecompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natDiffDecompressor_isPrefixMachine :=
  Kolmogorov.natDiffDecompressor_isPrefixMachine

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natDiffDecompressor_produces := Kolmogorov.natDiffDecompressor_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.natToBits_inj := Kolmogorov.natToBits_inj

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.nbAct := Kolmogorov.nbAct

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.nbAct_eq_of_eval_eq := Kolmogorov.nbAct_eq_of_eval_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.not_KP_le_length_add_log := Kolmogorov.not_KP_le_length_add_log

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.not_program_KP_le_condKP := Kolmogorov.not_program_KP_le_condKP

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.ofReal_half := Kolmogorov.ofReal_half

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.ofReal_two := Kolmogorov.ofReal_two

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.or_not_or_not_iff_imp_imp := Kolmogorov.or_not_or_not_iff_imp_imp

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.plainK_eq_of_condKP_eq_add := Kolmogorov.plainK_eq_of_condKP_eq_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.plainK_pair_le_KP_add_condK := Kolmogorov.plainK_pair_le_KP_add_condK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.plainK_pair_le_KP_add_plainK := Kolmogorov.plainK_pair_le_KP_add_plainK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionCheck := Kolmogorov.prefixExtensionCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionCheck_computable :=
  Kolmogorov.prefixExtensionCheck_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionMap := Kolmogorov.prefixExtensionMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionMap_isPrefixStableMachine :=
  Kolmogorov.prefixExtensionMap_isPrefixStableMachine

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionMap_mem_imp_produces :=
  Kolmogorov.prefixExtensionMap_mem_imp_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionMap_partrec := Kolmogorov.prefixExtensionMap_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionOut := Kolmogorov.prefixExtensionOut

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixExtensionOut_computable := Kolmogorov.prefixExtensionOut_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixProgramComplexity := Kolmogorov.prefixProgramComplexity

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixStable_prefixFree_complexity_eq :=
  Kolmogorov.prefixStable_prefixFree_complexity_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixTopology_continuous_iff := Kolmogorov.prefixTopology_continuous_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefixTopology_isOpen_iff := Kolmogorov.prefixTopology_isOpen_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.prefix_length_lt := Kolmogorov.prefix_length_lt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.primrec_decide_of_pred := Kolmogorov.primrec_decide_of_pred

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.real_sum_lower_bound := Kolmogorov.real_sum_lower_bound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.robustness_undecidable := Kolmogorov.robustness_undecidable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.runCheck := Kolmogorov.runCheck

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.runCheck_iff := Kolmogorov.runCheck_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabCompat := Kolmogorov.stabCompat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabCompat_iff := Kolmogorov.stabCompat_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabCompat_primrec := Kolmogorov.stabCompat_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabFind := Kolmogorov.stabFind

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabFind_eq_some_iff := Kolmogorov.stabFind_eq_some_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabFind_primrec := Kolmogorov.stabFind_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabFind_unique := Kolmogorov.stabFind_unique

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabMap := Kolmogorov.stabMap

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabMap_isPrefixStableMachine := Kolmogorov.stabMap_isPrefixStableMachine

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabMap_mem_imp_find := Kolmogorov.stabMap_mem_imp_find

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabMap_mem_of_find := Kolmogorov.stabMap_mem_of_find

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabMap_partrec_uniform := Kolmogorov.stabMap_partrec_uniform

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabOK := Kolmogorov.stabOK

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabOK_eq_true_iff := Kolmogorov.stabOK_eq_true_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabOK_of_prefixStable := Kolmogorov.stabOK_of_prefixStable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabOK_primrec := Kolmogorov.stabOK_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabPairCompat := Kolmogorov.stabPairCompat

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabPairCompat_eq_true := Kolmogorov.stabPairCompat_eq_true

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabPairCompat_of := Kolmogorov.stabPairCompat_of

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabPairCompat_primrec := Kolmogorov.stabPairCompat_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabSelect := Kolmogorov.stabSelect

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabSelect_eq_some_iff := Kolmogorov.stabSelect_eq_some_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabSelect_primrec := Kolmogorov.stabSelect_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabTriple := Kolmogorov.stabTriple

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabTriple_complete := Kolmogorov.stabTriple_complete

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabTriple_primrec := Kolmogorov.stabTriple_primrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabTriple_produces := Kolmogorov.stabTriple_produces

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabTriple_sound := Kolmogorov.stabTriple_sound

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabUniversal := Kolmogorov.stabUniversal

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabUniversal_apply := Kolmogorov.stabUniversal_apply

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabUniversal_isPrefixStableMachine :=
  Kolmogorov.stabUniversal_isPrefixStableMachine

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.stabUniversal_partrec := Kolmogorov.stabUniversal_partrec

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.streamTake := Kolmogorov.streamTake

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.streamTake_length := Kolmogorov.streamTake_length

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.streamTake_prefix_of_streamTake :=
  Kolmogorov.streamTake_prefix_of_streamTake

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.subPairBits := Kolmogorov.subPairBits

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.subPairBits_computable := Kolmogorov.subPairBits_computable

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.subPairBits_eval := Kolmogorov.subPairBits_eval

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.sum_s_real_eq := Kolmogorov.sum_s_real_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.takeWhile_eq_of_prefix := Kolmogorov.takeWhile_eq_of_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem48_exists_optimal_prefixStable :=
  Kolmogorov.exists_optimal_prefixStable_decompressor

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem50_prefixFree_iff_blockingRead :=
  Kolmogorov.blockingRead_iff_computable_prefixFree

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem52_isOpen_iff := Kolmogorov.prefixTopology_isOpen_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem53_continuous_iff := Kolmogorov.prefixTopology_continuous_iff

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem55_prefixStable_le_prefixFree :=
  Kolmogorov.prefixStable_prefixFree_complexity_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem71_extension_max := Kolmogorov.exists_extension_KP_ge

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72DiffDecoder := Kolmogorov.diffDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72DiffPair := Kolmogorov.diffDecoderPair

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72KPShiftDecoder := Kolmogorov.kpShiftDecoder

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72ShiftCode := Kolmogorov.shiftCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72ShiftCond := Kolmogorov.shiftCond

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72_fixed_point := Kolmogorov.condKP_self_plainK_eq

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.theorem72_stability := Kolmogorov.plainK_eq_of_condKP_eq_add

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.two_mul_KP_triple_le := Kolmogorov.two_mul_KP_triple_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.two_mul_le_two_pow := Kolmogorov.two_mul_le_two_pow

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.SUV.Ch04.two_mul_log2_le := Kolmogorov.two_mul_log2_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.lscPrimrec₂_listTake := Kolmogorov.primrec_list_take

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.mem_domainAt_of_produces := Kolmogorov.produces_mem_domainAt

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.natCode_primrec := Kolmogorov.primrec_natCode

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.plainK_le_KPPlain := Kolmogorov.plain_le_prefix

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.prefix_conditioning_le_plain := Kolmogorov.KP_le_KPPlain

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.prefix_plain_map_le := Kolmogorov.KPPlain_map_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.prefix_self_le_const := Kolmogorov.KP_self_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.streamTag_natCode_append := Kolmogorov.natCode_append_inj

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_62_tsum_ne_top_of_upperBound :=
  Kolmogorov.tsum_two_pow_neg_ne_top_of_KPPlain_le

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_62_upperBound_iff_tsum_ne_top_of_encoding :=
  Kolmogorov.KPPlain_le_iff_tsum_two_pow_neg_ne_top

@[deprecated (since := "2026-09-08")]
alias Kolmogorov.theorem_62_upperBound_of_tsum_ne_top :=
  Kolmogorov.KPPlain_le_of_tsum_two_pow_neg_ne_top
