import Mathlib.Data.List.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.List
import KolmogorovMathlib.Core.Basic

/-!
# Incompressibility and the Pigeonhole Principle

This module proves the fundamental counting argument of Algorithmic Information Theory:
Incompressibility. Because there are exactly `2^n` strings of length `n`, but only
`2^n - 1` programs of length strictly less than `n`, at least one string of length `n`
must be incompressible (its complexity is at least `n`).

This simple combinatorial fact is the engine behind Chaitin's Incompleteness Theorem.
-/

namespace Kolmogorov

-- ==========================================================
-- 1. Combinatorics of Programs
-- ==========================================================

/-- Generate a list of all bit strings of length ≤ k. -/
def programsLe : ℕ → List BitString
| 0 => [[]]
| k + 1 => [] :: ((programsLe k).map (false :: ·) ++ (programsLe k).map (true :: ·))

@[simp]
lemma length_programsLe_add_one (k : ℕ) : (programsLe k).length + 1 = 2^(k + 1) := by
  induction k with
  | zero => rfl
  | succ k ih =>
    simp only [programsLe, List.length_cons, List.length_append, List.length_map]
    have h_arith : (programsLe k).length + (programsLe k).length + 1 + 1 =
        ((programsLe k).length + 1) * 2 := by omega
    rw [h_arith, ih]
    rfl

/-- The map is deterministic. -/
lemma produces_unique {D : Map} {p y x1 x2 : BitString}
    (h1 : x1 ∈ D (p, y)) (h2 : x2 ∈ D (p, y)) : x1 = x2 :=
  Part.mem_unique h1 h2

open Classical in
/-- Mathematical (noncomputable) function that evaluates a program. -/
noncomputable def progToOut (D : Map) (y : BitString) (p : BitString) : Option BitString :=
  if h : ∃ x, x ∈ D (p, y) then some (choose h) else none

open Classical in
@[simp]
lemma progToOut_eq_some {D : Map} {y p x : BitString} :
    progToOut D y p = some x ↔ x ∈ D (p, y) := by
  unfold progToOut
  split_ifs with h
  · constructor
    · intro h_some; injection h_some with h_eq; rw [← h_eq]; exact choose_spec h
    · intro h_prod; have h_choose := choose_spec h
      rw [produces_unique h_choose h_prod]
  · constructor
    · intro h_some; contradiction
    · intro h_prod; exact False.elim (h ⟨x, h_prod⟩)

open Classical in
/-- The set of all words generated by programs of length ≤ k. -/
noncomputable def generatedWords (D : Map) (y : BitString) (k : ℕ) : Finset BitString :=
  ((programsLe k).filterMap (progToOut D y)).toFinset

lemma toFinset_filterMap_card_le {α β : Type} [DecidableEq β] (l : List α) (f : α → Option β) :
    (l.filterMap f).toFinset.card ≤ l.length := by
  induction l with
  | nil => rfl
  | cons a as ih =>
    rw [List.length_cons, List.filterMap_cons]
    cases f a with
    | none => simp only []; omega
    | some b =>
      simp only []
      rw [List.toFinset_cons]
      have h_ins := Finset.card_insert_le b (List.filterMap f as).toFinset
      omega

lemma card_generatedWords_le (D : Map) (y : BitString) (k : ℕ) :
    (generatedWords D y k).card ≤ (programsLe k).length :=
  toFinset_filterMap_card_le (programsLe k) (progToOut D y)

lemma mem_programsLe (k : ℕ) (p : BitString) (h : p.length ≤ k) : p ∈ programsLe k := by
  induction k generalizing p with
  | zero =>
    cases p with
    | nil => exact List.Mem.head []
    | cons _ _ => simp only [List.length_cons] at h; omega
  | succ k ih =>
    cases p with
    | nil => exact List.Mem.head _
    | cons hd tl =>
      have h_tl_len : tl.length ≤ k := by simp only [List.length_cons] at h; omega
      have h_tl_mem := ih tl h_tl_len
      simp only [programsLe, List.mem_cons, List.mem_append, List.mem_map]
      cases hd
      · right; left; exact ⟨tl, h_tl_mem, rfl⟩
      · right; right; exact ⟨tl, h_tl_mem, rfl⟩

open Classical in
/-- The set of compressible words (words with complexity ≤ k). -/
noncomputable def compressibleWords (D : Map) (y : BitString) (k : ℕ) : Finset BitString :=
  (generatedWords D y k).filter (fun x => condK D x y ≤ (k : ENat))

/-- The fundamental bound: The number of compressible words is strictly less than 2^(k+1). -/
theorem card_compressibleWords_lt (D : Map) (y : BitString) (k : ℕ) :
    (compressibleWords D y k).card < 2^(k + 1) := by
  calc
    (compressibleWords D y k).card
      ≤ (generatedWords D y k).card := Finset.filter_subset _ _ |> Finset.card_le_card
    _ ≤ (programsLe k).length       := card_generatedWords_le D y k
    _ < (programsLe k).length + 1   := by omega
    _ = 2^(k + 1)                   := length_programsLe_add_one k

-- ==========================================================
-- 2. Strings of Exact Length
-- ==========================================================

/-- Inductive construction of all bit strings of length exactly n. -/
def allStrings : ℕ → List BitString
| 0 => [[]]
| n + 1 => (allStrings n).map (false :: ·) ++ (allStrings n).map (true :: ·)

@[simp]
lemma length_allStrings (n : ℕ) : (allStrings n).length = 2^n := by
  induction n with
  | zero => rfl
  | succ n ih => unfold allStrings; simp [ih]; omega

@[simp]
lemma mem_allStrings (n : ℕ) (s : BitString) : s ∈ allStrings n ↔ s.length = n := by
  induction n generalizing s with
  | zero => cases s <;> simp [allStrings]
  | succ n ih =>
    cases s with
    | nil => simp [allStrings]
    | cons b bs =>
      unfold allStrings
      simp [ih]
      cases b <;> simp

/-- The Finset of all bit strings of length n. -/
def stringsOfLength (n : ℕ) : Finset BitString :=
  (allStrings n).toFinset

lemma allStrings_nodup (n : ℕ) : (allStrings n).Nodup := by
  induction n with
  | zero => simp [allStrings]
  | succ n ih =>
    unfold allStrings
    apply List.nodup_append.mpr
    constructor
    · apply List.Nodup.map _ ih; intro x y h; injection h
    constructor
    · apply List.Nodup.map _ ih; intro x y h; injection h
    · intro x hx y hy h_eq
      rw [List.mem_map] at hx; obtain ⟨a, _, rfl⟩ := hx
      rw [List.mem_map] at hy; obtain ⟨b, _, rfl⟩ := hy
      injection h_eq; contradiction

/-- The cardinality of the set of strings of length n is exactly 2^n. -/
lemma card_stringsOfLength (n : ℕ) : (stringsOfLength n).card = 2^n := by
  dsimp [stringsOfLength]
  rw [List.toFinset_card_of_nodup (allStrings_nodup n), length_allStrings]

lemma mem_stringsOfLength (n : ℕ) (s : BitString) :
    s ∈ stringsOfLength n ↔ s.length = n := by
  simp [stringsOfLength]

-- ==========================================================
-- 3. Incompressibility Theorem (Pigeonhole Principle)
-- ==========================================================

/-- For any map and length n, there exists at least one incompressible string. -/
theorem exists_incompressible_string (D : Map) (y : BitString) (n : ℕ) :
    ∃ s : BitString, s.length = n ∧ (n : ENat) ≤ condK D s y := by
  by_contra h_none
  push_neg at h_none
  cases n with
  | zero =>
    have h_lt := h_none [] rfl
    have h_contra := lt_of_le_of_lt (zero_le (condK D [] y)) h_lt
    exact lt_irrefl 0 h_contra
  | succ n' =>
    have h_subset : stringsOfLength (n' + 1) ⊆ compressibleWords D y n' := by
      intro s hs
      rw [mem_stringsOfLength] at hs
      rw [compressibleWords, Finset.mem_filter]
      have h_K_lt := h_none s hs
      -- If complexity is < n'+1, there must be a program generating it
      obtain ⟨len_enat, h_mem, h_val_lt⟩ := (sInf_lt_iff).mp h_K_lt
      obtain ⟨p, hp_prod, rfl⟩ := h_mem
      have h_len_le : programLength p ≤ n' := by
        have : (programLength p : ENat) < (n' + 1 : ENat) := h_val_lt
        exact ENat.coe_lt_coe.mp this |> Nat.lt_succ_iff.mp
      constructor
      · rw [generatedWords, List.mem_toFinset, List.mem_filterMap]
        exact ⟨p, mem_programsLe _ p h_len_le, progToOut_eq_some.mpr hp_prod⟩
      · exact le_trans (sInf_le ⟨p, hp_prod, rfl⟩) (ENat.coe_le_coe.mpr h_len_le)
    have h_card_le := Finset.card_le_card h_subset
    rw [card_stringsOfLength (n' + 1)] at h_card_le
    have h_card_limit := card_compressibleWords_lt D y n'
    exact absurd h_card_le (not_le_of_gt h_card_limit)

open Classical in
/-- The Fundamental Theorem: For any complexity threshold L,
    there exists a string whose plain Kolmogorov complexity is strictly greater than L. -/
theorem exists_complex_string (U : Map) (L : ℕ) :
    ∃ s : BitString, plainK U s > (L : ENat) := by
  let n := L + 1
  obtain ⟨s, _, h_complex⟩ := exists_incompressible_string U [] n
  use s
  have h_lt : (L : ENat) < (n : ENat) := by exact ENat.coe_lt_coe.mpr (Nat.lt_succ_self L)
  exact lt_of_lt_of_le h_lt h_complex

open Classical in
/-- Generalized Pigeonhole Principle: For any injective sequence of strings,
    there exists an index n where the string f(n) has complexity strictly greater than L. -/
theorem exists_complex_injective {f : ℕ → BitString} (hf : Function.Injective f) (U : Map) (L : ℕ) :
    ∃ n : ℕ, plainK U (f n) > (L : ENat) := by
  by_contra h_contra
  push_neg at h_contra
  -- S is the finite set of all strings whose complexity is ≤ L
  let S := compressibleWords U [] L
  have h_mem : ∀ n, f n ∈ S := by
    intro n
    -- Unfold S and compressibleWords to expose the Finset.filter
    dsimp only [S]
    rw [compressibleWords, Finset.mem_filter]
    -- We need to prove two things: (1) f n is generated, (2) its complexity is ≤ L
    constructor
    · -- Part 1: Prove it's in generatedWords
      have h_K_le := h_contra n
      -- Since the complexity is <= L, it must be < L + 1
      have h_K_lt : condK U (f n) [] < (L + 1 : ENat) :=
        lt_of_le_of_lt h_K_le (ENat.coe_lt_coe.mpr (Nat.lt_succ_self L))
      -- Extract the actual program using sInf_lt_iff
      obtain ⟨len_enat, h_mem_len, h_val_lt⟩ := (sInf_lt_iff).mp h_K_lt
      obtain ⟨p, hp_prod, rfl⟩ := h_mem_len
      -- Convert ENat bound back to Nat bound
      have h_len_le : programLength p ≤ L := by
        have : (programLength p : ENat) < (L + 1 : ENat) := h_val_lt
        exact ENat.coe_lt_coe.mp this |> Nat.lt_succ_iff.mp
      -- Prove membership in generatedWords
      rw [generatedWords, List.mem_toFinset, List.mem_filterMap]
      exact ⟨p, mem_programsLe L p h_len_le, progToOut_eq_some.mpr hp_prod⟩
    · -- Part 2: Prove its complexity is ≤ L
      exact h_contra n
  -- Let N be the size of the set of compressible words
  let N := S.card
  -- Create a set of the first N + 1 natural numbers: {0, 1, ..., N}
  let domain := Finset.range (N + 1)
  -- Map these N + 1 numbers to strings using f
  let mapped := domain.image f
  -- Because f is injective, the number of mapped strings is also N + 1
  have h_mapped_card : mapped.card = N + 1 := by
    rw [Finset.card_image_of_injective domain hf]
    exact Finset.card_range (N + 1)
  -- By our assumption (h_mem), all these mapped strings are in S
  have h_subset : mapped ⊆ S := by
    intro x hx
    rw [Finset.mem_image] at hx
    obtain ⟨n, _, rfl⟩ := hx
    exact h_mem n
  -- Therefore, the size of 'mapped' cannot exceed the size of S
  have h_le : mapped.card ≤ N := Finset.card_le_card h_subset
  -- Substitute mapped.card with N + 1 to get N + 1 ≤ N
  rw [h_mapped_card] at h_le
  -- This is a clear arithmetical contradiction
  omega

end Kolmogorov
