#!/usr/bin/env python3
"""Axiom sweep gate.

Every public `theorem` of the `KolmogorovMathlib` and
`KolmogorovCounterexamples` libraries must depend only on
the three standard Lean axioms `propext`, `Classical.choice` and `Quot.sound`.

The sweep works the way `#print axioms` does, but in one pass: it generates a
scratch Lean module that imports every maximal build root of the library (so
that every module of the library is in the environment), enumerates the
theorems that were *declared in* a `KolmogorovMathlib.*` module, and walks the
constants each proof term mentions.  Any axiom outside the allowed list is
reported together with the first theorem that reaches it, and the script exits
non-zero.

A single shared `seen` set makes the walk linear in the size of the reachable
environment, which is what makes it usable as a build gate; running one
`#print axioms` command per theorem would re-traverse the same subgraphs tens
of thousands of times.

Usage:  python3 scripts/axiom_sweep.py [--keep] [--out FILE]
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LEAN_TEMPLATE = r"""
/- Generated by `scripts/axiom_sweep.py`; do not edit. -/
{imports}

open Lean

namespace KolmogorovAxiomSweep

/-- The axioms a proof in this library is allowed to depend on. -/
def allowedAxioms : List Name := [`propext, `Classical.choice, `Quot.sound]

/-- Is `n` declared in a module of this library? -/
def inLibrary (env : Environment) (n : Name) : Bool :=
  match env.getModuleIdxFor? n with
  | none => false
  | some idx =>
    match env.header.moduleNames[idx.toNat]? with
    | none => false
    | some m =>
      `KolmogorovMathlib == m || (`KolmogorovMathlib).isPrefixOf m
        || `KolmogorovCounterexamples == m
        || (`KolmogorovCounterexamples).isPrefixOf m

/-- Constants mentioned by the type and (if present) the value of `ci`. -/
def usedConstants (ci : ConstantInfo) : Array Name :=
  let fromType := ci.type.getUsedConstants
  match ci.value? with
  | none => fromType
  | some v => fromType ++ v.getUsedConstants

/-- Walk everything reachable from `start`, recording the axioms met.
`seen` is shared across calls, so the whole sweep is one traversal. -/
def reachableAxioms (env : Environment) (seen : NameSet) (start : Name) :
    NameSet × Array Name := Id.run do
  let mut seen := seen
  let mut found : Array Name := #[]
  let mut stack : Array Name := #[start]
  while h : stack.size > 0 do
    let n := stack[stack.size - 1]
    stack := stack.pop
    if seen.contains n then
      continue
    seen := seen.insert n
    match env.find? n with
    | none => pure ()
    | some (.axiomInfo ax) =>
      unless allowedAxioms.contains ax.name do
        found := found.push ax.name
    | some ci =>
      for c in usedConstants ci do
        unless seen.contains c do
          stack := stack.push c
  return (seen, found)

run_cmd do
  let env ← Lean.getEnv
  let mut seen : NameSet := {}
  let mut checked : Nat := 0
  let mut violations : Array (Name × Array Name) := #[]
  for (n, ci) in env.constants.toList do
    if (match ci with | .thmInfo _ => true | _ => false) && inLibrary env n
        && !(Lean.isPrivateName n) && !n.isInternal then
      checked := checked + 1
      let (seen', found) := reachableAxioms env seen n
      seen := seen'
      if !found.isEmpty then
        violations := violations.push (n, found)
  Lean.logInfo m!"axiom sweep: {checked} public theorems checked"
  if violations.isEmpty then
    Lean.logInfo m!"axiom sweep: OK (only propext, Classical.choice, Quot.sound)"
  else
    for (n, axs) in violations do
      Lean.logError m!"{n} depends on disallowed axiom(s) {axs}"

end KolmogorovAxiomSweep
"""


def discover_roots() -> list[str]:
    """Maximal build roots: library modules that no other module imports."""
    out = subprocess.run(
        [sys.executable, "-B", "scripts/check_affected.py",
         "--print-project-build-roots"],
        cwd=REPO, capture_output=True, text=True)
    if out.returncode == 0 and out.stdout.strip():
        return out.stdout.split() + ["KolmogorovCounterexamples"]
    raise SystemExit("axiom sweep: could not discover project build roots")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep", action="store_true",
                    help="keep the generated Lean file")
    ap.add_argument("--out", default=None,
                    help="write the generated Lean file here")
    args = ap.parse_args()

    roots = discover_roots()
    imports = "\n".join(f"import {r}" for r in roots)
    source = LEAN_TEMPLATE.replace("{imports}", imports)

    if args.out:
        path = os.path.join(REPO, args.out)
        with open(path, "w") as f:
            f.write(source)
    else:
        fd, path = tempfile.mkstemp(suffix=".lean", dir=REPO,
                                    prefix="axiom_sweep_")
        with os.fdopen(fd, "w") as f:
            f.write(source)

    try:
        proc = subprocess.run(["lake", "env", "lean", path], cwd=REPO,
                              capture_output=True, text=True)
        sys.stdout.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        if proc.returncode != 0 or "error" in proc.stdout:
            print("ERROR: axiom sweep failed")
            return 1
        print("AXIOM SWEEP OK")
        return 0
    finally:
        if not args.keep and not args.out:
            os.unlink(path)


if __name__ == "__main__":
    raise SystemExit(main())
