#!/usr/bin/env python3
"""Regenerate `docs/SUV_COVERAGE.md`: book item -> theorem name -> module.

The book items and their status come from `docs/history/suv_items.tsv`
(`item <TAB> status <TAB> declaration[,declaration...]`, the frozen record of
which endpoint of Shen–Uspensky–Vereshchagin each declaration was added for).
Declaration names are resolved through the phase-3 rename table, so an item
recorded under its old book-indexed name is reported under the topic name it
carries now, and the module is read off the tree.

Usage:  python3 scripts/gen_suv_coverage.py [--check]

`--check` regenerates into memory and exits non-zero if the file on disk
differs, which is what CI would run.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ITEMS = REPO / 'docs/history/suv_items.tsv'
RENAMES = REPO / 'docs/history/phase3_renames.tsv'
OUT = REPO / 'docs/SUV_COVERAGE.md'
LIBS = ('KolmogorovMathlib', 'KolmogorovCounterexamples')

DECL_RE = re.compile(
    r'^(?:@\[[^\]]*\]\s+)*'
    r'(?:(?:private|protected|noncomputable|partial|unsafe)\s+)*'
    r'(?:theorem|lemma|def|abbrev|structure|class|instance|inductive)\s+'
    r"([^\s({\[:]+)")


def declaration_modules() -> dict[str, str]:
    """Fully qualified name -> module name, over both libraries."""
    out: dict[str, str] = {}
    for lib in LIBS:
        for path in sorted((REPO / lib).rglob('*.lean')):
            module = '.'.join(path.relative_to(REPO).with_suffix('').parts)
            ns: list[str] = []
            for line in path.read_text().split('\n'):
                if line.startswith('namespace '):
                    ns.append(line.split()[1])
                elif (line.startswith('end ') and ns
                      and line.split()[1] == ns[-1]):
                    ns.pop()
                m = DECL_RE.match(line)
                if m:
                    out.setdefault('.'.join(ns + [m.group(1)]), module)
    return out


def renames() -> dict[str, str]:
    table: dict[str, str] = {}
    if RENAMES.exists():
        for line in RENAMES.read_text().split('\n'):
            parts = line.split('\t')
            if len(parts) >= 2:
                table[parts[0]] = parts[1]
    return table


def render() -> str:
    where = declaration_modules()
    ren = renames()
    rows = []
    # Every declaration cited for a proved, existing or partly archived item
    # must exist in the tree; only a fully archived item may cite a name that
    # survives solely in `docs/ARCHIVED_TARGETS.md`.
    missing: list[tuple[str, str]] = []
    for line in ITEMS.read_text().split('\n'):
        line = line.rstrip()
        if not line or line.startswith('#'):
            continue
        parts = line.split('\t')
        if len(parts) == 2:
            parts.append('')
        item, status, decls = parts[:3]
        cells = []
        modules = []
        for d in decls.split(','):
            d = d.strip()
            if not d:
                continue
            d = ren.get(d, d)
            cells.append(f'`{d}`')
            module = where.get(d)
            if module is None and status != 'archived':
                missing.append((item, d))
            if module and module not in modules:
                modules.append(module)
        rows.append((item, status, ', '.join(cells) or '—',
                     ', '.join(f'`{m}`' for m in modules) or '—'))

    if missing:
        for item, d in missing:
            print(f'{item}: declaration `{d}` not found in the tree',
                  file=sys.stderr)
        raise SystemExit(2)
    proved = sum(1 for r in rows if r[1] == 'proved')
    existing = sum(1 for r in rows if r[1] == 'existing')
    archived = sum(1 for r in rows if r[1] == 'archived')
    partly = sum(1 for r in rows if r[1] == 'partly archived')
    out = [
        '# SUV coverage',
        '',
        'Shen, Uspensky, Vereshchagin, *Kolmogorov Complexity and Algorithmic',
        'Randomness*: which theorem of this library covers which item of the',
        'book, and in which module it lives.',
        '',
        'Generated by `scripts/gen_suv_coverage.py`; do not edit by hand.  The',
        'book items live in `docs/history/suv_items.tsv`, the declaration names',
        'are resolved through `docs/history/phase3_renames.tsv`, and the module',
        'is read off the tree.  `proved` means a declaration was added for the',
        'item, `existing` that the library already had an equivalent, and',
        '`archived` that the item was judged not worth formalising and its',
        'statement is preserved in `docs/ARCHIVED_TARGETS.md`; `partly',
        'archived` that one half of the item is proved (the declarations',
        'listed) and the other half is archived there.',
        '',
        f'{len(rows)} items: {proved} proved, {existing} existing, '
        f'{archived} archived, {partly} partly archived.',
        '',
        '| Book item | Status | Theorem | Module |',
        '| --- | --- | --- | --- |',
    ]
    for item, status, cells, modules in rows:
        out.append(f'| {item} | {status} | {cells} | {modules} |')
    out.append('')
    return '\n'.join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f'{OUT} is out of date; run scripts/gen_suv_coverage.py')
            return 1
        print(f'{OUT} is up to date')
        return 0
    OUT.write_text(text)
    print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
