#!/usr/bin/env python3
"""Generate `KolmogorovMathlib/Deprecated/`: one home for the deprecated aliases.

Every public rename recorded in `docs/history/phase3_renames.tsv` leaves the old
fully qualified name behind as

    @[deprecated (since := "...")]
    alias old_fqn := new_fqn

and all of those aliases live in `KolmogorovMathlib/Deprecated/`, grouped by the
topic directory of the target and split so that no file exceeds about 1,000
lines.  The modules are imported by the root aggregator `KolmogorovMathlib.lean`
and by nothing else, so no ordinary module can accidentally use a deprecated
name.

Usage:  python3 scripts/gen_deprecated.py [--check]

`--check` renders into memory and exits non-zero if the directory on disk
differs (a stale, missing or extra file), which is what `scripts/audit.sh` runs.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RENAMES = REPO / 'docs/history/phase3_renames.tsv'
LIBS = ('KolmogorovMathlib', 'KolmogorovCounterexamples')
SINCE = '2026-09-08'
MAX_LINES = 900

DECL_RE = re.compile(
    r'^(?:@\[[^\]]*\]\s+)*'
    r'(?:(?:private|protected|noncomputable|partial|unsafe)\s+)*'
    r'(?:theorem|lemma|def|abbrev|structure|class|instance|inductive)\s+'
    r"([^\s({\[:]+)")


def outdir(lib: str) -> Path:
    return REPO / lib / 'Deprecated'


def aggregator(lib: str) -> Path:
    return REPO / (lib + '.lean')


def declaration_modules() -> dict[str, str]:
    """Fully qualified name -> module name, over both libraries."""
    out: dict[str, str] = {}
    paths = [p for lib in LIBS for p in sorted((REPO / lib).rglob('*.lean'))]
    for path in paths:
        if 'Deprecated' in path.parts:
            continue
        module = '.'.join(path.relative_to(REPO).with_suffix('').parts)
        ns: list[str] = []
        for line in path.read_text().split('\n'):
            if line.startswith('namespace '):
                ns.append(line.split()[1])
            elif line.startswith('end ') and ns and line.split()[1] == ns[-1]:
                ns.pop()
            m = DECL_RE.match(line)
            if m:
                out.setdefault('.'.join(ns + [m.group(1)]), module)
    return out


def public_rows() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for line in RENAMES.read_text().split('\n'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) >= 4 and parts[3] == 'public':
            rows.append((parts[0], parts[1]))
    return rows


def topic_of(module: str) -> str:
    """`KolmogorovMathlib.Complexity.Chaitin` -> `Complexity`."""
    parts = module.split('.')
    return parts[1] if len(parts) > 2 else parts[-1]


def render() -> dict[str, dict[str, str]]:
    """Library -> (file name inside its `Deprecated/` -> file contents)."""
    where = declaration_modules()
    missing = [new for _, new in public_rows() if new not in where]
    if missing:
        for new in sorted(set(missing)):
            print(f'rename target `{new}` not found in the tree',
                  file=sys.stderr)
        raise SystemExit(2)

    by_topic: dict[tuple[str, str], list[tuple[str, str, str]]] = {}
    for old, new in sorted(set(public_rows())):
        module = where[new]
        by_topic.setdefault((module.split('.')[0], topic_of(module)),
                            []).append((old, new, module))

    files: dict[str, dict[str, str]] = {lib: {} for lib in LIBS}
    for (lib, topic), rows in sorted(by_topic.items()):
        # Three lines per alias plus the header; chunk to stay under the cap.
        per_chunk = max(1, (MAX_LINES - 40) // 3)
        chunks = [rows[i:i + per_chunk] for i in range(0, len(rows), per_chunk)]
        for k, chunk in enumerate(chunks, start=1):
            name = topic if len(chunks) == 1 else f'{topic}{k:02d}'
            imports = sorted({module for _, _, module in chunk})
            body = [f'import {m}' for m in imports]
            body += [
                '',
                '/-!',
                f'# Deprecated aliases: {topic}',
                '',
                f'Old names of declarations in the `{lib}.{topic}`',
                'material, kept so that code written against an earlier '
                'version of the',
                'library still compiles.',
                '',
                'Generated by `scripts/gen_deprecated.py` from the public rows '
                'of',
                '`docs/history/phase3_renames.tsv`; do not edit by hand.',
                '-/',
                '',
            ]
            for old, new, _ in chunk:
                body.append(f'@[deprecated (since := "{SINCE}")]')
                line = f'alias {old} := {new}'
                if len(line) <= 100:
                    body.append(line)
                elif len(f'alias {old} :=') <= 100:
                    body.append(f'alias {old} :=')
                    body.append(f'  {new}')
                else:
                    body.append('alias')
                    body.append(f'  {old} :=')
                    body.append(f'  {new}')
                body.append('')
            files[lib][f'{name}.lean'] = ('\n'.join(body).rstrip('\n') + '\n')
    return files


def root_aggregator(lib: str, files: dict[str, str]) -> str:
    """`<lib>.lean` with exactly these `Deprecated` imports."""
    wanted = [f'import {lib}.Deprecated.{Path(n).stem}' for n in files]
    kept = [line for line in aggregator(lib).read_text().split('\n')
            if not line.startswith(f'import {lib}.Deprecated.')]
    imports = sorted(
        [line for line in kept if line.startswith('import ')] + wanted)
    rest = [line for line in kept if not line.startswith('import ')]
    return '\n'.join(imports + rest)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    per_lib = render()
    if args.check:
        ok = True
        for lib in LIBS:
            files = per_lib[lib]
            if aggregator(lib).read_text() != root_aggregator(lib, files):
                print(f'{aggregator(lib)} does not import exactly the '
                      'generated Deprecated modules; run '
                      'scripts/gen_deprecated.py')
                ok = False
            out = outdir(lib)
            on_disk = {p.name for p in out.glob('*.lean')} \
                if out.exists() else set()
            for extra in sorted(on_disk - set(files)):
                print(f'{out}/{extra} is not generated by the rename table')
                ok = False
            for name, text in sorted(files.items()):
                path = out / name
                if not path.exists() or path.read_text() != text:
                    print(f'{path} is out of date; '
                          'run scripts/gen_deprecated.py')
                    ok = False
        if not ok:
            return 1
        print('the Deprecated modules are up to date '
              f'({sum(len(f) for f in per_lib.values())} modules)')
        return 0
    for lib in LIBS:
        files = per_lib[lib]
        out = outdir(lib)
        if files:
            out.mkdir(parents=True, exist_ok=True)
        if out.exists():
            for stale in out.glob('*.lean'):
                if stale.name not in files:
                    stale.unlink()
        for name, text in sorted(files.items()):
            (out / name).write_text(text)
        aggregator(lib).write_text(root_aggregator(lib, files))
        print(f'wrote {len(files)} modules into {out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
