/-
Copyright (c) 2024 Alexey Milovanov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexey Milovanov
-/
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.TotalComplexity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.TotalMaps
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProgramList
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.TotalProgramGraph
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.TotalGraphConservation
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.CanonicalImage
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.TotalReduction
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PlainProfile
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Partition
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.StrongProfile
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.CylinderRealization
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.FullCube
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.CurveBridges
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileBridges
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.JointRealization
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.MixedFamilyRun
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.MixedFamilyVersion
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AnyCurve
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileOmpObstruction
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaOmpTight
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Separation
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.SeparationCylinderTotal
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AntistochasticExistence
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.SufficientStatistic
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseTruncation
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseCandidates
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseEnumeration
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseRank
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseGain
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Properties
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.DistributionProjection
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProjectionConservation
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.StochasticTotalReduction
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UniformNoiseExtension
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UniformNoiseProjection
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoise
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseFibres
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.OrdinalPlainRandomness
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PlainSymmetry
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.RemAddNoiseSymmetry
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.RemAddNoiseFibreIndex
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.MinimalModelBounds
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PropMinHereditary
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.StepWisePlain
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1MarkingPredicates
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1MarkingCount
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1SparseSelector
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1MarkingStreams
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1MarkingRun
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1RunBounds
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1Run
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1RunSemantics
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1RunCharging
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1VersionDecoder
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1RunComplexity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1Core
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T1
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T3
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T3Boundary
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T3RunComplexity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T3BoundaryReplay
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.T3Profile
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.StepWiseTotal
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.WitnessPurification
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardConditional
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedStochasticity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseStochasticity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PropAddNoise
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileCardinality
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Lemma4Support
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileEndpointBound
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileOmpRadius
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaOmp
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaOmpEndpointGap
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaOmpResidual
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaOmpBlockCounting
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Lemma4Decoder
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Lemma4Uniform
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Lemma4
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.Hereditary
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseMultiplicity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedAddNoiseArith
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ChargedHeavyCandidates
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ChargedHeavyEnumeration
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ChargedHeavyRank
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ChargedHeavyComplexity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ChargedHeavyRawCharge
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ChargedHeavyGain
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedChargedHeavyGain
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedChargedHeavyMany
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AddNoiseProduct
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.RemAddNoise
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PlainPairSymmetry
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedPairSymmetry
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedNoiseTransport
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedSectionThree
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedTransportBetaLe
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedCornerHardRegime
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedCornerLengthScale
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedCornerMinimality
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedCornerProfile
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.CubeStochasticity
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.RemAddNoiseHalfPlane
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ConditionalGainSplit
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PairStrongModels
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.NormalPair
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BoundaryCurve
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BoundaryRealization
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.AuxiliaryProfile
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.NoiseAssembly
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ThmCardLog
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ThmCardNormal
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileUppest
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ProfileCardinalityLower
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.SeparationWitness
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ThmSeparation
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedAddNoiseLowBranch
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedAddNoiseLogCard
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedAddNoisePolySize
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedAddNoiseSmallGain
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedProjectionTight
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PropUpwardFrontier
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaUpwardCruxReduction
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaUpwardCruxSlack
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.ParameterCharge
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalTransport
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalTransportPow
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalRegimes
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.RadiusMonotone
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.RelativeInformation
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.PurityChargedArithmetic
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalAlphaRegime
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.WidthChargedTransport
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalWidthRegimes
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.UpwardOrdinalBetaRegime
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.FullCubeTransport
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedProjectionMany
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.LemmaUpwardCruxRounding
import KolmogorovMathlib.AlgorithmicStatistics.StrongModels.BudgetedCornerTradeoff

/-!
# Strong models

Models of a string that a *total* machine can produce, and the theory of VS40 §§4–7 built on
them: strong description profiles, sufficient statistics, and the theorems that separate the
strong picture from the plain one.  The group's parts:

### Total machines and their models

`TotalComplexity`, `TotalMaps`, `ProgramList`, `TotalProgramGraph`, `TotalGraphConservation`,
`TotalReduction`, `CanonicalImage`, `StrongProfile`, `PlainProfile`, `FullCube`,
`CylinderRealization`, `Partition`, `Properties`, `SufficientStatistic`.

### Profiles and curves

`CurveBridges`, `ProfileBridges`, `AnyCurve`, `BoundaryCurve`, `BoundaryRealization`,
`AuxiliaryProfile`, `ProfileCardinality`, `ProfileEndpointBound`, `ProfileUppest`,
`JointRealization`, `MixedFamilyRun`, `MixedFamilyVersion`, and the `LemmaOmp*` modules
around the obstruction `ProfileOmpObstruction`.

### Adding noise

`AddNoise` and its parts (`AddNoiseTruncation`, `AddNoiseCandidates`, `AddNoiseEnumeration`,
`AddNoiseRank`, `AddNoiseGain`, `AddNoiseFibres`, `AddNoiseProduct`,
`AddNoiseMultiplicity`, `AddNoiseStochasticity`, `PropAddNoise`), the uniform-noise
extensions `UniformNoiseExtension` and `UniformNoiseProjection`, the removal direction
`RemAddNoise` and its neighbours, and the budgeted forms `Budgeted*`.

### The charged-heavy argument

`ChargedHeavyCandidates`, `ChargedHeavyEnumeration`, `ChargedHeavyRank`,
`ChargedHeavyComplexity`, `ChargedHeavyRawCharge`, `ChargedHeavyGain`,
`BudgetedChargedHeavyGain`, `BudgetedChargedHeavyMany`, `BudgetedProjectionMany`.

### The theorems

`Lemma4` with `Lemma4Decoder`, `Lemma4Support` and `Lemma4Uniform`; `Hereditary` and
`PropMinHereditary`; `StepWisePlain` and `StepWiseTotal`; the `prop:upward` group
(`UpwardOrdinal*`, `WidthChargedTransport`, `PropUpwardFrontier`, `LemmaUpwardCrux*`);
`T1`, `T3` and their runs (`T1Run`, `T1MarkingRun`, `T3Boundary`, `T3BoundaryReplay`, …);
and `ThmSeparation` with `SeparationWitness`, `ThmCardLog` and `ThmCardNormal`.
-/
