/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.MonotoneComplexity.Dimension.ImageMeasure
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.Basic
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.Criteria
import KolmogorovMathlib.MonotoneComplexity.TreeMixture
import KolmogorovMathlib.Foundation.PrimrecExtras
import KolmogorovMathlib.AlgorithmicRandomness.EffectiveOpenNormalForm

/-!
# The weighted semimeasure of SUV Theorem 124 (§5.9.3, p. 184)

> "For each `k` consider the enumerable set of all finite sequences that have
> deficiency greater than `k`.  All the infinite continuations of these sequences
> form an open set `S_k`, and the `P`-measure of this set does not exceed `2^{-k}`.
> Now consider the measure `P_k` on `Ω` that is zero outside `S_k` and is equal to
> `2^k P` inside `S_k` … Now consider the sum `S = ∑_k P_k/(2k²)`."  (SUV p. 184)

`S_k` is `prefixHitSet (aPrioriDeficiencySet P k)` — r.e. by
`isRE_aPrioriDeficiencySet` and of mass `≤ 2^{-k}` by
`measure_prefixHitSet_aPrioriDeficiencySet_le` (both in
`MonotoneComplexity/LevinSchnorr/`), which is Chapter 5.6's Lemma 1.

`P_k(y) = 2^k · P(Ω_y ∩ S_k)` is exactly additive on the tree (it is a measure)
and lower semicomputable *uniformly in `k`*, because `Ω_y ∩ S_k` is the
effectively open set generated by the r.e. relation `defRel` below, and the mass
of such a set is lower semicomputable by
`cantorOpenMass_isLSC_of_isComputableMeasure` (`Dimension/ImageMeasure.lean`).
The pair `(k, y)` is packed into the single parameter string
`defParam k y = natCode k ++ y`, since that is the shape
`cantorOpenMass_isLSC_of_isComputableMeasure` takes.

The weights `1/(2k²)` of the source are obtained from the *geometric* weights of
`continuousTreeMixture` (`MonotoneComplexity/TreeMixture.lean`) by mixing the
**block averages** `b_i = 2^{-i} ∑_{2^i ≤ k < 2^{i+1}} P̂_k`: the mixture gives
`P̂_k` the weight `2^{-(i+1)} · 2^{-i} = 2^{-2i-1} ≥ 1/(2k²)` for `k` in the
`i`-th block.  A finite average of continuous tree semimeasures is one, and the
stage `s` of the average is read off the stage `s - i` of the components, so no
rounding is needed.
-/

namespace Kolmogorov

open MeasureTheory
open scoped ENNReal

/-! ## Packing a level and a string into one parameter -/

/-- The parameter string carrying the level `k` (in unary) and the string `y`. -/
def defParam (k : ℕ) (y : BitString) : BitString := natCode k ++ y

/-- The level read back from a parameter string. -/
def defLevel (x : BitString) : ℕ := (x.takeWhile id).length

/-- The string read back from a parameter string. -/
def defString (x : BitString) : BitString := x.drop (defLevel x + 1)

/-- The level read back from a parameter string is the level it was built from. -/
@[simp] lemma defLevel_defParam (k : ℕ) (y : BitString) : defLevel (defParam k y) = k := by
  have h : ∀ m : ℕ, (List.replicate m true ++ ([false] ++ y)).takeWhile id
      = List.replicate m true := by
    intro m
    induction m with
    | zero => simp
    | succ m ih => simp
  simp only [defLevel, defParam, natCode, List.append_assoc, h, List.length_replicate]

/-- The string read back from a parameter string is the string it was built from. -/
@[simp] lemma defString_defParam (k : ℕ) (y : BitString) : defString (defParam k y) = y := by
  rw [defString, defLevel_defParam, defParam, natCode]
  have h : ∀ m : ℕ, List.drop (m + 1) (List.replicate m true ++ [false] ++ y) = y := by
    intro m
    induction m with
    | zero => simp
    | succ m ih => simpa only [List.replicate_succ, List.cons_append, List.drop_succ_cons] using ih
  exact h k

/-- Reading the level off a parameter string is primitive recursive. -/
lemma primrec_defLevel : Primrec defLevel :=
  Primrec.list_length.comp (Primrec.list_takeWhile (p := fun b : Bool => b) Primrec.id)

/-- Reading the string off a parameter string is primitive recursive. -/
lemma primrec_defString : Primrec defString :=
  Primrec.list_drop.comp (Primrec.nat_add.comp primrec_defLevel (Primrec.const 1)) Primrec.id

/-! ## The effectively open set `Ω_y ∩ S_k` -/

/-- The r.e. relation generating `Ω_y ∩ S_k`: the strings extending `y` that have
a prefix of a priori deficiency above `k`. -/
def defRel (P : Measure CantorSeq) (p x : BitString) : Prop :=
  defString x <+: p ∧ ∃ q, q <+: p ∧ q ∈ aPrioriDeficiencySet P (defLevel x)

/-- The list of prefixes of a string. -/
def stringPrefixList (p : BitString) : List BitString :=
  (List.range (p.length + 1)).map fun i => p.take i

/-- The prefix list of a string contains exactly its prefixes. -/
lemma mem_stringPrefixList {p q : BitString} : q ∈ stringPrefixList p ↔ q <+: p := by
  constructor
  · rintro hq
    rw [stringPrefixList] at hq
    simp only [List.mem_map, List.mem_range] at hq
    obtain ⟨i, -, rfl⟩ := hq
    exact List.take_prefix _ _
  · intro hq
    rw [stringPrefixList]
    simp only [List.mem_map, List.mem_range]
    refine ⟨q.length, by have := hq.length_le; omega, ?_⟩
    obtain ⟨t, ht⟩ := hq
    rw [← ht, List.take_left]

/-- The prefix list is primitive recursive. -/
lemma primrec_stringPrefixList : Primrec stringPrefixList := by
  have h : Primrec fun p : BitString => List.range (p.length + 1) :=
    Primrec.list_range.comp (Primrec.nat_add.comp Primrec.list_length (Primrec.const 1))
  exact Primrec.list_map h Primrec.list_take.swap

/-- For a computable measure, the relation generating the deficiency set is recursively
enumerable. -/
lemma isRE_defRel {P : Measure CantorSeq} [IsProbabilityMeasure P]
    (hP : IsComputableMeasure P) :
    IsRE fun q : BitString × BitString => defRel P q.1 q.2 := by
  -- the deficiency membership, with the level read off the parameter
  have hmap : Computable fun r : (BitString × BitString) × BitString =>
      (defLevel r.1.2, r.2) :=
    Computable.pair (primrec_defLevel.to_comp.comp (Computable.snd.comp Computable.fst))
      Computable.snd
  have hmem : IsRE fun r : (BitString × BitString) × BitString =>
      r.2 ∈ aPrioriDeficiencySet P (defLevel r.1.2) :=
    (isRE_aPrioriDeficiencySet hP).compComputable hmap
  have hbound : Computable fun q : BitString × BitString => stringPrefixList q.1 :=
    primrec_stringPrefixList.to_comp.comp Computable.fst
  have hex : IsRE fun q : BitString × BitString =>
      ∃ b ∈ stringPrefixList q.1, b ∈ aPrioriDeficiencySet P (defLevel q.2) :=
    IsRE.existsInList hmem _ hbound
  have hcheck : Computable fun q : BitString × BitString =>
      normalFormIsPrefixB (defString q.2) q.1 :=
    (primrec₂_normalFormIsPrefixB.to_comp).comp
      (primrec_defString.to_comp.comp Computable.snd) Computable.fst
  refine (hex.and_computable hcheck).of_iff fun q => ?_
  rw [normalFormIsPrefixB_iff]
  constructor
  · rintro ⟨h1, b, hb1, hb2⟩
    exact ⟨h1, b, mem_stringPrefixList.1 hb1, hb2⟩
  · rintro ⟨h1, q', hq1, hq2⟩
    exact ⟨h1, q', mem_stringPrefixList.2 hq1, hq2⟩

/-- The open set generated at a parameter is the cylinder of `y` intersected with the sequences
hitting the deficiency set at level `k`. -/
lemma cantorOpen_defRel (P : Measure CantorSeq) (k : ℕ) (y : BitString) :
    cantorOpen (defRel P) (defParam k y)
      = cantorCylinder y ∩ prefixHitSet (aPrioriDeficiencySet P k) := by
  ext w
  simp only [cantorOpen, Set.mem_iUnion, Set.mem_inter_iff, defRel, defLevel_defParam,
    defString_defParam]
  constructor
  · rintro ⟨p, ⟨hyp, q, hqp, hq⟩, hwp⟩
    have hpw : IsCantorPrefix p w := hwp
    refine ⟨cantorCylinder_subset_of_prefix hyp hwp, ?_⟩
    rw [prefixHitSet_eq_iUnion_cantorCylinder]
    exact Set.mem_biUnion hq (cantorCylinder_subset_of_prefix hqp hwp)
  · rintro ⟨hwy, hwS⟩
    rw [prefixHitSet_eq_iUnion_cantorCylinder] at hwS
    obtain ⟨q, hq, hwq⟩ := Set.mem_iUnion₂.1 hwS
    have hyw : IsCantorPrefix y w := hwy
    have hqw : IsCantorPrefix q w := hwq
    rcases le_total y.length q.length with hle | hle
    · refine ⟨q, ⟨prefix_of_isCantorPrefix hyw hqw hle, q, List.prefix_refl q, hq⟩, hwq⟩
    · exact ⟨y, ⟨List.prefix_refl y, q, prefix_of_isCantorPrefix hqw hyw hle, hq⟩, hwy⟩


/-! ## The deficiency measures `P_k` -/

/-- The measure of a cylinder intersected with a measurable set splits over the two children. -/
lemma measure_inter_split (P : Measure CantorSeq) (x : BitString) {A : Set CantorSeq}
    (hA : MeasurableSet A) :
    P (cantorCylinder x ∩ A)
      = P (cantorCylinder (x ++ [false]) ∩ A) + P (cantorCylinder (x ++ [true]) ∩ A) := by
  rw [cantorCylinder_eq_union_children x, Set.union_inter_distrib_right,
    measure_union ((cantorCylinder_children_disjoint x).mono Set.inter_subset_left
      Set.inter_subset_left) ((measurableSet_cantorCylinder _).inter hA)]

/-- The set of sequences with a prefix in a given set is measurable. -/
lemma measurableSet_prefixHitSet (S : Set BitString) : MeasurableSet (prefixHitSet S) := by
  rw [prefixHitSet_eq_iUnion_cantorCylinder]
  exact MeasurableSet.biUnion (Set.to_countable S) fun x _ => measurableSet_cantorCylinder x

/-- The source's measure `P_k`: zero outside `S_k` and `2^k·P` inside, with the
defect assigned to the root so that it is a continuous tree semimeasure. -/
noncomputable def defMeasure (P : Measure CantorSeq) (k : ℕ) (y : BitString) : ℝ≥0∞ :=
  if y = [] then 1
  else (2 : ℝ≥0∞) ^ k * P (cantorCylinder y ∩ prefixHitSet (aPrioriDeficiencySet P k))

/-- Away from the root, the level-`k` deficiency measure is `2 ^ k` times the measure of the
cylinder intersected with the deficiency set. -/
lemma defMeasure_of_ne_nil {P : Measure CantorSeq} {k : ℕ} {y : BitString} (hy : y ≠ []) :
    defMeasure P k y
      = (2 : ℝ≥0∞) ^ k * P (cantorCylinder y ∩ prefixHitSet (aPrioriDeficiencySet P k)) :=
  if_neg hy

/-- Each level-`k` deficiency measure is a continuous tree semimeasure. -/
lemma isContinuousTreeSemimeasure_defMeasure {P : Measure CantorSeq} [IsProbabilityMeasure P]
    (k : ℕ) : IsContinuousTreeSemimeasure (defMeasure P k) := by
  refine ⟨by simp [defMeasure], fun x => ?_⟩
  have hne0 : x ++ [false] ≠ [] := by simp
  have hne1 : x ++ [true] ≠ [] := by simp
  rw [defMeasure_of_ne_nil hne0, defMeasure_of_ne_nil hne1, ← mul_add,
    ← measure_inter_split P x (measurableSet_prefixHitSet _)]
  by_cases hx : x = []
  · subst hx
    rw [defMeasure, if_pos rfl, cantorCylinder_nil, Set.univ_inter]
    calc (2 : ℝ≥0∞) ^ k * P (prefixHitSet (aPrioriDeficiencySet P k))
        ≤ (2 : ℝ≥0∞) ^ k * ((2 : ℝ≥0∞)⁻¹) ^ k := by
          gcongr
          exact measure_prefixHitSet_aPrioriDeficiencySet_le k
      _ = 1 := by
          rw [← mul_pow, ENNReal.mul_inv_cancel (by norm_num) (by norm_num), one_pow]
  · rw [defMeasure_of_ne_nil hx]

/-! ## The uniform lower-semicomputable approximation of the family `P_k` -/

/-- Multiplying the numerator by a natural multiplies the dyadic value by it. -/
lemma dyadicValue_nat_mul (c n s : ℕ) :
    dyadicValue (c * n) s = (c : ℝ≥0∞) * dyadicValue n s :=
  dyadicValue_natCast_mul_left c n s

/-- For a computable measure, the deficiency measures have a single computable family of
stagewise numerators, uniform in the level. -/
lemma exists_uniform_approx_defMeasure {P : Measure CantorSeq} [IsProbabilityMeasure P]
    (hP : IsComputableMeasure P) :
    ∃ A : ℕ → ℕ → BitString → BitString → ℕ,
      (∀ k s out ctx, dyadicValue (A k s out ctx) s
        ≤ dyadicValue (A k (s + 1) out ctx) (s + 1)) ∧
      (∀ k out ctx, ⨆ s, dyadicValue (A k s out ctx) s = defMeasure P k out) ∧
      Computable (fun p : ℕ × ℕ × BitString × BitString => A p.1 p.2.1 p.2.2.1 p.2.2.2) := by
  classical
  obtain ⟨approx, hmono, hsup, hcomp⟩ :=
    cantorOpenMass_isLSC_of_isComputableMeasure hP (isRE_defRel hP)
  refine ⟨fun k s y ctx => if y = [] then 2 ^ s else 2 ^ k * approx s (defParam k y) ctx,
    ?_, ?_, ?_⟩
  · intro k s y ctx
    by_cases hy : y = []
    · simp [hy, dyadicValue_two_pow_self]
    · simp only [if_neg hy, dyadicValue_nat_mul]
      have hcast : ((2 ^ k : ℕ) : ℝ≥0∞) = (2 : ℝ≥0∞) ^ k := by push_cast; ring
      rw [hcast]
      exact mul_le_mul_right (hmono s (defParam k y) ctx) _
  · intro k y ctx
    by_cases hy : y = []
    · simp [hy, dyadicValue_two_pow_self, defMeasure]
    · simp only [if_neg hy, dyadicValue_nat_mul, defMeasure_of_ne_nil hy]
      have hcast : ((2 ^ k : ℕ) : ℝ≥0∞) = (2 : ℝ≥0∞) ^ k := by push_cast; ring
      rw [hcast, ← ENNReal.mul_iSup]
      have hs := hsup (defParam k y) ctx
      simp only at hs
      rw [hs, cantorOpen_defRel]
  · have hpow : Computable fun n : ℕ => 2 ^ n := primrec_two_pow_aux.to_comp
    have hparam : Computable fun p : ℕ × ℕ × BitString × BitString =>
        defParam p.1 p.2.2.1 :=
      (Primrec.list_append.comp (primrec_natCode.comp Primrec.fst)
        (Primrec.fst.comp (Primrec.snd.comp Primrec.snd))).to_comp
    have happ : Computable fun p : ℕ × ℕ × BitString × BitString =>
        approx p.2.1 (defParam p.1 p.2.2.1) p.2.2.2 :=
      hcomp.comp (Computable.pair (Computable.fst.comp Computable.snd)
        (Computable.pair hparam (Computable.snd.comp (Computable.snd.comp Computable.snd))))
    have hthen : Computable fun p : ℕ × ℕ × BitString × BitString => 2 ^ p.2.1 :=
      hpow.comp (Computable.fst.comp Computable.snd)
    have helse : Computable fun p : ℕ × ℕ × BitString × BitString =>
        2 ^ p.1 * approx p.2.1 (defParam p.1 p.2.2.1) p.2.2.2 :=
      (Primrec.nat_mul.to_comp).comp (hpow.comp Computable.fst) happ
    have hdec : Computable fun p : ℕ × ℕ × BitString × BitString =>
        decide (p.2.2.1 = ([] : BitString)) := by
      have : PrimrecPred fun p : ℕ × ℕ × BitString × BitString => p.2.2.1 = ([] : BitString) :=
        Primrec.eq.comp (Primrec.fst.comp (Primrec.snd.comp Primrec.snd)) (Primrec.const [])
      exact (PrimrecPred.decide this).to_comp
    exact (Computable.cond hdec hthen helse).of_eq fun p => by
      by_cases hy : p.2.2.1 = ([] : BitString) <;> simp [hy]



/-! ## Dyadic bookkeeping for the block averages -/

/-- The dyadic value of a finite sum is the sum of the dyadic values. -/
lemma dyadicValue_sum_range_dim (S : Finset ℕ) (g : ℕ → ℕ) (t : ℕ) :
    dyadicValue (∑ j ∈ S, g j) t = ∑ j ∈ S, dyadicValue (g j) t := by
  classical
  induction S using Finset.induction_on with
  | empty => simp [dyadicValue]
  | insert a S ha ih =>
      rw [Finset.sum_insert ha, Finset.sum_insert ha, dyadicValue_add, ih]

/-- Raising the precision by `d` scales the dyadic value by `2 ^ -d`. -/
lemma dyadicValue_stage_add (n t d : ℕ) :
    dyadicValue n (t + d) = ((2 : ℝ≥0∞)⁻¹) ^ d * dyadicValue n t := by
  simp only [dyadicValue, pow_add, div_eq_mul_inv]
  rw [ENNReal.mul_inv (Or.inl (by positivity)) (Or.inl (by simp)), ← ENNReal.inv_pow]
  ring

/-! ## The block averages -/

/-- The average of the deficiency measures of the levels `2^i ≤ k < 2^{i+1}`.
The mixture below gives it the weight `2^{-(i+1)}`, so each `P_k` in the block
receives `2^{-2i-1} ≥ 1/(2k²)` — the weight of the source. -/
noncomputable def blockAverage (P : Measure CantorSeq) (i : ℕ) (y : BitString) : ℝ≥0∞ :=
  ((2 : ℝ≥0∞)⁻¹) ^ i * ∑ j ∈ Finset.range (2 ^ i), defMeasure P (2 ^ i + j) y

/-- Each block average of the deficiency measures is a continuous tree semimeasure. -/
lemma isContinuousTreeSemimeasure_blockAverage {P : Measure CantorSeq}
    [IsProbabilityMeasure P] (i : ℕ) : IsContinuousTreeSemimeasure (blockAverage P i) := by
  refine ⟨?_, fun x => ?_⟩
  · have h1 : ∀ j ∈ Finset.range (2 ^ i), defMeasure P (2 ^ i + j) ([] : BitString) = 1 :=
      fun j _ => by simp [defMeasure]
    rw [blockAverage, Finset.sum_congr rfl h1, Finset.sum_const, Finset.card_range,
      nsmul_eq_mul, mul_one, mul_comm]
    exact nat_two_pow_mul_inv_two_pow i
  · rw [blockAverage, blockAverage, blockAverage, ← mul_add, ← Finset.sum_add_distrib]
    gcongr with j hj
    exact (isContinuousTreeSemimeasure_defMeasure (P := P) (2 ^ i + j)).2 x

/-- The stage-`s` numerator of the `i`-th block average: the components are read
at stage `s - i`, which divides their value by `2^i`, i.e. averages them. -/
def blockApprox (A : ℕ → ℕ → BitString → BitString → ℕ) (i s : ℕ) (y ctx : BitString) : ℕ :=
  if s < i then 0 else ∑ j ∈ Finset.range (2 ^ i), A (2 ^ i + j) (s - i) y ctx

/-- The dyadic value of the block approximation is `2 ^ -i` times the sum of the component values
of the block. -/
lemma dyadicValue_blockApprox {A : ℕ → ℕ → BitString → BitString → ℕ} {i s : ℕ}
    (his : i ≤ s) (y ctx : BitString) :
    dyadicValue (blockApprox A i s y ctx) s
      = ((2 : ℝ≥0∞)⁻¹) ^ i
        * ∑ j ∈ Finset.range (2 ^ i), dyadicValue (A (2 ^ i + j) (s - i) y ctx) (s - i) := by
  obtain ⟨t, rfl⟩ : ∃ t, s = t + i := ⟨s - i, by omega⟩
  rw [blockApprox, if_neg (by omega)]
  simp only [Nat.add_sub_cancel]
  rw [dyadicValue_stage_add, dyadicValue_sum_range_dim]



/-- A stagewise non-decreasing family is monotone between any two stages. -/
lemma dyadicValue_mono_of_le {A : ℕ → ℕ → BitString → BitString → ℕ}
    (hmono : ∀ k s out ctx, dyadicValue (A k s out ctx) s
      ≤ dyadicValue (A k (s + 1) out ctx) (s + 1))
    (k : ℕ) (y ctx : BitString) {t t' : ℕ} (h : t ≤ t') :
    dyadicValue (A k t y ctx) t ≤ dyadicValue (A k t' y ctx) t' := by
  obtain ⟨d, rfl⟩ : ∃ d, t' = t + d := ⟨t' - t, by omega⟩
  clear h
  induction d with
  | zero => simp
  | succ d ih =>
      refine le_trans ih ?_
      have h1 := hmono k (t + d) y ctx
      simpa [Nat.add_assoc] using h1

/-- The block approximation is non-decreasing in the stage. -/
lemma blockApprox_mono {A : ℕ → ℕ → BitString → BitString → ℕ}
    (hmono : ∀ k s out ctx, dyadicValue (A k s out ctx) s
      ≤ dyadicValue (A k (s + 1) out ctx) (s + 1))
    (i s : ℕ) (y ctx : BitString) :
    dyadicValue (blockApprox A i s y ctx) s
      ≤ dyadicValue (blockApprox A i (s + 1) y ctx) (s + 1) := by
  by_cases his : i ≤ s
  · rw [dyadicValue_blockApprox his y ctx, dyadicValue_blockApprox (by omega : i ≤ s + 1) y ctx]
    have hstep : s + 1 - i = (s - i) + 1 := by omega
    rw [hstep]
    gcongr with j hj
    exact hmono (2 ^ i + j) (s - i) y ctx
  · rw [blockApprox, if_pos (by omega)]
    simp [dyadicValue]

/-- The block approximation converges to the block average. -/
lemma blockApprox_sup {P : Measure CantorSeq} [IsProbabilityMeasure P]
    {A : ℕ → ℕ → BitString → BitString → ℕ}
    (hmono : ∀ k s out ctx, dyadicValue (A k s out ctx) s
      ≤ dyadicValue (A k (s + 1) out ctx) (s + 1))
    (hsup : ∀ k out ctx, ⨆ s, dyadicValue (A k s out ctx) s = defMeasure P k out)
    (i : ℕ) (y ctx : BitString) :
    ⨆ s, dyadicValue (blockApprox A i s y ctx) s = blockAverage P i y := by
  refine le_antisymm (iSup_le fun s => ?_) ?_
  · by_cases his : i ≤ s
    · rw [dyadicValue_blockApprox his y ctx, blockAverage]
      gcongr with j hj
      rw [← hsup (2 ^ i + j) y ctx]
      exact le_iSup (fun t => dyadicValue (A (2 ^ i + j) t y ctx) t) (s - i)
    · rw [blockApprox, if_pos (by omega)]
      simp [dyadicValue]
  · rw [blockAverage]
    have hswap : ∑ j ∈ Finset.range (2 ^ i), defMeasure P (2 ^ i + j) y
        = ⨆ t, ∑ j ∈ Finset.range (2 ^ i), dyadicValue (A (2 ^ i + j) t y ctx) t := by
      have h1 : ∀ j, defMeasure P (2 ^ i + j) y
          = ⨆ t, dyadicValue (A (2 ^ i + j) t y ctx) t :=
        fun j => (hsup (2 ^ i + j) y ctx).symm
      simp_rw [h1]
      exact ENNReal.finsetSum_iSup (fun t₁ t₂ => ⟨max t₁ t₂, fun j =>
        ⟨dyadicValue_mono_of_le hmono _ y ctx (le_max_left t₁ t₂),
          dyadicValue_mono_of_le hmono _ y ctx (le_max_right t₁ t₂)⟩⟩)
    rw [hswap, ENNReal.mul_iSup]
    refine iSup_le fun t => ?_
    have hle := le_iSup (fun s => dyadicValue (blockApprox A i s y ctx) s) (t + i)
    rw [dyadicValue_blockApprox (by omega : i ≤ t + i) y ctx, Nat.add_sub_cancel] at hle
    exact hle

/-- The block approximation of a computable family is computable. -/
lemma computable_blockApprox {A : ℕ → ℕ → BitString → BitString → ℕ}
    (hcomp : Computable fun p : ℕ × ℕ × BitString × BitString => A p.1 p.2.1 p.2.2.1 p.2.2.2) :
    Computable fun p : ℕ × ℕ × BitString × BitString =>
      blockApprox A p.1 p.2.1 p.2.2.1 p.2.2.2 := by
  classical
  have hpow : Computable fun n : ℕ => 2 ^ n := primrec_two_pow_aux.to_comp
  have hlist : Computable fun p : ℕ × ℕ × BitString × BitString => List.range (2 ^ p.1) :=
    Primrec.list_range.to_comp.comp (hpow.comp Computable.fst)
  have hbody : Computable₂ fun (p : ℕ × ℕ × BitString × BitString) (j : ℕ) =>
      A (2 ^ p.1 + j) (p.2.1 - p.1) p.2.2.1 p.2.2.2 := by
    have harg : Computable fun r : (ℕ × ℕ × BitString × BitString) × ℕ =>
        ((2 ^ r.1.1 + r.2 : ℕ), ((r.1.2.1 - r.1.1 : ℕ), (r.1.2.2.1, r.1.2.2.2))) := by
      refine Computable.pair ?_ (Computable.pair ?_ (Computable.pair ?_ ?_))
      · exact (Primrec.nat_add.to_comp).comp (hpow.comp (Computable.fst.comp Computable.fst))
          Computable.snd
      · exact (Primrec.nat_sub.to_comp).comp
          (Computable.fst.comp (Computable.snd.comp Computable.fst))
          (Computable.fst.comp Computable.fst)
      · exact Computable.fst.comp (Computable.snd.comp (Computable.snd.comp Computable.fst))
      · exact Computable.snd.comp (Computable.snd.comp (Computable.snd.comp Computable.fst))
    refine (hcomp.comp harg).of_eq fun r => ?_
    rfl
  have hsum : Computable fun p : ℕ × ℕ × BitString × BitString =>
      ((List.range (2 ^ p.1)).map
        (fun j => A (2 ^ p.1 + j) (p.2.1 - p.1) p.2.2.1 p.2.2.2)).sum :=
    computable_list_sum_map hlist hbody
  have hdec : Computable fun p : ℕ × ℕ × BitString × BitString =>
      decide (p.2.1 < p.1) :=
    (PrimrecPred.decide (Primrec.nat_lt.comp (Primrec.fst.comp Primrec.snd) Primrec.fst)).to_comp
  refine (Computable.cond hdec (Computable.const 0) hsum).of_eq fun p => ?_
  by_cases hlt : p.2.1 < p.1
  · simp [blockApprox, hlt]
  · simp [blockApprox, hlt, sum_list_range_eq_finset_sum']

/-! ## The weighted semimeasure -/

/-- The source's `S = ∑_k P_k/(2k²)`, realised as the geometric mixture of the
block averages. -/
noncomputable def defWeightedSemimeasure (P : Measure CantorSeq) : BitString → ℝ≥0∞ :=
  continuousTreeMixture (blockAverage P)

/-- For a computable measure, the weighted mixture of the deficiency measures is a lower
semicomputable continuous semimeasure. -/
lemma isLSCContinuousSemimeasure_defWeightedSemimeasure {P : Measure CantorSeq}
    [IsProbabilityMeasure P] (hP : IsComputableMeasure P) :
    IsLowerSemicomputableContinuousSemimeasure (defWeightedSemimeasure P) := by
  obtain ⟨A, hmono, hsup, hcomp⟩ := exists_uniform_approx_defMeasure hP
  exact continuousTreeMixture_dyadicWeight_isLowerSemicomputableContinuousSemimeasure
    (a := blockApprox A) (blockAverage P)
    (fun i s out ctx => blockApprox_mono hmono i s out ctx)
    (fun i out ctx => blockApprox_sup hmono hsup i out ctx)
    (fun i => isContinuousTreeSemimeasure_blockAverage i)
    (computable_blockApprox hcomp)

/-- The source's weight: `P_k` occurs in `S` with a factor at least `1/(2k²)`. -/
lemma defMeasure_le_defWeightedSemimeasure {P : Measure CantorSeq} [IsProbabilityMeasure P]
    {k : ℕ} (hk : 1 ≤ k) (y : BitString) :
    ((2 : ℝ≥0∞)⁻¹) ^ (2 * Nat.log 2 k + 1) * defMeasure P k y ≤ defWeightedSemimeasure P y := by
  set i := Nat.log 2 k with hi
  have hkpos : k ≠ 0 := by omega
  have hlow : 2 ^ i ≤ k := Nat.pow_log_le_self 2 hkpos
  have hhigh : k < 2 ^ (i + 1) := Nat.lt_pow_succ_log_self (by norm_num) k
  have hj : k - 2 ^ i < 2 ^ i := by
    have : 2 ^ (i + 1) = 2 ^ i + 2 ^ i := by ring
    omega
  have hk_eq : 2 ^ i + (k - 2 ^ i) = k := by omega
  have hterm : defMeasure P k y ≤ ∑ j ∈ Finset.range (2 ^ i), defMeasure P (2 ^ i + j) y := by
    refine le_trans (le_of_eq ?_) (Finset.single_le_sum
      (f := fun j => defMeasure P (2 ^ i + j) y) (fun j _ => zero_le)
      (Finset.mem_range.2 hj))
    rw [hk_eq]
  calc ((2 : ℝ≥0∞)⁻¹) ^ (2 * i + 1) * defMeasure P k y
      = dyadicWeight i * (((2 : ℝ≥0∞)⁻¹) ^ i * defMeasure P k y) := by
        rw [dyadicWeight, ← mul_assoc, ← pow_add]
        congr 2
        omega
    _ ≤ dyadicWeight i * blockAverage P i y := by
        gcongr
        rw [blockAverage]
        gcongr
    _ ≤ defWeightedSemimeasure P y := continuousTreeMixture_dominates_component _ i y


end Kolmogorov
