/-
Copyright (c) 2026. All rights reserved.
-/
import KolmogorovMathlib.AlgorithmicRandomness.Disjointify
import KolmogorovMathlib.AlgorithmicRandomness.StageComputable
import KolmogorovMathlib.MonotoneComplexity.ContinuousStreamMap
import KolmogorovMathlib.MonotoneComplexity.Dimension.Basic
import KolmogorovMathlib.MonotoneComplexity.EffectiveOpen
import KolmogorovMathlib.MonotoneComplexity.EffectiveOpenBridge
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.FinsetDeficiency
import KolmogorovMathlib.MonotoneComplexity.LevinSchnorr.Infra
import KolmogorovMathlib.MonotoneComplexity.TwoSidedMeasureRepresentation

/-!
# The image of a computable measure is computable (SUV §5.9.3, p. 181)

> "Consider the image of the measure `μ` with respect to `f`, i.e. a measure `ν`
> on the set `Σ` such that `ν(U) = μ(f^{-1}(U))` for any `U ⊂ Σ`. … (It is easy
> to see that in this case `ν` is a computable measure.)"  (SUV §5.9.3, p. 181)

This module supplies the two ingredients of that remark:

* `setOf_le_comp_eq_cantorOpen` — the preimage `f^{-1}(Σ_u)` is the effectively
  open set `⋃ {Ω_p : u ⪯ f(p)}`, by continuity of `f`;
* `cantorOpenMass_isLSC_of_isComputableMeasure` — the mass of such a set is lower
  semicomputable uniformly in `u` (the analogue for the uniform measure is
  `cantorOpenMass_isLSC` in `MonotoneComplexity/EffectiveOpen.lean`).

Together with SUV Theorem 77(b)
(`exists_isComputableMeasure_of_isLowerSemicomputableContinuousSemimeasure`) and
`cantorMeasure_unique` they give `isComputableMeasure_of_isImageMeasure`, proved
in `Dimension/ChangeOfMeasure.lean`.
-/

namespace Kolmogorov

open MeasureTheory
open scoped ENNReal

/-- The total mass of a probability measure on `Ω` is the mass of the root
cylinder. -/
lemma cantorMass_nil (μ : Measure CantorSeq) [IsProbabilityMeasure μ] :
    cantorMass μ ([] : BitString) = 1 := by
  rw [cantorMass, cantorCylinder_nil, measure_univ]

/-- **SUV §5.9.3, p. 181.**  The `f`-preimage of the set `Σ_u` of extensions of
`u` is the effectively open set generated by the lower graph of `f`:

`{ω | u ⪯ f(ω)} = ⋃ {Ω_p | u ⪯ f(p)}`.

`⊇` is monotonicity of `f`, `⊆` is its continuity. -/
lemma setOf_le_comp_eq_cantorOpen {f : BitStream → BitStream}
    (hf : IsContinuousStreamMap f) (u : BitString) :
    {w : CantorSeq | BitStream.finite u ≤ f (BitStream.infinite w)}
      = cantorOpen (streamLowerGraph f) u := by
  ext w
  simp only [Set.mem_ofPred_eq, cantorOpen, Set.mem_iUnion, streamLowerGraph]
  constructor
  · intro hw
    obtain ⟨n, hn⟩ := (continuousStreamMap_finite_le_infinite_iff f hf w u).1 hw
    exact ⟨cantorPrefix w n, hn, mem_cantorCylinder_cantorPrefix w n⟩
  · rintro ⟨p, hp, hmem⟩
    have hpw : BitStream.finite p ≤ BitStream.infinite w :=
      BitStream.finite_le_infinite_iff.2 hmem
    exact le_trans hp (hf.1 hpw)

/-! ## Dyadic bookkeeping

Four routine facts about `dyadicValue n s = n / 2^s` used by the lower
semicomputability proof below. -/

/-- `s / 2^{2s+2} ≤ 1 / 2^{s+2}`: the error of `s` terms each accurate to
`2^{-(2s+2)}` is below the target accuracy `2^{-(s+2)}`. -/
private lemma dyadicValue_stage_error_le (s : ℕ) :
    dyadicValue s (2 * s + 2) ≤ dyadicValue 1 (s + 2) := by
  have h1 : dyadicValue s (2 * s + 2) ≤ dyadicValue (2 ^ s) (2 * s + 2) :=
    dyadicValue_mono_nat (le_of_lt Nat.lt_two_pow_self) _
  have h2 : dyadicValue (2 ^ s) (2 * s + 2) = dyadicValue 1 (s + 2) := by
    have h3 := dyadicValue_mul_two_pow 1 (s + 2) s
    have h4 : (s + 2) + s = 2 * s + 2 := by omega
    rw [h4, one_mul] at h3
    exact h3
  exact h1.trans (le_of_eq h2)

/-! ## The staged approximation of the mass of an effectively open set -/

/-- The mass of the first `s` intervals of a *disjoint* enumeration `D x`. -/
private noncomputable def openPartialMass (μ : Measure CantorSeq)
    (D : BitString → ℕ → Option BitString) (s : ℕ) (x : BitString) : ℝ≥0∞ :=
  ∑ i ∈ Finset.range s, (D x i).elim 0 (cantorMass μ)

/-- The stage-`s` numerator: the masses of the first `s` intervals of `D x`, each
computed by the approximation family `a` to precision `2^{-(2s+2)}`, summed,
rescaled to the grid `2^{-s}` and lowered by one grid unit (so that the value
stays below the true mass). -/
private def openApproxNum (a : BitString → ℕ → ℕ) (D : BitString → ℕ → Option BitString)
    (s : ℕ) (x : BitString) : ℕ :=
  (((List.range s).map (fun i => (D x i).elim 0 (fun u => a u (2 * s + 2)))).sum)
    / 2 ^ (s + 2) - 1

private lemma openApproxNum_eq (a : BitString → ℕ → ℕ) (D : BitString → ℕ → Option BitString)
    (s : ℕ) (x : BitString) :
    openApproxNum a D s x =
      (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u (2 * s + 2))) / 2 ^ (s + 2) - 1 := by
  rw [openApproxNum, sum_list_range_eq_finset_sum']

/-- The two-sided estimate for the sum of `s` approximated interval masses. -/
private lemma openApproxSum_bounds {μ : Measure CantorSeq} {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    (D : BitString → ℕ → Option BitString) (t s : ℕ) (x : BitString) :
    dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u t)) t
        ≤ openPartialMass μ D s x + dyadicValue s t ∧
      openPartialMass μ D s x
        ≤ dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u t)) t
          + dyadicValue s t := by
  induction s with
  | zero => simp [openPartialMass, dyadicValue]
  | succ s ih =>
      have hterm :
          dyadicValue ((D x s).elim 0 (fun u => a u t)) t
              ≤ (D x s).elim 0 (cantorMass μ) + dyadicValue 1 t ∧
            (D x s).elim 0 (cantorMass μ)
              ≤ dyadicValue ((D x s).elim 0 (fun u => a u t)) t + dyadicValue 1 t := by
        cases hD : D x s with
        | none => simp [dyadicValue]
        | some u => simpa using ha u t
      have hsum : (∑ i ∈ Finset.range (s + 1), (D x i).elim 0 (fun u => a u t))
          = (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u t))
            + (D x s).elim 0 (fun u => a u t) := Finset.sum_range_succ _ s
      have hmass : openPartialMass μ D (s + 1) x
          = openPartialMass μ D s x + (D x s).elim 0 (cantorMass μ) :=
        Finset.sum_range_succ _ s
      constructor
      · rw [hsum, dyadicValue_add, hmass, dyadicValue_add s 1 t]
        calc dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u t)) t
              + dyadicValue ((D x s).elim 0 (fun u => a u t)) t
            ≤ (openPartialMass μ D s x + dyadicValue s t)
              + ((D x s).elim 0 (cantorMass μ) + dyadicValue 1 t) := add_le_add ih.1 hterm.1
          _ = (openPartialMass μ D s x + (D x s).elim 0 (cantorMass μ))
              + (dyadicValue s t + dyadicValue 1 t) := by rw [add_add_add_comm]
      · rw [hsum, dyadicValue_add, hmass, dyadicValue_add s 1 t]
        calc openPartialMass μ D s x + (D x s).elim 0 (cantorMass μ)
            ≤ (dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u t)) t
                + dyadicValue s t)
              + (dyadicValue ((D x s).elim 0 (fun u => a u t)) t + dyadicValue 1 t) :=
              add_le_add ih.2 hterm.2
          _ = (dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u t)) t
                + dyadicValue ((D x s).elim 0 (fun u => a u t)) t)
              + (dyadicValue s t + dyadicValue 1 t) := by rw [add_add_add_comm]

/-- Rescaling a stage-`(2s+2)` numerator to the grid `2^{-s}` and lowering it by
one grid unit keeps it below any bound the original value has, up to `2^{-s}`. -/
private lemma dyadicValue_div_sub_one_le (A s : ℕ) (m : ℝ≥0∞)
    (h : dyadicValue A (2 * s + 2) ≤ m + dyadicValue 1 s) :
    dyadicValue (A / 2 ^ (s + 2) - 1) s ≤ m := by
  have hstage : s + (s + 2) = 2 * s + 2 := by omega
  rcases Nat.eq_zero_or_pos (A / 2 ^ (s + 2)) with h0 | hpos
  · rw [h0]
    simp [dyadicValue]
  · have hq1 : (A / 2 ^ (s + 2) - 1) + 1 = A / 2 ^ (s + 2) := by omega
    have hmul : ((A / 2 ^ (s + 2) - 1) + 1) * 2 ^ (s + 2) ≤ A := by
      rw [hq1]
      exact Nat.div_mul_le_self A (2 ^ (s + 2))
    have hkey : dyadicValue ((A / 2 ^ (s + 2) - 1) + 1) s ≤ m + dyadicValue 1 s := by
      calc dyadicValue ((A / 2 ^ (s + 2) - 1) + 1) s
          = dyadicValue (((A / 2 ^ (s + 2) - 1) + 1) * 2 ^ (s + 2)) (2 * s + 2) := by
            rw [← hstage, dyadicValue_mul_two_pow]
        _ ≤ dyadicValue A (2 * s + 2) := dyadicValue_mono_nat hmul _
        _ ≤ m + dyadicValue 1 s := h
    rw [dyadicValue_add] at hkey
    exact (ENNReal.add_le_add_iff_right (dyadicValue_one_ne_top s)).1 hkey

/-- The converse estimate: the rescaled, lowered numerator loses at most
`3 · 2^{-s}`. -/
private lemma le_dyadicValue_div_sub_one (A s : ℕ) (m : ℝ≥0∞)
    (h : m ≤ dyadicValue A (2 * s + 2) + dyadicValue 1 s) :
    m ≤ dyadicValue (A / 2 ^ (s + 2) - 1) s + dyadicValue 3 s := by
  have hstage : s + (s + 2) = 2 * s + 2 := by omega
  have hposk : 0 < 2 ^ (s + 2) := pow_pos (by norm_num) (s + 2)
  have hlt : A < (A / 2 ^ (s + 2) + 1) * 2 ^ (s + 2) :=
    (Nat.div_lt_iff_lt_mul hposk).1 (Nat.lt_succ_self _)
  have hle : A ≤ ((A / 2 ^ (s + 2) - 1) + 2) * 2 ^ (s + 2) := by
    have hq2 : A / 2 ^ (s + 2) + 1 ≤ (A / 2 ^ (s + 2) - 1) + 2 := by omega
    exact le_of_lt (lt_of_lt_of_le hlt (Nat.mul_le_mul_right _ hq2))
  calc m ≤ dyadicValue A (2 * s + 2) + dyadicValue 1 s := h
    _ ≤ dyadicValue (((A / 2 ^ (s + 2) - 1) + 2) * 2 ^ (s + 2)) (2 * s + 2)
        + dyadicValue 1 s := add_le_add (dyadicValue_mono_nat hle _) le_rfl
    _ = dyadicValue ((A / 2 ^ (s + 2) - 1) + 2) s + dyadicValue 1 s := by
        rw [← hstage, dyadicValue_mul_two_pow]
    _ = dyadicValue (A / 2 ^ (s + 2) - 1) s + (dyadicValue 2 s + dyadicValue 1 s) := by
        rw [dyadicValue_add, add_assoc]
    _ = dyadicValue (A / 2 ^ (s + 2) - 1) s + dyadicValue 3 s := by
        rw [← dyadicValue_add]

/-- The staged numerator stays below the partial mass. -/
private lemma openApproxNum_le {μ : Measure CantorSeq} {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    (D : BitString → ℕ → Option BitString) (s : ℕ) (x : BitString) :
    dyadicValue (openApproxNum a D s x) s ≤ openPartialMass μ D s x := by
  rw [openApproxNum_eq]
  refine dyadicValue_div_sub_one_le _ s _ ?_
  calc dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u (2 * s + 2)))
        (2 * s + 2)
      ≤ openPartialMass μ D s x + dyadicValue s (2 * s + 2) :=
        (openApproxSum_bounds ha D (2 * s + 2) s x).1
    _ ≤ openPartialMass μ D s x + dyadicValue 1 (s + 2) :=
        add_le_add le_rfl (dyadicValue_stage_error_le s)
    _ ≤ openPartialMass μ D s x + dyadicValue 1 s :=
        add_le_add le_rfl (dyadicValue_antitone_stage 1 (Nat.le_add_right s 2))

/-- The staged numerator is within `3 · 2^{-s}` of the partial mass. -/
private lemma le_openApproxNum {μ : Measure CantorSeq} {a : BitString → ℕ → ℕ}
    (ha : ∀ x s, dyadicValue (a x s) s ≤ cantorMass μ x + dyadicValue 1 s ∧
      cantorMass μ x ≤ dyadicValue (a x s) s + dyadicValue 1 s)
    (D : BitString → ℕ → Option BitString) (s : ℕ) (x : BitString) :
    openPartialMass μ D s x ≤ dyadicValue (openApproxNum a D s x) s + dyadicValue 3 s := by
  rw [openApproxNum_eq]
  refine le_dyadicValue_div_sub_one _ s _ ?_
  calc openPartialMass μ D s x
      ≤ dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u (2 * s + 2)))
          (2 * s + 2) + dyadicValue s (2 * s + 2) :=
        (openApproxSum_bounds ha D (2 * s + 2) s x).2
    _ ≤ dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u (2 * s + 2)))
          (2 * s + 2) + dyadicValue 1 (s + 2) :=
        add_le_add le_rfl (dyadicValue_stage_error_le s)
    _ ≤ dyadicValue (∑ i ∈ Finset.range s, (D x i).elim 0 (fun u => a u (2 * s + 2)))
          (2 * s + 2) + dyadicValue 1 s :=
        add_le_add le_rfl (dyadicValue_antitone_stage 1 (Nat.le_add_right s 2))

/-- The staged numerator is computable in the two computable data it is built
from: the approximation family `a` of the measure and the enumeration `D`. -/
private lemma computable_openApproxNum {a : BitString → ℕ → ℕ} (ha : Computable₂ a)
    {D : BitString → ℕ → Option BitString}
    (hD : Computable fun r : BitString × ℕ => D r.1 r.2) :
    Computable fun p : ℕ × BitString × BitString => openApproxNum a D p.1 p.2.1 := by
  have hD2 : Computable₂ D := hD
  have hopt : Computable fun r : (ℕ × BitString × BitString) × ℕ => D r.1.2.1 r.2 :=
    hD2.comp (Computable.fst.comp (Computable.snd.comp Computable.fst)) Computable.snd
  have hval : Computable₂ fun (r : (ℕ × BitString × BitString) × ℕ) (u : BitString) =>
      a u (2 * r.1.1 + 2) := by
    have hstage : Computable fun r : ((ℕ × BitString × BitString) × ℕ) × BitString =>
        2 * r.1.1.1 + 2 :=
      (Primrec.nat_add.comp
        (Primrec.nat_mul.comp (Primrec.const 2) (Primrec.fst.comp (Primrec.fst.comp
          Primrec.fst))) (Primrec.const 2)).to_comp
    exact ha.comp Computable.snd hstage
  have hterm : Computable₂ fun (p : ℕ × BitString × BitString) (i : ℕ) =>
      (D p.2.1 i).elim 0 (fun u => a u (2 * p.1 + 2)) := by
    refine (Computable.option_casesOn hopt (Computable.const 0) hval).of_eq ?_
    intro r
    cases hDr : D r.1.2.1 r.2 with
    | none => simp [hDr]
    | some v => simp [hDr]
  have hsum : Computable fun p : ℕ × BitString × BitString =>
      ((List.range p.1).map (fun i => (D p.2.1 i).elim 0 (fun u => a u (2 * p.1 + 2)))).sum :=
    computable_list_sum_map (Primrec.list_range.to_comp.comp Computable.fst) hterm
  have hpow : Computable fun p : ℕ × BitString × BitString => 2 ^ (p.1 + 2) :=
    (primrec_two_pow_aux.comp (Primrec.nat_add.comp Primrec.fst (Primrec.const 2))).to_comp
  have hdiv : Computable fun p : ℕ × BitString × BitString =>
      ((List.range p.1).map (fun i => (D p.2.1 i).elim 0 (fun u => a u (2 * p.1 + 2)))).sum
        / 2 ^ (p.1 + 2) :=
    Computable₂.comp Primrec.nat_div.to_comp hsum hpow
  have hfinal : Computable fun p : ℕ × BitString × BitString =>
      ((List.range p.1).map (fun i => (D p.2.1 i).elim 0 (fun u => a u (2 * p.1 + 2)))).sum
        / 2 ^ (p.1 + 2) - 1 :=
    Computable₂.comp Primrec.nat_sub.to_comp hdiv (Computable.const 1)
  exact hfinal.of_eq fun p => rfl

/-- **SUV §5.9.3, p. 181.**  For a computable measure `μ` and an r.e. relation
`R`, the mass `μ(⋃ {Ω_p : R p x})` of the effectively open set generated by `R`
is lower semicomputable, uniformly in `x`.

This is `cantorOpenMass_isLSC` (`MonotoneComplexity/EffectiveOpen.lean`, which
proves it for `uniformMeasure`) with the uniform measure replaced by an arbitrary
computable one; it is what SUV's "(It is easy to see that in this case `ν` is a
computable measure.)" (p. 181) needs. -/
theorem cantorOpenMass_isLSC_of_isComputableMeasure {μ : Measure CantorSeq}
    (hμ : IsComputableMeasure μ) {R : BitString → BitString → Prop}
    (hR : IsRE fun q : BitString × BitString => R q.1 q.2) :
    IsLSC (fun x _ => μ (cantorOpen R x)) := by
  classical
  obtain ⟨a, ha_comp, ha⟩ := hμ
  obtain ⟨f, hf, hfR⟩ := hR
  obtain ⟨c, hc⟩ := Nat.Partrec.Code.exists_code.mp hf
  have hc' : ∀ p y, (c.eval (Encodable.encode (p, y))).Dom ↔ R p y := by
    intro p y
    have h_eq : c.eval (Encodable.encode (p, y)) = (f (p, y)).map Encodable.encode := by
      have hc_app : c.eval (Encodable.encode (p, y)) =
          (fun n => Part.bind (Encodable.decode n : Option (BitString × BitString))
            fun q => (f q).map Encodable.encode) (Encodable.encode (p, y)) := by
        rw [hc]
      rw [hc_app]
      simp
    rw [h_eq]
    simp [hfR]
  have hRel : (fun p y => (c.eval (Encodable.encode (p, y))).Dom) = R := by
    funext p y
    exact propext (hc' p y)
  set D : BitString → ℕ → Option BitString :=
    fun x => disjEnum (cantorOpenREEnumerator c x) with hDdef
  -- the disjointified enumeration has the same union, hence the same mass
  have hDmass : ∀ x, (∑' i, (D x i).elim 0 (cantorMass μ)) = μ (cantorOpen R x) := by
    intro x
    have h1 : (⋃ j, coverSet (cantorOpenREEnumerator c x) j) = cantorOpen R x := by
      simp only [coverSet]
      rw [range_cantorOpenREEnumerator c x, hRel]
    rw [hDdef, tsum_measure_disjEnum μ (cantorOpenREEnumerator c x), h1]
  have hpartial : ∀ x, ⨆ s, openPartialMass μ D s x = μ (cantorOpen R x) := by
    intro x
    rw [← hDmass x, ENNReal.tsum_eq_iSup_nat]
    rfl
  -- the computability of the disjointified enumeration
  have hDcomp : Computable fun r : BitString × ℕ => D r.1 r.2 := by
    have hdec : Computable fun r : ℕ × ℕ => ((Encodable.decode r.1 : Option BitString).getD []) :=
      Computable.option_getD (Computable.decode.comp Computable.fst) (Computable.const [])
    have hF : Computable₂ fun n i : ℕ =>
        cantorOpenREEnumerator c ((Encodable.decode n : Option BitString).getD []) i :=
      (computable_cantorOpenREEnumerator c).comp hdec Computable.snd
    have hcomp := (computable_disjEnum hF).comp
      (Computable.encode.comp (Computable.fst (α := BitString) (β := ℕ))) Computable.snd
    refine hcomp.of_eq ?_
    intro r
    have hdecode : ((Encodable.decode (Encodable.encode r.1) : Option BitString).getD [])
        = r.1 := by simp
    simp only [hDdef, hdecode]
  set raw : ℕ → BitString → BitString → ℕ := fun s x _ => openApproxNum a D s x with hraw
  have hraw_le : ∀ (s : ℕ) (x ctx : BitString),
      dyadicValue (raw s x ctx) s ≤ μ (cantorOpen R x) := by
    intro s x _
    refine (openApproxNum_le ha D s x).trans ?_
    rw [← hpartial x]
    exact le_iSup (fun s => openPartialMass μ D s x) s
  refine ⟨makeMono raw, fun s out ctx => makeMono_mono raw s out ctx, ?_, ?_⟩
  · intro x ctx
    have hup : (⨆ s, dyadicValue (makeMono raw s x ctx) s) ≤ μ (cantorOpen R x) :=
      iSup_le fun s => dyadicValue_makeMono_le
        (v := fun x (_ : BitString) => μ (cantorOpen R x)) hraw_le s x ctx
    have hdown : μ (cantorOpen R x) ≤ ⨆ s, dyadicValue (makeMono raw s x ctx) s := by
      rw [← hpartial x]
      refine iSup_le fun s₀ => ?_
      refine ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_
      obtain ⟨u, hu⟩ := exists_inv_two_pow_lt (ε := (ε : ℝ≥0∞)) (by exact_mod_cast hε.ne')
      obtain ⟨u', hu'le, hu'eq⟩ : ∃ u', u ≤ u' ∧ max s₀ (u + 2) = u' + 2 :=
        ⟨max s₀ (u + 2) - 2, by omega, by omega⟩
      have hsmall : dyadicValue 3 (max s₀ (u + 2)) ≤ (ε : ℝ≥0∞) := by
        have h4 : dyadicValue (3 : ℕ) (max s₀ (u + 2))
            ≤ dyadicValue (1 * 2 ^ 2) (max s₀ (u + 2)) := dyadicValue_mono_nat (by norm_num) _
        have h5 : dyadicValue (1 * 2 ^ 2) (max s₀ (u + 2)) = dyadicValue 1 u' := by
          rw [hu'eq]
          exact dyadicValue_mul_two_pow 1 u' 2
        have h6 : dyadicValue 1 u' ≤ ((2 : ℝ≥0∞)⁻¹) ^ u := by
          rw [dyadicValue_one_eq_inv_two_pow']
          exact pow_le_pow_right_of_le_one' (by norm_num) hu'le
        exact ((h4.trans (le_of_eq h5)).trans h6).trans hu.le
      have hmono : openPartialMass μ D s₀ x ≤ openPartialMass μ D (max s₀ (u + 2)) x := by
        refine Finset.sum_le_sum_of_subset ?_
        intro i hi
        simp only [Finset.mem_range] at hi ⊢
        omega
      calc openPartialMass μ D s₀ x
          ≤ openPartialMass μ D (max s₀ (u + 2)) x := hmono
        _ ≤ dyadicValue (raw (max s₀ (u + 2)) x ctx) (max s₀ (u + 2))
            + dyadicValue 3 (max s₀ (u + 2)) := le_openApproxNum ha D _ x
        _ ≤ dyadicValue (makeMono raw (max s₀ (u + 2)) x ctx) (max s₀ (u + 2))
            + (ε : ℝ≥0∞) := add_le_add (makeMono_ge raw _ x ctx) hsmall
        _ ≤ (⨆ t, dyadicValue (makeMono raw t x ctx) t) + (ε : ℝ≥0∞) :=
            add_le_add
              (le_iSup (fun t => dyadicValue (makeMono raw t x ctx) t) (max s₀ (u + 2))) le_rfl
    exact le_antisymm hup hdown
  · exact makeMono_computable raw (computable_openApproxNum ha_comp hDcomp)

end Kolmogorov
